### ISSUE TITLE
Custom naming convention with the Accelerator

### ISSUE THREAD

**Issue by bradcart1971** [Azure/Enterprise-Scale#1001]
I am deploying a landing zone in production on 7/6 and would like to get custom naming in place before we go live. Is this something I can do within Accelerator? If not, do you have a suggestion how I might be able to do it still leveraging the accelerator? 

I want the customer to use the accelerator during app migrations but we need to figure out the custom naming.

Any help would be appreciated

**Comment by jtracey93** [comment]
Hey @bradcart1971,

Thanks for reaching out. If you want to use custom naming then I suggest looking at the [ALZ-Bicep](https://aka.ms/alz/bicep) project to deploy Azure landing zones. 

This project allows you to specify custom naming for all objects/resource is that you wish to deploy.

Custom naming isn't possible in the Portal Experience Accelerator today.

Thanks 

Jack
