### ISSUE TITLE
Bug report: Creation of Microsoft.DBforMySQL instance via the portal is blocked by Deny-MySql-http policy

### ISSUE THREAD

**Issue by nonamecoder2002** [Azure/Enterprise-Scale#1002]
**Describe the bug**
Creation of "Microsoft.DBforMySQL" instance via the portal is blocked by "Deny-MySql-http" policy

The deployment template created by the portal does`nt have field "Microsoft.DBforMySQL/servers/sslEnforcement"

"Deny-MySql-http" policy has condition that checks if that field exists and for that reason the creation of the instance is blocked via the portal.

link to the policy: https://www.azadvertizer.net/azpolicyadvertizer/Deny-MySql-http.html

**Steps to reproduce**

1. Go to portal.azure.com
2. Go to "Microsoft.DBforMySQL" create menu
3. Go to "Review + create"
4. Creation of  "Microsoft.DBforMySQL" instance is blocked by "Deny-MySql-http" policy

**Screenshots**

**Comment by rokeno** [comment]
+1

**Comment by jtracey93** [comment]
Hey @nonamecoder2002 & @rokeno,

I take it these options are not exposed via the portal experience to satisfy the policy rules?

Are you about to create via IaC (Bicep, Terraform etc...)? 

Alternatively you can change the policy effect to audit instead. But in ALZ we take a preventive and proactive approach. Hence being set to deny by default. 

Also it may be worth you creating this as feedback for the MySQL team via https://feedback.azure.com and linking back to here once created to enable us to track further with product teams. 

Thanks and look forward to hearing from you. 

Jack

**Comment by Dushelov** [comment]
Hey @jtracey93. ALZ is created for big enterprises and to have best practices of security in place( in easy words). So official answer is to force thousand of ppl stop to use portal and use only IaC? Sorry, but isn't it smarter then to go with append policy?

**Comment by jtracey93** [comment]
Hi @Dushelov,

ALZ is designed for all shapes and sizes of organizations. However, as part of platform automation and devops design area we do recommend the use of IaC and therefore hence this stance we have taken. Also, large organizations commonly are driving/leading with IaC for deployment and configuration, so I don't think our approach is completely unjustified. 🙂

You make a good point that this could be made a append or modify policy, I'd lean towards modify as can then create remediation tasks etc. 👍

However, this should be a choice an organization makes as if policy does things to resources behind the scenes without app owners or platform teams being aware there is a risk.

We highly encourage consumers to build upon the foundations we provide to suit their needs/requirements based on their design decisions etc.

Would you be willing to contribute a policy to this repository for an append/modify for this scenario? If so, here are some tips and places to add it too etc.

1. Add the policy to the following files:
    - Public: `eslzArm/managementGroupTemplates/policyDefinitions/policies.json`
    - China (Mooncake): `eslzArm/managementGroupTemplates/policyDefinitions/china/mcPolicies.json`
    - US Gov (Fairfax): `eslzArm/managementGroupTemplates/policyDefinitions/gov/fairfaxPolicies.json`
2. Update docs:
    - `WhatsNew.md` - `docs/wiki/Whats-new.md`

Let us know

**Comment by jtracey93** [comment]
@nonamecoder2002 @rokeno, the default effect in this initiative where this policy is used and assigned in ALZ in `audit` did you change this via the parameter `MySQLEnableSSLEffect` to `deny` https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-EncryptTransit.html

This was done for this exact scenario, so just trying to clear up if its a bug or something that we know of and as youve changed the effect, which is fine 🙂, has caused this?

Let us know
