### ISSUE TITLE
Policydefinition Enable diagnostics for resources does not have param for keyvault metrics

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#1005]
<p>The policy definition Enable diagnostics for resources uses the built-in policy Deploy Diagnostic Settings for Key Vault to Log Analytics workspace. This policy has parameters logsEnabled (default value: true) and metricsEnabled (default value:false!)
Unfortunately it is not possible to set metricsEnabled to true via the policy initiative. We would like to have key vault metrics enabled. </p>

**Comment by neok-g** [comment]
Yes I can imagine the amount of work since 2 extra parameters for 64 policies. But I probably would advise to do it because at this moment we notice inconsistent behaviour. All the custom Enterprise Scale policies that deploy diagnostic settings have the metricsEnabled parameter default on true whilst the built-in policies have the metricsEnabled parameter default on false.
Besides we also have to use the ISO-27001 initiative because of compliance and regulation which contains the AuditDiagnosticSettings. This policy works different as well: it audits a parameter array containing a list of provided resources and for all those resources it uses a single logsEnabled and metricsEnabled parameter to inspect. So at this moment are key-vaults are compliant according to 'ISO-27001' but they non-compliant according to 'Enable diagnostics for resources'.

**Comment by neok-g** [comment]
Could you please provide an update on this one?

**Comment by jtracey93** [comment]
Hey @neok-g,

We are awaiting to review and merge PR #1022 before working on these. We hope to review and merge this PR this week.

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by paulgrimley** [comment]
@neok-g I have received a response from the Monitor team that this is by design as this is not the recommended way to ingest metrics at scale in Azure due to performance limitations. Metric API or use the new batch API can be used and there are plans to  enhance the metrics explorer https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-getting-started but no timelines currently.
