### ISSUE TITLE
Moving subscriptions to Decommissioned Management Group and preventing resource creation

### ISSUE THREAD

**Issue by arsenvlad** [Azure/Enterprise-Scale#1007]
<p>There was a previously closed issue (https://github.com/Azure/Enterprise-Scale/issues/258) touching on the same concept but creating this new one instead. </p>
<p>ALZ docs describe the theory behind Decommissioned management group:
<img src="https://user-images.githubusercontent.com/1821568/178559796-140b69d3-e8a2-41bd-bc57-fdfb4cc280b9.png" alt=image> </p>
<p>and https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/Readme.md#file---delete---sandboxlanding-zone </p>
<p>Currently, ALZ implementation does not show how to do the subscription movement to the Decommissioned MG and how to create a policy to prevent resource creation in all subs in that MG. </p>
<p>Maybe good to provide these out of the box. </p>

**Comment by jtracey93** [comment]
Thanks @arsenvlad for raising this. And this is a great call out and an area we actually had on our list to enhance also.

What policies do you suggest for the Decommissioned Management Group out of the box?

**I suggest:**

- Allowed resource types
    - With nothing in the allowed list by default on the assignment
 
That'll be pretty much it as it'll block everything pretty much 👍

Thoughts?

### Automation for moving sub

We'd see most customers being able to handle this already today with their Infra-as-Code tooling. Were you thinking of something different, or is it just guidance thats missing?

**Comment by arsenvlad** [comment]
I agree with your policy suggestion: nothing in the allowed list by default on assignment.

For the automation for moving sub, maybe adding a clarification in the guidance that the sub movement into the MG should be done via IaC tooling and automation (i.e., not Azure Policy with DINE effect). Also, should the movement happen before the subscription is marked as Disabled or after?

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2
