### ISSUE TITLE
Log categories "Deploy Diagnostic Settings for Recovery Services Vault to Log Analytics workspace for resource specific categories."

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#1011]
<p>The built-in policy Deploy Diagnostic Settings for Recovery Services Vault to Log Analytics workspace for resource specific categories only checks the logcategories:
                          &quot;CoreAzureBackup&quot;,
                          &quot;AddonAzureBackupJobs&quot;,
                          &quot;AddonAzureBackupAlerts&quot;,
                          &quot;AddonAzureBackupPolicy&quot;,
                          &quot;AddonAzureBackupStorage&quot;,
                          &quot;AddonAzureBackupProtectedInstance&quot; </p>
<p>However a recovery services vault has the following log categories available:
AzureBackupReport
CoreAzureBackup
AddonAzureBackupJobs
AddonAzureBackupAlerts
AddonAzureBackupPolicy
AddonAzureBackupStorage
AddonAzureBackupProtectedInstance
AzureSiteRecoveryJobs
AzureSiteRecoveryEvents
AzureSiteRecoveryReplicatedItems
AzureSiteRecoveryReplicationStats
AzureSiteRecoveryRecoveryPoints
AzureSiteRecoveryReplicationDataUploadRate
AzureSiteRecoveryProtectedDiskDataChurn
Health </p>
<p>So this conflicts with the builtin policy Audit Diagnostic Settings which checks for all log categories. Please modify the policy &quot;Deploy Diagnostic Settings for Recovery Services Vault to Log Analytics workspace for resource specific categories.&quot; so that it inspects all log categories available for recovery services vault. </p>

**Comment by neok-g** [comment]
Could you please provide an update on this one?

**Comment by jtracey93** [comment]
Hey @neok-g,

We are awaiting to review and merge PR #1022 before working on these. We hope to review and merge this PR this week.

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by neok-g** [comment]
> Trigger ADO Sync 2

What does this exactly mean ?

**Comment by jtracey93** [comment]
this is some internal stuff for us syncing issues to our ADO instance. Please ignore

**Comment by neok-g** [comment]
OK. So I understand that #1022 has been merged so now all these issues are being fixed? Is there a ETC available yet?

**Comment by jtracey93** [comment]
We are looking to get started on these soon, yes. No ETA to share at this time. But please feel free to also contribute if you have the time and wish too. If not, we will get to in the coming weeks

**Comment by neok-g** [comment]
Yes I might have time to contribute the coming days but not sure how sure how this process works.

**Comment by jtracey93** [comment]
Hey @neok-g,

Im really sorry but ive just checked and this policy is infact a built-in policy, so please could you raise an issue on the "azure-policy" repo (https://github.com/Azure/azure-policy/issues) and link to this issue here for tracking.

Or we could consider adding a custom definition for it [here](https://github.com/Azure/Enterprise-Scale/tree/main/src/resources/Microsoft.Authorization/policyDefinitions) in ALZ and then also changing the reference in our [initiative](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics.json).

You'll also need to add this new definition to this [array](https://github.com/Azure/Enterprise-Scale/blob/main/src/templates/policies.bicep#L70)

Really sorry for only just spotting this was a built-in. Let me know once created on the Azure Policy repo and I can follow up with the PG 👍

**Comment by neok-g** [comment]
Created the issue: https://github.com/Azure/azure-policy/issues/1017

**Comment by paulgrimley** [comment]
Hi @neok-g just in the way of an update, internal discussions are still ongoing regarding this across engineering teams and some progress has been made but nothing I can firm up but will keep you posted.

**Comment by paulgrimley** [comment]
Hi @neok-g I've just heard back from the team responsible for this Policy and they are planning to work on this Q2 CY2023.

**Comment by paulgrimley** [comment]
Further update on this, I've just spoken to the BCDR PM responsible for this and as part of plans to move diagnostic logs to resource-specific tables as per https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs#resource-specific these categories will be included, timescales for this being available are towards end of CY2023.

**Comment by paulgrimley** [comment]
Just to provide an update on this, I connected with the engineering owner on this item and there is a dependency from another team meaning this has introduced a slip from planned date communicated in previous post (end of CY2023), it could still make this timescale but more realistically its likely CY2024 Q1.

**Comment by paulgrimley** [comment]
Following up on previous updates I have spoken with the PM owner for this, they are code complete and on track. 

One thing to note is that for ALZ we are working separately with diagnostic team on updated diag policies that allow you to choose either 'audit' or 'alllogs' so ALZ won't be catering for level of granularity by default moving forward but we will provide guidance on how to adopt this granularity should you require. cc: @Springstone

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.

**Comment by Springstone** [comment]
For this particular issue, please use the new policy https://www.azadvertizer.net/azpolicyadvertizer/2f4d1c08-3695-41a7-a0a0-8db4a0e25233.html
