### ISSUE TITLE
🪲 Bug Report - No diagnostic settings for microsoft.networking/vpnGateways

### ISSUE THREAD

**Issue by CTCasperHagemann** [Azure/Enterprise-Scale#1012]
<h2 id=describethebug>Describe the bug </h2>
<p>First time using this project, so bear with me if I have overlooked something…
After deploying the project with the recommended deployment flow, it appears that the VPN gateway deployed through the vwan topolody does not get any diagnostic settings through policies. </p>
<p>The below example is a simple wvan hub, with only firewall and VPN enabled. </p>
<h2 id=toreproduce>To Reproduce </h2>
<p>Steps to reproduce the behaviour: </p>
<ol>
<li>Deploy the project from step 1 to 8 and use the wvan topolody (https://github.com/Azure/ALZ-Bicep/wiki/DeploymentFlowVWAN). </li>
<li>Go to the resource group of your hub resources and verify the diagnostic settings sub-menu </li>
</ol>
<h2 id=expectedbehaviour>Expected behaviour </h2>
<p>A policy should apply diagnostic settings on the object microsoft.network/vpngateways
It appears that the policy file policy<em>definition</em>es<em>deploy</em>diagnostics_vnetgw.json handles the type Microsoft.Network/virtualNetworkGateways, and not the type deployed with the vwan topolody
The firewall deployed in the same subscription and Resource Group receives the correct diagnostic settings </p>
<h2 id=screenshots>Screenshots &#128247; </h2>
<p><img src="https://user-images.githubusercontent.com/109648418/179910509-eba55dc6-2029-4ade-a1ed-e462057fa2aa.png" alt=image> </p>
<h2 id=correlationid>Correlation ID </h2>
<h2 id=additionalcontext>Additional context </h2>
<p>Maybe missing an entire policy definition for the object microsoft.network/vpngateways? </p>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by chris5287** [comment]
@jtracey93 can we get an update on this, just discovered we are missing this in our implementation!

**Comment by jtracey93** [comment]
Hey @chris5287 this is done but it is in our policy-refresh branch as we  are making a large number of policy improvements. 

We plan to complete this work in March and merge it into main and pull down to all of our implementation options shortly after. 

You can see the policy we've created for this here and use it in the mean time: https://github.com/Azure/Enterprise-Scale/blob/policy-refresh/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-VWanS2SVPNGW.json

Thanks

Jack

**Comment by jtracey93** [comment]
This is live in #1273
