### ISSUE TITLE
Connectivity between Online and Corp Landing Zones

### ISSUE THREAD

**Issue by AnjaneyalnDatla** [Azure/Enterprise-Scale#1016]
_**_Background:_**_

We have recently started our migration to the cloud. All our current workloads are running on-premises. With our first implementation/migration to the cloud, we are hoping to deploy an Application Gateway connected to API Management instance to expose api's that need to be externally exposed. Anybody from internal trying to call the API's can go directly to API Management Instance.

Slowly, we will move the on-premises api's one after the other to azure and update the API Management route.

For the cloud setup, we are trying to implement enterprise scale landing zones. We have chosen to go with [Adventure Works](https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md).

**Question:** 
The question we have is about the landing zones, specifically where should the Application Gateway and APIM be deployed?

The way we understood the different landing zones is:
 - Corp :  This landing zone will be ideal for internal corporate applications/api's. This landing zone will have vnet(s) with hybrid connectivity(which will connect to on-premises).  So API Management can be deployed here but the application gateway cannot be (since this is only for internal and having a public IP is not allowed here)
 - Online : This landing zone will have internet facing applications/api's and will/should not have any hybrid connectivity (connect to on-premises). So Application Gateway can be deployed here but the API Management instance cannot be deployed here as it will not work since it cannot talk to the on premises applications(because of lack of hybrid connectivity).

Options we have thought of so far -
Option 1: Deploy Application Gateway in Online and APIM in Corporate, peer Online subscription with Corp Subscription.
Option 2: Deploy Application Gateway in Online and APIM in Corporate, enable transit connectivity between Online and Corp via the Connectivity Subscription(the hub)

Are there any other options? How have other people implemented this scenario?

We are looking for suggestions from the community to help us decide the better approach. Thank you in advance.

**Comment by jtracey93** [comment]
Hey @AnjaneyalnDatla,

Thanks for asking the question.

This would be all an online workload in most cases we see. As there is no **hard** rule that says online landing zones, and their vNets, cannot be connected back to the hub vNet to get back to on-premises if they require it for the application workload to function/operate.

If all these components form 1 application workload (app + APIM + App GW) they are better suited in a single landing zone (potentially per environment also - prod/test/dev etc.). The placement of them in the management group hierarchy is purely to control "what must be true" from a governance, security and compliance standpoint, as detailed further in our tailoring guidance here: https://aka.ms/alz/tailoring.

Hope this helps, let us know

Thanks

Jack

**Comment by AnjaneyalnDatla** [comment]
Hey @jtracey93. 

Thank you very much for the suggestion. I went through the Tailoring documentation you shared as well and it now makes more sense to me. Thanks again!.
