### ISSUE TITLE
Base cost

### ISSUE THREAD

**Issue by reza8iucs** [Azure/Enterprise-Scale#1018]
Hi,

We're planning to test drive ESLZ. 

Can someone please let me know roughly what's the minimum cost of ESLZ per month? If I deploy this today and do zero transactions , how much do i need to pay at the end of the month (roughly)?  I understand some of these services like DDOS and Azure Firewall standard are not cheap. 

Also, can deploy Azure Firewall and DDOS later? change Bicep and redeploy?

Thanks

**Comment by jtracey93** [comment]
Hi @reza8iucs,

We have guidance here on pricing: https://github.com/Azure/Enterprise-Scale/wiki/What-is-Enterprise-Scale#pricing

You can however not deploy Azure Firewall & DDoS as part of ALZ deployment and later enable if you wish in different ways, depending on how you chose to deploy in the first place. But then you will not be charged for the services.

The heart of ALZ/ESLZ which is Management Groups and Policy are free to use. Some policy actions may enable certain policies that deploy other resources, like Microsoft Defender for Cloud or Logs to Log Analytics Workspaces, all of which will have differing cost based on how much they are used, which can be seen via the pricing calculator.

**Comment by jtracey93** [comment]
Stale
