### ISSUE TITLE
Tenant Root Scope appears to not be required for Subscription Placement

### ISSUE THREAD

**Issue by joshuadmatthews** [Azure/Enterprise-Scale#1023]
The docs at https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/es-schema.md say that Tenant Root Scope is needed for subscription placement. I am using the ALZ-Bicep repository, but assuming they are doing the same thing I am in fact able to run the subscriptionPlacement.bicep with only Owner at the Root management group. Just posting to check if this is expected and if maybe the doc should be updated. Or maybe this doc doesn't apply to the actions from the ALZ-Bicep repo?

**Comment by jtracey93** [comment]
Hey @joshuadmatthews,

You are indeed correct, only permissions on the sub and management group is required here.

Do you want to put a PR in to update the doc you referenced to update it? 

> TIP: you can use the browser and just click on the pencil in the top right hand corner of the document to update it and submit a PR: 
![image](https://user-images.githubusercontent.com/41163455/186125842-bdadb6f6-5869-40fd-809e-9790d527b030.png)

**Comment by jtracey93** [comment]
fixed in #1029
