### ISSUE TITLE
Bug Report / The DeployIfNotExists policy Deploy-Diagnostics-Firewall will not get compliant

### ISSUE THREAD

**Issue by klausgh4836** [Azure/Enterprise-Scale#1024]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.2.5

**azure provider**: >= 3.5.0

**module**: v2.1.2

#### Describe the bug

The policy [Deploy-Diagnostics-Firewall](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_firewall.json) used by the policy set [Deploy-Diagnostics-LogAnalytics](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json) does not get into the status compliant. 

#### Steps to Reproduce

The reason is that the policy [Deploy-Diagnostics-Firewall](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_firewall.json) enables 3 azure firewall logging options of possible 13.  [Link to the relevant code line](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_firewall.json#L146) 
`"logs": [
                        {
                          "category": "AzureFirewallApplicationRule",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AzureFirewallNetworkRule",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AzureFirewallDnsProxy",
                          "enabled": "[parameters('logsEnabled')]"
                        }
                      ]`
<br>
The existenceCondition is checking whether all logging options are enabled. [Link to the relevant code line.](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_firewall.json#L82) 
`"existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",
                "equals": "true"
              },`

#### Possible Solution
A possible solution is to add all logging options to the logs array at [line 146.](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_firewall.json#L146).
`"logs": [
                        {
                          "category": "AzureFirewallApplicationRule",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AzureFirewallNetworkRule",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AzureFirewallDnsProxy",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWApplicationRule",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWNatRule",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWThreatIntel",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWIdpsSignature",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWDnsQuery",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWFqdnResolveFailure",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWApplicationRuleAggregation",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWNetworkRuleAggregation",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWNatRuleAggregation",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AZFWNetworkRule",
                          "enabled": "[parameters('logsEnabled')]"
                        }
                      ],`

**Comment by jtracey93** [comment]
This was fixed in #992
