### ISSUE TITLE
Suggest design for multi geopolitical region data sovereignty requirements

### ISSUE THREAD

**Issue by joshuadmatthews** [Azure/Enterprise-Scale#1025]
My organization is in the process of designing our ESLZ, and we are having trouble deciding what is the "right" way of dividing things to address Data Sovereignty, IAM, and multi geopolitical region networking requirements. 

We started by adding Management Groups under Landing Zones MG for the various geopolitical regions, (EU, US, NonProd, etc.) but then realized we need to do the same under Management MG to separate logging policies, data and identity access. Then seemingly the same separation under Connectivity MG to account for the VNets that would be needed in these different regions so that we don't have spokes from sovereign regions connected to a hub in an outside region that data should not flow though.

With so many management group additions, we started leaning towards moving the divisions up above the ESLZ and essentially having stamped copies of the entire ESLZ for each geopolitical region. But some of us feel that this is getting away from the spirit of ESLZ. 

Can any guidance be provided for how to adapt ESLZ for use cases with Sovereignty requirements across Data, Networking, and IAM?

**Comment by jtracey93** [comment]
Hi @joshuadmatthews,

Have you seen and read the tailoring guidance we have in CAF: https://aka.ms/alz/tailoring ? This is a good starting point.

If you could share some more information on the requirements, we may be able to assist you further? Also are you working with any contacts from Microsoft for your organization?

**Comment by jtracey93** [comment]
Stale
