### ISSUE TITLE
[Preview]: Assign Built-In User-Assigned Managed Identity to Virtual Machines contains hardcoded location

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#1033]
<p>The following policies contain a hardcoded location of 'EASTUS' which causes compliancy issues, because for some organisations this location might not be allowed: </p>
<ul>
<li><p>[Preview]: Assign Built-In User-Assigned Managed Identity to Virtual Machines </p> </li>
<li><p>[Preview]: Assign Built-In User-Assigned Managed Identity to Virtual Machine Scale Sets </p> </li>
</ul>
<p>Please make location configurable via param. </p>

**Comment by jtracey93** [comment]
Hey @neok-g,

Can you provide the definition IDs for these policies, instead of their display names so we can track down where this may need fixing?

Thanks

Jack

**Comment by neok-g** [comment]
Hi @jtracey93 

Below they are:

[Preview]: Assign Built-In User-Assigned Managed Identity to Virtual Machines
/providers/Microsoft.Authorization/policyDefinitions/d367bd60-64ca-4364-98ea-276775bddd94


[Preview]: Assign Built-In User-Assigned Managed Identity to Virtual Machine Scale Sets
/providers/Microsoft.Authorization/policyDefinitions/516187d4-ef64-4a1b-ad6b-a7348502976c

**Comment by jtracey93** [comment]
Thanks @neok-g.

These are built-in policies and ones we do not use, yet, in ALZ. (We will look to use when migrating ALZ to AMA from MMA)

Therefore, could you raise on the [Azure Policy repo](https://github.com/Azure/azure-policy)?

Also looping in @paulgrimley as this policy is related to AMA and something we need to be aware and potentially can raise to the AMA team in our conversations that are ongoing today?

@neok-g please let us know the link to the other issue you raise on the Azure Policy Repo 👍

**Comment by neok-g** [comment]
@jtracey93 Here it is: https://github.com/Azure/azure-policy/issues/1004

**Comment by jtracey93** [comment]
Thanks @neok-g, I will close this issue as now raised upstream on the correct repo for built-ins.

However, I did speak to @paulgrimley who is currently in active discussions with the Azure Monitor PG team and will raise this to them, as when we migrate ALZ to AMA from MMA (currently planning this with the Azure Monitor PG team) we will also require the ask you have in the issue 👍

**Comment by paulgrimley** [comment]
Thanks for raising awareness @neok-g @jtracey93 I have shared this with the AMA lead for their awareness

**Comment by jtracey93** [comment]
trigger sync

**Comment by paulgrimley** [comment]
Hi @neok-g just to let you know we have tracked down the team who manages this policy and the change has been made and is currently in testing, once this has completed it will then be ready to release so hoping this won't be too long now. 

Appreciate you making us aware of this and helping others avoid this issue in future 👍

**Comment by Fulforce** [comment]
Hi @paulgrimley & @jtracey93 , I just wondered if you have any update on when this issue may be fixed? The location is still hardcoded to East US and causes issues when deploying. If it could be created with a parameter which allows us to choose the location of the resource group, that would be great. Thank you

**Comment by paulgrimley** [comment]
Hi @Fulforce this is a little more involved than first expected, there is active co-ordination across a number of product teams / policy authors to align as this could introduce breaking changes if not aligned. I am awaiting an update in New Year as some of those involved are now on holiday.

**Comment by Fulforce** [comment]
@paulgrimley That's great, thank you so much. I realise now that the issue requires a cross team effort due to Enterprise Scale and other landing zone considerations. I will provide an update and note it on the internal documentation at my organisation. For now, we may look at duplicating the policy and modifying the resource group deployment location to UK South or another allowed region.

**Comment by paulgrimley** [comment]
@Fulforce We've made some progress and testing with a fix to the policy and I'm just waiting for confirmation of rollout and will keep you posted.

**Comment by NikolaiKleppe** [comment]
Just wondering if there are any updates on this? 

I'm considering making a custom policy out of this as well in the meantime so we can change the location because of compliance. But if the updated policy will contain breaking changes it might not be compatible with the custom policy, causing an additional round of re-deployments across the tenant

**Comment by paulgrimley** [comment]
@NikolaiKleppe its still ongoing and discussions are happening between PG teams and you are right there is a breaking change that needs to be considered so this is contributing to the delays and resolution. I have an agenda item to discuss with ALZ team and report back on what we suggest short-term

**Comment by paulgrimley** [comment]
I have been advised that PR's are in the system and hoping to be merged in next couple of weeks to address this. Will update you as I hear anything

**Comment by paulgrimley** [comment]
Pleased to confirm that the updates have now been pushed to production, thank you everyone for their input and influencing this fix. Closing for now and can re-open if needed
