### ISSUE TITLE
Deprecated policy for storage account diagnostic settings

### ISSUE THREAD

**Issue by chrisking81** [Azure/Enterprise-Scale#1034]
<p><strong>Describe the bug</strong>
We currently include a deprecated policy to set the diagnostic settings on a storage account, in the reference implementations. </p>
<p><strong>Definition ID:</strong> 6f8f98a4-f108-47cb-8e98-91a0d85cd474 </p>
<p>This has been replaced with the following 5 separate policy definitions: </p>
<ul>
<li>storage accounts (59759c62-9a22-4cdf-ae64-074495983fef) </li>
<li>blob services (b4fe1a3b-0715-4c6c-a5ea-ffc33cf823cb) </li>
<li>file (25a70cc8-2bd4-47f1-90b6-1478e4662c96) </li>
<li>queue (7bd000e3-37c7-4928-9f31-86c4b77c5c45) </li>
<li>table (2fb86bf3-d221-43d1-96d1-2434af34eaa0) </li>
</ul>
<p>The initiative 'Deploy Diagnostic Settings to Azure Services' will need to be updated to remove the deprecated policy, and replace with the five new policy definitions. </p>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by jtracey93** [comment]
Trigger ADO Sync - Re-assigning to @{assignees=System.Object[]; url=https://github.com/Azure/Enterprise-Scale/issues/1034}.assignees[0].login to Ensure ADO Sync Assignee Take Place

**Comment by jtracey93** [comment]
Trigger ADO Sync - No Current Assignee

**Comment by jtracey93** [comment]
Trigger ADO Sync - No Current Assignee

**Comment by jtracey93** [comment]
will review PR shortly
