### ISSUE TITLE
Policy Doc Updates

### ISSUE THREAD

**Issue by SharmainePopov** [Azure/Enterprise-Scale#1035]
<p>I'd like to see a starter pack for Azure Policy that mirrors what is achieved with the automated ALZ deployment.  Something the client can access without cruising a repo or deploying a full ALZ. Many client resources dealing with this aren't developers. Also consistency across LZ deployment options (arm blue button, terraform, bicep, pub sec etc.), not sure we get the same set from each deployment. </p>

**Comment by jtracey93** [comment]
Hey @SharmainePopov,

We do have consistency between all ALZ implementation options as the source of truth are the policies in this repo, and we pull them from here into Terraform & Bicep implementations respectively 👍

We can certainly add a link from this page https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md to the ALZ-Bicep Custom Policy Definitions module: https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions as this just allows all the policy definitions from ALZ to be deployed to any Management Group, that can then be used and assigned anywhere as that customer desires.

Does that sound like a good plan?

Let us know and we can action 👍

Thanks

Jack

**Comment by SharmainePopov** [comment]
Hi
That’s good info. I think the clients need something referenced outside the code base, to be honest. It would be great to see it in the ALZ doc set for lay (non coder) people. At least a summary of what could be done and where to go to find out how.

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | ***@***.******@***.***> | 416-799-0807

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by jtracey93** [comment]
Trigger ADO Sync - Re-assigning to @{assignees=System.Object[]; url=https://github.com/Azure/Enterprise-Scale/issues/1035}.assignees[0].login to Ensure ADO Sync Assignee Take Place

**Comment by jtracey93** [comment]
Trigger ADO Sync - Re-assigning to jtracey93 to Ensure ADO Sync Assignee Take Place

**Comment by jtracey93** [comment]
Trigger ADO Sync - Re-assigning to jtracey93 to Ensure ADO Sync Assignee Take Place
