### ISSUE TITLE
Bug Report - AzOps deployments failing from accelerator 

### ISSUE THREAD

**Issue by shantihy** [Azure/Enterprise-Scale#1040]
**We cannot continue the deployment code getting error**
{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template variable 'keyVaultName' is not valid: The template function 'RESOURCEGROUP' is not expected at this location. Please see https://aka.ms/arm-template-expressions for usage details.. Please see https://aka.ms/arm-template-expressions for usage details.'."}

**Steps to reproduce**

1. platform devOps and automation, if we select service principle or use exiting service principle
2. code do not run but if i do only github and access token, code do run but it not creating repo in github

**Screenshots**
![image](https://user-images.githubusercontent.com/87405430/189151476-0238c23e-b0f5-4e76-95af-413ba65f87dd.png)

**Comment by jtracey93** [comment]
Hey @shantihy,

Thanks for raising this bug. We have identified the fix and have tested and will merge the fix as part of #1043 hopefully later this morning👍
