### ISSUE TITLE
Bug Report - policies failing on lite deployments

### ISSUE THREAD

**Issue by crossitwe11** [Azure/Enterprise-Scale#1041]
Hi, the AdventureWorks/WingTip deployment keeps failing for me.   My correlation id is 6b27f884-c0c2-4b39-907c-b66c240759fc. The policies would not deploy like above, so I ran it again. It got past policies and now the private dns entries are failing to deploy. {
"status": "Failed",
"error": {
"code": "InvalidDeployment",
"message": "The 'location' property is not allowed for 'alz-PrivDNSLite-southcentralus-3e0046' at resource group scope. Please see https://aka.ms/deploy-to-subscription for usage details."
}
}

I have tried with multiple subscriptions.

**Comment by jtracey93** [comment]
Hey @crossitwe11 ,

Thanks for raising this bug. We have identified the fix and have tested and will merge the fix as part of #1043 hopefully later this morning👍
