### ISSUE TITLE
InvalidDeploymentBug Report

### ISSUE THREAD

**Issue by shantihy** [Azure/Enterprise-Scale#1044]
**Describe the bug*
InvalidDepolyment
**Steps to reproduce**

1. platform devops and autoamtion if we add our own SP and passwords 
2

**Screenshots**
![image](https://user-images.githubusercontent.com/87405430/189394649-4b828ae5-de92-42db-9cc6-c640baf6d549.png)

**Comment by jtracey93** [comment]
Hi @shantihy,

Apologies about this, i have just fixed and test in PR #1045 should be merged soon.

Thanks

Jack
