### ISSUE TITLE
PowerPoint Enterprise Scale

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/Enterprise-Scale#1050]
<p>For presenting enterprise scale an PowerPoint would be useful ready to download </p>

**Comment by jtracey93** [comment]
@JefferyMitchell do we have a presentation available for general consumption in the community anywhere in CAF etc?

**Comment by JefferyMitchell** [comment]
Hello @guidovbrakel! You can find a deck here in the Microsoft Partner Network resources. 
https://assetsprod.microsoft.com/mpn/en-us/cloud-adoption-framework-ready-methodology.pptx
