### ISSUE TITLE
Bug Report: Diagnostic policies look for a hardcoded named resource

### ISSUE THREAD

**Issue by anwather** [Azure/Enterprise-Scale#1060]
<p>Diagnostic policies look for a hardcoded named resource. The name <code>setByPolicy</code> is hardcoded in the conditions for each diagnostic DINE policy. </p>

**Comment by anwather** [comment]
#1059

**Comment by jfaurskov** [comment]
Closing as this is a duplicate of #478. PR for fix is in the works here #1059
