### ISSUE TITLE
Bug Report: Deploy core policy definitions to ESLZ intermediate root management group failes wite error

### ISSUE THREAD

**Issue by maxgaulhofer** [Azure/Enterprise-Scale#1061]
<p><strong>Describe the bug</strong> </p>
<p>When deploying policy 2 &quot;Deploy core policy definitions to ESLZ intermediate root management group&quot; some policies fail to deploy </p>
<p><strong>Steps to reproduce</strong> </p>
<p>1.# Deploy core policy definitions to ESLZ intermediate root management group </p>
<p>New-AzManagementGroupDeployment -Name &quot;$($DeploymentName)-policy1&quot; <code>
                                -ManagementGroupId $ESLZPrefix</code>
                                -Location $Location <code>
                                -TemplateFile .\eslzArm\managementGroupTemplates\policyDefinitions\policies.json</code>
                                -topLevelManagementGroupPrefix $ESLZPrefix `
                                -Verbose </p>
<p><strong>Screenshots</strong> </p>
<p><img src="https://user-images.githubusercontent.com/6785359/192731026-ecc9cfb0-744c-4b96-ad80-6c11e6e78114.png" alt=afbeelding> </p>
<p>New-AzManagementGroupDeployment : 10:13:18 - The deployment '-policy1' failed with error(s). Showing 3 out of 4 error(s).
Status Message: The policy set definition 'Deploy-Diagnostics-LogAnalytics' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-Diagnostics-AVDS
calingPlans,Deploy-Diagnostics-WVDAppGroup,Deploy-Diagnostics-WVDWorkspace,Deploy-Diagnostics-WVDHostPools,Deploy-Diagnostics-ACI,Deploy-Diagnostics-ACR,Deploy-Diagnostics-AnalysisService,Deploy-Diagnostics-ApiForFHIR,Deploy-Diagnostics-APIMgmt,Deploy-Diagn
ostics-ApplicationGateway,Deploy-Diagnostics-AA,Deploy-Diagnostics-Bastion,Deploy-Diagnostics-CDNEndpoints,Deploy-Diagnostics-CognitiveServices,Deploy-Diagnostics-CosmosDB,Deploy-Diagnostics-Databricks,Deploy-Diagnostics-DataExplorerCluster,Deploy-Diagnosti
cs-DataFactory,Deploy-Diagnostics-DLAnalytics,Deploy-Diagnostics-EventGridSub,Deploy-Diagnostics-EventGridTopic,Deploy-Diagnostics-EventGridSystemTopic,Deploy-Diagnostics-ExpressRoute,Deploy-Diagnostics-Firewall,Deploy-Diagnostics-FrontDoor,Deploy-Diagnosti
cs-Function,Deploy-Diagnostics-HDInsight,Deploy-Diagnostics-iotHub,Deploy-Diagnostics-LoadBalancer,Deploy-Diagnostics-LogicAppsISE,Deploy-Diagnostics-MariaDB,Deploy-Diagnostics-MediaService,Deploy-Diagnostics-MlWorkspace,Deploy-Diagnostics-MySQL,Deploy-Diag
nostics-NetworkSecurityGroups,Deploy-Diagnostics-NIC,Deploy-Diagnostics-PostgreSQL,Deploy-Diagnostics-PowerBIEmbedded,Deploy-Diagnostics-RedisCache,Deploy-Diagnostics-Relay,Deploy-Diagnostics-SignalR,Deploy-Diagnostics-SQLElasticPools,Deploy-Diagnostics-SQL
MI,Deploy-Diagnostics-TimeSeriesInsights,Deploy-Diagnostics-TrafficManager,Deploy-Diagnostics-VirtualNetwork,Deploy-Diagnostics-VM,Deploy-Diagnostics-VMSS,Deploy-Diagnostics-VNetGW,Deploy-Diagnostics-WebServerFarm,Deploy-Diagnostics-Website'. 
(Code:InvalidCreatePolicySetDefinitionRequest)
Status Message: The policy set definition 'Deploy-MDFC-Config' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Deploy-ASC-SecurityContacts'. 
(Code:InvalidCreatePolicySetDefinitionRequest)
Status Message: The policy set definition 'Enforce-EncryptTransit' request is invalid. Policy definitions should be specified only at or above the policy set definition's scope. The following policy definitions are invalid: 'Append-AppService-httpsonly,Appe
nd-AppService-latestTLS,Deny-AppServiceApiApp-http,Deny-AppServiceFunctionApp-http,Deny-AppServiceWebApp-http,Deploy-MySQL-sslEnforcement,Deny-MySql-http,Deploy-PostgreSQL-sslEnforcement,Deny-PostgreSql-http,Append-Redis-sslEnforcement,Append-Redis-disableN
onSslPort,Deny-Redis-http,Deploy-SqlMi-minTLS,Deny-SqlMi-minTLS,Deploy-SQL-minTLS,Deny-Sql-minTLS,Deny-Storage-minTLS,Deploy-Storage-sslEnforcement'. (Code:InvalidCreatePolicySetDefinitionRequest)
CorrelationId: 0a4a3458-1b00-4bbb-a0f2-bc3d3574723a
At line:1 char:1 </p>
<ul>
<li>New-AzManagementGroupDeployment -Name &quot;$($DeploymentName)-policy1&quot; ` </li>
<li>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<ul>
<li>CategoryInfo          : NotSpecified: (:) [New-AzManagementGroupDeployment], Exception </li>
<li>FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureManagementGroupDeploymentCmdlet </li> </ul> </li>
</ul>

**Comment by jtracey93** [comment]
Hey @maxgaulhofer,

This is a known issue im afraid due to an eventual consistency error that we have documented here in this long running issue #902 

If you follow the workaround and redploy over the top, this should resolve the issue for you 👍

Let us know if not

Thanks

Jack

**Comment by jtracey93** [comment]
closing as stale
