### ISSUE TITLE
Bug Report -Existing Management Group

### ISSUE THREAD

**Issue by aj-msft** [Azure/Enterprise-Scale#1080]
<p><strong>Existing Management Group with the same name under the Root Tenant gets moved while running the Accelerator</strong> </p>
<p><strong>Steps to reproduce</strong> </p>
<ol>
<li>Create MG named &quot;ELZ-Corp&quot; under root tenant </li>
<li>Move subscriptions under the newly created MG </li>
<li>Run the Accelerator deployment and specify the prefix as ELZ. </li>
<li>Leave the existing name for Corp as is and run the accelerator </li>
<li>The Landing zone deployment would have moved the initially created &quot;ELZ-Corp&quot; Management Group along with the subscription to the newly created Landing zone that was built using the accelerator. </li>
</ol>
<p>This is an issue as customers who have existing Management Group with the same name as what is specified within the Accelerator could face issues when the MG and subscriptions are moved under the new Landing zone and policies are applied. It would be good to see a warning if there are any MG groups with the same name already present in the customer environment. </p>

**Comment by jtracey93** [comment]
Hey @aj-msft,

Good find.

What would you want the error message to say and where would you like it to appear?

We can then get this implemented.

We can make this a dynamic warning though it would just be a generic warning displayed all the time. As in the portal experience we cannot do any pre-validation I'm afraid. The error would look similar to this on the MG blade:
![image](https://user-images.githubusercontent.com/41163455/195713150-d4ea70fe-3b74-4e13-aa39-9891c1b5a8fd.png)

**Comment by aj-msft** [comment]
Hey @jtracey93 

Thanks for getting back to me. 

A warning along the lines stating that any existing management groups with the same name as what is specified in the Accelerator deployment would be moved to the new Landing zone would suffice if it were displayed in the validation screen.

Thanks
Ajay

**Comment by jtracey93** [comment]
Hey @aj-msft we cannot make this appear on the validation screen, as this is a screen that is provided by the underlying service used for custom portal experiences.

However, we can make it appear on the "Azure core" tab/page, would that be sufficient?

Let us know

Thanks

Jack

**Comment by jtracey93** [comment]
Hey @aj-msft,

Any thoughts on my last suggestion (https://github.com/Azure/Enterprise-Scale/issues/1080#issuecomment-1281924441)?

Let us know

Thanks

Jack

**Comment by aj-msft** [comment]
Hi @jtracey93,

Would it be possible to add it to the tabs where Management Groups are created (Platform, Azure Core, Landing Zone etc) ?
If so, that would be great.

Regards
Ajay
