### ISSUE TITLE
Name field in Lab request form

### ISSUE THREAD

**Issue by 0shaughnessy** [Azure/Enterprise-Scale#1082]
<p>I think that it might be good to put a note in the lab request form to specify the name entry will be used to build actual subscription resources when it is provisioned &amp; make sure it is suitable as naming variable in Azure. My name is pretty long and has an apostrophe in it which I believe may have been stopping my provisioning from occurring. </p>

**Comment by jtracey93** [comment]
Hey @0shaughnessy,

I take it you are an internal FTE at Microsoft. If so can you ping in the ALZ internal teams channel so we can assist you further 👍
