### ISSUE TITLE
Landing zone template can't be run in China Azure

### ISSUE THREAD

**Issue by zhouease** [Azure/Enterprise-Scale#1089]
In China Azure, select "deploy a customer template" and then "Azure Landing Zone" and fill in with the required info. And then select "Review + create". Then following issue pops up: 
{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template variable 'azPrivateDnsPolicyAssignment' is not valid: The language expression property 'https://management.chinacloudapi.cn' doesn't exist, available properties are 'https://management.azure.com/, https://management.usgovcloudapi.net'.. Please see https://aka.ms/arm-template-expressions for usage details.'."}

**Comment by jtracey93** [comment]
Hi @zhouease,

Thanks for the issue. Unfortunately, the portal experience is not supported for Azure China. 

Please deploy via https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/README-AzureChina.md

Or consider ALZ-Bicep - https://aka.ms/alz-bicep
