### ISSUE TITLE
🪲 Bug Report - Duplicate value in policy definition

### ISSUE THREAD

**Issue by extmaper** [Azure/Enterprise-Scale#1107]
## Describe the bug

In policy definition https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/lib/policy_definitions/policy_definition_es_Deploy-Diagnostics-Website.json#L174 there is duplicate entry of AppServiceHTTPLogs.

## To Reproduce

Open linked json file and check rows 165-168 and 173-176.

## Expected behaviour (remove rows 173-176)

One entry of the category (remove rows 173-176).

## Screenshots 📷

![image](https://user-images.githubusercontent.com/56257151/200818005-dfdc4ffc-028d-4b30-979c-95d3fa999084.png)

**Comment by jtracey93** [comment]
cc: @paulgrimley FYI, need to log a bug on backlog and associate this issue👍

Its a "bug" but not an impacting one, nothing is broken, just we have a duplicate in the if rule which needs tidying.

**Comment by paulgrimley** [comment]
Captured in backlog and ready for triage

**Comment by jtracey93** [comment]
Fixed in #1115
