### ISSUE TITLE
Unable to modify email notification severity for Defender for Cloud Bug Report

### ISSUE THREAD

**Issue by kpenar-bjss** [Azure/Enterprise-Scale#1111]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.2.9

**azure provider**:     azurerm - 3.29.0

**module**: management

### Description

When trying to change Defender for Cloud email notification severity to medium or low the module.enterprise_scale deployment is overwriting changes made by manual resource deployment: 

resource "azurerm_security_center_assessment_policy" "alert_management" {
  provider     = azurerm.management
  display_name = "Alert_management"
  severity     = "Medium"
  description  = "DFC warning alert"
}

When deployed, all changes to azurerm_security_center_assessment_policy are overwritten by default (severity=high)

#### Describe the bug
There is no option or advanced setting that I would be able to use to change email notification severity within  module.enterprise_scale. 

security_center = {
        enabled = true
        config = {
          email_security_contact             = var.management_resources_email_security_contact
          enable_defender_for_app_services   = true
          enable_defender_for_arm            = true
          enable_defender_for_containers     = true
          enable_defender_for_dns            = true
          enable_defender_for_key_vault      = true
          enable_defender_for_oss_databases  = true
          enable_defender_for_servers        = true
          enable_defender_for_sql_servers    = true
          enable_defender_for_sql_server_vms = true
          enable_defender_for_storage        = true
        }
      }

**Comment by kpenar-bjss** [comment]
Thank you for quick response @krowlandson,

I tested proposed solution:
First I excluded default:

{
    "exclude_es_root": {
        "policy_assignments": [
            "Deploy-MDFC-Config"
        ],
        "policy_definitions": [
            "Deploy-ASC-SecurityContacts"
        ],
        "policy_set_definitions": [
            "Deploy-MDFC-Config"
        ],
        "role_definitions": [],
        "archetype_config": {
            "parameters": {},
            "access_control": {}
        }
    }
}

then introduced altered custom policy definition, that was mentioned in custom definition set that in turn was called in policy assignment. 

                        "alertNotifications": {
                          "state": "On",
                          "minimalSeverity": "Medium"

Unfortunately this have not resolve the issue as I suspect might be caused by another policy that is assigned in out of the box caf enterprise scale. I will keep investigating it however thank you for pointing me in right direction.

**Comment by krowlandson** [comment]
@kpenar-bjss you shouldn't need to make any edits to the archetype for this. You only need to add your custom policy definition to your custom lib folder 👍🏻 

For an environment already deployed, you may need to re-evaluate and then remediate the policy assignment.

**Comment by mo-KrzysztofPenar** [comment]
@krowlandson I have reworked my solution. Now, not excluding out of the box Deploy-MDFC-Config assignment. Instead I added new custom made definition and assignment and it is working as required. The parameter defined in assignment was email that I use as recipient of alerts.

Thank you for help
