### ISSUE TITLE
Azure Firewall - Policy to deploy diagnostic settings for Firewall to Log Analytics workspace - missing 'Azure Firewall Flow Trace Log' category

### ISSUE THREAD

**Issue by chrholt** [Azure/Enterprise-Scale#1117]
### Versions
**Module**: ALZ v2.4.1 
terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_diagnostics_firewall.json

### Description
There is missing a category for Azure Firewall diagnostic settings policy. The missing category is **Azure Firewall Flow Trace Log**

This category needs to be added or replace all with category group _allLogs_. The Azure Firewall resources which this policy deploys diagnostics settings to will never be compliant due to a mismatch between existenceCondition and what the policy actually deploys.

**Screenshots**
![azfw_policy_compliance_state](https://user-images.githubusercontent.com/16928150/201680504-10c3a534-a8bb-4cd8-b13b-5393442fcdc5.png)
![policy_definition](https://user-images.githubusercontent.com/16928150/201680512-16badafa-93a3-4298-80ba-b400290f19a1.png)
![diagnostic_setting](https://user-images.githubusercontent.com/16928150/201680510-963209f0-1977-4339-9e06-f7aa656e22a7.png)

**Comment by jtracey93** [comment]
Working on adding this new category in PR #1119 hopefully will be merged here later today
