### ISSUE TITLE
Feature Request: Allow complete configuration (enable options) of Azure Defender for VMs

### ISSUE THREAD

**Issue by archmangler** [Azure/Enterprise-Scale#1121]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Yes:

- Enabling Microsoft Defender for Azure VMs only allows partial enabling of Azure defender protections for the VM, leaving the key features up to the user to enable via the portal. 
- This is non-ideal and somewhat defeats the purpose of the AZure CAF enterprise module allowing this option
 
In detail:

- When ``  is enabled by default for a landing zone subscriptions, the subscription shows that the VM Defender Plan is only "partial", and most of the key features for Azure Defender are missing.

![Screenshot 2022-11-17 at 2 06 54 PM](https://user-images.githubusercontent.com/3898404/202369526-94e3801f-becc-4041-a7e3-b47c08acec5e.png)

Corresponding default configuration:

```
variable "configure_management_resources" {
  
.
.
.

  default = {
    settings = {
      log_analytics = {
        enabled = true
        config = {
          retention_in_days                                 = 60
          enable_monitoring_for_arc                         = true
          enable_monitoring_for_vm                          = true
          enable_monitoring_for_vmss                        = true
          enable_solution_for_agent_health_assessment       = true
          enable_solution_for_anti_malware                  = true
          enable_solution_for_azure_activity                = true
          enable_solution_for_change_tracking               = true
          enable_solution_for_service_map                   = true
          enable_solution_for_sql_assessment                = true
          enable_solution_for_sql_vulnerability_assessment  = true
          enable_solution_for_sql_advanced_threat_detection = true
          enable_solution_for_updates                       = true
          enable_solution_for_vm_insights                   = true
          enable_sentinel                                   = true
        }
      }
      security_center = {
        enabled = true
        config = {
          email_security_contact             = "yyyy@bbbb"
          enable_defender_for_app_services   = true
          enable_defender_for_arm            = true
          enable_defender_for_containers     = true
          enable_defender_for_dns            = true
          enable_defender_for_key_vault      = true
          enable_defender_for_oss_databases  = true
          enable_defender_for_servers        = true
          enable_defender_for_sql_servers    = true
          enable_defender_for_sql_server_vms = true
          enable_defender_for_storage        = true
        }
      }
    }
.
.
.
}


```

#### Describe the solution you'd like

Additional configuration toggles (enabled by default to `true`) to allow enabling these sub-features of "enable_defender_for_servers":

- Vulnerability assessment for machines
- Agentless scanning for machines (preview)

<B>A clear and concise description of any alternative solutions or features you've considered.:</B>

Dissatisfying workarounds like post-deploy scripts to enable sub features of Microsoft Defender for VMs ...

#### Additional context

Enterprise deployments require all these features to be enabled by default in preparation for compliance audits.

**Comment by jtracey93** [comment]
@Springstone one to add to our current policy review stuff please 👍

**Comment by spotakash** [comment]
I also want to confirm that current defender settings `true` is not enabling defender downstream settings for VM and Kubernetes completely. 
It seems like current policy, binded to setting configuration, is only enable top level defender but depended on service are not getting enable. Therefore, policy association to setting has to be change in CAF Module.

- Full Defender Suite and downstream Settings Should also get enabled as part of Landing Zone Policy Assignments. 
- Also, if CSPM can also be enabled and can have separate flag;
`enable_defender_for_cspm   = true`

Example: 
Defender is being enabled for workload but notice `Partial` for **Server** and **Kuberntes**
![image](https://user-images.githubusercontent.com/7689697/219272280-25b0d9c6-cc96-4380-80c9-e4a11ade092c.png)

Inside **Server** we can notice VA Assesment is not enabled for Machine.
![image](https://user-images.githubusercontent.com/7689697/219272605-f91ceda2-4103-4d0c-8e15-743f60335b26.png)

Similarly for **Kubernetes,** Defender Daemon Set and Azure Policy for K8 is not getting enable.
![image](https://user-images.githubusercontent.com/7689697/219272878-88e8fa04-f421-4073-88fa-55ea2006034f.png)

**Comment by jtracey93** [comment]
Thanks @spotakash we are already addressing these in an upcoming policy refresh we are working on and hope to have out in March.

In this we have already addressed CPSM, and the vulnerability assessment on servers (this can be seen in #1175 - please note this isnt live yet as we are working on releasing the policy-refresh/updates as a batch once ready as mentioned above.)

However the K8S pieces i think we might need to investigate and bring into the policy-refresh work, if possible (not everything is available/exposed to be "policyable"). @Springstone & @paulgrimley can you add a User Story to the existing feature to address to K8S stuff here.

It may also be one that we need to bring to the attention of the MDFC team, if not "policyable", and bring @JefferyMitchell in to help us here as he is starting a conversation with this PG team for a similar ask.

**Comment by paulgrimley** [comment]
Thanks @jtracey93 tracking the Azure Policy for Kubernetes under spike AB#26798 @Springstone @spotakash

**Comment by Springstone** [comment]
This has been resolved as part of the Q1 FY23 policy refresh. Should you have any concerns, feel free to re-open the issue or create a new one.
NOTE: Microsoft Defender for Cloud is upgrading Policy capabilities to be consistent and we will implement them as they become available.
