### ISSUE TITLE
Feature Request - Add Policy for "Deploy Diagnostics settings for Log Analytics to Log Analytics workspace"

### ISSUE THREAD

**Issue by janegilring** [Azure/Enterprise-Scale#1124]
It is possible to send diagnostic logs and metrics to for a Log Analytics workspace to a central Log Analytics workspace.

![image](https://user-images.githubusercontent.com/2039662/202480090-82948aea-ac3e-47e3-88c1-49f10cd941d7.png)

Since individual Landing Zones often deploy their own Log Analytics workspaces, it would be nice to include Log Analytics to the Azure Policy initiative _Deploy-Resource-Diag_ deployed by ALZ.

It could then configure diagnostic logs even for the central Log Analytics workspace deployed by ALZ, and in practice send the diagnostic logs to itself.

**Comment by jtracey93** [comment]
Hey @janegilring,

Good call. Do you want to contribute this via a PR following this as an example: https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Bastion.json and then add to this initiative https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics.json?

Let us know

Thanks

Jack

**Comment by janegilring** [comment]
@jtracey93 Definitely, happy to contribute 👍

**Comment by jtracey93** [comment]
Cool ill assign this to you, let me know if you need any support.
