### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by m-haiderali** [Azure/Enterprise-Scale#1125]
**Describe the bug**
"alz-HubSpoke" deployment fails with status of "conflict". When dive deep it shoes that inside "Connectivity" subscription, under "[Prefix]-vnethub-[location]" resource group following two succeeds:

1. [Prefix]-azfwpolicy-[location]
2. [Prefix]-fw-[location]-pip

But following one fails with status "conflict" and error code "InternalServerError"

1. [Prefix]-hub-[location]

**Steps to reproduce**

1. Select on deploy button.
2. Select all recommended option as they are.
3. Start Deployment
4. Got error for [Prefix]-privatedns resource group not found
5. Created [Prefix]-privatedns inside Connectivity Subscription
6. Start Deployment again.
7. Got error with message as "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.".

**Screenshots**
![image](https://user-images.githubusercontent.com/83274089/202483192-b32d35db-b85b-431c-9060-dfb2f410d1a1.png)
![image](https://user-images.githubusercontent.com/83274089/202484578-b7857964-d4a3-43bf-bfae-c24aee43bdf9.png)
![image](https://user-images.githubusercontent.com/83274089/202484745-b0a8f0df-8e8a-4e6f-9015-7f58fbfd827a.png)
![image](https://user-images.githubusercontent.com/83274089/202484931-da27c38d-e0c4-4024-acac-1682b8ae0e7b.png)

**Comment by jtracey93** [comment]
Hey @m-haiderali,

Thanks for the issue.

Can you click into this and send a screenshot please ?
![image](https://user-images.githubusercontent.com/41163455/202511593-11cdb3d5-434c-4408-bdd7-2667300f3128.png)

**Comment by m-haiderali** [comment]
Thank you for your reply @jtracey93.
Here is the required screenshot:
![image](https://user-images.githubusercontent.com/83274089/202736729-7de8481b-a38e-49a9-a4b1-52b5f25badca.png)

**Comment by m-haiderali** [comment]
Here is the screenshot @jtracey93 
![Details](https://user-images.githubusercontent.com/83274089/202852171-ded1689a-ab5a-4d0a-863a-fb7e2ec1f74e.jpeg)

**Comment by jtracey93** [comment]
Thanks @m-haiderali 

Have you been able to retry the deployment by re running the experience with the same input options and values?

**Comment by m-haiderali** [comment]
Yes i tried almost 4 times (with same input options and values) but it fails at this step every time, also as mentioned at first it failed and gave error "[Prefix]-privatedns resourceGroup not found", i created this resource group inside connectivty, it moved forward, created some resources inside the privatedns group but it is not moving forward after this.

**Comment by m-haiderali** [comment]
By the way i am using ""Enterprise-scale for small enterprises" template.

**Comment by jtracey93** [comment]
@m-haiderali Can you advise of all the parameter inputs you are using here so we can test and try and repro?

**Comment by m-haiderali** [comment]
Apart from following everything is selected by default (Some of the followings are also default options but I mentioned anyway).

Platform subscription options = Dedicated
Customer Usage Selection Option = Enabled
Log Analytics Data Retention = 60 Days
Deploy integrated CI/CD pipeline? = No
Deploy networking topology = Hub and spoke with Azure Firewall (with default options and "Availability Zones" is selected as all)
No "Corp" Landing Zone Subscription
"Online" subscription is selected

**Comment by jtracey93** [comment]
@m-haiderali Can you confirm which one of these you are using please?
![image](https://user-images.githubusercontent.com/41163455/203027065-21accf64-f5d6-40cf-9041-6170a256279e.png)

As the "small enterprises" one does not have a dedicated option for platform subscriptions, so am confused here?

I would suggest the "AdventureWorks" implementation for your requirements 

Let me know
