### ISSUE TITLE
Feature Request - Validate diagnostic settings

### ISSUE THREAD

**Issue by DevSecNinja** [Azure/Enterprise-Scale#1138]
**Describe the solution you'd like**

Recently I migrated the management subscription I use in combination with the Terraform ES module. It went surprisingly smooth, but I noticed that for some of the resources the diagnostic settings didn't change to the new Log Analytics workspace that was created. Azure Policy tells me the resources are compliant, but resources don't send their diagnostic logs to a foo-bar'd workspace.

I checked one of the policies and noticed that we only check if the logs and metrics are enabled, but not to which workspace ID the diagnostics are forwarded to:

````
        "existenceCondition": {

          "allOf": [

            {

              "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",

              "equals": "[parameters('logsEnabled')]"

            },

            {

              "field": "Microsoft.Insights/diagnosticSettings/metrics.enabled",

              "equals": "[parameters('metricsEnabled')]"

            }

          ]
````

In my opinion, we should change the policy to also validate if the correct workspace ID is set, so that the Azure Policy compliance view is accurate. This prevents an organization from thinking they are compliant, while actually missing out on some critical logs that should be forwarded to e.g. Sentinel.

Curious to hear your thoughts!

(CC @krowlandson)

**Comment by jtracey93** [comment]
Hey @DevSecNinja,

Great spot and this is something we are aware of.

Our long term vision, that we are actively working on, is migrating our diagnostic settings to a new built-in equivalent.

Before we invest time and effort into amending our custom policies that we provide here, we should investigate with the PG if this will be covered by a built-in soon.

@paulgrimley @krowlandson - agree?

**Comment by DevSecNinja** [comment]
Thanks @jtracey93! Interested to hear more about the built-in equivalent

**Comment by paulgrimley** [comment]
@DevSecNinja Great feedback, thanks for sharing. I will speak with the team creating the built-in policies we are looking to adopt and see if this has been considered. As things change, please keep checking the what's new page as we'll post in their updates to consume built-in which are on the horizon but not firm timescales I can confidently share at this stage.

**Comment by paulgrimley** [comment]
@DevSecNinja conversations all still ongoing with this and I'm working with PG and have recently reviewed and shared your feedback as part of the review AB#26961

**Comment by jtracey93** [comment]
This will be resolved as ALZ migrates towards the new built-in initiatives for diagnostic settings here: https://www.azadvertizer.net/azpolicyinitiativesadvertizer/f5b29bc4-feca-4cc6-a58a-772dd5e290a5.html

Stay tuned

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
