### ISSUE TITLE
Diagnostic name on existing settings

### ISSUE THREAD

**Issue by torivara** [Azure/Enterprise-Scale#1157]
**Describe the bug**
I have been trying to use the ALZ framework for a brownfield project. Some settings are configured by Terraform, and we are transitioning over to using policy for diag settings deployment. Problem is we have a specific naming of the diag settings in Terraform, and no easy way of removing them currently. This means that we have several non-compliant resources, that are actually compliant, but their diag settings name is not "setByPolicy". In my mind this should mark them compliant, as they are sending logs where they should.

Are diagnostic setting names supposed to be a compliance check? If I try to remediate them, sometimes I get an error about sinks only being used in one setting. Other times we get double logging.

[This line](https://github.com/Azure/Enterprise-Scale/blob/3bb0a9443d3febc27c371ab89167c8eddea3ab6f/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-NIC.json#L72) is what seems to make diag setting name a compliancy issue. NIC as example.

Currently I have edited the definitions to exclude the "name" as a check, but I can see that this is a bigger issue. This is also a problem with built-in definitions, but I can't quite see why the setting name should be a compliance check. I am considering doing a transition to [Tao Yang's diag definitions](https://github.com/tyconsulting/azurepolicy/tree/master/policy-definitions/resource-diagnostics-settings/log-analytics), as these do not require name to correct for compliance.

Am I doing something wrong? Will the compliance be correct if I don't include the "name" part?

**Steps to reproduce**

1. Create a resource
2. Create a diagnostic setting for this resource, named "test" with all logs shipped to correct workspace
3. Assign policy for diag DINE
4. Resource will be marked non-compliant

**Screenshots**

Example with ServiceBus (diag setting):
![image](https://user-images.githubusercontent.com/16333425/208626164-8d3cf7ca-ae25-4e5d-bf87-e443d6266216.png)

Compliance status:
![image](https://user-images.githubusercontent.com/16333425/208626314-28ed4aa8-9d31-46b3-b76b-5559f2399c48.png)

Not found because name does not match profileName in policy assignment.

**Comment by jtracey93** [comment]
Thanks for the issue @torivara.

You are indeed correct that its non-compliance status is flagged as it cannot find the specific diagnostic settings resource with the name set from the parameter:
![image](https://user-images.githubusercontent.com/41163455/208656610-a77df61a-0edb-4ee2-a67d-8e47c32f0d98.png)

We are currently working with the diagnostic settings PG and looking to move a lot of these custom ALZ policies for diagnostic settings to built-in, using category groups also, which also do not include the check for the diagnostic settings profile name.

Therefore, I think this is actually a feature request to remove the below highlighted line from all the diagnostic settings policies existence checking and only check on logs enabled, metrics enabled and the target LAW, agreed?
![image](https://user-images.githubusercontent.com/41163455/208657089-8b3d8bd1-905c-45ea-bfd6-734f80ea9af4.png)

Looping in @krowlandson & @matt-FFFFFF to see if they have any thoughts on this to add on top of mine?

Also looping in @paulgrimley who is the PM leading the diagnostic settings work we are doing with PG in ALZ here also as we may need to create a new user story to do this. And another to ask all built-in's to update their logic for this too.

Finally @torivara, would you be willing to create a PR to complete this work in all the diagnostic settings ALZ custom policies?

> **Side Note:** @torivara if you are creating diagnostic settings profiles to send logs to the same LAW as a target, you should be seeing duplication of logs and costs from what we have been discussing with PG, please let us know if you are seeing this differently so we can raise with PG to confirm understandings.

Thanks

Jack

**Comment by torivara** [comment]
I appreciate the quick feedback! 👍 

I'll look into a PR for updating the definitions that need it. Also I would be interested to know if we are losing out on some compliance info when removing the name property under details. Do you know of anyone able to answer that?

**Comment by jtracey93** [comment]
No worries. The only thing you'll lose from my perspective is ensuring the name of the diagnostic settings profile on the resource is as you specify and **it** has the categories and target LAW as you specify.

Without the profile name being checked it will just check that all categories that are in the policy are sent to the LAW specified.

**Comment by jtracey93** [comment]
This may be why it may be better to actually leave it as is, and no that "this" profile contains "this" config if you follow?

**Comment by matt-FFFFFF** [comment]
If there is consistency on the naming of the existing diag settings then an override to the policy parameter would be sufficient here.

I do think we need to investigate how these policies can be more specific in the detection logic. The name only is a fairly blunt instrument.

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
