### ISSUE TITLE
Policies deprecated in the ARM Template

### ISSUE THREAD

**Issue by andresfelipe66** [Azure/Enterprise-Scale#1159]
**Describe the bug**

After running the ARM template to create the policies for each management group and subscription I could see 3 are deprecated.

2 Custom policies set definition: 

[Deprecated]: SQL servers should use customer-managed keys to encrypt data at rest
[Deprecated]: Latest TLS version should be used in your API App
1 policy assignment:

[Deprecated]: Latest TLS version should be used in your API App

**Steps to reproduce**

1. Deploy the ARM Template
2. Run the AzGovViz and review the list of policies 

**Screenshots**

<img width="945" alt="Screenshot_2" src="https://user-images.githubusercontent.com/20842185/208715124-4e0d58ea-64e2-437d-8a9e-c2a35911bbce.png">

**Comment by paulgrimley** [comment]
Hi @andresfelipe66 I'm trying to understand is this an issue with AzGovViz incorrectly reporting deprecated state. The policies you mention are built-in policies and are _not_ showing as deprecated so I am little confused with your findings.

**Comment by andresfelipe66** [comment]
Hi @paulgrimley. I validated the information in AzGovViz and asadvertizer and is showing as deprecated in both of them

[Latest TLS version should be used in your API App](https://www.azadvertizer.net/azpolicyadvertizer/8cb6aa8b-9e41-4f4e-aa25-089a7ac2581e.html?desc=compareJson&left=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2F8cb6aa8b-9e41-4f4e-aa25-089a7ac2581e_1.0.0.json&right=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2F8cb6aa8b-9e41-4f4e-aa25-089a7ac2581e_1.0.0-deprecated.json)

[SQL servers should use customer-managed keys to encrypt data at rest](https://www.azadvertizer.net/azpolicyadvertizer/0d134df8-db83-46fb-ad72-fe0c9428c8dd.html?desc=compareJson&left=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2F0d134df8-db83-46fb-ad72-fe0c9428c8dd_2.0.1.json&right=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2F0d134df8-db83-46fb-ad72-fe0c9428c8dd_2.0.1-deprecated.json)

**Comment by paulgrimley** [comment]
@andresfelipe66 thanks for sharing and its helped clear up my confusion. I've added to our backlog and looping in @Springstone who will be looking into this

**Comment by Springstone** [comment]
@jtracey93 This issue is resolved with the merge of #1175.

@andresfelipe66 please confirm based on the `main` repo. This should be fully resolved. Thanks again for raising this as an issue.
