### ISSUE TITLE
Control for legacy monitoring agents in default policy assignments

### ISSUE THREAD

**Issue by richeney** [Azure/Enterprise-Scale#1161]
## Issue

There is a recommended migration from the older Log Analytics agents (MMA/OMS) to the new Azure Monitor Agent. The older agent will be [retired](https://learn.microsoft.com/azure/azure-monitor/agents/azure-monitor-agent-migration) on August 31, 2024.

Some of the existing default policy assignments install the older agent. Also there is a *enableAMA* property for the Dependency agent when deployed with the AMA rather than the MMA. Example for the Linux version:

```json
{
  "properties": {
    "publisher": "Microsoft.Azure.Monitoring.DependencyAgent",
    "type": "DependencyAgentLinux",
    "typeHandlerVersion": "9.5",
    "autoUpgradeMinorVersion": true,
    "settings": {
      "enableAMA": "true"
    }
  }
}
```

## Policy

I haven't done a full review, but the [default policy assignments](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep#L193) include these policy initiatives:

| Policy Initiative name | Description | 
|---|---|
| 55f3eceb-5573-4f18-9695-226972c6d74a | Legacy - Enable Azure Monitor for VMs |
| 75714362-cae7-409e-9b99-a8e5075b7fad | Legacy - Enable Azure Monitor for Virtual Machine Scale Sets |

## Suggestion

I suggest that initially a new parameter is added to control whether those "Legacy" policies are assigned. 

I understand there is a longer term plan for the introduction of the new Preview policy initiatives such as *[Preview]: Enable Azure Monitor for Hybrid VMs with AMA* (59e9c3eb-d8df-473b-8059-23fd38ddd0f0), plus new policies to audit for the older ones.

**Comment by jtracey93** [comment]
Thanks @richeney for the issue. Have transferred to the Enterprise-Scale repo as all our policies in all implementations are sourced here 👍

Also looping in @paulgrimley as he is leading the PM effort on our migration to AMA with PG. @paulgrimley will leave this to you to handle, but may be worth consolidating into the issue #1055 and closing this one to keep things tidy.

**Comment by richeney** [comment]
Agree to close in favour of #1055.
