### ISSUE TITLE
Deploy-Resource-Diag vs Deploy-Diagnostics-LogAnalytics

### ISSUE THREAD

**Issue by FallenHoot** [Azure/Enterprise-Scale#1166]
**Describe the Issue**
Deploy-Resource-Diag is an old policy compared to the new one V2 [Deploy-Diagnostics-LogAnalytics](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics.json)
https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Diagnostics-LogAnalytics.html

Confusion or outdated documentation:
https://github.com/Azure/Enterprise-Scale/blob/fc93df704a1c3e7a3f69e1af24c74ca8403dc0cb/docs/wiki/ALZ-Policies.md
![image](https://user-images.githubusercontent.com/19664186/210218955-75b76535-eb7d-4bce-aa84-781ceeec64a8.png)

Just want to verify that the following is attended or if a PR needs to be created to fix the wording?

**Comment by jtracey93** [comment]
Hey @FallenHoot,

The doc is just a little outdated here and needs to be updated to V2.0.0, I'll do that now.

The `Depoly-Resource-Diag` is just the assignment name (as per https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/managementGroupTemplates/policyAssignments/DINE-ResourceDiagnosticsPolicyAssignment.json#L27-L34) of the `Deploy-Diagnostics-LogAnalytics` initiative (https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Diagnostics-LogAnalytics.html). So no different policies, just different names used on assignment vs the initiative.
