### ISSUE TITLE
DINE policy - deploy diagnostics settings for App Service fails

### ISSUE THREAD

**Issue by MarcelHeek** [Azure/Enterprise-Scale#1169]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: N/A

**azure provider**: N/A

**module**: Azure/terraform-azurerm-caf-enterprise-scale (v3.1.2)

#### Describe the bug

The policy "Deploy Diagnostic Settings for App Service to Log Analytics workspace" (part of the Deploy-Resoource-Diag) appears to be having an invalid category  called 'AppServiceAntivirusScanAuditLogs'. When remediating an incompliant item, the following error appears;

 **_"{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"Category 'AppServiceAntivirusScanAuditLogs' is not supported."}]}_**

Additional screenshot to illustrate
![image](https://user-images.githubusercontent.com/84451910/211050453-aca0c3d5-715a-4e84-bd03-8e95198bc533.png)

If I take a look at the App Service and manually go into the diagnostics settings I can only see the following categories;
![image](https://user-images.githubusercontent.com/84451910/211050765-874d2caa-2139-4afe-ad4c-1ed2224fc1b3.png)

These categories are in the policy definition including the unsupported one, see the excerpt from the definition;
```json
             "properties": {
                      "logs": [
                        {
                          "category": "AppServiceAntivirusScanAuditLogs",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AppServiceHTTPLogs",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AppServiceConsoleLogs",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AppServiceAppLogs",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AppServiceFileAuditLogs",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AppServiceAuditLogs",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AppServiceIPSecAuditLogs",
                          "enabled": "[parameters('logsEnabled')]"
                        },
                        {
                          "category": "AppServicePlatformLogs",
                          "enabled": "[parameters('logsEnabled')]"
                        }
                      ],
                      "metrics": [
                        {
                          "category": "AllMetrics",
                          "enabled": "[parameters('metricsEnabled')]",
                          "retentionPolicy": {
                            "days": 0,
                            "enabled": false
                          },
                          "timeGrain": null
                        }
                      ],
```

#### Steps to Reproduce

Remediation fails over and over again. On multiple App Registrations in multiple tenant environments

#### Screenshots

see above

#### Additional context

N/A

**Comment by krowlandson** [comment]
Thank you for raising this @MarcelHeek.

As this is a policy query, I have moved this to the [Azure/Enterprise-Scale](https://github.com/Azure/Enterprise-Scale) repository.

Once resolved, we will pull the fixed policy into the Terraform module 👍🏻

**Comment by jtracey93** [comment]
Hey @MarcelHeek, 

Thanks for raising. Can you confirm the App Service Plan/SKUs please here, as I think these are only supported on Premium SKUs as per: https://azure.github.io/AppService/2020/12/09/AzMon-AppServiceAntivirusScanAuditLogs.html

Let us know

I think I even have the fix already if so 👍

**Comment by MarcelHeek** [comment]
@jtracey93 

Thanks for the quick response. Just randomly took one of the failed remediations of App Service diagnostics and the App Service Plan is : Production | P3V3. Others are also of type Production, but different SKU.

I cannot see anything called Premium ASP in the portal.

**Comment by jtracey93** [comment]
Hey @MarcelHeek,

Apologies for the delay in my reply. Can you confirm the App Service Plan SKU using this: https://azure.microsoft.com/en-gb/pricing/details/app-service/windows/ to see all SKUs.

Also in the subscription can you confirm if Microsoft Defender for App Service is enabled on the standard tier?

**Comment by MarcelHeek** [comment]
Hi @jtracey93 

For one tenant I had 4 App Services that initially could not be remediated at the time of raising this issue. In the meantime there were some changes that affect this. Note: The ASP's for these app services were not changed!

So at first (last week) I did the 'Deploy Diagnostics for App Services' remediation that resulted in 4 failed remediations. After that I remediated the 'Configure Azure Defender for App Service to be enabled' policy with definitionID '/providers/Microsoft.Authorization/policyDefinitions/b40e7bcd-a1e5-47fe-b9cf-2f534d0bfb7d'. 

Today I remediated the 4 App Services again and 3 of them are remediated with success and 1 failed. The successful ones have the P3v3:1 ASP with Defender enabled. And the one that still fails has the S1:1 ASP with Defender enabled.

So the combination of Premium ASP + Defender enabled makes remediation succeed. The S1 ASP + Defender enabled does not rendering a Web App without diagnostics settings set. This is obviously unwanted.

There should be differentiation within the policy to enable the `AppServiceAntivirusScanAuditLogs` category only when Premium ASP + Defender is set (including the other categories) and  enable all categories except `AppServiceAntivirusScanAuditLogs`  for all other ASP / Defender combinations.

**Comment by jtracey93** [comment]
@MarcelHeek,

Awesome thanks for the detail here and that all makes sense.

I think I have a fix for the policy with this logic for handling premium, see below.

Would you be willing to test this in your environment as we know the issue is occurring? See the below "fix" definition:

This would be the new `Deploy Diagnostics for App Services`

```json
{
  "mode": "All",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Web/sites"
        },
        {
          "value": "[field('kind')]",
          "notContains": "functionapp"
        }
      ]
    },
    "then": {
      "effect": "deployIfNotExists",
      "details": {
        "type": "Microsoft.Insights/diagnosticSettings",
        "existenceCondition": {
          "allOf": [
            {
              "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",
              "equals": "[parameters('logsEnabled')]"
            },
            {
              "field": "Microsoft.Insights/diagnosticSettings/metrics.enabled",
              "equals": "[parameters('metricsEnabled')]"
            },
            {
              "field": "Microsoft.Insights/diagnosticSettings/workspaceId",
              "equals": "[parameters('logAnalytics')]"
            }
          ]
        },
        "roleDefinitionIds": [
          "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
        ],
        "deployment": {
          "properties": {
            "mode": "incremental",
            "template": {
              "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "parameters": {
                "name": {
                  "type": "string"
                },
                "logAnalytics": {
                  "type": "string"
                },
                "metricsEnabled": {
                  "type": "string"
                },
                "logsEnabled": {
                  "type": "string"
                },
                "profileName": {
                  "type": "string"
                },
                "serverFarmId": {
                  "type": "string"
                }
              },
              "variables": {},
              "resources": [
                {
                  "type": "Microsoft.Resources/deployments",
                  "apiVersion": "2021-04-01",
                  "name": "[uniqueString(resourceGroup().id)]",
                  "properties": {
                    "mode": "Incremental",
                    "template": {
                      "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                      "contentVersion": "1.0.0.0",
                      "resources": [
                        {
                          "condition": "[equals(reference(parameters('serverFarmId'), '2021-03-01', 'Full').sku.tier, 'Premium')]",
                          "type": "Microsoft.Web/sites/providers/diagnosticSettings",
                          "apiVersion": "2017-05-01-preview",
                          "name": "[concat(parameters('name'), '/', 'Microsoft.Insights/', parameters('profileName'), '-premium')]",
                          "dependsOn": [],
                          "properties": {
                            "workspaceId": "[parameters('logAnalytics')]",
                            "metrics": [
                              {
                                "category": "AllMetrics",
                                "enabled": "[parameters('metricsEnabled')]",
                                "retentionPolicy": {
                                  "enabled": false,
                                  "days": 0
                                }
                              }
                            ],
                            "logs": [
                              {
                                "category": "AppServiceAntivirusScanAuditLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceHTTPLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceConsoleLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceAppLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceFileAuditLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceAuditLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceIPSecAuditLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServicePlatformLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              }
                            ]
                          }
                        },
                        {
                          "condition": "[not(equals(reference(parameters('serverFarmId'), '2021-03-01', 'Full').sku.tier, 'Premium'))]",
                          "type": "Microsoft.Web/sites/providers/diagnosticSettings",
                          "apiVersion": "2017-05-01-preview",
                          "name": "[concat(parameters('name'), '/', 'Microsoft.Insights/', parameters('profileName'), '-basic')]",
                          "dependsOn": [],
                          "properties": {
                            "workspaceId": "[parameters('logAnalytics')]",
                            "metrics": [
                              {
                                "category": "AllMetrics",
                                "enabled": "[parameters('metricsEnabled')]",
                                "retentionPolicy": {
                                  "enabled": false,
                                  "days": 0
                                }
                              }
                            ],
                            "logs": [
                              {
                                "category": "AppServiceHTTPLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceConsoleLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceAppLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceAuditLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServiceIPSecAuditLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              },
                              {
                                "category": "AppServicePlatformLogs",
                                "enabled": "[parameters('logsEnabled')]"
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                }
              ],
              "outputs": {
                "policy": {
                  "type": "string",
                  "value": "[concat(parameters('logAnalytics'), 'configured for diagnostic logs for ', ': ', parameters('name'))]"
                }
              }
            },
            "parameters": {
              "logAnalytics": {
                "value": "[parameters('logAnalytics')]"
              },
              "name": {
                "value": "[field('name')]"
              },
              "metricsEnabled": {
                "value": "[parameters('metricsEnabled')]"
              },
              "logsEnabled": {
                "value": "[parameters('logsEnabled')]"
              },
              "profileName": {
                "value": "[parameters('profileName')]"
              },
              "serverFarmId": {
                "value": "[field('Microsoft.Web/sites/serverFarmId')]"
              }
            }
          }
        }
      }
    }
  },
  "parameters": {
    "profileName": {
      "type": "String",
      "metadata": {
        "displayName": "Profile Name for Config",
        "description": "The profile name Azure Diagnostics"
      }
    },
    "logAnalytics": {
      "type": "String",
      "metadata": {
        "displayName": "logAnalytics",
        "description": "The target Log Analytics Workspace for Azure Diagnostics",
        "strongType": "omsWorkspace"
      }
    },
    "metricsEnabled": {
      "type": "String",
      "metadata": {
        "displayName": "Enable Metrics",
        "description": "Enable Metrics - True or False"
      },
      "allowedValues": [
        "True",
        "False"
      ],
      "defaultValue": "False"
    },
    "logsEnabled": {
      "type": "String",
      "metadata": {
        "displayName": "Enable Logs",
        "description": "Enable Logs - True or False"
      },
      "allowedValues": [
        "True",
        "False"
      ],
      "defaultValue": "True"
    }
  }
}
```

**Comment by MarcelHeek** [comment]
@jtracey93 

Sure, will give it a try. Will let you know as soon as I have some results to report back.

**Comment by MarcelHeek** [comment]
@jtracey93 

Technically the policy works like a charm.

But from CAF-ESLZ perspective introducing a suffix "-basic" for the profileName would be undermining the current MO of the https://github.com/Azure/terraform-azurerm-caf-enterprise-scale module which uses one large policy initiative/set with a single parameter to control the name of the diagnostics settings for all configure/deploy diagnostics settings policies. 

```json
"name": "[concat(parameters('name'), '/', 'Microsoft.Insights/', parameters('profileName'), '-basic')]",
```
So, would it be possible to use the same parameter value regardless of the ASP sku and/or defender status?

**Comment by jtracey93** [comment]
Thanks @MarcelHeek for the collaboration here. 

I agree on the diagnostic setting policy naming point, I did this for easier testing from memory (was a while back).

As you've done so much here, do you want to create a PR to update the policy (https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WebServerFarm.json) and then get the recognition of a contribution to this repo?

And you can set the naming to as you suggested, using the same profile name 👍

Let me know either way so we can get this fixed and rolled out 👍

> Also review our new contribution guidance which has specifics on policy as well now https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide#working-with-alz-custom-policies

Thanks

Jack

**Comment by MarcelHeek** [comment]
Hi I missed your last comment, but will see if I can contribute asap.

**Comment by MarcelHeek** [comment]
@jtracey93 

I was testing with the same diagnostic settings name for both the premium and the basic sku, but I think that is not possible as the policy processor reports an error in the template validation. The error is as follows;

```text
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The resource 'Microsoft.Web/sites/WebApp/providers/Microsoft.Insights/diagnosticSettings/alz-diagnostic-log' at line '1' and column '180' is defined multiple times in a template. Please see https://aka.ms/arm-template/#resources for usage details.'."}]}
```

So, obviously the template renders two objects with the same objects to be created and the deployment is halted. 
I reckon the only way is to differentiate in the diagnostics name, or is there some other way to work around that. I am not a policy expert, so I am not aware what all the possible options are, but I guess you are 😉

**Comment by krowlandson** [comment]
@MarcelHeek, this seems a fair error and probably why @jtracey93 used the different names initially.

As an alternative, as I believe the only difference is the `logs` value, you could store this as an object variable with two options for the two SKUs, and then use the SKU to inject the correct value.

This would be similar to the following example from our main `eslzArm.json` deployment template:

https://github.com/Azure/Enterprise-Scale/blob/cc34a01382daf2c06f866dfc9258850881f07737/eslzArm/eslzArm.json#L689-L693

Let me know if you need further guidance on how to do this.

**Comment by jtracey93** [comment]
Thanks @krowlandson & @MarcelHeek for your comments/effort here. Yes you are correct, that's why I used different names, might be the simplest approach, but Kevin's is certainly the cleverest.

I'll let you decide @MarcelHeek how to progress but let us know if you need anything

**Comment by MarcelHeek** [comment]
@jtracey93 As said, I am not the expert in the policy definition coding area. But I will give it an attempt to see if I can get variables into the policy definition structure in working order.

Will reach out though if I get stuck beyond repair 😉

**Comment by MarcelHeek** [comment]
@jtracey93 @krowlandson 

I will be honest. As a simple consumer of the downstream [module](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale) I am afraid this is not something easy for me to grasp the concept in just a couple of hours and contribute to this policy. The documentation regarding arm templates as well as policy templates and all the possible functions that are or are not available in policy templates / arm templates can severely sidetrack me for prolonged time and from my other responsibilities (including peer pressure from not delivering on my pbi's in the sprint)

So, I hope one of you guys can find the time and take care of the changes in the policy, so I can wait for the integration of the changes in the downstream module as I follow every release closely.

Thanks in advance......

**Comment by jtracey93** [comment]
No worries, thanks for trying @MarcelHeek we will try and prioritise shortly in our next sprint

**Comment by jtracey93** [comment]
For completeness, internal ADO tracking AB#26316

**Comment by jtracey93** [comment]
@ReneHezser FYI this is the GitHub Issue relating to the User Story you have AB#26316
