### ISSUE TITLE
Issue with Az policy (DINE) Configure diagnostic settings for Table Services to Log Analytics workspace

### ISSUE THREAD

**Issue by MarcelHeek** [Azure/Enterprise-Scale#1173]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: N/A

**azure provider**: N/A

**module**: Azure/terraform-azurerm-caf-enterprise-scale (v3.1.2)

### Description
Issue with Az policy (DINE) Configure diagnostic settings for Table Services to Log Analytics workspace

#### Describe the bug

This policy seems to be also triggered for Storage accounts that do not have Table Services enabled. So this policy renders incompliant for non-existing resources.

See the screenshot below with the remediation results for a set of incompliant tableservices;
![image](https://user-images.githubusercontent.com/84451910/211052857-965d3140-a64e-4169-9c9e-96524ee1290e.png)
Please note that the first is remediated with success as this Storage Account has Table Services enabled. The others however do not.

When looking into the related events the following error is available:

**_Error Code : RemediatedResourceNotFound
Reason : The resource being remediated '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/xxxxx/providers/microsoft.storage/storageaccounts/xxxxxxxxxxx/tableservices/default' could not be retrieved._**

When actually clicking on the resourse from the policy remediation blade the following is shown, demonstrating there is no actual resource propertiesfound;

![image](https://user-images.githubusercontent.com/84451910/211053289-2096ddfb-18b0-4f9a-9670-21bcb44490fd.png)

This also seems to appear if other Storage Account services, like Queue, Blob or File are not enabled within the Storage account

#### Steps to Reproduce

Remediation fails again and again

#### Screenshots

See above

#### Additional context

N/A

**Comment by matt-FFFFFF** [comment]
ADO AB#26066

**Comment by matt-FFFFFF** [comment]
@MarcelHeek we have repro'd the issue and are working with engineering to address. Thanks for raising!

In the mean time you could exclude these resources by copying the definition and editing the policyRule to:

```json
{
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Storage/storageAccounts/tableServices"
        },
        {
          "field": "name",
          "notEquals": "default"
        }
      ]
    }
  }
}
```

**Comment by jtracey93** [comment]
Please read #1203 for more analysis on this issue and info on the workarounds proposed here

**Comment by Nadiahansen15** [comment]
any news on how to fix this?

**Comment by ReneRebsdorf** [comment]
We are seeing this at scale at clients due to usage of the storage account kind 'BlobService', causing policy compliance reports to have false-negatives.

Are there any updates on expected resolution for this built in policy versus storage account diagnostic settings support?

Do you have an update that you are able to share @jtracey93 ?

We are considering making policy exemptions where this occurs, but that is non-trivial due to the randomness of how this pops up depending on landing zone resource usage.

**Comment by jtracey93** [comment]
We are currently planning a change to the diagnostic settings policies and moving towards some new built-in's based on category groups.

@Springstone is this one we have tested to see if it resolved in the new policies?

**Comment by EliranTurgeman** [comment]
Hi Team, Any update?

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
