### ISSUE TITLE
Duplicated log category in Azure policy "Deploy Diagnostic Settings for VPN Gateway to Log Analytics workspace"

### ISSUE THREAD

**Issue by jeromeecho** [Azure/Enterprise-Scale#1190]
**Describe the bug**
Duplicated log category in Azure policy definition "Deploy Diagnostic Settings for VPN Gateway to Log Analytics workspace"
 "category": "RouteDiagnosticLog" is duplicated.
Diagnostic setting for VPN gateway will not deployed by this DINE policy, The remediation task will fail. 

**Screenshots**
![image](https://user-images.githubusercontent.com/39689589/215426013-61f8caf4-d484-471c-a67c-1274e63bad39.png)

**Comment by jtracey93** [comment]
Thanks for raising @jeromeecho, would you be interested in submitting a PR to remove this duplication in the file (https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-VNetGW.json)?

Guidance on contributing can be found here: https://aka.ms/alz/contributing 

Let us know either way so we can ensure this is resolved 👍

**Comment by jtracey93** [comment]
Still active

**Comment by prjelesi** [comment]
duplicated entry removed - https://github.com/Azure/Enterprise-Scale/pull/1214
