### ISSUE TITLE
Feature Request: Enable DfC LA/AM agent auto provisioning via module

### ISSUE THREAD

**Issue by gbr759** [Azure/Enterprise-Scale#1192]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A bit of an odd one this.  We have a landing zone that's deployed and configured by the CAF module, but we're running through the DfC recommendations and we have some fails due to auto-provisioning not being enabled.  We have the log analytics agent provisioning enabled via the standard DINE policy (which works fine), but the DfC policy which checks compliance isn't checking to see if the extension is installed on the VMs, it's specifically looking to see if the "on" button is enabled via the native DfC auto-provisioning environment settings.  A couple of screenshots below to make it a little clearer:

The on/off setting in question:

![image](https://user-images.githubusercontent.com/88782924/215147629-5e4c8f72-335c-4600-a9f1-7d5e1918ed06.png)

The policy which is causing the failures in DfC:

![image](https://user-images.githubusercontent.com/88782924/215144033-3b58e8fb-bf06-4247-bb12-015bb610998a.png)

#### Describe the solution you'd like

What I'd like to know is, is there a parameter that we're missing somewhere that would enable the on/off auto-provisioning via the module to avoid these policy fails?  If not, is this something that could be added into a future release to avoid the non-compliance issues, without having to create exemptions?

**Comment by krowlandson** [comment]
Thank you for raising this @gbr759. I have moved this to the ES repo as this is where we manage policy related matters for ALZ.

@jtracey93... this appears similar to #1121 so we can either keep open for additional detail, or close as duplicate?

**Comment by jtracey93** [comment]
@Springstone can you comment and advise if we should close one of these issues as duplicated and also if this is included in current policy refresh work?

**Comment by jtracey93** [comment]
This is enabled, but the MDFC portal config settings are not reflecting. This is another item to raise with the MDFC PG as something we'd like to be able to policy

**Comment by Springstone** [comment]
We are working with the MDfC PG to improve consistency between Policy and MDfC portal UI. At the moment we enable all MDfC capabilities available today (with 3 preview features not enabled yet).

**Comment by Springstone** [comment]
Please note that due to recently announced strategic change of direction for Defender for Cloud (https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/microsoft-defender-for-cloud-strategy-and-plan-towards-log/ba-p/3883341), in which they will no longer be depending on either AMA or MMA agent, and will have alternate infrastructures providing required capabilities by April 2024. As there is nothing further we can follow up on, will be closing this issue. Feel free to re-open or open a new issue, should you still have concerns.
