### ISSUE TITLE
Deny-PublicPaaSEndpoints contains two policy definitions that IMO do not really fit to the policy initiative description

### ISSUE THREAD

**Issue by mezzofix** [Azure/Enterprise-Scale#1202]
[AB#26965](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/26965) 

The following policy set definition https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints.json labeled  Deny-PublicPaaSEndpoints contains two policy definitions that IMO do not really fit to the policy initiative description, namely:

The policy definitione ID is for [Azure Key Vault should have firewall enabled](https://portal.azure.com/). There’s a better policy that in fact disables public network access, and that is Azure Key Vault should disable public network access
`
[KeyVaultPublicIpDenyEffect: {](javascript:void(0))
type: "String",
[metadata: {](javascript:void(0))
displayName: "Public network access should be disabled for KeyVault",
description: "This policy denies creation of Key Vaults with IP Firewall exposed to all public endpoints"
},
[allowedValues: [](javascript:void(0))
"Audit",
"Deny",
"Disabled"
],
defaultValue: "Deny"
}
`

And 

`
[{](javascript:void(0))
policyDefinitionReferenceId: "StorageDenyPaasPublicIP",
policyDefinitionId: "/providers/Microsoft.Authorization/policyDefinitions/34c877ad-507e-4c82-993e-3452a6e0ad3c",
[parameters: {](javascript:void(0))
[effect: {](javascript:void(0))
value: "[parameters('StoragePublicIpDenyEffect')]"
}
},
groupNames: []
}
`

This should be really the  Storage accounts should disable public network access policy.

**Comment by Springstone** [comment]
Hi @mezzofix , thanks for sharing. The current policies being used do work and achieve the goal, but recent enhancements in available aliases have resulted in the two new policies you've proposed as enhancements that do fit better.
We'll add your suggestion to our backlog.
Thanks again.

**Comment by Springstone** [comment]
Addressing this issue in #1237
