### ISSUE TITLE
Bug Report - link to detailed networking topology is broken for Adventureworks

### ISSUE THREAD

**Issue by khushil** [Azure/Enterprise-Scale#1204]
**Describe the bug**
In the documentation at https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md there is a file referenced for 'For a detailed networking topology diagram for this reference implementation click here'. However that link (https://github.com/Azure/Enterprise-Scale/blob/main/docs/media/es-hubspoke-nw.png) gives a 404 and that file doesn't seem to exist in the repo or organisation.

**Steps to reproduce**

1. Go to https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md
2. Click link for detailed networking topology diagram

**Screenshots**

**Comment by jtracey93** [comment]
Thanks for reporting. PR #1205 will fix this once merged
