### ISSUE TITLE
Double square brackets for many policy definitions

### ISSUE THREAD

**Issue by torivara** [Azure/Enterprise-Scale#1225]
**Describe the bug**

Not sure if I am missing something here, or if there was a change in policy syntax I am not aware of.

Suddenly all the parameter references are prefixed with an additional left square bracket. There is a mention of double left square brackets in the [documentation](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-expressions#escape-characters), but I am not sure why this has been done to many of the policy definitions.

If I try to copy some of the definitions in to a GUI policy editor, it does not detect the parameters as used.

Is this a major search/replace that replaced too much? My copies of the polices from a while back did not have this issue, and somehow I can't find the commit where it was introduced.

We are currently not using these policy definitions directly, but I was doing some work on a PowerShell updater feature and suddenly many policies needed update. I just want to confirm that this is indeed an intended update before I attempt it.

**Steps to reproduce**

1. Create a new policy definition manually
2. Copy policyRule and Parameters from an affected policy definition in ALZ source (e.g. [Diag CosmosDB](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-CosmosDB.json))
3. Try to save the policy

**Screenshots**
![image](https://user-images.githubusercontent.com/16333425/220112375-487e2a2c-26ab-45fe-a25d-a06564ab85f2.png)

![image](https://user-images.githubusercontent.com/16333425/220112575-d9f47e79-a69c-4575-b109-aa7690a2a17b.png)

**Comment by jtracey93** [comment]
Hey @torivara,

Thanks for the issue. This is by design and the fix if not deploying via one of our implementation options is documented here https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide#:~:text=When%20working%20within,normal%20%2C%5B%27

The escaping is needed to support the ALZ portal expeirence.
