### ISSUE TITLE
Azure Template Specs to execute Enterprise Scale Landing Zones scripts

### ISSUE THREAD

**Issue by ZinouUser** [Azure/Enterprise-Scale#1230]
**Describe the bug**
I'm trying to use Azure Template Specs to execute Enterprise Scale Landing Zones scripts. I've specified "relativePath" property of the templateLink entity instead of uri property  to execute one sample script of ALZ in Main/Child template fashion but i got and error :
" 15:12:29 - The deployment 'LandingZoneSpecDeploy' failed with error(s). Showing 1 out of 1 error(s). Status Message:  (Code:BadRequest)  CorrelationId: e70d577b-0467-45ca-86df-d91f8da5615a"

The execution of the temlplate is done with a Powershell command. When I added the -Debug flag to get more details, i get this output :

{
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Resources/deployments/LandingZoneSpecDeploy/operations/AA9D5E28C24B6985",
      "operationId": "AA9D5E28C24B6985",
      "properties": {
        "provisioningOperation": "Create",
        "provisioningState": "Failed",
        "timestamp": "2023-02-28T14:12:24.9622562Z",
        "duration": "PT0.7306622S",
        "trackingId": "cb04fc10-0f82-4a60-9002-f9d38a2a089d",
        "statusCode": "NotFound",
        "statusMessage": {
          "status": "Failed",
          "error": {
            "code": "BadRequest",
            "message": ""
          }
        },
        "targetResource": {
          "id": "/providers/Microsoft.Management/managementGroups/Connectivity/providers/Microsoft.Resources/deployments/alz-HubSpoke-francecentral-72a64e91-690a-59dc-a014-01e639e4fd2f",
          "resourceType": "Microsoft.Resources/deployments",
          "resourceName": "alz-HubSpoke-francecentral-72a64e91-690a-59dc-a014-01e639e4fd2f"
        }
      }
    }

I think that this error is related to apiversion. Based on Microsoft documentation, the apiVersion of Microsoft.Resources/deployments must be 2020-06-01 or later.

I used "apiProfile": "2019-03-01-hybrid" in the main and child templates but i got version not supported errors.

Any idea to manage the issue of incompatibility of api-version when using Azure Template Specs.

Thank you

**Comment by jtracey93** [comment]
Hey @ZinouUser,

Template specs are not something we today have tested and therefor support for the templates in this repo.

You could increase the API version on the deployments resources, or instead look at making the ALZ-Bicep modules template specs (aka.ms/alz/bicep).

But we will not be looking to support template specs for the templates in this repo.

Thanks

Jack

**Comment by ZinouUser** [comment]
Hello @jtracey93,

Thank you for your quick reply.

I will try to increase the API version on the deployments resources.

Thanks
