### ISSUE TITLE
Deny/Block Azure OpenAI

### ISSUE THREAD

**Issue by FallenHoot** [Azure/Enterprise-Scale#1246]
Owners and Contributors can [create a request](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview#how-do-i-get-access-to-azure-openai) for Azure OpenAI Service part of Azure Cognitive Services. The issue is that not all organizations approve this service across the Azure Tenant, thus to prevent this at-scale access, we need to deny Azure OpenAI on all future subscriptions outside of the ones whitelisted for use. 

Explanation:
This policy rule will deny any deployment of Azure Cognitive Services with the "OpenAI" kind, except for the subscription specified in the "equals" field.
To apply this policy, you can use Azure Policy by creating a new policy definition with the above rule and assign it to the appropriate scope (e.g., management group, subscription, resource group, etc.). Make sure to replace "YOUR-SUBSCRIPTION-ID-HERE" with the ID of the subscription you want to allow. Once the policy is in effect, any attempt to create or use an Azure Cognitive Services OpenAI instance in any subscription except for the allowed subscription will be denied.
*Note that if you are using Azure RBAC to manage access to your resources, you will also need to assign appropriate roles to users or groups in order to allow them to access the subscription where the Azure Cognitive Services OpenAI instance is allowed.

```json
{
    "mode": "All",
    "policyRule": {
        "if": {
            "allOf": [
                {
                    "field": "type",
                    "equals": "Microsoft.CognitiveServices/accounts"
                },
                {
                    "field": "Microsoft.CognitiveServices/accounts/kind",
                    "equals": "OpenAI"
                }
            ]
        },
        "then": {
            "effect": "deny",
            "not": {
                "field": "subscriptionId",
                "equals": "YOUR-SUBSCRIPTION-ID-HERE"
            }
        }
    },
    "parameters": {}
}

**Comment by jtracey93** [comment]
Thanks for raising this. However, we will not be supporting a policy of this nature within ALZ as a definition we maintain, deploy and support for customers.

Thanks

Jack
