### ISSUE TITLE
Feature Request - `Deploy-Diagnostics-WVDHostPools` missing category `Connection Graphics Data Logs Preview`

### ISSUE THREAD

**Issue by NucLabs** [Azure/Enterprise-Scale#1250]
**Describe the bug**
The policy **Deploy-Diagnostics-WVDHostPools** is missing a recently introduced log category: **Connection Graphics Data Logs Preview**
The result is that noncompliant host pool resources will stay noncompliant after a successful remediation

**Steps to reproduce**

1. Assign the policy Deploy-Diagnostics-WVDHostPools to a resourcegroup or subscription
2. Create an AVD Host Pool or remediate an existing one.
3. Observe the remediation deployment is performed successfully.
4. The AVD Host Pool is still noncompliant, because the new log category is not selected

**Screenshots**
![image](https://user-images.githubusercontent.com/25298846/225350940-1ca4952c-8e81-45af-9d9d-da91029a94fd.png)

**Proposed solution**
Add log category **ConnectionGraphicsDataLogs** to the deployment section of the policy
I already made a custom policy my environment that works fine this way.

I can imagine that there is a policy to not include preview log categories to policies. But as shown here, it breaks the policy

**Comment by jtracey93** [comment]
Thanks for raising @NucLabs we will check with PG about how "preview" this is and then will update the policy appropriately.

**Comment by jtracey93** [comment]
@paulgrimley FYI need to get logged as user story in ADO somewhere 👍

**Comment by paulgrimley** [comment]
Logged for consideration as part of Policy refresh work AB#27325

**Comment by ReneHezser** [comment]
The policy-refresh branch will soon be merged into main.

**Comment by NucLabs** [comment]
> The policy-refresh branch will soon be merged into main.
Can somebody tell me when 'soon' is?  If I'm correct the change is not yest merged into main.

**Comment by paulgrimley** [comment]
@nuclabs the fix has been completed and is in testing, subject to not finding any major issues we are planned to release within the next few days to the ESLZ repo, we then need to update Bicep and Terraform implementations once we merge to main in this repo and that work is planned for this month.
