### ISSUE TITLE
The policy Deploy-Diagnostics-EventGridTopic does not deploy the Data Plane Operations Logs category

### ISSUE THREAD

**Issue by NucLabs** [Azure/Enterprise-Scale#1253]
**Describe the bug**
The policy definition **Deploy-Diagnostics-EventGridTopic** deploys two log categories, while the actual diagnostic setting has three categories available. Result is that "Microsoft.EventGrid/topics" resource will not reach compliant state after deployment or remediation

**Steps to reproduce**

1. Assign the policy
2. Deploy an Event Grid Topic ("Microsoft.EventGrid/topics") within the scope of the assignment
3. After a few minutes the policyDeployment kicks in, but the resource will remain noncompliant

**Screenshots**
Snippet of the policy definition
![image](https://user-images.githubusercontent.com/25298846/225657406-99bc1cf5-b6ca-4164-a90c-ef3b88e9925f.png)

Result after the policyDeployment
![image](https://user-images.githubusercontent.com/25298846/225658236-45b4e1e3-85cd-4660-9fef-a4b423275b48.png)

non-compliance reason in the portal
![image](https://user-images.githubusercontent.com/25298846/225657772-d3c56f11-6367-4601-8387-c4e9bcbce6b2.png)

**Comment by jtracey93** [comment]
AB#27340
