### ISSUE TITLE
Deploy SQL Database Transparent Data Encryption contains a bug

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#1257]
**Describe the bug**
The Enterprise Scale policy definition 'Deploy SQL Database Transparent Data Encryption' contains a bug. The existenceCondition evaluates the field Microsoft.Sql/transparentDataEncryption.status and the deployment attempts to set that field. The problem is that that field does no longer exist in more recent apiVersions. Status has been replaced with state so this policy always evaluates noncompliant see https://learn.microsoft.com/en-us/azure/templates/microsoft.sql/servers/databases/transparentdataencryption?pivots=deployment-language-bicep.

**Snippet of the existenceCondition:**

          "existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Sql/transparentDataEncryption.status",
                "equals": "Enabled"
              }
            ]
          },

**Snippet of the deployment resources:**

                "resources": [
                  {
                    "name": "[concat( parameters('sqlServerName'),'/',parameters('sqlServerDataBaseName'),'/current')]",
                    "type": "Microsoft.Sql/servers/databases/transparentDataEncryption",
                    "apiVersion": "2014-04-01",
                    "properties": {
                      "status": "Enabled"
                    }
                  }
                ],

**Export of a SQL server with TDE disabled. Note the field state instead of status:**

        {
            "type": "Microsoft.Sql/servers/databases/transparentDataEncryption",
            "apiVersion": "2022-08-01-preview",
            "name": "[concat(parameters('servers_sqlserv2023_name'), '/master/Current')]",
            "dependsOn": [
                "[resourceId('Microsoft.Sql/servers', parameters('servers_sqlserv2023_name'))]"
            ],
            "properties": {
                "state": "Disabled"
            }
        },

**Screenshots**

**Comment by pkorolo** [comment]
@jtracey93 , I have not worked with this one, I do not know if anyone /who did.

**Comment by paulgrimley** [comment]
AB#27407 created as a bug @Springstone please review 

cc: @jtracey93

**Comment by Springstone** [comment]
Addressing in PR #1264

**Comment by neok-g** [comment]
@Springstone @jtracey93 Will this new built-in policy (https://www.azadvertizer.net/azpolicyadvertizer/86a912f6-9a06-4e26-b447-11b16ba8659f.html) be included in the iniative [Deploy-Sql-Security](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Sql-Security.html) and is this part of #1264?

**Comment by jtracey93** [comment]
This is our plan, yes @neok-g

**Comment by neok-g** [comment]
> This is our plan, yes @neok-g

Thank you @jtracey93 . Do you know when this PR will be completed and merged to main? Cause then we can decide if we temporary include this built-in policy in some of our own custom initiatives.

**Comment by jtracey93** [comment]
Likely towards the end of this week, as its part of our larger policy refresh work. If not it will be next week.

**Comment by neok-g** [comment]
Any update on this one? It is not merged to main and the ALZ bicep repo yet? Thanks.

**Comment by neok-g** [comment]
Ok I thought these were synced on a daily basis with the ALZ Bicep repo but the sync is under construction?
