### ISSUE TITLE
Create and associate Service Endpoint Policy with Subnets

### ISSUE THREAD

**Issue by AmanBicep** [Azure/Enterprise-Scale#1259]
Need Module for Creation of Service Endpoint Policies 
Associate the policy with Subnet which has Service Endpoint enabled

**Comment by AmanBicep** [comment]
We need Service endpoints for Micrososft.Storage so that communication is restricted and secured.

We were able to create the polies through bicep but associations are not happening.

**Comment by stevenoneill** [comment]
The difference I understand is that Private Endpoints impose a cost Per Endpoint...which can add up quickly, in addition to the cost of data xfer (albest $0.01/gb or something like that).

Service Endpoints should be sufficient in most cases, more cost effective, and less complex to deal with.

Can this please be reconsidered instead of wontfix @jtracey93 ?

**Comment by jtracey93** [comment]
Understood @steveoneil however, nothing is preventing folks from adding their own policies on top of the ALZ ones and assigning where applicable in the hierarchy.

Also Private Endpoints have a wider service coverage and is the evolution of Service Endpoints, therefore as the ALZ team, we have aligned to the direction of using Private Endpoints.

So I'm afraid this isn't something we are looking to retro-add to ALZ

**Comment by polliard-jmfe** [comment]
I would advise you take a poll to see how widespread your user base is that leverages service endpoints (SE).  The reality is that you lose a lot of your audience by excluding service endpoints.  They are still vital within MS ecosphere and many organizations leverage them to control costs when a SE will suffice, and a PE is unneeded.  Cost is a primary driver in most large enterprises.

**Comment by jtracey93** [comment]
Thanks for the input @polliard-jmfe. For clarity, we are not saying don't use SEs in an ALZ architecture, however we are leading with private endpoints as that is the more widely adopted solution.

I will re-open this and invite yourself, @stevenoneill & @AmanBicep to provide some more clarity to your asks around SEs and ALZ, which the core team can discuss over further as there does seem to be some interest here 👍

If you can all provide some insights in comments with bullet points like the below examples, that would be great so we are clear on the asks:

- Add policy initiative to enforce Service Endpoint usage for service x to ALZ library
- Update CAF Guidance to mention SEs

Looking forward to seeing your suggestions

Thanks

Jack

**Comment by stevenoneill** [comment]
Top of mind:

- Add policies/initiatives to audit/enforce Service Endpoint usage for each valid service
- Add policies/initiatives to configure Service Endpoint on subnets for [parameter array of services]
- Update CAF Guidance metnion SE and strategy considerations -- enable surgical per service as needed or enable for all always?
- Cosolidated support matrix across services for PEs and SEs -- which services support one, the other, both, preview status, etc..

@polliard-jmfe @AmanBicep any addtional thoughts?

**Comment by JefferyMitchell** [comment]
@jtracey93 @paulgrimley Aligning ALZ to Azure Product Roadmap we focus on Azure Private Link. 

Azure landing zone principal - https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-principles#alignment-with-azure-native-design-and-roadmaps

"Use Azure-native platform services and capabilities whenever possible. This approach should align with Azure platform roadmaps to ensure that new capabilities are available within your environments. Azure platform roadmaps should help inform the migration strategy and the Azure landing zone conceptual trajectory."

In alignment with service endpoint guidance - https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview

*Note: (Microsoft recommends use of Azure Private Link for secure and private access to services hosted on Azure platform. For more information, see [Azure Private Link](https://learn.microsoft.com/en-us/azure/private-link/private-link-overview)."

**Comment by stevenoneill** [comment]
There are sections of CAF which indicate Service Endpoint could be a preferred given the need.  For example, AIS landing zone...

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/integration-services/network-topology-and-connectivity#connectivity-to-ais-paas-services

![image](https://user-images.githubusercontent.com/15053495/232535794-0db32734-87f6-4f4f-a17e-68ddcc9782d0.png)

**Comment by JefferyMitchell** [comment]
@kunalbabre Can we get this updated in AIS landing zones guidance as well.

**Comment by kunalbabre** [comment]
@JefferyMitchell , @stevenoneill  thank you for flagging, we will address this soon.

**Comment by kunalbabre** [comment]
PR raised: https://github.com/MicrosoftDocs/cloud-adoption-framework/pull/1123

**Comment by stevenoneill** [comment]
Kinda figured that could be the outcome of my post, ha.  Still feels like the unwritten messaging here is that Service Endpoints will be deprecated at some point, adopt PEs today.  And that cost is not a factor with private networking considerations.  SEs are a great way to balance things out and feel like they don't get enough love in the CAF/ALZ docs.
