### ISSUE TITLE
Bug Report - deployment to AZGOV fails.

### ISSUE THREAD

**Issue by Schutzhund3** [Azure/Enterprise-Scale#1279]
**Describe the bug**
I had deployed LZ a few times in the past for testing - but for different reasons removed it. I think I may have also removed some policies in the process. Now when I try to deploy in AzureGov I get:
"The element for [steps('lzSettings').denyClassicResources] could not be found in the createuidefinition" when clicking on the 'Deploy to AzureGov'.

**Steps to reproduce**

1. click 'Deploy to AzureGov' on main page.
2.

**Screenshots**

**Comment by Springstone** [comment]
Hi @Schutzhund3, thank you for raising this. Denying the deployment of classic resources is a new policy, and there may be an issue in Azure Gov.  We'll review this issue and provide feedback asap.

**Comment by Schutzhund3** [comment]
I am deploying via the portal accelerator.

**Comment by Springstone** [comment]
@Schutzhund3 many thanks. I've found the issue and have a PR pending to fix this issue: https://github.com/Azure/Enterprise-Scale/pull/1293

**Comment by Springstone** [comment]
@Schutzhund3 we have merged the fix and tested the portal accelerator successfully.
