### ISSUE TITLE
How to remove policy assignments?

### ISSUE THREAD

**Issue by azMantas** [Azure/Enterprise-Scale#128]
**Describe the bug**

Every single time I try to remove a policy assignment via push workflow, "system commit" restores everything back. I have tried to remove assignment from policyAssignments at _Microsoft.Management-managementGroups_  as well as delete entire _Microsoft.Authorization_policyAssignments..._ file but no luck.
I am only able to delete assignment at the portal and then make a pull to my repo. Is it the only way to remove policy assignments?

**Screenshots**
![image](https://user-images.githubusercontent.com/47916866/88842124-4a23e500-d1df-11ea-9d2d-3dbd8fe4600a.png)

**Comment by uday31in** [comment]
ARM do not support "complete" mode at Management group scope and hence it is not possible to delete assignments/definitions via ARM.  We are looking at ways to enable deletion and will update this issue once we have design proposal. In the meantime, please use other ways to delete the assignment and run the refresh to ensure deletion are tracked in Git.

```gh api -X POST repos/<github_username>/<repository_name>/dispatches --field event_type="GitHub CLI"```
