### ISSUE TITLE
Deployment failed, RoleAssignmentUpdateNotPermitted

### ISSUE THREAD

**Issue by cyb3n3tic** [Azure/Enterprise-Scale#1280]
We have attempted to deploy a landing zone via the portal but due to problems with subscriptions the initial successful deployment had to be destroyed. Subsequent deployments are failing on alz-SqlAuditRbac1 and alz-SqlAuditRbac2, both showing conflict and the same detail -  "DeploymentFailed", "BadRequest", "RoleAssignmentUpdateNotPermitted\" "Tenant ID, application ID, principal ID, and scope are not allowed to be updated"

Reading around it seems to relate to needing to clean up existing roles and assignments in the subscriptions but there aren't any assignments other than Owner etc that are inherited. I can't work out where the problem is?

Any suggestions as how best to proceed to cleanup and redeploy? We have been deleting the resource group and management groups created each time, reusing the same subscriptions. Worst case scenario we could create new subscriptions I suppose, but better if we don't have to ideally.

There are production workloads in the environment so approach is suitably cautious.

Thanks in advance.

**Comment by charlesderber** [comment]
You might need to clean up manually from the IAM area for specific RG, subscriptions or management group the system identity which got deleted when you removed Azure policies which had deny or deploy if not exist effect. Deleted system identities wont be there in Azure AD but will show up in IAM as not found Identity object

**Comment by Springstone** [comment]
When you do the cleanup, you need to go to the "platform" subscription (not the management group) and delete orphaned identities (Identity Not Found) under IAM Role Assignments.
There are two managed identities that get orphaned when you do this cleanup in that subscription (I can't remember the roles off hand).

**Comment by cyb3n3tic** [comment]
OK, thanks - will see if more can be discovered via cli and failing that will blow away the subscriptions also for a totally clean slate as the subs are the only aspects that remain from the failed deployments.

**Comment by jtracey93** [comment]
any update here @cyb3n3tic?

**Comment by cyb3n3tic** [comment]
We found one orphaned role assignment using cli but the subsequent deployment still failed. Likely we'll create new subscriptions and start again I think as most expedient. I'll close this issue now though, no need to leave open.

Thanks all

**Comment by jtracey93** [comment]
No worries. Thanks for responding @cyb3n3tic.

You are welcome to use my personal script that I wrote to clear down an ALZ deployment, including orphaned role assignments on subscriptions in the Management Group hierarchy if you wish: https://github.com/jtracey93/PublicScripts/tree/master/Azure/PowerShell/Enterprise-scale

**USE AT YOUR OWN RISK AND READ THE INSTRUCTIONS - IT WILL DELETE ALL RESORUCES IN THE SUBSCRIPTIONS BY DESIGN**

**Comment by cyb3n3tic** [comment]
Thanks Jack, I have been wary to do so as this is a production account and I am risk averse so opted for manual clean up so far

**Comment by cyb3n3tic** [comment]
Thanks for the assistance
