### ISSUE TITLE
Azure Landing Zones - Community Call - 25th September 2023

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#1287]
![ALZ Community Call - September 2023](https://user-images.githubusercontent.com/41163455/233429845-83fa531a-5d36-48cb-bd6d-e5a8779e18d2.png)

We are excited to invite you to our 6th external Azure Landing Zones community call on the 25th of September 2023 @ 17:00 CET! (16:00 UK/BST - 11:00 EST - 08:00 PST - 01:00 ACT)

> As always this will be recorded and published to the [CAE YouTube Channel](https://aka.ms/caeyoutube) and shared via our [community calls wiki page](https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls) 👍

As before we have an open agenda, so please comment below with things you would like to cover or any questions you have👍

### Agenda:

- TBC
- Q&A (please raise topics and questions to discuss in this issue)

### Registration

**Sign up for the call** [here!](https://msit.events.teams.microsoft.com/event/06040365-2c03-4b4e-98f9-510c2c122554@72f988bf-86f1-41af-91ab-2d7cd011db47)

### Round-up

We look forward to another interactive discussion with lots interesting topics!

**For links to our previous community calls see:** [https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls](https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls)

> **Note: We fully intend to run these at least quarterly in 2023 👍**

**Comment by YSDimov** [comment]
Should we expect any tactical changes in Microsoft strategy to support terraform, terraform modules after Hashicorp software license changed?

**Comment by matt-FFFFFF** [comment]
> Should we expect any tactical changes in Microsoft strategy to support terraform, terraform modules after Hashicorp software license changed?

We are continuing to work with Hashicorp closely to ensure that our customers can be successful on Azure using their tools. We are not planning to make any changes at this time.

See https://www.hashicorp.com/license-faq#impact-on-terraform-providers
