### ISSUE TITLE
Policy definition for Front door diagnostic logs only works against Front Door classic

### ISSUE THREAD

**Issue by tlfzhylj** [Azure/Enterprise-Scale#1288]
**Describe the bug**
The policy definition "Deploy Diagnostic Settings for Front Door to Log Analytics workspace don't work against new Front Door.

The definition only enable logging for Front Door classic.

https://www.azadvertizer.net/azpolicyadvertizer/Deploy-Diagnostics-FrontDoor.html

**Screenshots**
![](https://user-images.githubusercontent.com/29739663/233611713-f3eae0c2-3bc0-42b3-9101-b616df7561f6.png)

![](https://user-images.githubusercontent.com/29739663/233611735-26d4a0ff-2417-4364-93ca-dfa4fc728e5b.png)

**Comment by jtracey93** [comment]
Thanks @tlfzhylj, we will triage and address.

Looping in @Springstone & @paulgrimley

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
