### ISSUE TITLE
[Preview]: Deploy Dependency agent to be enabled on Windows virtual machines with Azure Monitoring Agent settings does not get triggered

### ISSUE THREAD

**Issue by MarcelHeek** [Azure/Enterprise-Scale#1301]
**Describe the bug**
On a 2022-datacenter sku VM with the policy intitiative `[Preview]: Enable Azure Monitor for VMs with Azure Monitoring Agent(AMA)` assigned that gets the AMA agent deployed, does not get the dependency agent installation triggered.
The VM is not identified as an incompliant resource. 

The Policy definition appears to be missing the 2022-* imagesku types 

**Steps to reproduce**

1. Assign policy initiative `[Preview]: Enable Azure Monitor for VMs with Azure Monitoring Agent(AMA)` to a certain scope
2. Deploy marketplace VM of sku type 2022-datacenter
3. The AMA Agent, user assigned identity and DCR are deployed for the VM
4. However the Dependency agent is not although the assignment parameter  "Enable Process and Dependencies" are set to true.

**Screenshots**
Evidence that the policy does not produce any incompliant resource the deploy to
![image](https://user-images.githubusercontent.com/84451910/235433586-7f743589-81dd-4663-a8e8-1e7b811bc462.png)

**Comment by Springstone** [comment]
Hi @MarcelHeek. Please note we have little influence on built-in policies and cannot fix these. I would recommend you open a support ticket in Azure for this issue.

That being said, this is a known issue and impacts custom gallery images as well as migrated virtual machines, and as you've correctly identified an incomplete list of SKUs. There is an update to this policy on the way that will allow you to skip the OS/SKU check (a flag is provided), which should arrive very soon.

**Comment by Springstone** [comment]
Hi @MarcelHeek FYI we are following up with the policy owners on this. Unfortunately, it isn't something we can fix on short notice, and this will probably take a while to resolve. Will keep you posted. Thanks for highlighting the issue!

**Comment by cloxleywatkins** [comment]
Similar issue here, do we know when this might be resolved?

**Comment by Springstone** [comment]
Hi @MarcelHeek, @cloxleywatkins, this has now been resolved as of a few weeks ago. Please use the new initiative https://www.azadvertizer.net/azpolicyinitiativesadvertizer/924bfe3a-762f-40e7-86dd-5c8b95eb09e6.html

Note: the parameter scopeToSupportedImages to skip the OS version check.
