### ISSUE TITLE
How can I disable the continous export policy for Defender for Cloud?

### ISSUE THREAD

**Issue by tlfzhylj** [Azure/Enterprise-Scale#1305]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: n/a

**azure provider**: n/a

**module**: 3.3.0

#### Describe the bug

Is it possible to remove the continious export configuration in Defender for Cloud + the policy which create the resource group which holds the Defender for cloud export configuration?

I still want Defender for Cloud to be enabled, but I don't need the continious export.

**Comment by matt-FFFFFF** [comment]
Tagging @paulgrimley and @Springstone

**Comment by Springstone** [comment]
Hello @tlfzhylj, that you for raising the issue. Unfortunately, the policy that configures continuous export does not have an effect property (which would allow us to parameterize whether it's enabled): https://www.azadvertizer.net/azpolicyadvertizer/ffb6f416-7bd2-4488-8828-56585fef2be9.html
We will reach out to the policy owner and ask that they include the `effect` parameter, but this may take a while to resolve.

As a short-term workaround, you can use an override on the assignment to disable that policy: 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/2101287/236425588-8d1adda4-e31e-4ae7-aace-24583fc221d7.png">
Future subscriptions moved into ALZ management groups will not configure continuous export.

**Comment by tlfzhylj** [comment]
Thank you, @Springstone. It sounds like an okey workaround.

It'd be great if this gets parameterized.

**Comment by Springstone** [comment]
@tlfzhylj we've raised feedback to engineering, but it will be while to be addressed (or may not be). As there isn't much more we can do, and have provided a workaround, I will be closing the issue. Feel free to raise a new issue if this is causing pain with additional context.
