### ISSUE TITLE
Include more log categories for PostgreSQL Flexible Servers in policy for diagnostic setting

### ISSUE THREAD

**Issue by chrholt** [Azure/Enterprise-Scale#1309]
**Describe the solution you'd like**
Add more log categories in the diagnostic settting policy for postgreSQL flexible servers.
In this policy it is only "PostgreSQLLogs" category that exists - [Deploy-Diagnostics-PostgreSQL.json#L166](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-PostgreSQL.json#L166).

I suggest adding these log categories for Flexible Servers:

- PostgreSQLFlexSessions
- PostgreSQLFlexQueryStoreRuntime
- PostgreSQLFlexQueryStoreWaitStats
- PostgreSQLFlexTableStats
- PostgreSQLFlexDatabaseXacts

Because of the existenceCondition this policy will also always be non-compliant due to checking if all logs are enabled
`{
       "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",
       "equals": "true"
 }`

**Comment by Springstone** [comment]
Hi @chrholt! Thanks for raising the issue. A couple of things to ask and share. 
First, I'm curious where you are getting the list of categories from, as I deployed a new PostgreSQL flexbile server and have a different list of categories available (this list may have changed recently - are you checking an existing deployment):
<img width="383" alt="image" src="https://github.com/Azure/Enterprise-Scale/assets/2101287/5020a24a-37bd-4c0b-80ba-f3c024f684c7">

Second, and more importantly, product owners and our policy teams are enhancing diagnostic settings policies for Azure services based on categories (as an example see https://www.azadvertizer.net/azpolicyadvertizer/6567d3f3-42d0-4cfb-9606-9741ba60fa07.html). Unfortunately, PostgreSQL has not been given the needed love as yet. This work is ongoing as something we in ALZ collectively refer to as "Diagnostic Settings v2", and we're hoping to see this implemented for all services over the next several months. 

As part of our overall strategy going forward, we prefer `built-in` policies maintained by service owners, over maintaining `custom` policies that need regular maintenance, so we are generally holding off until the new diagnostics settings policies are available. 

If there is an urgent need for this, we can look at updating the existing `custom` to include all log sources available, something like:
```
Microsoft.Insights/diagnosticSettings/logs[*]
```

Our recommendation is to wait for the official `built-in` policies, but will do our best to ensure your requirements are addressed.

**Comment by chrholt** [comment]
We can manage without for now, knowing that changes are coming. Thanks.

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
