### ISSUE TITLE
Feature Request ALZ/ELSZ Policies

### ISSUE THREAD

**Issue by Acenl12** [Azure/Enterprise-Scale#1315]
I would like an azure policy imitative with all CAF azure policies so it's easily assignable to existing environments. Current it's a lot of work with enterprise policy as code or bicep @jtracey93
Ideally all the policies in `src/resources/Microsoft.Authorization/policyDefinitions` would be included in an initative.

**Comment by jtracey93** [comment]
Hello @Acenl12 

Thanks for the feature request.

This is something we will not be able to provide im afraid as anyone who consumes it, would suffer a lot of breaking changes as we update it with new policies and remove old ones etc.

Plus this goes against the way in ALZ which we say to use policies, simply grouping everything in one initative, whilst may seem like a good idea at first, is frought with danger and we are likely to hit policy initative limits.

Therefore this is something we will not look to be adding to ALZ.

You can however use the ALZ Bicep modules to load all the definitions we provide to any target management group, specifically the [`customPolicyDefinitions.bicep`](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions) module.

You can then use the [`alzDefaultPolicyAssignments.bicep`](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults) module and amend it, and take inspiration from, to assign all the default policy assignments to your management group hierarchy, will require customization if not usin ALZ hierarchy.

Thanks

Jack
