### ISSUE TITLE
Deny-MgmtPorts-From-Internet causes error on rules with port ranges

### ISSUE THREAD

**Issue by DavidRobson** [Azure/Enterprise-Scale#1318]
**Describe the bug**
After implementing Deny-MgmtPorts-From-Internet in Audit mode, cannot save an NSG rule that has a management port and also a port range. Get the following error in the portal:

Error: A function or parameter in policy assignment 'Deny-MgmtPorts-Internet' associated with the policy definition 'Deny-MgmtPorts-From-Internet' could not be validated. Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner error is 'The provided arguments for template language function 'lessOrEquals' is not valid: all function arguments should be of numeric types. Please see https://aka.ms/arm-template-expressions#lessOrEquals for usage details.'.

**Steps to reproduce**

1. Deploy the Deny-MgmtPorts-From-Internet policy in Audit mode
2. Try to create a new NSG rule from an IP address and put the port range as "3389,1234-1235"
3. This will result in an error and the rule cannot be saved

**Screenshots**
![New NSG Rule](https://github.com/Azure/Enterprise-Scale/assets/1055155/48787626-cba2-4193-abe5-37623c2a8914)
![New NSG Rule Error](https://github.com/Azure/Enterprise-Scale/assets/1055155/128da183-e69d-4b4e-81ac-aee620c92583)

**Comment by buckinghamjf** [comment]
Hi Dave,

Based on very little knowledge of the solution you are trying to setup, i
would create a new rule, number 4096 with a name of deny_all which will
null and void the preconfigured rules.  Once done, then create rules for
just those ports that are specifically.  Also when blocking from Internet,
instead of using ip address as the parameter,  use tag and pick Internet
from the azure list of options, hopefully helps.

If no luck, you have my private email I think, if it's the D Robson I used
to work with, drop me an email and I can take a look if you like.

Kind Regards

Jason Buckingham

**Comment by DavidRobson** [comment]
Hi @buckinghamjf,

Not sure if it's the same D Robson - I am at Quest Software?

Yes I can work around the issue by tweaking my rules to not include 3389 and a port range in the one rule (split them into two rules).

The problem is the users were complaining that this worked before and now doesn't. It seems to be a bug in the rule defined in this repository. I haven't had time to see if I can fix the rule myself yet. I will see if I can tweak it and open a PR.

For reference here is the PR that added the policy we are having an issue with: https://github.com/Azure/Enterprise-Scale/pull/1247

Looks like it was written by @Springstone - not sure if you tested this particular use case?

**Comment by Springstone** [comment]
Hi @DavidRobson, thanks for raising this issue. I will do some testing around the scenario; I did test extensively for Deny which was the main requirement. Could you validate if you use the policy with Deny, but on the assignment, change Enforcement Mode to "Do not enforce". This should still audit but not block (deny).

**Comment by Springstone** [comment]
@DavidRobson again, many thanks for raising the issue, it is only through contributions like yours that we can continue to make ALZ better for all. PR #1323 should fix your issue. As an additional callout, I would recommend using assignment "do not enforce" on DENY policies if you only want to audit - this is a better mechanism in general for auditing on deny policies.

**Comment by DavidRobson** [comment]
@Springstone I have deployed this new policy and it's working as expected in our environment. Thanks for fixing it up.
I also moved to do not enforce as you suggested.
