### ISSUE TITLE
Azure landing zone accelerator missing config page to Integrate your Azure environment with GitHub 

### ISSUE THREAD

**Issue by W0GER** [Azure/Enterprise-Scale#1319]
**Describe the bug**
Following the guidance from here:
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/wingtip/README.md

Specifically: 
> What will be deployed?
> (Optionally) Integrate your Azure environment with GitHub (Azure DevOps will come later), where you provide the PA Token to create a new repository and automatically discover and merge your deployment into Git.

Not sure if I'm missing something, but I don't see a way to configure the GitHub PA Token. 

**Steps to reproduce**

1. Start the Azure landing zone accelerator - I'm using the url from the button at the top of the page noted above: https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json
2. Step through the tabs/pages:
2.1 Deployment Settings
2.2 Azure Core Setup
2.3 Platform management, security, and governance
2.4 Network topology and connectivity
2.5 Identity
2.6 Landing zones configuration
2.7 Decommissioned/Sandbox
2.8 Review + create

Expected: Tab/page to configure the GitHub connection

**Screenshots**
<img width="1580" alt="image" src="https://github.com/Azure/Enterprise-Scale/assets/11900533/24499ae8-db9d-4b84-89d7-a1750d527e48">

**Comment by jtracey93** [comment]
@pkorolo can you update the docs please for this one?

@W0GER we have removed the "Platform DevOps and automation" section last week as per the whats new page: https://aka.ms/alz/whatsnew and https://github.com/Azure/Enterprise-Scale/wiki/Deploying-ALZ-Platform-DevOps#operating-the-azure-platform-using-azops-infrastructure-as-code-with-github-actions

You can still use AzOps if desired, by following the setup steps from the AzOps repos as linked to on the page: https://github.com/Azure/Enterprise-Scale/wiki/Deploying-ALZ-Platform-DevOps#operating-the-azure-platform-using-azops-infrastructure-as-code-with-github-actions

Thanks

**Comment by pkorolo** [comment]
@W0GER thank you for bringing this to our attention.

@jtracey93 will deal with this asap.

**Comment by pkorolo** [comment]
@W0GER I have submitted PR to iron-out the documentation deployment guidance redundancies, to so avoid future confusion.
As @jtracey93 pointed out, AzOps GH integration has been removed from ALZ portal experience.

**Comment by pkorolo** [comment]
PR tbr
