### ISSUE TITLE
Bug Report: Deny Virtual Machines and Virtual Machine Scale Sets from not using OS Managed Disks

### ISSUE THREAD

**Issue by anwather** [Azure/Enterprise-Scale#1320]
The override in the policy assignment is invalid - because the original policy does not contain a DENY effect.

**Steps to reproduce**

1. From the policy assignment
```
"overrides":[
                    {
                        "kind": "policyEffect",
                        "value": "Deny"
                    }
                ]
```
2. From the policy definition there is no parameter for effect - it is just an audit policy.

Could be fixed by duplicating the policy definition and adding an effect parameter containing a deny.

**Comment by jtracey93** [comment]
Hey @anwather, this policy works as intended and is assigned by default. You dont need an effect parameter to use overrides, if there is one it must be in the allowed values (if specfied) but its not required.

As per https://learn.microsoft.com/en-gb/azure/governance/policy/concepts/assignment-structure#overrides-preview
