### ISSUE TITLE
Getting BadRequest (ExtendedCode: 51008) with adding Connection Strings to WebApp. Possible custom policy issues

### ISSUE THREAD

**Issue by har-singh** [Azure/Enterprise-Scale#1326]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.3.5 (also tested with v1.4.5)

**azure provider**: v3.53.0

**module**: 3.3.0

### Description

When trying to add Connection Strings to the Web App we are getting `Status=400 Code="BadRequest"`.

```json
{
  "Code": "BadRequest",
  "Message": "The parameter properties has an invalid value.",
  "Target": null,
  "Details": [
    {
      "Message": "The parameter properties has an invalid value."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "51008",
        "MessageTemplate": "The parameter {0} has an invalid value.",
        "Parameters": [
          "properties"
        ],
        "Code": "BadRequest",
        "Message": "The parameter properties has an invalid value."
      }
    }
  ],
  "Innererror": null
}
```

As soon as the TLS policy **AppService append sites with minimum TLS version to enforce.** is disabled the Connection Strings gets created.

#### Steps to Reproduce

1. Create WebApp with Connection Strings:

```terraform
resource "azurerm_windows_web_app" "web_app" {
  name                = "web_app_62"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_service_plan.web_app_service.location
  service_plan_id     = azurerm_service_plan.web_app_service.id
  https_only          = true
  app_settings        = { "minTlsVersion" = "1.2" }

  site_config {
    minimum_tls_version     = 1.2
    ftps_state              = "Disabled"
    http2_enabled           = true
    scm_minimum_tls_version = 1.2
    always_on               = false
  }

  lifecycle {
    ignore_changes = [
      tags["cost_centre"], site_config
    ]
  }

  connection_string {
    name  = "ConnStr"
    type  = "SQLServer"
    value = "key: value; key1: value"
  }
}
```

#### Additional context

Landing Zone deployed with **archetype_id: es_corp_custom_lz**.

For testing we removed the policy **Append-AppService-latestTLS** from the initiative and it works . It also works when the "effect" parameter is set to "Disabled" instead of "Append" during the assignment of the policy.

**Comment by matt-FFFFFF** [comment]
Tagging @Springstone for attention
