### ISSUE TITLE
Bug Report: Sandbox and Corp denies different gateway resources 

### ISSUE THREAD

**Issue by picccard** [Azure/Enterprise-Scale#1333]
## Question
There is a difference in the listOfResourceTypesNotAllowed for Corp and Sandbox (when deploying ALZ-Bicep).
Should Corp and Sandbox deny the same list of resource? If not could, the description for these assignments differ to express this.
E.g., in Sandbox VirtualNetworkGateways are allowed, but not in Corp. 

# Description
On the wiki page [ALZ-Policies.md](https://github.com/Azure/Enterprise-Scale/blob/0c6b33011bf0129f860a4253e17496bec36c9d35/docs/wiki/ALZ-Policies.md)

```text
Assignment Name: "Enforce ALZ Sandbox Guardrails"
Description: "Deny the deployment of vWAN/ER/VPN gateways."

Assignment Name: "Deny the deployment of vWAN/ER/VPN gateway resources"
Description: "... Denies deployment of vWAN/ER/VPN gateway resources in the Corp landing zone."
```

Both descriptions mentions "... deployment of vWAN/ER/VPN gateway..."
But when deploying the ALZ-Bicep modules there is a difference in the listOfResourceTypesNotAllowed.

Corp mg-group [ALZ-Bicep-assignment](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_deny_hybridnetworking.tmpl.json):
```json
"listOfResourceTypesNotAllowed": {
  "value": [
    "microsoft.network/expressroutecircuits",
    "microsoft.network/expressroutegateways",
    "microsoft.network/expressrouteports",
    "microsoft.network/virtualwans",
    "microsoft.network/vpngateways",
    "microsoft.network/p2svpngateways",
    "microsoft.network/vpnsites",
    "microsoft.network/virtualnetworkgateways"
  ]
}
```

Sandbox mg-group [ALZ-Bicep-assignment](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/assignments/lib/policy_assignments/policy_assignment_es_enforce_alz_sandbox.tmpl.json) and the [Enterprice-Scale template](https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-ALZ-SandboxPolicyAssignment.json):

```json
"listOfResourceTypesNotAllowed": {
  "value": [
    "microsoft.network/expressroutecircuits",
    "microsoft.network/expressroutegateways",
    "microsoft.network/virtualwans",
    "microsoft.network/virtualhubs",
    "microsoft.network/vpngateways",
    "microsoft.network/vpnsites"
  ]
}
```

**Comment by Springstone** [comment]
@picccard Thanks for raising this, we'll review and remediate asap.

**Comment by Springstone** [comment]
Addressed in PR #1336

**Comment by picccard** [comment]
Both the description and assingment name that is beeing quoted is from [ this wiki page](https://github.com/Azure/Enterprise-Scale/blob/0c6b33011bf0129f860a4253e17496bec36c9d35/docs/wiki/ALZ-Policies.md).

**Comment by Springstone** [comment]
Got it! Understand the context now. In any case, it is a valid issue, and we have a PR in to address consistency. Many thanks for raising the issue.
