### ISSUE TITLE
Why does the module create and RBAC-assign so many app's with Contributor rights?

### ISSUE THREAD

**Issue by binaryPUNCH** [Azure/Enterprise-Scale#1348]
Hello!

Question: why does this module create so many service principals (managed identities) with Contributor rights? Is that truly necessary? I suspect it grants policies the permissions required to remediate. 

Could you explain why Contributor and not something more specific? Isn't this a theoretical attack vector, or can we trust that only the Azure Policy engine can authorize as it? This is on the management group level so inherited on all landing zone subscriptions, hence the concern.

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/1857719/dc9b1891-7c12-4971-9a9e-ee64ca6e67ef)

Thanks!

**Comment by matt-FFFFFF** [comment]
Hi @binaryPUNCH 

We plan to use the correct role definitions defined in the policy definition in the next version of the ALZ module - see the new example 

We will also support the additional scopes, as defined by the assignPermissions metadata property. For example granting access to a resource that's outside the scope of the policy assignment.

See https://GitHub.com/Azure/terraform-AzureRM-alz for a mock up

**Comment by paulgrimley** [comment]
Discussed in the Policy weekly review call and this (review) will be picked up in next policy refresh (July - September) @Springstone

**Comment by jikuja** [comment]
Question about implentation: Is the plan to use tenant-scoped role-definition from policy's `roleDefinitionIds` directly, extract only GUIDs from `roleDefinitionIds` or something else?

**Comment by jtracey93** [comment]
We will indeed use the roles from the policy definitions, and validate that they are correct and work before releasing in ALZ

**Comment by Springstone** [comment]
@binaryPUNCH @jikuja we have remediated all ALZ policies and assignments using excessive RBAC roles to be least privilege aligned, as far as possible. Please do note though, that Defender for Cloud policies are now using Owner (we have queried this, but this is deliberate due to the nature of those resources).
