### ISSUE TITLE
Bug Report - Custom policy Deploy-Sql-vulnerabilityAssessments does not remediate correctly

### ISSUE THREAD

**Issue by mwmeehan** [Azure/Enterprise-Scale#1355]
**Describe the bug**

When trying to remediate, it will show as successful but not actually remediate.  The issue we are running into is the parameter "vulnerabilityAssessmentsEmail" is shown as a string, but the master sql database produces an array for recurring emails.  The policy continues to show non-compliant because the master sql database vulnerability assessment email has an array and the policy is looking for a string.

We attempted to change it to "Array" or "[ String ]" and that breaks the custom policy

**Steps to reproduce**

1. Run remediation task
2. Remediation shows successful but does not actually change vulnerability settings and email is an Array but policy looks for String.

**Screenshots**
![image](https://github.com/Azure/Enterprise-Scale/assets/116912396/d5bf3c0a-4bda-4a62-be00-aa51ff7726a9)
![image](https://github.com/Azure/Enterprise-Scale/assets/116912396/51b9656b-12e5-4d49-a00d-e8d3ec4d5123)

**Comment by jtracey93** [comment]
@springstone can you take a look please

**Comment by mwmeehan** [comment]
Checking in to see if there is any update on this?

**Comment by jtracey93** [comment]
@mwmeehan, this has made it into our next quarters (starting next week) policy refresh cycle. We will start triaging these issues next week to identify next steps :)

**Comment by Springstone** [comment]
Hi @mwmeehan, think I have it sorted now with help from @matt-FFFFFF. PR going in to remediate the issue, however, it requires a new policy as parameters are changing (string to array). The original policy will remain as is, but will be deprecated as part of the PR, and a new policy will replace it (appended with a guid octet). 
Please let us know if it meets your expectations, I have limited time/ability to test all scenarios.
I'll close this issue once we merge to main, but feel free to re-open or create a new issue if there is still a problem.
