### ISSUE TITLE
Recommendation on default registered Azure Subscription Resource Providers

### ISSUE THREAD

**Issue by stefanstranger** [Azure/Enterprise-Scale#1356]
To enable the deployment of certain Azure Resources, Azure Resource Providers need to be registered. 

Not all Resource Providers are registered when deploying an new Landing Zone (Azure Subscription).

A recommended default list of to be registered Resource Providers would be helpful.

Regards,
Stefan Stranger [MSFT]

**Comment by matt-FFFFFF** [comment]
AzureRM registers these:

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/resourceproviders/required.go

**Comment by jtracey93** [comment]
Yup i thought as much, is it the same for AzApi as well?

Still need to document though as we have seen this cause issues for customers. Any others to add to the list?

**Comment by oZakari** [comment]
AzApi is separate from AzureRM

https://registry.terraform.io/providers/Azure/azapi/latest

**Comment by matt-FFFFFF** [comment]
> AzApi is separate from AzureRM
> 
> 
> 
> https://registry.terraform.io/providers/Azure/azapi/latest

Yes, it also registers providers. I think it does this when it goes to create/read a resource in a given RP. So, before making the GET/PUT it will register the provider.

**Comment by matt-FFFFFF** [comment]
> > AzApi is separate from AzureRM
> > 
> > 
> > 
> > https://registry.terraform.io/providers/Azure/azapi/latest
> 
> Yes, it also registers providers. I think it does this when it goes to create/read a resource in a given RP. So, before making the GET/PUT it will register the provider.

This is handled by the new Go SDK for Azure

https://github.com/Azure/terraform-provider-azapi/issues/82#issuecomment-1095749366

**Comment by matt-FFFFFF** [comment]
> Yup i thought as much, is it the same for AzApi as well?
> 
> 
> 
> Still need to document though as we have seen this cause issues for customers. Any others to add to the list?

Would we just copy the TF one? They've come up with that list to ensure the fewest issues.

**Comment by Springstone** [comment]
@jtracey93 @matt-FFFFFF any further input / discussion required here?

**Comment by matt-FFFFFF** [comment]
The CAF-enterprise-scale uses AzureRM and will therefore register RPs for all platform subscriptions

**Comment by jtracey93** [comment]
guidance provided here: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Resource-Provider-Recommendations
