### ISSUE TITLE
Deny-MgmtPorts-From-Internet does not always block NSG creation

### ISSUE THREAD

**Issue by DavidRobson** [Azure/Enterprise-Scale#1357]
**Describe the bug**
Policy is set to Deny and Enforce. We want to block any NSGs from being exposed to the internet on management ports.
If you try and add a rule to an existing NSG, it is blocked as expected.
If you deploy a new NSG with the rule defined, it bypasses the policy and lets you create the NSG. The policy then flags this rule, but it should be blocked.
This happens via the Azure Portal or via Bicep.

**Steps to reproduce**
This bicep script is blocked as expected, because the rules are split from the NSG creation.
```
resource testNsg 'Microsoft.Network/networkSecurityGroups@2022-07-01' = {
  name: 'nsg-test2'
  location: 'westus2'
}

resource testNsgRules 'Microsoft.Network/networkSecurityGroups/securityRules@2022-07-01' = {
  name: 'RDP'
  parent: testNsg
  properties: {
    access: 'Allow'
    description: 'Allow RDP'
    destinationAddressPrefix: '*'
    destinationPortRange: '3389'
    direction: 'Inbound'
    priority: 100
    protocol: '*'
    sourceAddressPrefix: '*'
    sourcePortRange: '*'
  }
}
```
If you instead put the rules in the initial creation, it creates the NSG successfully and bypasses the policy.
```
resource testNsg 'Microsoft.Network/networkSecurityGroups@2022-07-01' = {
  name: 'nsg-test'
  location: 'westus2'
  properties: {
    securityRules: [
      {
        name: 'RDP'
        properties: {
          access: 'Allow'
          description: 'Allow RDP'
          destinationAddressPrefix: '*'
          destinationPortRange: '3389'
          direction: 'Inbound'
          priority: 100
          protocol: '*'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
        }
      }
    ]
  }
}
```

**Screenshots**
You can see the NSG was created and bypassed the policy.
![image](https://github.com/Azure/Enterprise-Scale/assets/1055155/075ec5d1-30cf-4dea-bbef-7b9e267f36d7)

**Comment by jtracey93** [comment]
@Springstone can you take a look please

**Comment by Springstone** [comment]
Hi @DavidRobson, thanks for raising this. It looks like there is an issue with policy evaluation logic, as the policy should detect this. Let me investigate further, will keep you posted.

**Comment by DavidRobson** [comment]
I have logged an Azure support case as well - not sure if it's something that can be fixed in the policy or on their end. So far haven't got far with them but will let you know if they come up with anything.

**Comment by DavidRobson** [comment]
So I did some testing, it seems if you modify the policy to apply to type "Microsoft.Network/networkSecurityGroups" instead (and modify it to use counts etc appropriately) then it blocks the other use case.
So basically one policy blocks one use case, another blocks the other.

I tend to agree it's a bug in the policy evaluation logic, but so far having no luck with MS support. Do you think they would ever fix it?
I think in theory we could make a policy that included both to cover both use cases. It would make the already complicated policy twice as complicated again, but I think that might be the only way aside from trying to get MS to fix the policy engine?

@Springstone what do you think the next steps should be? I am pretty keen to get this fixed - I guess we should confirm with MS if they'll ever fix the policy engine. If they say they won't do you accept PRs on this repository or is it something you could easily fix?

**Comment by Springstone** [comment]
Hi @DavidRobson, I'm currently trying to expand on the policy to include 'Microsoft.Network/networkSecurityGroups', as it looks like this resource also needs to be evaluated to catch your scenario but having a few challenges. If you could share you policy rule that works in your scenario, that may be very helpful.

**Comment by DavidRobson** [comment]
Yeah sounds the same as what I came up with. I got it working for the simple use cases - but those array ones I didn't get working yet. It goes from being 2 layers of arrays to 3 layers so steps up the complexity a bit! I will see how I go if I can get it to work before you fix it I'll let you know.
As you can tell we are really stress testing this policy for you at the moment :)

**Comment by Springstone** [comment]
I have the basics working now, but as you identified, as soon as you start trying to tackle the arrays, I get all kinds of error messages. 
Here is the [updated policy](https://github.com/Springstone/Enterprise-Scale/blob/DenyMgmtFix/src/resources/Microsoft.Authorization/policyDefinitions/Deny-MgmtPorts-From-Internet.json)
So it will work in the use case you shared, specifying a single port for the rule. However, you can work around this by providing a port range "3388-3390" for example.

**Comment by Springstone** [comment]
I'm almost there... still not properly evaluating port ranges, working on refining that part, which is the most complicated bit of the logic in the policy. In the meantime, please do help test the changes. Remember to remove the first '[' in formulas we use to escape.

**Comment by Springstone** [comment]
@DavidRobson I think I have it working now for all scenarios. Please can you test the policy before I PR it into `main` :)
Here is the [updated policy](https://github.com/Springstone/Enterprise-Scale/blob/DenyMgmtFix/src/resources/Microsoft.Authorization/policyDefinitions/Deny-MgmtPorts-From-Internet.json)

**Comment by Springstone** [comment]
Got it 100% :)
If you would be so kind to test it, I would appreciate it.

**Comment by DavidRobson** [comment]
@Springstone I did some testing and it worked as you described - blocked any with port ranges. As we have a pretty large deployment I'm a bit wary to go that far as it might break some legitimate use cases with ARM/Bicep/Terraform.
I did a bit of testing today and I think I came up with something that works for all cases (hopefully!).

https://github.com/DavidRobson/Enterprise-Scale/blob/Deny-MgmtPorts-1357/src/resources/Microsoft.Authorization/policyDefinitions/Deny-MgmtPorts-From-Internet.json

I think the trick was to replace the first() function to current() inside the count where evaluation. I have tried a few different tests and so far seems to be working. I updated the first() to current() on the existing one as well as I think this is the right syntax? I tried to keep to all the same formatting rules etc.

Let me know if you'd like me to raise a PR and I can go through the contributing guide and add anything to release notes etc. I'm pretty sure there's a process to generate that big file as well which I haven't looked into yet... Do you have internal automated testing you run I couldn't see any in this repo so I was building up some of my own scripts to test this policy. Do you keep them in another repository or just do manual testing?
