### ISSUE TITLE
Migrate to new MDFC Storage Policy

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#1366]
We should replace the existing MDFC policy in our initiative that enables MDFC on storage accounts to the new version of the built in definition: https://www.azadvertizer.com/azpolicyadvertizer/cfdc5972-75b3-4418-8ae1-7f5c36839390.html

This enables malware scanning etc.

**Comment by Springstone** [comment]
This issue has been addressed and merged into the policy-refresh branch for this quarter. It will be merged into `main` towards the end of September.

**Comment by neok-g** [comment]
I noticed that changes are merged into main. That's great but when are they synced to the ALZ_bicep repo https://github.com/Azure/ALZ-Bicep?
