### ISSUE TITLE
Misleading documentation for Enforce-Guardrails-KeyVault

### ISSUE THREAD

**Issue by binaryPUNCH** [Azure/Enterprise-Scale#1367]
The documentation for the [Enforce-Guardrails-KeyVault](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-Guardrails-KeyVault.html) policy appears to suggest that the default values are "AUDIT". However, a thorough examination of the JSON definition reveals that, in fact, two of the parameters default to "DENY".

We did not notice this during our upgrade of the terraform-azurerm-caf-enterprise-scale deployment from version 2.3.1 to 4.0.1. This is when the said policy was initially incorporated, and its inclusion was not documented under any "breaking changes" [here](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases).

We request an update to the documentation to reflect these discrepancies. Furthermore, we would appreciate if all alterations to non-audit policies could be indicated in the release notes under "breaking changes". This will help us to proactively identify and address these changes before they impact our workload teams.

**Comment by jtracey93** [comment]
We will take this into consideration for future release notes 👍

It's technically not a "breaking change" from a policy or module usage perspective, but we can certainly try and make it clearer when new policies with deny/deploy effects are assigned to help you identify these.

cc: @matt-FFFFFF @Springstone @paulgrimley
