### ISSUE TITLE
Azure Firewall Basic SKU and DNS proxy

### ISSUE THREAD

**Issue by sebassem** [Azure/Enterprise-Scale#1370]
**Describe the bug**
When selecting the Basic Tier of Azure Firewall, and the option to use it as DNS proxy , the deployment fails as the Basic tier doesn't support this feature. It would be better to hide this option if the basic tier is selected

**Steps to reproduce**

1. Select the Basic tier in Azure Firewall
2. Select the option to use the Azure Firewall as DNS proxy

**Screenshots**

![image](https://github.com/Azure/Enterprise-Scale/assets/38246040/de2baac9-2fbc-46db-95b4-e002b3ff8f20)

**Comment by jtracey93** [comment]
Thanks @sebassem this has been fixed and rolled out :)
