### ISSUE TITLE
Allow Select in Portal deployment SKU Gen1 VPN Gateway Zone redundant options

### ISSUE THREAD

**Issue by anlucen** [Azure/Enterprise-Scale#1372]
For Portal option deployment, the only options Gen2AZ. However, there are options for G1 that has Zone redundant. In the case customer design to use that it must be created manually. The request is able to select the Gen1AZ options as well through the portal.

**Comment by jtracey93** [comment]
Hey @anlucen,

Thanks for the feature request. We are leading with Gen 2 GWs as they offer better scale support without the need for re-deployment and reconfiguration of a VPN GW.

Is there any reason that the Gen2 lowest SKU wasn't suitable. E.g. was there a hard requirement that it must be Gen 1?

Let us know 👍👍

**Comment by mundayn** [comment]
My main concern would be that VpnGw2 is over twice the price of VpnGw1

$183.9787/month v $474.4712/month

**Comment by jtracey93** [comment]
We are discussing this internally and will report back soon

**Comment by anlucen** [comment]
@jtracey93 after a few discussion with the customer finally was ok to implement the VPNGw AZ as best practice. However, they were asking why can't pick that in the portal automation if in the other tools is possible. Let me know any thoughts

**Comment by jtracey93** [comment]
Thanks for letting me know. This is because in the ALZ custom portal template, we do not allow the deployment of Gen 1 SKUs as we want customers to deploy Gen 2 and be setup for long term success.

Closing issue
