### ISSUE TITLE
The policy docs/wiki/ALZ-Policies.md

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#1378]
### Discussed in https://github.com/Azure/Enterprise-Scale/discussions/1377

<div type='discussions-op-text'>

<sup>Originally posted by **mrunmayeeindap** July 11, 2023</sup>
Deploy Diagnostic Settings for Database for PostgreSQL to Log Analytics workspace is not working. It is throwing error attach error. Could you please check.

<img width="344" alt="image" src="https://github.com/Azure/Enterprise-Scale/assets/57096562/6653d3dd-9fa0-4410-84c8-354220715e19">
</div>

**Comment by Springstone** [comment]
Hi @jtracey93. I'm missing context here. I've deployed the policy - which is where you are getting the error - maybe a copy and paste issue? Assignment works fine as well.

**Comment by jtracey93** [comment]
closing as stale
