### ISSUE TITLE
Can I just apply the Azure Policies from the ESLZ to an existing Landing Zone

### ISSUE THREAD

**Issue by mundayn** [Azure/Enterprise-Scale#1379]
Hi,

I have an existing landing zone structure, and I'd like to apply the policies that get applied as part of the landing zone deployment.

As an example, the policy definition "Public network access should be disabled for PaaS services" and  "Configure Azure PaaS services to use private DNS zones", I'd like to deploy this to my existing "Corp" management group.

What would be the steps to do this?

Some of the others I have done manually, but this looks quite complicated, so I'd love to automate it.

Thanks,

**Comment by jtracey93** [comment]
Hey @mundayn,

You can use the [ALZ Bicep Custom Policy Definitions Module](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions), to get all of the ALZ policy definitions, then you can assign them wherever you like in your hierarchy 

Thanks 

Jack
