### ISSUE TITLE
Deployment Failed when disabling LAW in the Trey Research scenario. 

### ISSUE THREAD

**Issue by lavanack** [Azure/Enterprise-Scale#1380]
**Describe the bug**
When deploying the [Trey Research](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2Fdocs%2Freference%2Ftreyresearch%2FarmTemplates%2Fes-lite.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2Fdocs%2Freference%2Ftreyresearch%2FarmTemplates%2Fportal-es-lite.json) without Log Analytics Workspace (LAW). the deployment fails (tested multiple times).

**Steps to reproduce**

1. Use the [Trey Research](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2Fdocs%2Freference%2Ftreyresearch%2FarmTemplates%2Fes-lite.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2Fdocs%2Freference%2Ftreyresearch%2FarmTemplates%2Fportal-es-lite.json) scenario
2. Select No for "Deploy Log Analytics Workspace" (The same deployment - ie same options - with LAW will succeed)

**Screenshots**
![image](https://github.com/Azure/Enterprise-Scale/assets/48048478/99d9f0fa-b86f-43ee-8dbc-1f12d64ab93a)

**Comment by jtracey93** [comment]
Thanks for raising the issue @lavanack 👍

Is there any reason for using Trey Research over Adventure Works, as this support single platform sub now (and has done for some time). This would be my recommendation going forward as we are looking to remove the trey research option as it is now possible in Adventure Works: https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md

Can you try adventure works and let us know?

**Comment by lavanack** [comment]
My customer is a SMC customer with a very small IT team and wanted the smallest/easiest deployment scenario to test. Thanks for the information about upcoming removal of the Trey Research scenario. My customer doesn't want to test the Adventure Works scenario without LAW but I will do by myself and let you know (when time permits)
