### ISSUE TITLE
Visio diagram for the enterprise scale landing zone design.

### ISSUE THREAD

**Issue by DimaRazb** [Azure/Enterprise-Scale#1384]
I would like to see an editable and scalable Visio diagram for the enterprise-scale landing zone design for trey research
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md#what-will-be-deployed

**Comment by mundayn** [comment]
There is a link to that here:
https://github.com/Azure/Enterprise-Scale/discussions/570

**Comment by DimaRazb** [comment]
Thanks, we could post this link on the page though
