### ISSUE TITLE
TLS deploy policies seem to have too high permissions

### ISSUE THREAD

**Issue by rikunarhi-cloud2** [Azure/Enterprise-Scale#1403]
**Describe the bug**

Most TLS policies have Owner role defined in the policy definition. With using the Enterprise scale module it policy assignment identities with too high role. 

- https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-MySQL-sslEnforcement.json#L87C73-L87C73
- https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-PostgreSQL-sslEnforcement.json#L88
- https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-SQL-minTLS.json#L75C1-L75C1
- https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-SqlMi-minTLS.json#L75C10-L75C10
- https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Storage-sslEnforcement.json#L87C10-L87C10

If I understand correct the role required for these should be Contributor rather than Owner. 

**Screenshots**

Example of using the policy assignment with the Enterprise scale module.

![image](https://github.com/Azure/Enterprise-Scale/assets/106966114/ea340aa7-6350-462d-8782-f3b19063c831)

**Comment by jtracey93** [comment]
Thanks for raising @rikunarhi-cloud2, we are actually working on this in the latest policy refresh (see milestone) which is due to complete at the end of September.

@Springstone can you take a look to ensure these polices are covered please to help close this one out?

**Comment by jtracey93** [comment]
Actually from what I can see #1392 will fix this.

@springstone to confirm

**Comment by Springstone** [comment]
@rikunarhi-cloud2 thanks for calling this out. Already on our roadmap, and will be resolved as part of this quarters refresh. The PR is already in to the policy-refresh branch.
Just calling out that for PostgreSQL and MySQL there are no built-in RBAC roles we can leverage (we have raised this with engineering and requested that they provide effective roles). In the meantime, we're reducing the scope for those policies to "Contributor" - not ideal, but is the minimum scoped role available to us today.

**Comment by Springstone** [comment]
This issue has been addressed and merged into the policy-refresh branch for this quarter. You should expect it to be merged into `main` towards the end of September.
