### ISSUE TITLE
Add zone privatelink.azuredatabricks.net to private endpoint policy set

### ISSUE THREAD

**Issue by cveld** [Azure/Enterprise-Scale#1409]
**Describe the solution you'd like**

It seems that currently the policy set Deploy Private DNS zones https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json does not contain a reference to the built-in policy for private dns zone privatelink.azuredatabricks.net.

Policy: "Configure Azure Databricks workspace to use private DNS zones"
https://www.azadvertizer.com/azpolicyadvertizer/0eddd7f3-3d9b-4927-a07a-806e8ac9486c.html

Would be great if you can add this policy to the set.

**Comment by pkorolo** [comment]
@Springstone submitted suitable PR, under review.

**Comment by pkorolo** [comment]
@cveld finished with respective PR

@Springstone will let you know when tis will become available (soon)
