### ISSUE TITLE
💡 Feature Request - Add metricsEnabled parameter to policy definitions

### ISSUE THREAD

**Issue by teemukom** [Azure/Enterprise-Scale#1413]
## Describe the solution you'd like

When deploying diagnostics settings one might need to disable metrics for particular resource type.

## Describe alternatives you've considered

Parameterized option to opt-in/opt-out of metrics in Diagnostics Settings

**Comment by jtracey93** [comment]
Thanks for raising @teemukom, I have transferred this issue to the Enterprise-Scale repo as all our policies in ALZ live here as the source of truth.

This has come up a few times in the past, and we are looking to address it in next quarters policy refresh cycle (Oct-Dec 2023)

Related to #1245, #1252 

cc: @Springstone

**Comment by ri-we** [comment]
@jtracey93 will there the metricsEnabled parameter be added to all policies? And is the ETA still this quarter? imo setting the default to true for the metrics is wrong. We collect the audit and security logs centrally and metrics are left to the internal customer’s needs. Enabling metrics can have your costs go through the roof. Is there any development for using categories?

**Comment by jtracey93** [comment]
Ill hand over to @springstone to provide an answer here
