### ISSUE TITLE
Double Opening Square Brackets causing failure.

### ISSUE THREAD

**Issue by mrunalbrahmbhatt** [Azure/Enterprise-Scale#1416]
https://github.com/Azure/Enterprise-Scale/blame/87908788a2ea6a89c9821161ca26c7e061dd95d0/src/resources/Microsoft.Authorization/policyDefinitions/Deny-AppServiceApiApp-http.json#L54C13-L54C21

"**[[**parameter('effect')]"

**Comment by jtracey93** [comment]
This is by design to allow our implementations to work as we need them.

Please review the contributing guide that advises on this: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide#escaping-policy-functions

**Comment by mrunalbrahmbhatt** [comment]
Thanks for the clarification.
