### ISSUE TITLE
Add Configure Microsoft Defender for Storage to be enabled besides Configure Microsoft Defender for Storage (Classic) to be enabled

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#1417]
**Issue**
The Enterprise Scale policy initiative Deploy Microsoft Defender for Cloud configuration uses the policy Configure Microsoft Defender for Storage (Classic) to be enabled. However Azure Security Center (ASC) Benchmark policy initiative uses the policy Microsoft Defender for Storage should be enabled (AuditIfNotExists).

The consequence is that if the classic defender plan for storage is deployed the policy remains non-compliant according to the ASC policy.

**Feature request**
In the Enterprise Scale policy initiative "Deploy Microsoft Defender for Cloud configuration"
Add the policy "Configure Microsoft Defender for Storage to be enabled" (/providers/Microsoft.Authorization/policyDefinitions/cfdc5972-75b3-4418-8ae1-7f5c36839390)

**Comment by jtracey93** [comment]
Hi @neok-g,

I believe we already have this covered in #1366 and is in our policy refresh work that is upcoming to be released at the end of September.

Tagging @Springstone who is leading this work for insights and so he can share and close this issue, if already handled.

**Comment by Springstone** [comment]
Hi @neok-g, indeed this will be included in our next policy refresh scheduled for the end of this month. We will be assigning both by default, but you can of course change default assignments.

**Comment by neok-g** [comment]
Thank you for the quick response
