### ISSUE TITLE
Deploy Diagnostic Settings for Cosmos DB to Log Analytics workspace is missing a log category

### ISSUE THREAD

**Issue by NucLabs** [Azure/Enterprise-Scale#1420]
**Describe the bug**
The policydef Deploy Diagnostic Settings for Cosmos DB to Log Analytics workspace is missing a log category 

**Steps to reproduce**

1. Assign the policy and create a new Cosmos DB
2. Observe that, after a succesful policy deployment, the policy is not compliant 

**Screenshots**
Portal view:
![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/97c3c667-cd59-4d6f-8cb9-662eb186b76f)

policy Definition snippet:
![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/c66a42a8-f93c-49f4-bb74-512e31dac602)

**Comment by jtracey93** [comment]
@springstone not sure if we want to squeeze this into the latest refresh?

**Comment by Springstone** [comment]
@jtracey93 @NucLabs apologies for the delay, been swamped with some other workstreams. This is an easy fix and I will push it through this week for merge to main next week.

**Comment by Springstone** [comment]
PR is in, and this should merge to the main branch early next week.
