### ISSUE TITLE
Bug Report: Policy PaaS should Disable Public Access - not working for container apps

### ISSUE THREAD

**Issue by steph409** [Azure/Enterprise-Scale#1423]
**Describe the bug**
I have deployed [this policy](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints.json). However, it is still possible to deploy public container apps. It would be great if the built-in policy _Container Apps environment should disable public network access? would be added to the initiative.

**Steps to reproduce**
Deploy the policy with effect "Deny" where-ever possible. Then it is still possible to create a container app which is exposed to the internet.

**Comment by steph409** [comment]
Hi @jtracey93,
thank you so much for looking at it so quickly! :) 

From my point of view the first one should be part of the initiative [Deny-PublicPaaSEndpoints.json](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints.json) 

The third one should probably added to the [enforce-encrypt-transit](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-EncryptTransit.json) initiative if it is not already there?

thanks! :)

**Comment by Springstone** [comment]
Confirming we've added to backlog for next refresh cycle.

**Comment by JamJarchitect** [comment]
PR has been merged which resolved this.
