### ISSUE TITLE
Address range overlaps for AZFW management subnet if deployed the defaults with a VPN gateway

### ISSUE THREAD

**Issue by sebassem** [Azure/Enterprise-Scale#1427]
**Describe the bug**
When deploying ALZ with default IP address ranges, deploying a VPN gateway and a firewall in the basic sku, there is an IP address range conflict between the gateway and management subnet

**firewall management subnet:** 10.100.1.0/26
**Subnet for vpn:** 10.100.1.0/24

**Steps to reproduce**

1. Deploy ALZ from the portal experience
2. Deploy a VPN gateway
3. Deploy a basic Azure firewall
4. Leave the default IP address ranges

**Screenshots**

![image](https://github.com/Azure/Enterprise-Scale/assets/38246040/3aa5a0c5-09cd-4ae0-924c-3512b42d3371)

**Comment by Springstone** [comment]
@sebassem thanks for raising this, will add to our backlog and address after policy-refresh merge to main.
