### ISSUE TITLE
Allow the use of resource specific tables in diagnostic settings

### ISSUE THREAD

**Issue by kewalaka** [Azure/Enterprise-Scale#1428]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Microsoft recommend that diagnostics for certain resources are set to a resource-specific table rather than the default one (Azure Diagnostics), I believe the current solution doesn't provide an option to accomplish this.

This setting is visible in the portal by selecting "Log Analytics workspaces" as the destination & then choosing the "resource specific" destination table, for those resources that support it.

An example resource where this applies is Data Factory (which is particularly critical due to the number of columns this service can create), another would be the Azure Firewall.

#### Describe the solution you'd like

Provide a parameter to use resource-specific tables for resources that support it.  This is accomplished in ARM with the following:

```"logAnalyticsDestinationType": "Dedicated"```

**Comment by matt-FFFFFF** [comment]
Hi @springstone, believe this is already on our backlog

**Comment by kewalaka** [comment]
actually perhaps I'm not explaining myself properly, now I understand the CAF & read the policies a little more carefully, wouldn't the following do what is needed? 

```json
{
  "extend_es_landing_zones": {
    "policy_assignments": [],
    "policy_definitions": [],
    "policy_set_definitions": [],
    "role_definitions": [],
    "archetype_config": {
      "parameters": {
        "Deploy-Diagnostics-Firewall": {
          "logAnalyticsDestinationType": "Dedicated"
        }
      },
      "access_control": {}
    }
  }
}
```

(using the Azure Firewall assignment to the LZ archetype, as an example)

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
