### ISSUE TITLE
Policy 'Deny-MgmtPorts-From-Internet' prevent Service fabric managed cluster deployment. 

### ISSUE THREAD

**Issue by prjelesi** [Azure/Enterprise-Scale#1430]
**Describe the bug**
Policy  'Deny-MgmtPorts-From-Internet'  block deployment of Service managed cluster. As part of Service fabric managed cluster deployment, service is also trying to deploy vnet, NSG , vm and LB and fail in this step. Service exist, but cluster can not be managed or new cluster can not be added.  

**Steps to reproduce**

1. Deploy Service fabric managed cluster using terraform or portal on subscription under landing zone management group.

**Comment by Springstone** [comment]
Hi @prjelesi. This isn't a bug in the Deny-MgmtPorts-From-Internet policy, the policy is doing what it is supposed to. The problem is this particular service, which doesn't support PrivateLink/Endpoints, which is also an issue using any other services like Key Vault, which is a security best practice. Will review with ALZ team.

As a workaround, I suggest creating an exemption to this policy for the resource group hosting Service Fabric.

**Comment by prjelesi** [comment]
@Springstone workaround that you proposed can't work. During deployment od managed cluster, service fabric managed cluster service create new resource groups and all resources inside (LB, VMSS< network, NSG etc). We can not know name of the RG before it is created. We know prefix (SFC) and maybe we can use this to exclude but this is not the best way since it can also cover some other things.

**Comment by jtracey93** [comment]
@prjelesi & @Springstone from what I can see a SFC can have NSGs as specified here: https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-best-practices-networking#network-security-rules

And none of these conflict with the policy rule checks, so if a template like this is used the SFC should deploy https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.servicefabric/service-fabric-secure-nsg-cluster-65-node-3-nodetype

**Comment by prjelesi** [comment]
@jtracey93 i review template quickly and look like it is not for SFC managed cluster. 
This is what i need https://learn.microsoft.com/en-us/azure/templates/microsoft.servicefabric/managedclusters?pivots=deployment-language-arm-template

I will try to use "networkSecurityRules" and combination or other parameters for LB and RDP access to achieve this. 
Tnx!
