### ISSUE TITLE
Azure Landing Zones - Community Call - 6th December 2023

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#1431]
![image](https://github.com/Azure/Enterprise-Scale/assets/41163455/f09431ce-cae7-4037-acae-dc656abcdd8b)

We are excited to invite you to our 7th external Azure Landing Zones community call on the 6th of December 2023 @ 08:30 CET (07:30 UK/BST - 02:30 EST - 23:30 PST - 16:30 AEDT)

> As always this will be recorded and published to the [CAE YouTube Channel](https://aka.ms/caeyoutube) and shared via our [community calls wiki page](https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls) 👍

As before we have an open agenda, so please comment below with things you would like to cover or any questions you have👍

### Agenda:

- TBC
- Q&A (please raise topics and questions to discuss in this issue)

### Registration

**Sign up for the call** [here!](https://msit.events.teams.microsoft.com/event/b843fdd2-eeca-44c7-a575-b2d39ada8794@72f988bf-86f1-41af-91ab-2d7cd011db47)

### Round-up

We look forward to another interactive discussion with lots interesting topics!

**For links to our previous community calls see:** [https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls](https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls)

> **Note: We fully intend to run these at least quarterly in 2023 👍**

**Comment by simone-bennett** [comment]
Hi @jtracey93 , just letting you know that the link to sign up for future calls is incorrect in the youtube description :)

**Comment by jtracey93** [comment]
Thanks @simone-bennett - have updated them 👍

**Comment by BigBaghDaddy** [comment]
I could not make the call, is there a recording? Could you share the link please?

**Comment by jtracey93** [comment]
Now available on YouTube https://youtu.be/E3Pz_VcefZ4 @nickatUC
