### ISSUE TITLE
Deploy Diagnostic Settings for VWAN S2S VPN Gateway to Log Analytics workspace

### ISSUE THREAD

**Issue by anwarnk** [Azure/Enterprise-Scale#1436]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.2

**azure provider**: 3.75.0

**module**: 4.2.0

#### Describe the bug

We have vWan setup using the main module, and have configured a S2S VPN.  The diagnostic logs for "...VWAN S2S VPN Gateway..." show it is not compliant. We try and do a remediation task however cannot see it in the list under 'Deploy Diagnostic Settings to Azure Services'.  Creating the logs manually does not change the status to compliance either.

#### Screenshots
##non compliant 
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/105373983/6952ed2f-d075-4eb7-b571-d0a135eae8f5)

##Manually created logs 

![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/105373983/1b128b3d-3507-4d7d-9c96-dd6ee7f98e1d)

Policy still showing as non-complaint

#### Additional context

We noticed that if we click on the resource that is not compliant, it takes us to the 'VPN Gateway' it does not have the diagnostic logs exposed to us. The setting is under the vWan > Hub > S2S.

**Comment by Springstone** [comment]
@anwarnk an update. There are a number of significant changes coming for diagnostic settings, so we're not prioritizing changes in ALZ until those land. We've added this issue to our backlog and will keep tracking so we can resolve this as the new policies/initiatives become available.

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
