### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kevinmccurdybrd** [Azure/Enterprise-Scale#1440]
**Describe the bug**
Policy "Configure backup on virtual machines without a given tag to a new recovery services vault with a default policy" is missing OS Definitions for Ubuntu 22_04-lts

The policy definition is missing all variations of 22_04:

![image](https://github.com/Azure/Enterprise-Scale/assets/101918588/70584e36-dd91-49bb-97f2-e52114088afa)

**Steps to reproduce**

1. Have the CAF in any iteration (We use the ES Terraform Implementation) 
2. AzAdvertizer shows the same: https://www.azadvertizer.net/azpolicyadvertizer/98d0b9f8-fd90-49c9-88e2-d3baf3b0dd86.html

**Screenshots**

**Comment by jtracey93** [comment]
Hey @kevinmccurdybrd,

As this is a built in policy definition, please could you raise an Azure Support ticket for this as this is the quickest way to get this to the owners of the built-in policy to get it resolved, which will then automatically roll into your ALZ assignments 

Thanks

Jack 👍
