### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by mwmeehan** [Azure/Enterprise-Scale#1444]
**Version 6.0.0 of Deploy-MDFC-Config throws an error due to an invalid trailing character**

**Steps to reproduce**

1. Ran the deployment to pull the new version
2. Error due to a "." at the end of the new version 6.0.0.

**Screenshots**
![image](https://github.com/Azure/Enterprise-Scale/assets/116912396/0333894e-842c-4a44-88a7-a8437dacc1b1)

![image](https://github.com/Azure/Enterprise-Scale/assets/116912396/a28aaf0d-9cc5-4c26-b7cc-5f7552a3e37a)

**Comment by jtracey93** [comment]
@Springstone can you resolve this please?

**Comment by Springstone** [comment]
We've put in a fix for this, thank you very much for letting us know.
