### ISSUE TITLE
Feature Request - Builtin Set Definition Paramters 

### ISSUE THREAD

**Issue by ASHR4** [Azure/Enterprise-Scale#1451]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

Trying to configure the diagnostic settings for Azure KeyVault which is in the Deploy-Diagnostics-LogAnalytics set definition. Find the specific policy [here](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Monitoring/KeyVault_DeployDiagnosticLog_Deploy_LogAnalytics.json)

The only parameters available for me to configure are [these](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/79aefacd3250d9616fb21e4c9709e43526e32cc0/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json#L1443-L1450) despite this definition supporting the following parameters:

- effect
- profileName
- logAnalytics
- metricsEnabled
- logsEnabled
- matchWorkspace

#### Describe the solution you'd like

Allow for the customisation of all parameters within the set definitions utilised by this module, rather than leaving them out

#### Additional context

**Comment by Springstone** [comment]
Adding to the backlog for this quarter.

**Comment by Springstone** [comment]
Hi @ASHR4, an update. The PG is busy reworking all the diagnostic settings built-in policies, and we're waiting on those to land before making any additional changes in ALZ. Your request is very valid and it is on our backlog, and we'll implement this as soon as the new policies/initiatives become available. 

In the short term, suggest you update the ALZ custom initiative with the additional parameters you need.

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
