### ISSUE TITLE
Feature Request - Diagnostic Settings to Event Hub / Questions

### ISSUE THREAD

**Issue by mundayn** [Azure/Enterprise-Scale#1454]
Hey all,

Love your work here.

The "Deploy Diagnostic Settings to Azure Services" initiative works very well, but I have a few clients who would like to use Event Hub to collect their data, so it can then be collected by 3rd party SIEM tools.

There is a built in initiative called "Enable audit category group resource logging for supported resources to Event Hub", but, this has 33 Policies built in, whereas your policy mentioned above for Log Analytics has 70.

So I am missing a ton of logs for different services using the built in initiatives.

Do you have any intention on building a similar one for Event Hub?
If not, can you use your powers to poke the relevant policy team to update the Event Hub Policy to match?
Do you have any other recommendations for me now?

Not that this is a 1 for 1 comparison as I know there will be different scenarios, but if you search "to event hub" in AzAdvertizer there are 48 entries vs "to log analytics" there are 140.

Thanks,

**Comment by jtracey93** [comment]
Hey @mundayn,

Thanks for your kind words.

We actually are working closely with the Diagnostics Settings PG on getting closer to parity for the initiative you called out which covers all destinations types (Storage, Event Hub & LAW) as we want to replace our custom one with the built-in for easier maintenance. We are interested in the "Enable audit category group resource logging for supported resources to Log Analytics" policy initiative specifically, but the work will be done across all destination types on the built in initiatives. 

We are currently working towards making this happen with the PG and hoping to have something by the end of the calendar year, but there are a couple of cross-PG dependencies that we are reliant upon to make this happen.

So stay tuned 👍 

In the meantime, we don't plan to make any changes to our current diagnostic settings policies as we have a future "breaking change", as described above, planned. 

An option you could take in the meantime is to create the customs yourself, using ours as inspiration. It should be fairly straight forward to make them work with event hubs by changing the `then` part of the policies.

Thanks

Jack

**Comment by mundayn** [comment]
Hey @jtracey93 !

Happy new year!

Any chance if you have any news or ETA to share on what you mentioned above?

If not where can I follow for updates on this?
