### ISSUE TITLE
Bug Report Deployment template validation fails when selecting Virtual WAN and single subscription

### ISSUE THREAD

**Issue by ahammond-dev** [Azure/Enterprise-Scale#1470]
**Describe the bug**
When selecting a Single Platform Subscription and Virtual WAN as the network topology the following error is produced when reaching the Review + Create page.  This occurs whether routing intent is enabled or not.  This does not occur when selecting another network topology such as hub and spoke. It also does not occur when selecting dedicated platform subscriptions.

{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The value for the template parameter 'enablevWANRoutingIntent' at line '109' and column '35' is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.'."}

**Steps to reproduce**

1. Begin the deployment by clicking the "Deploy to Azure" Link on https://github.com/Azure/Enterprise-Scale#deploying-enterprise-scale-architecture-in-your-own-environment
2. On the Azure Core Setup page, select "single" under Platform subscription options.
3. On the Network topology and connectivity page, select "Virtual WAN (Microsoft managed)" under Deploy networking topology.
4. All other settings can remain as the defaults.

**Screenshots**
![image](https://github.com/Azure/Enterprise-Scale/assets/81582664/160ad66f-69a9-4d45-9cb9-b9e569e8a567)

**Comment by jtracey93** [comment]
Thanks for reporting @rozkurt can you take a look and investigate this please and come back to this thread here and @ahammond-dev 👍

**Comment by rozkurt** [comment]
@ahammond-dev @jtracey93 I reviewed the code and just noticed what causing this issue. I'm currently testing the fix and hoping that it would be merged and be available early next week!

**Comment by rozkurt** [comment]
@ahammond-dev The fix has been applied, tested and merged into the main branch now. Please test it if possible and let us know if you notice any other issues. Thank you once again for reporting it!

CC: @jtracey93
