### ISSUE TITLE
Update reference implementation docs to reference the creation of managed identities

### ISSUE THREAD

**Issue by BeatrizSilv** [Azure/Enterprise-Scale#1473]
This is a small request to please reference the creation of managed identities in the 'what will be deployed?' section: https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md#what-will-be-deployed

One of my customers recently used this reference implementation and they were very confused when they saw multiple apps created with contributor roles, for example. We later confirmed that this is necessary for 'deployifnotexists' policies. 

I noticed later that the use of managed identities is referenced, but this section is a bit hidden: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#why-are-managed-identities-deployed-as-part-of-the-alz-policies

To avoid any confusion, adding a reference to the main page (https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md#what-will-be-deployed) would make things clearer on what to expect, especially if you're not well versed in Azure policy.

**Comment by jtracey93** [comment]
Thanks @BeatrizSilv for raising the issue.

We recently added this to the ALZ Policies wiki page, is this sufficient, as placing these on a diagram is actually quite hard as they live at a scope that isnt currently shown on the diagram, e.g. Management Group scope.

https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#why-are-managed-identities-deployed-as-part-of-the-alz-policies

Let us know

**Comment by BeatrizSilv** [comment]
Thank you for your reply, @jtracey93. It took me a while to find that FAQ section, which is why I think it would be helpful to add at least a note about the creation of managed identities in the 'what will be deployed?' section, since is the first page users see when they want to read more about the reference implementation.

Does that make sense?

**Comment by jtracey93** [comment]
Sure, @BeatrizSilv, do you want to submit a PR with the proposed changes?
