### ISSUE TITLE
Deploy-Private-DNS-Zones not automatically creating private DNS record for privatelink.azure-api.net

### ISSUE THREAD

**Issue by anwarnk** [Azure/Enterprise-Scale#1479]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.5.7

**azure provider**: 3.81

**module**: 5.0.0

#### Describe the bug

We have deployed an APIM in a landing zone with a private endpoint, whilst in connectivity we can see the private DNS zone called "privatelink.azure-api.net" the policy "Deploy-Private-DNS-Zones" does not have the configuration to automatically create the A record for it, is this missing or intentional?

#### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

**Comment by Springstone** [comment]
Investigating. Thanks for raising the issue, we're investigating and will propose a solution asap.

**Comment by Springstone** [comment]
Waiting on this PR to be merged to enable custom assignment of Private DNS Zones: https://github.com/Azure/Enterprise-Scale/pull/1618

**Comment by Springstone** [comment]
We have published a generic Private DNS Zones policy that can be used to enable the feature for services that don't have a dedicated built-in policy (https://www.azadvertizer.net/azpolicyadvertizer/Deploy-Private-DNS-Generic.html). Closing as this should address the ask, but feel free to re-open if needed.
