### ISSUE TITLE
Policy Deploy-Private-DNS-Zones missing notebooks for azure machine learning workspace

### ISSUE THREAD

**Issue by steph409** [Azure/Enterprise-Scale#1482]
**The initiative Deploy-Private-DNS-Zones is missing the DNS entry for privatelink.notebooks.azure.net**

The machine learning workspace, [as per documentation](https://learn.microsoft.com/de-de/azure/machine-learning/how-to-troubleshoot-secure-connection-workspace?view=azureml-api-2#azure-dns-troubleshooting), needs entries in two private DNS zones, privatelink.api.azureml.ms and privatelink.notebooks.azure.net.

Currently, the initiative Deploy-Private-DNS-Zones uses a built-in policy only takes care of the first one. I was not able to find a built-in policy that would do the trick.

When I deployed the private Machine learning workspace, while connecting, I got the following error message:
<img width="532" alt="ml_demo_error" src="https://github.com/Azure/Enterprise-Scale/assets/33083326/e58b4b85-a638-4909-ae93-bcf91b0772ee">

When I manually add the private DNS zone configuration for notebooks, it disappears and connection works as expected. 

It would be great if this would be done automatically by the initiative as well.

**Comment by jtracey93** [comment]
Thanks @steph409 for the issue report. @Springstone can we investigate 👍

**Comment by Springstone** [comment]
We have a related issue #1486, we'll group these together to address the issue for both. AB#32352

**Comment by Springstone** [comment]
As there is no built-in policy for Notebooks, we'll test this with a new custom policy we'll be introducing for generic Private DNS Zones, and validate that it works.

**Comment by haflidif** [comment]
> As there is no built-in policy for Notebooks, we'll test this with a new custom policy we'll be introducing for generic Private DNS Zones, and validate that it works.

@Springstone  Any ETA on that Custom Policy ?

**Comment by haflidif** [comment]
> > As there is no built-in policy for Notebooks, we'll test this with a new custom policy we'll be introducing for generic Private DNS Zones, and validate that it works.
> 
> @Springstone Any ETA on that Custom Policy ?

Am I looking at it in the wrong way or isn't this policy here https://www.azadvertizer.net/azpolicyadvertizer/ee40564d-486e-4f68-a5ca-7a621edae0fb.html Version 1.1.0 already supporting two PrivateDNSZoneGroupIDs ?

**Comment by Springstone** [comment]
@haflidif this was resolved and merged in this PR #1621. Closing as this is merged. Please feel free to re-open if needed.
Also for any additional Private DNS Zone issues, please consider using https://www.azadvertizer.net/azpolicyadvertizer/Deploy-Private-DNS-Generic.html which should allow you to configure private DNS zones for resources missing built-in policies.
