### ISSUE TITLE
Bug Report: Databricks typo in policy definition for private endpoints

### ISSUE THREAD

**Issue by juanandmsft** [Azure/Enterprise-Scale#1484]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Describe the bug

Minor typo in policy definition referring to "Databrics" instead of "Databricks".

#### Screenshots
![image](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/assets/55385320/c017ae47-88c3-4bae-bc00-26892d588ec3)

**Comment by Springstone** [comment]
@juanandmsft thanks for raising this. PR in progress, just needs testing before merge.

**Comment by Springstone** [comment]
This is now merged to the policy refresh branch, and will go live with the next major refresh release. Closing as no further action required.
