### ISSUE TITLE
Bug Report - Single Subscription for Platform denies the creation of PIP resulting in VPN GW deployment failure

### ISSUE THREAD

**Issue by jonathan-vella** [Azure/Enterprise-Scale#1498]
**Describe the bug**
When opting to use a single subscription for platform, one of the policies which are assigned to the "platform" mg is "deny the creation of public ip". Due to the effect of this policy, we cannot create a VPN Gateway during Portal deployment. This also applies to Bicep accelerator.
Error ""Resource 'x-vpngw-germanywestcentral-pip' was disallowed by policy. Reasons: 'Public IPs must not be created under this scope.'."

**Steps to reproduce**

1. Select "single subscription" option for Platform in Portal deployment experience
2. In "Network topology and connectivity" switch "Deploy VPN Gateway" to yes

**Screenshots**

**Comment by jonathan-vella** [comment]
In the customer's case, it was 100% greenfield. In my case, I have completely cleaned up my environment using the ESLZ cleanup script by Jack Tracey, and re-deployed using the Bicep Accelerator. In both cases, this is the issue:
![Screenshot 2023-12-08 202627](https://github.com/Azure/Enterprise-Scale/assets/25802147/5f9143ca-e82e-445e-b0e7-63c9f9dd2fb6)

**Comment by Springstone** [comment]
Taken offline to troubleshoot. A deployment configuration issue resulted in this issue. 
Closing as there is no action on ALZ team.
