### ISSUE TITLE
Clarification of behaviour of "Configure Azure Recovery Services vaults to use private DNS zones"

### ISSUE THREAD

**Issue by djbark** [Azure/Enterprise-Scale#1501]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.6.5

**azure provider**: 3.83.0

**module**: 5.0.3

#### Describe the bug

I notice that the policy _“[Preview]: Configure Azure Recovery Services vaults to use private DNS zones“_ policy creates DNS Privatelink entries for “AzureSiteRecovery” but not for “AzureBackup”.  Is there a reason why it doesn't not create entries for AzureBackup?  Or should a feature request be raised to enhance this policy?

**Comment by Springstone** [comment]
@djbark The built-in policies are resource specific, as you may be aware Backup and Recovery Service Vaults behave slightly differently. We are working with the product group to enhance policies to include both as expected. Support will be coming, and will update asap.

**Comment by Springstone** [comment]
@djbark This has been addressed fully in two PRs, the private link PR is https://github.com/Azure/Enterprise-Scale/pull/1578. These PRs are in the Policy-Refresh branch, and will be merged to main towards the end of May. Closing the issue as no further action required from ALZ team.
