### ISSUE TITLE
Bug Report: Policy initiative for HDInsight private endpoints uses "cluster" groupId, when available ones are "headnode" and "gateway"

### ISSUE THREAD

**Issue by juanandmsft** [Azure/Enterprise-Scale#1510]
**Describe the bug**
The ESLZ policy initiative for HDInsight private endpoints [uses "cluster" groupId](https://github.com/Azure/Enterprise-Scale/blob/1a640ce212e721d1bd4f648bf07284976d94deeb/src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json#L714), but available ones are "headnode" and "gateway".

Built-in policy does not hardcode the groupId, so two invocations should be available in the initiative, one for "gateway", one for "headnode" group types.

**Steps to reproduce**

1. Create HDInsight cluster with PL.
2. Create a private endpoint from Networking blade.

**Screenshots**

![image](https://github.com/Azure/Enterprise-Scale/assets/55385320/81731f68-b656-47fa-bdd9-6a2b90fce22e)

**Comment by Springstone** [comment]
@juanandmsft this is a built-in policy unfortunately, which we don't have any control over. The recommended path to get help on this would be to raise a support ticket in Azure. Honestly, I don't know much about HDInsights, so can't provide any additional guidance.
As there is no action on the ALZ team, will close this issue - please feel free to re-open if needed.
