### ISSUE TITLE
Doc links (3x) broken on Deploying ALZ ZTNetwork wiki page

### ISSUE THREAD

**Issue by cbezenco** [Azure/Enterprise-Scale#1519]
**Describe the bug**
The three links on this doc page https://github.com/Azure/Enterprise-Scale/wiki/Deploying-ALZ-ZTNetwork#azure-landing-zone-portal-accelerator-deployment-with-zero-trust-network-principles  are broken 

**Steps to reproduce**

1.Check URL above
**Screenshots**

**Comment by jtracey93** [comment]
@JefferyMitchell or @brsteph would you mind taking a look at this and submitting a PR to fix it?

**Comment by brsteph** [comment]
PR #1525 has been submitted to address
