### ISSUE TITLE
Feature Request - replace Deny-Sql-minTLS with built-in

### ISSUE THREAD

**Issue by vegazbabz** [Azure/Enterprise-Scale#1541]
Replace the policy "Azure SQL Database should have the minimal TLS version set to the highest version" ([Deny-Sql-minTLS](https://www.azadvertizer.net/azpolicyadvertizer/Deny-Sql-minTLS.html)) with the built-in policy "[Azure SQL Database should be running TLS version 1.2 or newer](https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F32e6bbec-16b6-44c2-be37-c5b672d103cf)".

**Reasoning:**
No reason to have min. TLS version as a parameter. v1.2 (or 1.3) is the only version to use. Rest is insecure and should _never_ be used.
Legacy apps running this, should be exempted from this policy, however, it should not be the organization’s default to have 1.0 or 1.1, which is why it should not be supported in a policy used for an initiative for the LZ MG.

It is currently part of the policy initiative "Deny or Deploy and append TLS requirements and SSL enforcement on resources without Encryption in transit" ([Enforce-EncryptTransit](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-EncryptTransit.html)).

**Comment by jtracey93** [comment]
Thanks @vegazbabz 

For the policy enhancement suggestions here, we will triage and come back to you with any further questions or clarity we may have or require and let you know an outcome.

> If you haven't already checkout our new GitHub Issue Form for taking in new [ALZ Policy Requests](https://github.com/Azure/Enterprise-Scale/issues/new?assignees=springstone&labels=policy&projects=&template=Policy_Submission.yml&title=%5BPolicy%5D%3A+)

Thanks - the ALZ Team

**Comment by vegazbabz** [comment]
> 
> > If you haven't already checkout our new GitHub Issue Form for taking in new [ALZ Policy Requests](https://github.com/Azure/Enterprise-Scale/issues/new?assignees=springstone&labels=policy&projects=&template=Policy_Submission.yml&title=%5BPolicy%5D%3A+)
> 
> Thanks - the ALZ Team

Already checked this out and reported one there. However, this seems to be for _new_ policies and not for enhancements of existing. If that is not correct, then please update the descriptions :)

**Comment by jtracey93** [comment]
@springstone, see above comment around form

**Comment by Springstone** [comment]
Addressed in PR https://github.com/Azure/Enterprise-Scale/pull/1622
