### ISSUE TITLE
Feature Request - replace Deny-Storage-minTLS with built-in

### ISSUE THREAD

**Issue by vegazbabz** [Azure/Enterprise-Scale#1542]
Replace the ALZ policy "**Storage Account set to minimum TLS and Secure transfer should be enabled**" ([Deny-Storage-minTLS](https://www.azadvertizer.net/azpolicyadvertizer/Deny-Storage-minTLS.html)) with the 2 built-in policies:
- [Storage accounts should have the specified minimum TLS version](https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Ffe83a0eb-a853-422d-aac2-1bffd182c5d0)
- [Secure transfer to storage accounts should be enabled](https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F404c3081-a854-4457-ae30-26a93ef643f9)

The ALZ policy contains the same policyRule as the 2 policies combined.

Part of policy initiative "Deny or Deploy and append TLS requirements and SSL enforcement on resources without Encryption in transit" ([Enforce-EncryptTransit](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-EncryptTransit.html)).

**Rationale**:
[Follows strategy to use built-in when possible.](https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/ALZ-Policies.md#why-are-there-custom-policy-definitions-as-part-of-azure-landing-zones)
Furthermore, it does not make sense to include two (2) different settings in one policy initiative. If you want to follow that logic, then why not make one policy with all settings for SQL or AppServices, etc. It would be messy.
In addition, troubleshoot, including custom error messaging, will be easier for deny effect, and the auditing will be easier for audit effect, as you can see exactly which policy is in effect, which means you can see which setting/property is causing the issue.

**Comment by jtracey93** [comment]
Thanks @vegazbabz 

For the policy enhancement suggestions here, we will triage and come back to you with any further questions or clarity we may have or require and let you know an outcome.

> If you haven't already checkout our new GitHub Issue Form for taking in new [ALZ Policy Requests](https://github.com/Azure/Enterprise-Scale/issues/new?assignees=springstone&labels=policy&projects=&template=Policy_Submission.yml&title=%5BPolicy%5D%3A+)

Thanks - the ALZ Team

**Comment by Springstone** [comment]
@vegababz This is a good shout, and thank you for the thorough documentation. We'll add it to our backlog.
