### ISSUE TITLE
Feature Request - align policy definition names for sandbox and decomm

### ISSUE THREAD

**Issue by vegazbabz** [Azure/Enterprise-Scale#1544]
Misalignment between Assignment name & Definition name found here:
https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#sandbox
https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#decommissioned
and on the policies themselves:
https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-ALZ-Sandbox.html
https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-ALZ-Decomm.html

On ALZ-Policies page, the definition name “Enforce ALZ Sandbox Guardrails” should be either changed to the policy displayname [Enforce policies in the Sandbox Landing Zone](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-ALZ-Sandbox.html) or the policy display name 
“Enforce policies in the Sandbox Landing Zone” should be changed to “Enforce ALZ Sandbox Guardrails”.

The same for “Enforce ALZ Decommissioned Guardrails” that should be either changed to the policy displayname [Enforce policies in the Decommissioned Landing Zone](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-ALZ-Decomm.html) or policy display name “Enforce policies in the Decommissioned Landing Zone” should be changed to “Enforce ALZ Decommissioned Guardrails".

**Comment by Springstone** [comment]
@vegazbabz PR is in to address this.

**Comment by Springstone** [comment]
I'm closing the issue as it is minor, and the PR is in for approval.
