### ISSUE TITLE
Bug Report - Broken link in ALZ-Policies Wiki page

### ISSUE THREAD

**Issue by riosengineer** [Azure/Enterprise-Scale#1556]
**Describe the bug**
Minor one but I noticed this today going through the docs. 

The link to the ALZ Policy FAQ and Tips on the ALZ-Policies.md page link looks to be broken. I have done a search and couldn't see an existing mention of this, or an open PR but apologies if there is and I've missed it. 

**Steps to reproduce**

1. https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/ALZ-Policies.md
2. Click hyperlink under FAQ and Tips for "ALZ Policy FAQ and Tips" to see broken link
3. Sends  you to this page https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/ALZ-Policies-FAQ

**Comment by jtracey93** [comment]
Hey @riosengineer, 

We advise browsing the wiki, via the wiki directly https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies , this works fine for me, just tested

Thanks
