### ISSUE TITLE
Feature Request - add recommendation around Encryption with customer-managed keys (CMK)

### ISSUE THREAD

**Issue by vegazbabz** [Azure/Enterprise-Scale#1558]
[Deny or Audit resources without Encryption with a customer-managed key (CMK)](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-Encryption-CMK.html) is not part of the [policy list](https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/ALZ-Policies.md).

This means it lack recommendation on the scope. Back to some of the other ALZ policies questions, _why do policy initiatives exist that are not used or recommended?_

I believe this should be implemented on intermediate root group as best practice. However, I do understand that not all clients want to use CMK - although this is best practice and recommended. So really, just some clear guidelines around the usage of CMK should be provided.

**Comment by jtracey93** [comment]
This comes in the box as nothing built-in exists in the platform. As you correctly call out, not everyone will want/need CMK so we cannot make this a default assignment using the 80/20 rule, therefore it will stay unassigned.

However, customers have it available should they wish to use it.

**Comment by vegazbabz** [comment]
> This comes in the box as nothing built-in exists in the platform. As you correctly call out, not everyone will want/need CMK so we cannot make this a default assignment using the 80/20 rule, therefore it will stay unassigned.
> 
> However, customers have it available should they wish to use it.

I completely agree, what I am missing is a place in the wiki that addresses this and mention to people that they have this policy initiative available, and why it would be best practice to use it.

**Comment by Springstone** [comment]
@vegazbabz This is a good call out, and will be more relevant in the near future, where we are planning on adding more custom policies but not assigning by default. 
To clarify, CMK is not the best practice for everyone, it's a good practice. Encryption is a best practice, customers managing their own keys in an enhanced practice, if they have the skills available to do so effectively - hence we have MMK. 
Your point is taken, and we are in the process of adding custom policies aligned with CMK governance (not assigned by default) but will provide more options to customer wanting that additional level of security - and we'll provide additional wiki guidance aligned with this.

#ab33219

**Comment by Springstone** [comment]
@vegazbabz You're totally correct on your viewpoint and analysis, however, we cannot implement this by default given the vast majority aren't ready for CMK. For those few customers that are ready and aligned to CMK we recommend implementing appropriate policies once ALZ is deployed to meet requirements. ALZ is a reference architecture, not perfect for everyone, but perfect for the 80%. 
We're looking into revisiting the CMK perspective but have a lot of other things on the go at the moment, so may be a while before anything moves in ALZ in that space.

**Comment by Springstone** [comment]
Addressed in PR #1622, additionally you will be able to choose the scope to apply the initiative.
