### ISSUE TITLE
Portal Deployment - Issue when selecting option to Connect corp landing zones to connectivity hub

### ISSUE THREAD

**Issue by matheuscarboni** [Azure/Enterprise-Scale#1570]
Selecting Yes on option for "Connect corp landing zones to the connectivity hub" leads to following validation issue on the Review+ Create screen:

`{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The template resource 'alz-UserAssignedIdentityRg-southcentralus-08891d32-5f1c-59dd1' at line '1689' and column '9' is not valid: Evaluation result of language expression '[variables('subscriptionIds')[copyIndex()]]' is type 'Object', expected type is 'String'.. Please see https://aka.ms/arm-functions for usage details.'."
}
`

**Comment by arjenhuitema** [comment]
Thank you @matheuscarboni for raising this issue. I've started working on it and will keep you informed here.

**Comment by arjenhuitema** [comment]
Hi @matheuscarboni, hope you are doing well. The issue has been fixed in the latest release and it's ready to be deployed. If you have other questions or comments, please let me know.
