### ISSUE TITLE
[Policy]: Enforce recommended guardrails for Azure Key Vault Managed HSM 

### ISSUE THREAD

**Issue by vegazbabz** [Azure/Enterprise-Scale#1571]
### Policy Definition or Initiative

Initiative

### Built-in/Custom

Custom

### Built-in policy definition or initiative ID

<GUID>

### Custom policy definition or initiative description

For the organizations that use Managed HSM.
It should be similar to “Enforce recommended guardrails for Azure Key Vault” ([Enforce-Guardrails-KeyVault](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-Guardrails-KeyVault.html)) just with Managed HSM instead.

### Scope

Intermediate Root

### Default Assignment

- [ ] Yes

### Comments/thoughts

This is best practice and most secure to use AKV Managed HSM.

**Comment by vegazbabz** [comment]
| AKV policy| HSM equivalent |
| -------- | ------- |
|Key Vault keys should have an expiration date|[[Preview]: Azure Key Vault Managed HSM keys should have an expiration date](https://www.azadvertizer.net/azpolicyadvertizer/1d478a74-21ba-4b9f-9d8f-8e6fced0eec5.html)|
|- Key vaults should have deletion protection enabled<br>- Key vaults should have soft delete enabled|[Azure Key Vault Managed HSM should have purge protection enabled](https://www.azadvertizer.net/azpolicyadvertizer/c39ba22d-4428-4149-b981-70acb31fc383.html)
|Keys should have more than the specified number of days before expiration|[[Preview]: Azure Key Vault Managed HSM Keys should have more than the specified number of days before expiration](https://www.azadvertizer.net/azpolicyadvertizer/ad27588c-0198-4c84-81ef-08efd0274653.html)|
|Azure Key Vault should have firewall enabled|[[Preview]: Azure Key Vault Managed HSM should disable public network access](https://www.azadvertizer.net/azpolicyadvertizer/19ea9d63-adee-4431-a95e-1913c6c1c75f.html)|

Consider adding more custom policies such as this one https://www.azadvertizer.net/azpolicyadvertizer/61cbe0c0-05d8-4853-8233-9b9e89c8456d.html

**Comment by Springstone** [comment]
@vegazbabz please review the latest release with the additional KeyVault params, and advise on any gaps. Closing as we have an HSM story but if you find gaps please let us know.
