### ISSUE TITLE
Feature Request - Update Deny-PublicPaaSEndpoints to include Eventhub

### ISSUE THREAD

**Issue by steph409** [Azure/Enterprise-Scale#1573]
Hi everyone,

currently, it is possible to deploy eventhub with public access. it does not seem to be included in [this initiative](https://github.com/Azure/Enterprise-Scale/blob/9ead68e2c05f1ca534489379c03be54b8cc32cba/src/resources/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints.json). There has already been [an issue which asked eventhub to be included in this initiative](https://github.com/Azure/Enterprise-Scale/issues/975). The issue got [closed with a PR](https://github.com/Azure/Enterprise-Scale/pull/1273/files#diff-64ee2c93f8e558836414defcc76ec71758fc1bb50f574e169d6f5750e904a64f), but from the changes, it seems the policy has not been updated to include eventhub. It would be great if eventhub would be included in the policy.

**Describe the solution you'd like**

There is a built-in policy that should be added to the Deny-PublicPaaSEndpoints initiative: [Event Hub Namespaces should disable public network access](https://www.azadvertizer.net/azpolicyadvertizer/0602787f-9896-402a-a6e1-39ee63ee435e.html)

Best regards,
Stephanie

**Comment by Springstone** [comment]
Hi @steph409, many thanks for raising this. EventHub is indeed missing from the initiative, and we've created a backlog item to get this added.

**Comment by Springstone** [comment]
@steph409 Closing, as this is now included in the upcoming Policy refresh.
