### ISSUE TITLE
Feature Request: Eventhub missing in TLS requirements initiative

### ISSUE THREAD

**Issue by steph409** [Azure/Enterprise-Scale#1579]
Eventhub has a property for the minimum TLS version. This property should be included in the Initiative "Enforce-TLS-SSL".

There is a built-in Policy that can be used: [Event Hub namespaces should have the specified minimum TLS version](https://www.azadvertizer.net/azpolicyadvertizer/4b282e56-3249-4812-8ab8-6e0f208cea7b.html)

**Describe the solution you'd like**

The mentioned policy should be added to the Initiative.

**Comment by Springstone** [comment]
@Steph409 Thank you for raising the issue, we'll add it to our backlog.

**Comment by Springstone** [comment]
Addressed in PR: https://github.com/Azure/Enterprise-Scale/pull/1622
