### ISSUE TITLE
[PolicySet]: Deploy Diagnostics Settings for multiple resource types to send logs to Storage Account

### ISSUE THREAD

**Issue by diiyyani** [Azure/Enterprise-Scale#1581]
### Policy Definition or Initiative

Initiative

### Built-in/Custom

Custom

### Built-in policy definition or initiative ID

<GUID>

### Custom policy definition or initiative description

This is a policyset that deploys Diagnostics Settings for multiple resource types to send logs to Storage Account

### Scope

Landing Zones

### Default Assignment

- [ ] Yes

**Comment by Springstone** [comment]
@diiyyani this is coming soon. We'll be providing the option to choose target - Log Analytics, Event Hub or Storage.

**Comment by diiyyani** [comment]
Hello @Springstone, I have added a policyset for this. I've raised the PR as well.

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review  https://aka.ms/alz/whatsnew for details.

If you find gaps in diagnostic settings coverage, please add the missing services to this discussion: [#1644](https://github.com/Azure/Enterprise-Scale/discussions/1644) as this is where we will track this going forward.

For you specific use case, please review this initiative: https://www.azadvertizer.net/azpolicyinitiativesadvertizer/b6b86da9-e527-49de-ac59-6af0a9db10b8.html
