### ISSUE TITLE
Bug Report - azPortal Template link returning 404

### ISSUE THREAD

**Issue by tareafina** [Azure/Enterprise-Scale#1582]
**Describe the bug**
The "azPortal" link into the Custom Template deployment for ALZ is returning 404 

**Steps to reproduce**

1. Go To Azure Portal -> Deploy a Custom Template -> Azure Landing Zone -> click on Template "azPortal" Link
2. This forward to a Github returning 404

**Screenshots**

![image](https://github.com/Azure/Enterprise-Scale/assets/63680060/7115eeab-c092-4ce8-8754-6f52a5ec4b13)

![image](https://github.com/Azure/Enterprise-Scale/assets/63680060/4741c2ab-418d-4782-8bca-67fb79e1e06e)

**Comment by Springstone** [comment]
@tareafina Good shout and thank you for pointing this out. We'll work on addressing this asap.

**Comment by jtracey93** [comment]
This has been resolved by the custom portal team and is rolling out as we speak
