### ISSUE TITLE
Deploy-Diagnostics-MlWorkspace is not working for all types of "Microsoft.MachineLearningServices/workspaces"

### ISSUE THREAD

**Issue by NucLabs** [Azure/Enterprise-Scale#1583]
**Describe the bug**
Apparently more then one (sub?) types of machine learning workspaces (Microsoft.MachineLearningServices/workspaces) do exist in Azure. In the portal the type is different (**Azure AI** vs **Azure AI project**), but the resource type is, confusingly, the same.
The policy Deploy-Diagnostics-MlWorkspace tries to deploy diagnostic settings on both types, but only succeeds on the second one (Azure AI project).
Diagnostic settings for both types are very different: Azure AI only has metrics, while the logs/metrics of Azure AI project match the ones defined in the policy definition.

The error reported by the policyaction (deployment) is **Category 'AmlComputeClusterEvent' is not supported**

**Screenshots**
![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/85ba3c47-7e45-4187-b8d5-b05dea5dccf1)

![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/7b27516a-2008-4856-8389-82a2674a1e07)

**Comment by Springstone** [comment]
@NucLabs thanks for raising your concern. We are aware of the issues in this space and are transitioning to a more comprehensive solution in the near term. This is a general problem with the various resource providers that we have no control over. In the near term you will have to log ALL METRICS to get all the required data for all resource providers (until all the RPs support Audit Logs only category).

**Comment by NucLabs** [comment]
I did a little dive into the policies that are available now. Are you referring to the "Enable logging by category group*" builtin policies. Will the CAF initiative contain those, instead of the custom policies?

**Comment by Springstone** [comment]
There are a new set of policies and initiatives coming soon, 412 policies and 6 initiatives, covering 137 Azure services and a set depending on the log target (Log Analytics, Event Hub or Storage).

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
