### ISSUE TITLE
External Community Call - 12th June 2024

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#1596]
Sign up: https://msit.events.teams.microsoft.com/event/7f00ed0a-86d7-4c9f-88a9-aafa5ac386bb@72f988bf-86f1-41af-91ab-2d7cd011db47

Please leave comments below on topics you'd like covered

**Comment by DarrylRomano** [comment]
Will there be a video link afterwards?  or a North American timezone call as well?

**Comment by jtracey93** [comment]
Hi @DarrylRomano,

Every quarter we flip between APAC and US friendly slots to ensure everyone is included. 

It will be available on YouTube within 24 hours of the call though. Checkout https://aka.ms/alz/community for the links
