### ISSUE TITLE
Feature Request: Policies for Grafana missing

### ISSUE THREAD

**Issue by steph409** [Azure/Enterprise-Scale#1604]
**Describe the feature**
Grafana is missing in the following initiatives:
1. [Deny-public-paas](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints.json) - there is a [built-in policy which should be added](https://www.azadvertizer.net/azpolicyadvertizer/e8775d5a-73b7-4977-a39b-833ef0114628.html)

2. The policy is also missing in the [Deploy-Private-DNS ](https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json) but there is already an open ticket for that #1485 

Would be great that you add grafana to both initiatives!

Thanks,
Stephanie

**Comment by Springstone** [comment]
@steph409 Thanks for raising this issue. FYI Deny-PublicPaas has been updated and is part of this PR : https://github.com/Azure/Enterprise-Scale/pull/1622.
@rozkurt to review adding to Private DNS Zones policy.

**Comment by Springstone** [comment]
@steph409 This has been addressed fully in two PRs, the private link PR is #1578. These PRs are in the Policy-Refresh branch, and will be merged to main towards the end of May. Closing the issue as no further action required from ALZ team.
