### ISSUE TITLE
Deployment Template Error: SQL Server Policy Set Definition

### ISSUE THREAD

**Issue by liamfoneill** [Azure/Enterprise-Scale#161]
Just got an error on a fresh deployment of Bootstrap Template - it's trying to create the definition for SQL Server Security Policy Set/Initiative before the child policies definitions are deployed it seems like: 

![image](https://user-images.githubusercontent.com/1243172/89770505-c5966800-daf6-11ea-8df0-4b06ab0ca6ab.png)

Deployment Correlation ID: 3d0d6f03-9238-4f40-afd1-e5f5c928b496
Tracking ID: 45dbc7eb-7332-49d7-a7dd-b6fcdc4949e9

Status Message:

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "DeploymentFailed",
                "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
                "details": [
                    {
                        "code": "BadRequest",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy set definition 'Deploy-Sql-Security' request is invalid. The following policy definitions could not be found: '/providers/Microsoft.Management/managementGroups/liam/providers/Microsoft.Authorization/policyDefinitions/Deploy-Sql-Tde;/providers/Microsoft.Management/managementGroups/liam/providers/Microsoft.Authorization/policyDefinitions/Deploy-Sql-SecurityAlertPolicies;/providers/Microsoft.Management/managementGroups/liam/providers/Microsoft.Authorization/policyDefinitions/Deploy-Sql-AuditingSettings;/providers/Microsoft.Management/managementGroups/liam/providers/Microsoft.Authorization/policyDefinitions/Deploy-Sql-vulnerabilityAssessments'.\"\r\n  }\r\n}"
                    }
                ]
            }
        ]
    }
}

**Comment by uday31in** [comment]
@liamfoneill  - which implementation did you select?

cc: @krnese

**Comment by liamfoneill** [comment]
Quickstart Template (the one on Repo Root Readme)

**Comment by krnese** [comment]
@liamfoneill - could you reproduce this?

**Comment by liamfoneill** [comment]
I deleted everything and did it again and it didn't occur second time. Seems like a race condition

**Comment by krnese** [comment]
Per our earlier discussion, I will close this for now and we will monitor the occurrence of this moving forward - thx for reporting!
