### ISSUE TITLE
Azure Landing Zone template doesn't work properly

### ISSUE THREAD

**Issue by arantza-gft** [Azure/Enterprise-Scale#1617]
**Describe the bug**
The "Azure Landing Zone" template of the Azure portal does not work correctly. I follow the wizard steps and when I get to the validation point, it fails. These are the errors:
![template](https://github.com/Azure/Enterprise-Scale/assets/166702901/8b4625af-cc13-455b-851c-e3d45de622e9)

{"code":"MultipleErrorsOccurred","details":[{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-Mgs-westeurope-7ef11e7f-7f13-5de0-b95f-1b87472dc98f","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-MgmtSub-westeurope-7ef11e7f-7f13-5de0-b95f-1b87472dc98f","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-ConnectivitySub-westeurope-7ef11e7f-7f13-5de0-b95f-1b87472dc","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-IdentitySub-westeurope-7ef11e7f-7f13-5de0-b95f-1b87472dc98f","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-LAPolicy-westeurope-7ef11e7f-7f13-5de0-b95f-1b87472dc98f","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-ASB-westeurope-7ef11e7f-7f13-5de0-b95f-1b87472dc98f","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-ResourceDiagnostics-westeurope-7ef11e7f-7f13-5de0-b95f-1b874","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-ActivityDiagnostics-westeurope-7ef11e7f-7f13-5de0-b95f-1b874","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-CostOptimization-westeurope-7ef11e7f-7f13-5de0-b95f-1b87472d","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."},{"code":"InvalidTemplate","target":"/providers/Microsoft.Resources/deployments/alz-ZoneResilient-westeurope-7ef11e7f-7f13-5de0-b95f-1b87472dc98","message":"Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'."}],"message":"Multiple error occurred: BadRequest,BadRequest,BadRequest,BadRequest,BadRequest,BadRequest,BadRequest,BadRequest,BadRequest,BadRequest. Please see details."}
**Steps to reproduce**

1. Login to the azure portal with a user with elevated global permissions and with permissions on / (root management groups).
2. Type in the general search box "arm" and select the option "deploy a custom template".
![step1](https://github.com/Azure/Enterprise-Scale/assets/166702901/0bdc778e-04b5-407d-ac03-1bcf4390f8f6)

3. select the options "azure landing zone" and "Quickstart template"and click on next.
![template](https://github.com/Azure/Enterprise-Scale/assets/166702901/bf5d878e-ceff-40d3-a50e-97a2fa585223)

4. fill in all the fields until the end and click on "review and create" button, at this point is where it fails and the errors mentioned above appear 
![validationFinalErrors](https://github.com/Azure/Enterprise-Scale/assets/166702901/936d3d34-959c-4cdf-a727-fda797a3c528)

**Comment by Springstone** [comment]
Hi @arantza-gft, thank you for reporting this issue. I have confirmed that I also get the same error, and am busy investigating the issue.

**Comment by Springstone** [comment]
It seems there is an issue with this link:

![image](https://github.com/Azure/Enterprise-Scale/assets/2101287/81552e65-b0e6-4895-be8d-f606cb7fc48e)

We'll work on getting this updated asap.

In the meantime, you can use this link to successfully deploy the template:

[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json)

**Comment by arantza-gft** [comment]
Hi Sacha
Thanks for your email.

I will look for your response.

Have a nice day
Best regards

**Comment by arantza-gft** [comment]
Hi Sacha
Thank you so much for your help.
The link work properly 😊

Best regards

**Comment by djtech2k-MS** [comment]
I am seeing the same issue.  When going through the portal to the "Deploy Custom Template > Landing Zone" section, the ESLZ template fails and the params are different that the Deploy link from above.

**Comment by Springstone** [comment]
@djtech2k-MS Please use the link above to deploy for now. We are working with PG to address the link issues as reported.
