### ISSUE TITLE
policy definition Deploy-Diagnostics-Website is incompliant because of new log category in App Service resource 

### ISSUE THREAD

**Issue by NucLabs** [Azure/Enterprise-Scale#1620]
**Describe the bug**
A new log category was added to WebApps (see picture) rendering all WebApp resources incompliant for the policy  **Deploy-Diagnostics-Website**

**Steps to reproduce**

1. Assign the policy Deploy-Diagnostics-Website to a scope
2. Deploy a web app in the scope. Diagnostic settings will be configured, but not for the **App Service Authentication logs** category

**Screenshots**
![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/4116bde0-481c-4d60-b8d2-f3545e3264e0)
![image](https://github.com/Azure/Enterprise-Scale/assets/25298846/68147662-951f-4dc0-a618-3fc892e586c1)

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review  https://aka.ms/alz/whatsnew for details.

If you find gaps in diagnostic settings coverage, please add the missing services to this discussion: [#1644](https://github.com/Azure/Enterprise-Scale/discussions/1644) as this is where we will track this going forward.
