### ISSUE TITLE
Defender selection fails: Error inlogs read Defender plan not selected

### ISSUE THREAD

**Issue by francoislegrange** [Azure/Enterprise-Scale#1631]
Deploying the accelerator step "Platform management, security, and governance" has a lot of radio buttons to enable or disable deployment features. But when deployment run, logs show that Defender deployment failed because a Defender plan was not selected. There are no option to select a plan in the accelerator

**Steps to reproduce**

1. Kick off process from here https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/
2. Select all Defender options under "Platform management, security, and governance"

**Screenshots**

**Comment by Springstone** [comment]
@francoislegrange Thanks for reporting. Please see this issue for more information: https://github.com/Azure/Enterprise-Scale/issues/1606.
Will be fixed as part of the policy refresh, for now, only Defender for API is impacted, and you will need to manually configure that.
