### ISSUE TITLE
Policy Deploy-ASC-SecurityContacts is always non-compliant

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#1637]
**Describe the bug**
The policy Deploy Microsoft Defender for Cloud Security Contacts remains non-compliant despite of successfull remediation task

**Steps to reproduce**

See https://github.com/Azure/Enterprise-Scale/issues/1477. This issue was resolved but it seems to back.

**Screenshots**

**Comment by Springstone** [comment]
This is a known issue due to PG making changes to the API. We're waiting for those changes to settle, and at the same time hoping they'll publish a built in :)
But will review and update for next sprint.

**Comment by Springstone** [comment]
We're tracking this in #1627, so will close this one.
