### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by nielsophey** [Azure/Enterprise-Scale#164]
**Describe the bug**

when cloning the repo under a Windows 10 machine I always get an error "Filename too long" in the azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/contoso (contoso)/ Folder. Multiple files are mentioned e.g.  azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/contoso (contoso)/platform (platform)/identity (9e32661b-498f-4fd8-bffc-c9ecb4830430)/.AzState/Microsoft.Authorization_policyAssignments-Deploy-vNet-Identity.parameters.json

If I clone the repo in the wsl on the same machine in a different folder it works...
**Steps to reproduce**

1. Create a new repo out of the template
2. Open VS-Code in Windows
3. Try to clone the new repo
4. Get the error message even if I try to use c:\es

**Screenshots**

![image](https://user-images.githubusercontent.com/19270496/89819721-2bf9a580-db4c-11ea-8368-687f86ae7d4a.png)

**Comment by krnese** [comment]
Can you please follow the step described @ https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/getting-started.md#enabling-long-paths-on-windows ?

**Comment by nielsophey** [comment]
I just double checked - I'm sorry I have updated git today on the machine and the regkey is still set, but after the gut update installation you have to set "git config --system core.longpaths true" again...

I did not know that - sorry
