### ISSUE TITLE
Private DNS Resolver in Hub-Spoke VNET

### ISSUE THREAD

**Issue by gerrynicol** [Azure/Enterprise-Scale#1642]
[AB#35135](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/35135)

### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Maybe not a feature request but more a question around ALZ design. It appears the documentation for the Azure private DNS resolver has changed and the recommendation is now to have this hosted in a seperate spoke VNET with the Private DNS Zones linked to this rather than the Hub vNET. (This seems to be due to potential issues with having it hosted in the same VNET as an express route gateway). The ALZ deployment still has the vNET links to the Azure Private DNS zones to the Hub vNET. Just looking for thoughts on the differences here and also thoughts on what Subscription that shared services spoke vNET should sit? The Connectivity Subscription?

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

To match with the Azure Private DNS Resolver documentation. https://learn.microsoft.com/en-us/azure/architecture/networking/architecture/azure-dns-private-resolver

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Can you describe any alternatives that you have taken since this feature does not exist?

N\A

### Feature Implementation

```Shell
N\A
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Closing this off as we have addressed this and presented on community call which you can see here: https://youtu.be/m4_peeUdZoY?si=ylM5_y1N4ox0t8Og&t=377
