### ISSUE TITLE
Deny-Subnet-Without-Nsg policy blocks the deployment of Subnet using Terraform 

### ISSUE THREAD

**Issue by dpb519** [Azure/Enterprise-Scale#1665]
**Describe the bug**
Once the policy to block subnets without NSG is enforced via deny mode. We are unable to deploy a subnet using the terraform. The terraform resource provider doesn't have an option to pass the NSG while creating the subnet. Only way is to do the association after the subnet is created. However once the said policy is enforced, we wont be able to create the subnet.

We are aware of the other ways to do the association, however while creating a new subnet on an existing virtual network and terraform template, we are unable to find a way forward.

**Comment by jtracey93** [comment]
Hey @dpb519,

This is a known behaviour I'm afraid for terraform, and we document it here https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Getting-Started#additional-considerations-when-deploying-landing-zone-resources-with-terraform

You could look at using the AzApi provider to achieve this though  https://learn.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworks/subnets?pivots=deployment-language-terraform or https://learn.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworks?pivots=deployment-language-terraform
