### ISSUE TITLE
Policy Refresh for Enterprise scale environment.

### ISSUE THREAD

**Issue by Anto4595** [Azure/Enterprise-Scale#1667]
Hello Team,

Based on this Article. https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#may-2024

We deployed Enterprise Scale Environment in Oct-2022 and never refreshed the Policies. 

So Please suggest how we can refresh policies based on the Above Article.

Any information and Steps will be helpful.

Thank You...

**Comment by jtracey93** [comment]
Please checkout https://aka.ms/alz/update where we have guidance for this 👍
