### ISSUE TITLE
this should be $policyDefinitionPath insead of $policySetDefinitionPath

### ISSUE THREAD

**Issue by Pawel1985** [Azure/Enterprise-Scale#1669]
https://github.com/Azure/Enterprise-Scale/blob/c6fe0fe5a35d4fe0199cec58c7105e9d34d4f029/docs/wiki/Update-ALZ-Custom-Policies-to-Latest.md?plain=1#L246

this should be $policyDefinitionPath insead of $policySetDefinitionPath

**Comment by jtracey93** [comment]
Hey @Pawel1985,

Thanks for the issue, do you want to submit a PR with this change?

**Comment by Pawel1985** [comment]
hi @jtracey93, I submitted the PR for that, my very first ever ;)

**Comment by jtracey93** [comment]
closed by #1685
