### ISSUE TITLE
Bug Report: Update changes from Upstream assumes the local repo exists...

### ISSUE THREAD

**Issue by abudja** [Azure/Enterprise-Scale#167]
"Configure your repo to update changes from upstream" section (https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/setup-github.md#5-configure-your-repo-to-update-changes-from-upstream) assumes the local repo already exists. However, if we follow the instructions from the top we don't have a local repo by this stage... While the instructions in the pre-requisites clone the repo (https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/getting-started.md) they also instruct us to delete the folder...

Also, Enterprise-Scale "In a box" instructions (https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/deploy-tenant.md) want us to "Configure your repo to update changes from upstream" BEFORE cloning of the repo, which is in (https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/deploy-tenant.md).

**Comment by ljtill** [comment]
Closing this issue as we've redesigned [AzOps](https://github.com/Azure/AzOps) and how it operates, please visit the [Accelerator](https://github.com/Azure/AzOps-Accelerator) repository for more information.
