### ISSUE TITLE
Azure policy Deploy SQL database vulnerability assessment is now deprecated

### ISSUE THREAD

**Issue by amp-pds** [Azure/Enterprise-Scale#1676]
### What happened? Provide a clear and concise description of the bug, including deployment details.

The Azure policy Deploy SQL database vulnerability assessment which is in the Deploy SQL database built-in security configuration policy set is now tagged as deprecated.

Can the policy set be updated with the latest policy to replace that?

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Springstone** [comment]
Hi @amp-pds! Please note that the initiative in question has been updated, and there is a new version available (and deployed by ALZ as of the latest release) - the new initiative is https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Sql-Security_20240529.html (the old initiative has been deprecated).
