### ISSUE TITLE
Feature Request - CAF Diagram - Add VNET & Peering to Identity?

### ISSUE THREAD

**Issue by mundayn** [Azure/Enterprise-Scale#1678]
Hi all,

Would it make sense to show VNET peering to Identity in the CAF ESLZ diagrams? As there are DC1 and DC2 examples, I think it would be clearer for people to understand how they connect to the HUB, something like this (rough draft). I've swapped around Management and Identity so they sit better:

![image](https://github.com/Azure/Enterprise-Scale/assets/19361863/6757d287-b72a-4951-b9d0-0017447965a1)

**Comment by Springstone** [comment]
Looks like the VISIO update addresses your ask. Closing as there is no further action required.
