### ISSUE TITLE
Enterprise-Scale In a Box instructions not aligned with the Contoso reference Implementation

### ISSUE THREAD

**Issue by abudja** [Azure/Enterprise-Scale#168]
Enterprise-Scale In a Box instructions (https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/deploy-tenant.md) are not aligned with the Contoso Reference Implementation. The screenshots in the instructions have different options than the template.
 

![image](https://user-images.githubusercontent.com/44183085/90085206-badc0d00-dd5a-11ea-973e-fc3204c27447.png)

**Comment by hjscherer** [comment]
ES iab document has been updated and reflects the latest portal experience.
