### ISSUE TITLE
[Policy]: Update of Configure Microsoft Defender CSPM to be enabled to newer built-in policy

### ISSUE THREAD

**Issue by ReneRebsdorf** [Azure/Enterprise-Scale#1680]
### Policy Definition or Initiative

Definition

### Built-in/Custom

Built-in

### Built-in policy definition or initiative ID

72f8cee7-2937-403d-84a1-a4e3e57f3c21

### Custom policy definition or initiative description

72f8cee7-2937-403d-84a1-a4e3e57f3c21 is from 2024-01-31 and supersedes the currently implemented 689f7782-ef2c-4270-a6d0-7664869076bd which is used in the initiative 'Deploy-MDFC-Config_20240319'

The new policy implements extensions: [] to Microsoft.Security/pricings/CloudPosture

I suggest Deploy-MDFC-Config_20240319 is updated to replace 689f7782-ef2c-4270-a6d0-7664869076bd with 72f8cee7-2937-403d-84a1-a4e3e57f3c21 and use the default values already set in 72f8cee7-2937-403d-84a1-a4e3e57f3c21 to "enable-by-default"

### Scope

Intermediate Root

### Default Assignment

- [X] Yes

**Comment by jtracey93** [comment]
PR #1682 closed this
