### ISSUE TITLE
Azure Landing Zone Accelerator Deployment Errors

### ISSUE THREAD

**Issue by FazzaLabs21** [Azure/Enterprise-Scale#1690]
Hi All, Im new to landing zones

When deploying the Azure landing zone accelerator from the custom template into a new blank Azure Tenant with just one subscription in it, I got a failed deployment with this main error: 
The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. Click here for details

These are the deployments errors: 

Landing zone Error: 
Apunipima-corpalz-DiagSettingsMGs-australiaeast-c87bc71a-6be0-5d
The subscription '295b4246-f0ee-4c57-b287-433cec1384e3' is not registered to use microsoft.insights. (Code: Conflict)

Apunipima-landingzonesalz-DiagSettingsMGs-australiaeast-c87bc71a
The subscription '295b4246-f0ee-4c57-b287-433cec1384e3' is not registered to use microsoft.insights. (Code: Conflict)

Apunipimaalz-DiagSettingsMGs-australiaeast-c87bc71a-6be0-5d1a-a5
The subscription '295b4246-f0ee-4c57-b287-433cec1384e3' is not registered to use microsoft.insights. (Code: Conflict)

Apunipima-sandboxesalz-DiagSettingsMGs-australiaeast-c87bc71a-6b
The subscription '295b4246-f0ee-4c57-b287-433cec1384e3' is not registered to use microsoft.insights. (Code: Conflict)

Apunipima-onlinealz-DiagSettingsMGs-australiaeast-c87bc71a-6be0-
The subscription '295b4246-f0ee-4c57-b287-433cec1384e3' is not registered to use microsoft.insights. (Code: Conflict)

Apunipima-decommissionedalz-DiagSettingsMGs-australiaeast-c87bc7
The subscription '295b4246-f0ee-4c57-b287-433cec1384e3' is not registered to use microsoft.insights. (Code: Conflict)

Apunipima-platformalz-DiagSettingsMGs-australiaeast-c87bc71a-6be
The subscription '295b4246-f0ee-4c57-b287-433cec1384e3' is not registered to use microsoft.insights. (Code: Conflict)

alz-KvGuardrailsPlat-australiaeast-c87bc71a-6be0-5d1a-a585-233fa
The policy definition specified in policy assignment 'Enforce-GR-KeyVault' is out of scope. Policy definitions should be specified only at or above the policy assignment scope. If the management groups hierarchy changed recently or if assigning a management group policy to new subscription, please allow up to 30 minutes for the hierarchy changes to apply and try again. (Code: InvalidCreatePolicyAssignmentRequest)

alz-MonitorPolicyLite-australiaeast-c87bc71a-6be0-5d1a-a585-233f
The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure)
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed), {
  "error": {
    "code": "InvalidCreatePolicyAssignmentRequest",
    "message": "The policy definition specified in policy assignment 'Deploy-AMBA-Connectivity' is out of scope. Policy definitions should be specified only at or above the policy assignment scope. If the management groups hierarchy changed recently or if assigning a management group policy to new subscription, please allow up to 30 minutes for the hierarchy changes to apply and try again."
  }
} (Code: BadRequest)

Im deploying into AUS East. 

Any Ideas, I can provide more information if required. 
What are the main isuess here, if i can fix them, how do i redeploy the template without creating Conflicts

![image](https://github.com/Azure/Enterprise-Scale/assets/157605212/251b57d3-b1ca-44a4-8e94-619532c78f5f)

**Comment by Springstone** [comment]
@FazzaLabs21 thanks for opening the issue. You can ignore the issues referring to "30 minutes" as this is an ARM error relating to policy deployment failures and should go away when we resolve the other issue. The first issue is most likely because the resource provider isn't registered on the subscription. Can you please confirm that it is registered:

![image](https://github.com/Azure/Enterprise-Scale/assets/2101287/b01501df-15d6-44df-815d-a9001f1d1746)

**Comment by FazzaLabs21** [comment]
Hi @Springstone. Thanks for coming back to me. 

Microsoft Insights is registered
![image](https://github.com/Azure/Enterprise-Scale/assets/157605212/5a8fc211-d1e1-43e1-976d-2f07aecdf875)

I have just enabled all Insights related resource providers. 
![image](https://github.com/Azure/Enterprise-Scale/assets/157605212/d70f9bdc-efaf-47de-af38-eb66b6c7b746)

**Comment by Springstone** [comment]
@FazzaLabs21 have you tried deploying again, is it working now? Or are you still getting the same error?

**Comment by FazzaLabs21** [comment]
Hi Springstone i deployed again and it worked. Should of tried that before opening a bug ticket, but im new to this. 
Many Thanks.
