### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ilvg** [Azure/Enterprise-Scale#1693]
**Describe the bug**
[alz-IDPeering2] deployment step fails. 
"message": "{\r\n  \"error\": {\r\n    \"code\": \"MinimumApiVersionNotSpecifiedForAddressSpaceUpdateInPeeredVnet\",\r\n    \"message\": \"Address space update operation on virtual network can not be performed as the minimum required API version for working with Vnet Peering is 2021-01-01, and the provided client API version is 2020-05-01.\",\r\n    \"details\": []\r\n  }\r\n}"

**Steps to reproduce**

1. Deploy using Azure Accelerator from https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/
2. Select Identity subscription in one of the screens.

**Screenshots**

**Comment by jtracey93** [comment]
Hey this was resolved in our latest release yesterday :)
