### ISSUE TITLE
Bug Report: Initiative Deploy-MDFC-Config_20240319 does not set parameters correctly for policy migrateToMdeTvm

### ISSUE THREAD

**Issue by steph409** [Azure/Enterprise-Scale#1694]
**Describe the bug**

The initiative  Deploy-MDFC-Config_20240319 has one policy migrateToMdeTvm. This policy takes two input parameters:
1) Effect
2) Slected Vulnerability Assessment provider

When assigning the initiative, it is not possible to set those parameters, as they are not passed in in [the initiative code](https://github.com/Azure/Enterprise-Scale/blob/819c3532f95ce647538a86aeb5639f85ced0198a/src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config_20240319.json#L399).

It would be great if those two parameters were exposed by the initiative, so that they can be modified.

**Steps to reproduce**

Assign initiative Deploy-MDFC-Config_20240319

**Screenshots**

<img width="948" alt="image" src="https://github.com/Azure/Enterprise-Scale/assets/33083326/043e6605-bcdc-4f95-a683-3f9fc1c8fa7f">

**Comment by Springstone** [comment]
@steph409 you can't change the provider, which is why it is hardcoded, and this is why we've "defaulted" to `DeployIfNotExists`. Are you looking to `Disable` this? (as stated, you can't change the provider).
