### ISSUE TITLE
Policy Set, Enforce-Guardrails-Network Bug Report

### ISSUE THREAD

**Issue by MikaelJcSoderberg** [Azure/Enterprise-Scale#1697]
**Describe the bug**
There are wrong values for this parameter :
modifyNsgRuleAccess
`
"modifyNsgRuleAccess": {
   "type": "string",
   "defaultValue": "Deny",
   "allowedValues": [
      "Audit",
      "Deny",
      "Disabled"
    ]
}
`

It should be
`
"modifyNsgRuleAccess": {
   "type": "string",
   "defaultValue": "Deny"
   "allowedValues": [
     "Allow",
     "Deny"
   ]
}
`
**Steps to reproduce**
Assign Enforce-Guardrails-Network

**Screenshots**
![image](https://github.com/Azure/Enterprise-Scale/assets/156294454/ee29e55a-9637-4124-8291-1227eb5328b9)

**Comment by jtracey93** [comment]
@Springstone can you take a look at this one please buddy?

**Comment by Springstone** [comment]
The allowed parameters are indeed incorrect but should not be an issue if you use `Deny`. To address this issue, we have a PR in to address the correct allowed parameters.

**Comment by Springstone** [comment]
Have a PR in #1702 that fixes this and ensure built-in policy alignment for parameters.
