### ISSUE TITLE
Bug Report: Deny-LogicApps-Without-Https.json

### ISSUE THREAD

**Issue by rybal06** [Azure/Enterprise-Scale#1719]
**Describe the bug**

The policy has the same condition copied twice:
```json
                        "anyOf": [
                            {
                                "field": "Microsoft.Web/sites/httpsOnly",
                                "exists": "false"
                            },
                            {
                                "field": "Microsoft.Web/sites/httpsOnly",
                                "equals": "false"
                            }
                        ]
                    }
```
**Steps to reproduce**

1. View the policy in this repo
2. Observe the duplication

**Suggested Action**

1. Remove the duplicate condition from the policy and the "AnyOf" block.

**Comment by teemukom** [comment]
It's not duplicate: the first one checks if the field doesn't exist and the second one if it's value equals to false.
