### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by szemy1** [Azure/Enterprise-Scale#172]
**Describe the bug**
I was trying to deploy the enterprise scale in a box demo, using a Free Azure Account and azops github action failed. 
I have changed the github pipline files:
main/.github/workflows/azops-pull.yml
main/.azure-pipelines/azops-pull.yml
to reflect the free Azure account type  "MS-AZR-0044P" but it still fails. As a result, it doesn't clone my azure enviroment to github

**Steps to reproduce**

1. Please try to run the deployment steps with a Free Azure account

**Screenshots**
![g1XRjKu](https://user-images.githubusercontent.com/8614651/90132088-76a63800-dd6d-11ea-9c84-23f1200e9680.png)

**Comment by uday31in** [comment]
1) can you please try re-running the action?
2) does it work if you don't specify offer_type?

**Comment by uday31in** [comment]
AZOPS_EXCLUDED_SUB_OFFER      by defaults filter FREE subscription type.

Please override that variable in azops-push.yml and azops-pull.yml to include that subscription.

https://github.com/Azure/AzOps/blob/d7ad3a639dff56ed272f141257424cf4a4036293/src/public/Initialize-AzOpsGlobalVariables.ps1#L50

**Comment by szemy1** [comment]
Thank you very much it worked with 3 Subs as well!
