### ISSUE TITLE
Deny-Private-DNS-Zones.json Bug Report

### ISSUE THREAD

**Issue by clissdo** [Azure/Enterprise-Scale#1721]
### Line 42 appears to have a redundant square bracket at the start of the paramater call that is causing an error on import
   
 "policyRule": {
      "if": {
        "field": "type",
        "equals": "Microsoft.Network/privateDnsZones"
      },
      "then": {
        "effect": "[[parameters('effect')]"
      }
    }
  }
}

**Comment by jtracey93** [comment]
Hey @clissdo,

This is not a bug but is the way we need policies to construct the portal experience as we document here in the contribution guide: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide#escaping-policy-functions

If you want to copy a policy to manually, please use AzAdvertizer to do so, as an example for this policy: https://www.azadvertizer.net/azpolicyadvertizer/Deny-Private-DNS-Zones.html

![image](https://github.com/user-attachments/assets/16a53184-aa48-4269-9dca-4dc1147243ee)

Thanks
