### ISSUE TITLE
ALZ Deployment Error: alz-HubSpoke-westeurope-17458f10-5574-537e-98be-2c8501542248

### ISSUE THREAD

**Issue by Anto4595** [Azure/Enterprise-Scale#1722]
Hello @jtracey93 @Springstone 

We are trying to deploy using  Azure Landing Zone Accelerator and after deployment we getting error for 

alz-HubSpoke-westeurope-17458f10-5574-537e-98be-2c8501542248

The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure)

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed), {

  "status": "Failed",

  "error": {

    "code": "ResourceDeploymentFailure",

    "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.",

    "details": [

      {

        "code": "DeploymentFailed",

        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",

        "details": [

          {

            "code": "Conflict",

            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"InternalServerError\",\r\n        \"message\": \"An error occurred.\",\r\n        \"details\": []\r\n      }\r\n    ]\r\n  }\r\n}"

          }

        ]

      }

    ]

  }

} (Code: Conflict)

Can you help what needs to be fixed or need to look for to move forward ?

Awaiting Reply.

Thank You...

**Comment by jtracey93** [comment]
Hey @Anto4595,

Please can you go onto the hub subscription and look at the deployment history and look for a more detailed error message than the one shared above?

https://learn.microsoft.com/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal#subscription-deployments

Or if you can share a correlation ID that will also help us track down what is happening

Thanks

**Comment by Anto4595** [comment]
Hello @jtracey93 We tried to redeploy it and some successful and some where failed.

Subscription: d4-tp-platform-connectivity-dev

For **PolicyDeployment_8574800135058467698**

Correlation ID: 908c8492-f6f8-419c-b86a-5222ab1f2eaf

The error was {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"code\": \"Conflict\",\r\n  \"message\": \"Conflict in InsertAsync for collection ActionGroups\"\r\n}"}]}

For **alz-MDFCSubEnable-westeurope-5bdf1ac0-f50a-5066-9df0-29b9c69721** 

Correlation ID: fe99c3bf-de63-4ba7-b128-ec9166aaa16d

Error: {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"The json value of actions failed validation, with reason: Actions : input Workspace resource id could not be found. Resource id = /subscriptions/c76f0bc2-0b4d-422c-af39-b68d21b6ca4c/resourceGroups/d4-mgmt/providers/Microsoft.OperationalInsights/workspaces/d4-law, error tracking number: 73832ffc-7a68-4f43-9067-172cefb36ffa\"\r\n  }\r\n}"}]}

**Comment by jtracey93** [comment]
Hi this looks like it couldn't find the Log analytics workspace, did you disable it in the portal experience?


You can ignore the policy deployment ones as this is a remediation task creating these from the assigned policies and this just looks like you deployed the AMBA solution as well during the deployment and it has conflicted, but it will get picked up eventually on another scan or change to the in scope resource.

It may be worth cleaning this entire deployment up and starting again, is this a customer or test/dev deployment?

**Comment by Anto4595** [comment]
It was enabled before. So after enabling the Resource Providers for Network, Security, Insights and Automation and run the deployment it was completed successfully....

Thank You @jtracey93 for the inputs...

**Comment by Springstone** [comment]
Awesome, glad you figured it out. Closing as no further action required.
