### ISSUE TITLE
Portal deployment fails to download the template

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/Enterprise-Scale#1744]
**Describe the bug**
Navigating to the portal deployment fails with the issue shown in the screen shot below

**Screenshots**
![image](https://github.com/user-attachments/assets/235a130b-3089-4da7-a2a9-52248a42b793)

**Comment by jtracey93** [comment]
Now working as expected, shortlink issue resolved 
![image](https://github.com/user-attachments/assets/27687082-b34e-41f9-8645-9ad77a3032d7)
