### ISSUE TITLE
Deployment fails while provisioning the VPN Gateway in vwan hub

### ISSUE THREAD

**Issue by mbilalamjad** [Azure/Enterprise-Scale#1748]
**Describe the bug**
Deployment fails with the following error "The vpn gateway deployment operation failed due to an intermittent error."

**Screenshots**
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/880c8de5-e1a5-46cb-b732-88a02ca2f965">

**Comment by jtracey93** [comment]
Believe #1743 resolves this - @brsteph and @Springstone to confirm

**Comment by Springstone** [comment]
#1743 specifically addresses a combination of settings for multi-region VWAN deployments involving gateways, that has now been fixed. In this specific case, there could have been an ARM issue that resulted in the failure. 
If you run the deployment again, do you get the same error?

**Comment by mbilalamjad** [comment]
Tried the template in #1743, that worked and didn't run into this issue

**Comment by brsteph** [comment]
That template was fixing more specific errors - I don't think I had seen the intermittent issue.  When you click into the module itself, what steps in it are failing?  There might be more details about the specific step of the VWAN deployment.

For this, is East US the primary region, or the secondary region?

**Comment by mbilalamjad** [comment]
> That template was fixing more specific errors - I don't think I had seen the intermittent issue. When you click into the module itself, what steps in it are failing? There might be more details about the specific step of the VWAN deployment.
> 
> For this, is East US the primary region, or the secondary region?

Hey @brsteph, I cleaned up the deployment as it was costing $$, East US was primary and West US was secondary, the issue happened while provisioning the VPN Gateway in East US with the template live at the time of reporting this issue, post that I used your template from your branch a couple of times and it deployed fine, we can close this for now and revisit in case it reoccurs
