### ISSUE TITLE
Bug Report - Private DNS link failure when using "Single" Platform subscription

### ISSUE THREAD

**Issue by sdolgin** [Azure/Enterprise-Scale#1752]
Greetings!

When deploying the ALZ Accelerator to a single platform subscription there is an error with the Private DNS Zone links:

![image](https://github.com/user-attachments/assets/13099150-da74-4d36-a774-a1f4f5130648)

From the error details it appears to be trying to create the VNET link more than once:

Private zone 'privatelink.azurecr.io' is already linked to the virtual network '/subscriptions/<subID>/resourceGroups/ALZ-vnethub-eastus/providers/Microsoft.Network/virtualNetworks/ALZ-hub-eastus'. (Code: Conflict)

![image](https://github.com/user-attachments/assets/bf83b484-f5fe-47d8-8a8f-633acf416c9e)

/cc @brsteph

**Comment by brsteph** [comment]
@Springstone  - Looking into this with @sdolgin, testing a fix.
