### ISSUE TITLE
Possibility of deploying Trey Research reference twice in the same tenant

### ISSUE THREAD

**Issue by EstebanZ** [Azure/Enterprise-Scale#1763]
Hi,

I have a question about the possibility of deploying the Trey Research reference (https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md) twice in the same Azure tenant.

Currently, I have one Trey Research implementation with specific customizations (three subscriptions: mgmt, connectivity, and identity). I would like to know if it is possible to perform a second deployment of this same reference in the same tenant without affecting tenant-level components.

Additionally, I have attached a diagram where the crossed-out components were not deployed 
<img width="573" alt="image" src="https://github.com/user-attachments/assets/b873f601-cff9-48d5-b84c-aa8954e3b971">

I would appreciate any guidance or additional documentation you can provide on this topic.

Thanks in advance.

**Comment by mundayn** [comment]
To the best of my knowledge, nothing is Tenant Level, or "Tenant Root Group" level, everything is that the "Intermediate root management group", in your scenario "Contoso".

So if you built "Contoso-New" under "Tenant Root Group", applied the new ESLZ to this, nothing would be impacted at the "Contoso" level.

**Comment by EstebanZ** [comment]
Thank you very much for your response. I understand that everything is managed at the intermediate root management group level, in this case, “Contoso”.

**Comment by EstebanZ** [comment]
Given that everything is managed at the intermediate root management group level (in this case, “Contoso”), I would like to understand at a high level how roles might be affected when deploying ESLZ. Specifically:

Roles: Are there any predefined roles that ESLZ deploys, and how do they interact with existing roles in the tenant? Could there be any potential conflicts or overlaps?

**Comment by jtracey93** [comment]
As long as you chose a different root ID prefix, which im sure you will, you can deploy multiple times in the same tenant.

Everything from an ALZ perspective is stored at the intermediate root management group level, even our custom roles.
