### ISSUE TITLE
Bug Report - InternalServerError using ALZ Portal Accelerator

### ISSUE THREAD

**Issue by SeanKelly35** [Azure/Enterprise-Scale#1775]
Note from ALZ Core Team:
>[!IMPORTANT]
> Known issue in ARM, being resolved as we speak: see https://github.com/Azure/Enterprise-Scale/issues/1775#issuecomment-2374537416

---

Landing zone accelerator from the Microsoft Azure Training for AZ-305 is having issues completing the template correctly. I am getting an internal server error message. I followed the instructions precisely on this page: https://learn.microsoft.com/en-us/training/modules/cloud-adoption-framework-ready/6-deploy-blueprint

Yet I still get the error.
![image](https://github.com/user-attachments/assets/1e348694-2a56-46ae-a5bb-df2e1c3d8534)

Explain with Copilot says to select a resource from the select a resource pane, I find a hidden resource and then it errors out saying there was still an internal server error. 

![image](https://github.com/user-attachments/assets/96940eb5-9a01-441f-960c-8e8beb3d2152)

Hoping to get some help so that I can continue my studies. Thanks.

**Comment by SeanKelly35** [comment]
Here are the settings of my attempted landing zone accelerator deployment
![image](https://github.com/user-attachments/assets/97b9e972-dde9-4bc1-9234-d09db6047c72)
![image](https://github.com/user-attachments/assets/406ddc45-de00-49d4-bccd-33c761909642)
![image](https://github.com/user-attachments/assets/4a7ae1e8-bca9-47cc-8a87-835b63b7e7bd)
![image](https://github.com/user-attachments/assets/15b12a59-dc35-4fc1-8cc0-abbab4ff016f)

**Comment by jdrepo** [comment]
Same problem here, tried it in different tenants and with different settings and I always get after review + create  validate the above mentioned "internal server error"

`{"code":"InternalServerError","message":"Encountered internal server error. Diagnostic information: timestamp '20240925T062626Z', subscription id '', tracking id '8a909214-2339-43d2-8622-c7227ab8ce56', request correlation id '4e2ffe5b-98d9-447b-9466-502aaaa8b4e6'."}`

![image](https://github.com/user-attachments/assets/acc326ce-fc51-4fdd-acc1-0e0bf5cdcc50)

![image](https://github.com/user-attachments/assets/056fd7b4-e997-4e5b-bd4e-e2fd466f7f84)

Are there any further logs available where I can see what the problem for the internal server error is ?

**Comment by jtracey93** [comment]
Hey @SeanKelly35 & @jdrepo,

Thanks for reporting. We also noticed this to and have tracked this down to a bug in ARM that we are working closely with the engineering team to resolve.

We have identified the cause and are working out steps to remediate the rollout the changes to ARM ASAP.

For clarity this is not an issue with ALZ, and is impacting many other ARM/Bicep templates that use a particular nested deployment feature in a certain way. We understand this may be frustrating but we are working closely between the two teams to resolve as fast as possible.

Thanks for understanding

Jack

**Comment by jensdiedrich** [comment]
Hey @jtracey93 

no problem at all, so I know that it has nothing to do with my tenant or subscription. 
So I will go the ALZ-Bicep path

Regards

**Comment by SeanKelly35** [comment]
Thanks so much for getting back to me. I can wait for a bit. Cheers!

**Comment by jtracey93** [comment]
Hey @jensdiedrich @SeanKelly35 @jdrepo 

This has now been fixed and rollout was made overnight, and we have tested and all working :)

**Comment by jdrepo** [comment]
Hey @jtracey93 , thanks for the notification, yes now it seem that I can get over the review + create step and the deployment starts now. But now I have an issue with the single subscription scenario. Will open another issue

**Comment by SeanKelly35** [comment]
@jtracey93 Thanks a bunch will give it a try later today.
