### ISSUE TITLE
Single subscription scenario fails

### ISSUE THREAD

**Issue by jdrepo** [Azure/Enterprise-Scale#1779]
**Describe the bug**

Tried to rollout single subscription scenario and got a deplyoment error in the "alz-MonitorPolicyLite" deployment.
Seems to me that there are two management groups "-identity" and "-connectivity" expected to exist but they are not deployed.

Error messages

`The management group 'trey-identity' cannot be found. (Code: ManagementGroupNotFound)`

`The management group 'trey-connectivity' cannot be found. (Code: ManagementGroupNotFound)`

**Steps to reproduce**

1. Deploy with the attached parameter.json file

[parameters.trey.json](https://github.com/user-attachments/files/17148923/parameters.trey.json)

**Screenshots**

![image](https://github.com/user-attachments/assets/0335fcb0-97bc-44eb-a9ee-a3c9a1421908)

**Comment by Springstone** [comment]
Hi @jdrepo, can you please share where you are deploying from? (the page specifically). Is there a specific scenario you are testing? (I see most options are disabled)
The single subscription model is not regularly tested as this isn't the recommended deployment architecture, however, understand there are scenarios where this is the only option.

**Comment by jdrepo** [comment]
Hi @Springstone, I was deploying directy from the GitHub Repo ( https://github.com/Azure/Enterprise-Scale/#deploying-azure-landing-zones-enterprise-scale-architecture-in-your-own-environment )
I only disabled all the MDfC and Connectivity stuff, all the other options are enabled.
I know that a single sub deployment is not the recommended way, I would like to use it to understand the ALZ concepts and workflows without the need to have minimum of 3 subs.

**Comment by Springstone** [comment]
@jdrepo confirm the issue, which is related to AMBA. We'll investigate how to resolve the issue, but as a workaround on the "Baseline alerts..." section, if you set the top two options to no, it should deploy fine:
![image](https://github.com/user-attachments/assets/0a6f2cd4-21b8-46f2-a643-7bdbe229990a)

**Comment by arjenhuitema** [comment]
Hi @jdrepo, thank you for reporting the problem. I have pinpointed the issue, and a solution is now in a pull request.

**Comment by jdrepo** [comment]
Hi @arjenhuitema , thanks for fixing, looking forward to the new version...
