### ISSUE TITLE
ASC Continuous Export Policy Missing from Hub and Spoke 

### ISSUE THREAD

**Issue by huanl40** [Azure/Enterprise-Scale#180]
I noticed the ASC Continuous Export Policy is now omitted from the Hub and Spoke implementation. The policy was previously included with the VWAN implementation. Should this policy be included for Hub and Spoke as well?

**Comment by krnese** [comment]
Thanks for reaching out. This policy is now available as a built-in policy, and hence we will not continue to ship this as a custom policy. 
![image](https://user-images.githubusercontent.com/12991708/90556549-6ccf6b00-e199-11ea-8668-763258462c9e.png)
