### ISSUE TITLE
Bug Report: Applying Policies to an existing environment is throwing an error

### ISSUE THREAD

**Issue by ansingha** [Azure/Enterprise-Scale#181]
**Describe the bug**
Trying to apply Policies to an existing environment using this https://github.com/Azure/Enterprise-Scale/tree/main/azopsreference
 
It was working till last week but is throwing this error today:

_Deployment template validation failed: 'The template resource 'EntScaleoob-sub-policyDef-bda258a0-0836-5684-96c5-be265be92522' at line '196' and column '9' is not valid: The language expression property 'location' doesn't exist, available properties are 'name, tags, properties'.. Please see https://aka.ms/arm-template-expressions for usage details.'. (Code: InvalidTemplate)_

**Steps to reproduce**

1. Logged into Azure Portal in one tab 
2. Opened this URL in another tab and clicked at ‘Deploy to Azure’ button https://github.com/Azure/Enterprise-Scale/tree/main/azopsreference

**Screenshots**
![image](https://user-images.githubusercontent.com/66444438/90338817-38667e00-dfe4-11ea-8ebd-779c0e7e40cc.png)

**Comment by uday31in** [comment]
Can you please let us know policy definition you are trying to deploy and at what scope?

**Comment by ansingha** [comment]
It was working till Thursday but failing for every Policy today.

**Comment by uday31in** [comment]
We are investigating an issue with portal team regarding this? Is it possible to share screenshot of Azure Portal when you click on "Deploy To Azure"?

**Comment by ansingha** [comment]
![image](https://user-images.githubusercontent.com/66444438/90338960-554f8100-dfe5-11ea-94ab-d1180829c126.png)
