### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by muhammad-sha-meme** [Azure/Enterprise-Scale#1813]
**Describe the solution you'd like**

Is there a way that we can deploy azure exemptions along with EPAC in a single bicep file ? any roadmap for this ? It would be handy if we can have exemptions.bicep file to deploy across multiple scopes such as subscription / resoruce group

**Comment by Springstone** [comment]
@muhammad-sha-meme a different team looks after EPAC. Can you please raise the issue there: https://github.com/Azure/enterprise-azure-policy-as-code

As we can't help with this, I'll close the issue here.
