### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SharmainePopov** [Azure/Enterprise-Scale#1815]
Could you provide a small feature - a downloadable csv of alz policy vs scope? Not just the custom alz policy but all that are considered in the standard alz deployment

**Comment by MikaelJcSoderberg** [comment]
https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/media/ALZ%20Policy%20Assignments%20v2.xlsx

Is that something you can use instead of a csv.

**Comment by Springstone** [comment]
@SharmainePopov as @MikaelJcSoderberg kindly shared we do have an Excel that contains all the default assigned policies and initiatives by scope. It is available on the ALZ Policies wiki directly above this link https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#intermediate-root.

Closing as this seems to address your requirement. Should you have a further ask, feel free to re-open.

**Comment by SharmainePopov** [comment]
I just want to point out - for cases where a client may want to compare what they have implemented vs what the Microsoft ALZ implementation recommends and provides (as in a brownfield engagement, a partner ALZ etc)  - it would be very helpful to have this as a csv or text list.

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | ***@***.******@***.***> | 416-799-0807

**Comment by SharmainePopov** [comment]
Hi this is a wiki

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | ***@***.******@***.***> | 416-799-0807
