### ISSUE TITLE
Feature Request - Initiative Deploy-MDFC-Config_20240319

### ISSUE THREAD

**Issue by sweprs** [Azure/Enterprise-Scale#1841]
**Describe the solution you'd like**

The iniative:
https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config_20240319.json

is missing a parameter for **effect** on policy id **766e621d-ba95-4e43-a6f2-e945db3d7888** (Setup subscriptions to transition to an alternative vulnerability assessment solution)

The default is **DeployifNotExists** but if we don't use an external assesment provider I want to have a chance to change the value to **Disabled**

**Comment by Springstone** [comment]
@sweprs thanks for raising the issue. Will review and update.

**Comment by sweprs** [comment]
Great, thanks!
