### ISSUE TITLE
Feature Request - Please add Monitor Agent Deployment for VMSS to Initiative Deploy-VM-Monitoring

### ISSUE THREAD

**Issue by rhaug77** [Azure/Enterprise-Scale#201]
The initiative "Deploy-VM-Monitoring" which is assigned to the management group "ES" contains the deployment of the monitoring agents. Is there a reason why the deployment of the agents (Windows / Linux) for VMSS is not included? 
Please add the deployment of the monitoring agents for VMSS as part of the initiative.

Thank you
@krnese

**Comment by krnese** [comment]
This has been completed in Wingtip reference implementation, and Contoso and AdventureWorks will have similar refresh this week

**Comment by krnese** [comment]
The work is completed.
