### ISSUE TITLE
Unable to deploy Enterprise-Scale templates from command-line

### ISSUE THREAD

**Issue by tescales** [Azure/Enterprise-Scale#204]
**Describe the bug**
Referencing the deployment().templateLink.uri property only works if the template is being run from a repo URL (as happens when clicking Deploy to Azure). When the template repo is cloned and the deployment run locally, that property is missing so the deployment fails. I verified this problem exists with Wingtip, Contoso and AdventureWorks.

I have worked around this in my own templates by using a conditional variable like so:
`"thisRepoUri": "[if(contains(deployment().properties, 'templateLink'), deployment().templateLink.uri, 'https://raw.githubusercontent.com/tescales/azure-letsencrypt/master')]"`

**Steps to reproduce**

1. git clone 
2. az deployment tenant create --template-file xxx.json

**Screenshots**
![image](https://user-images.githubusercontent.com/17342265/91368291-8b4aed00-e7bd-11ea-875a-a85d7631a965.png)

**Comment by krnese** [comment]
Thanks. The templates are optimized for portal deployment, and to be deployed using the URIs for the main - as well as the linked templates depending on your selection. Is there a reason why you want to deploy via cli for bootstrapping?

**Comment by krnese** [comment]
For completeness - here's how you would deploy the reference implementation using command-line:
New-AzTenantDeployment -Name <name> -Location <location> -TemplateUri "https://raw.githubusercontent.com/Azure/Enterprise-Scale/main/docs/reference/wingtip/armTemplates/es-foundation.json"
