### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by cangdaox** [Azure/Enterprise-Scale#205]
**Describe the bug**
Validation failed. 
...... does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/NoMarketplace-20200827024317' or the scope is invalid. If access was recently granted, please refresh your credentials."

I am not sure if it's a bug, IAM issue, or subscription issue. I am attempting to use many different types of subscriptions to try to make it work but the error is consistently the same. Any help is appreciated.

**Steps to reproduce**

1. Deploy template
2. Reach Review + create section and it will not pass validation

**Screenshots**

![image](https://user-images.githubusercontent.com/23113717/91425133-96c70400-e80f-11ea-815b-99295e834030.png)

**Comment by krnese** [comment]
Pls see the following article on the pre-reqs - granting permission to do ARM template deployment at the tenant root (/) scope @ https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md

**Comment by cangdaox** [comment]
Yes. I definitely fulfilled that requirement and it has been over 30 minutes and I have already tried logging in and out. Maybe I might have to wait a little bit longer?

**Comment by krnese** [comment]
Thanks for confirming. Yes, it can take some time before the roleAssignment is fully completed. If you still encounter issues, pls send me an email at krnese[at]microsoft.com and I will follow-up directly.

**Comment by cangdaox** [comment]
Issue is resolved. It was my misunderstanding the whole time about the root, "/", management group. It is only exposed via PowerShell it seems so do it via PowerShell and not the GUI. Through the GUI, the highest level that can be seen is the root management group. Should've just read the docs! (I did but apparently didn't understand it to it's entirety).
https://docs.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin

**Comment by krnese** [comment]
Thanks for confirming it is working now!
