### ISSUE TITLE
Template Validation Failed (tenant.json)

### ISSUE THREAD

**Issue by mjazwiecki** [Azure/Enterprise-Scale#207]
when trying to push changes through push pipeline (or workflow, as the error is the same for both ADO and GitHub), the following error occurs: 
![image](https://user-images.githubusercontent.com/51361414/91534852-8e0b2680-e912-11ea-9316-f2151dad7630.png)
any idea how to make it work?
thanks

**Comment by uday31in** [comment]
Can you provide template parameter artefact used?


Thanks,
Uday
________________________________

**Comment by mjazwiecki** [comment]
`{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "input": {
      "value": {
        "Id": "/providers/Microsoft.Management/managementGroups/mat-sandboxes",
        "Type": "/providers/Microsoft.Management/managementGroups",
        "Name": "mat-sandboxes",
        "TenantId": "[cut]",
        "DisplayName": "mat-sandboxes",
        "UpdatedTime": "0001-01-01T00:00:00Z",
        "UpdatedBy": null,
        "ParentId": "/providers/Microsoft.Management/managementGroups/mat",
        "ParentName": "mat",
        "ParentDisplayName": "mat",
        "Children": null,
        "properties": {
          "policyDefinitions": [],
          "policySetDefinitions": [],
          "policyAssignments": [
            {
              "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
              "contentVersion": "1.0.0.0",
              "parameters": {
                "input": {
                  "value": {
                    "Identity": null,
                    "Location": "northeurope",
                    "Name": "Allowed-RGLocation",
                    "Properties": {
                      "Description": null,
                      "DisplayName": "Allowed locations for resource groups",
                      "NotScopes": null,
                      "Parameters": {
                        "listOfAllowedLocations": {
                          "value": [
                            "northcentralus",
                            "northeurope",
                            "westeurope"
                          ]
                        }
                      },
                      "PolicyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/[cut]",
                      "Scope": "/providers/Microsoft.Management/managementGroups/mat-sandboxes"
                    },
                    "ResourceType": "Microsoft.Authorization/policyAssignments"
                  }
                }
              }
            }
          ],
          "roleDefinitions": [],
          "roleAssignments": []
        }
      }
    }
  }
}`

**Comment by uday31in** [comment]
You have got it extra values that is not required

```
{
	"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"input": {
			"value": {
				"Id": "/providers/Microsoft.Management/managementGroups/mat-sandboxes",
				"Type": "/providers/Microsoft.Management/managementGroups",
				"Name": "mat-sandboxes",
				"TenantId": "[cut]",
				"DisplayName": "mat-sandboxes",
				"UpdatedTime": "0001-01-01T00:00:00Z",
				"UpdatedBy": null,
				"ParentId": "/providers/Microsoft.Management/managementGroups/mat",
				"ParentName": "mat",
				"ParentDisplayName": "mat",
				"Children": null,
				"properties": {
					"policyDefinitions": [],
					"policySetDefinitions": [],
					"policyAssignments": [{

						"Identity": null,
						"Location": "northeurope",
						"Name": "Allowed-RGLocation",
						"Properties": {
							"Description": null,
							"DisplayName": "Allowed locations for resource groups",
							"NotScopes": null,
							"Parameters": {
								"listOfAllowedLocations": {
									"value": ["northcentralus", "northeurope", "westeurope"]
								}
							},
							"PolicyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e765b5de-1225-4ba3-bd56-1ac6695af988",
							"Scope": "/providers/Microsoft.Management/managementGroups/mat-sandboxes"
						},
						"ResourceType": "Microsoft.Authorization/policyAssignments"


					}],
					"roleDefinitions": [],
					"roleAssignments": []
				}
			}
		}
	}
}
```

**Comment by mjazwiecki** [comment]
thank you!
