### ISSUE TITLE
Deployment issue when using Azure Devops 

### ISSUE THREAD

**Issue by denisbuco** [Azure/Enterprise-Scale#210]
I´m running into this error, when trying to deploy the Contoso Enterprise Scale via Release Pipeline:

Deployment template validation failed: 'The template resource 'policydeployment' at line '1' and column '4592' is not valid: The language expression property 'location' doesn't exist, available properties are 'name, properties'.. Please see https://aka.ms/arm-template-expressions for usage details.

This seems to be the "breakpoint" with the policy template: 
![image](https://user-images.githubusercontent.com/33481621/91838890-7a332d80-ec4e-11ea-91fd-7863341e7064.png)

Any hint what the issue could be?

**Comment by krnese** [comment]
Can you point me to the exact file you are trying to deploy?

**Comment by denisbuco** [comment]
> Can you point me to the exact file you are trying to deploy?


https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/armTemplates/auxiliary/policies.json

I´ve uploaded all files to a Repo inside my DevOps project and run the main es-vwan.json for deployment.

**Comment by krnese** [comment]
Pls note that all these templates are crafted in a way where they are optimized for portal deployment experience as we are doing multiple (conditional) linked template deployments - which we cannot do using templates deployed from local machine/pipeline. I'd recommend you deploy via portal, and if you want to transition to IaC later, you can connect AzOps to your tenant after the fact.
