### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by denisbuco** [Azure/Enterprise-Scale#212]
Documentation: 

https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/setup-azuredevops.md

Configure repository permissions
The build service account <Project> Build Service (<Organization>) must have the following permissions on the repository:

<Project>\Contributors

**Build Service seems to need more permissions. The Docker image deployment is failing, without these permissions**.

![image](https://user-images.githubusercontent.com/33481621/92009959-818b3180-ed49-11ea-8455-8dbeb992cce7.png)

**Comment by ljtill** [comment]
Closing this issue as we've recently redesigned the AzOps module with the new [AzOps-Accelerator](https://github.com/Azure/AzOps-Accelerator) repository.
