### ISSUE TITLE
AzOps-Push workflow got stuck

### ISSUE THREAD

**Issue by faister** [Azure/Enterprise-Scale#225]
**Describe the bug**
AzOps-Push workflow got stuck

**Steps to reproduce**

1. I have done an ES deployment on my management group/subscription. Then when I deployed my own custom policy at a feature branch, during validation the AzOps-Push workflow did not complete. It finally timed out after 2 hours.
2. I cleaned up my previous ES deployment using the PS script described [here](https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/troubleshooting.md#deployment-region). Also deleted the previous management group. I tried afresh with a new ES Contoso template deployment against a new management group.
3. Followed the ES IAB exercise to deploy a vWAN policy assignment and same issue happened - AzOps-Push workflow got stuck, timed out after 2 hours.
4. The issue seems to be with the NorthStar-MG-DC-management deployment, I found that there was an InternalServerError, which doesn't describe much what happened. See screen shots below.

**Screenshots**
![azopspushstucked](https://user-images.githubusercontent.com/8053228/92835902-28915c80-f41f-11ea-86e6-3b3bb55d773b.png)
![azopspushdeployments](https://user-images.githubusercontent.com/8053228/92835931-2f1fd400-f41f-11ea-87a9-395abd614785.png)
![northstarmgdeploymentinservererror](https://user-images.githubusercontent.com/8053228/92835954-347d1e80-f41f-11ea-98f9-f39aae72e593.png)

**Comment by krnese** [comment]
Thanks. Can you please share the correlationId of this deployment? I am unable to see the full string in the screenshot

**Comment by faister** [comment]
Thanks @krnese for pointing out to me that policy assignment had changed. took a deeper look and the history of the policy assignment which had been updated on 7 Sep - https://github.com/Azure/Enterprise-Scale/commit/e7790ee969549337a4cb418e8e9deb883bd66e4e#diff-e6abe7e2f76b50a1cb2cae00ddeee708

**Comment by azMantas** [comment]
I think that I am facing the same issue. Get the same error in deployment blade and the deployment stuck.
My policy is located in .Azstate folder and I am using this template to deploy assignmets 
```
{
    "Identity": {
        "type": "SystemAssigned"
    },
    "Location": "westeurope",
    "Name": "",
    "Properties": {
        "Description": "",
        "DisplayName": "",
        "NotScopes": null,
        "Parameters": {
            "param": {
                "value": [
                    ""
                ]
            }
        },
        "PolicyDefinitionId": "",
        "Scope": "/providers/Microsoft.Management/managementGroups/SDU"
    }
}
```
Any hints ?
