### ISSUE TITLE
Don't encourage Automatic deletion of head branches, as people can break AzOps-pull action when PR merging

### ISSUE THREAD

**Issue by marcosgm** [Azure/Enterprise-Scale#231]
**Describe the bug**
We should not encourage automatically removing feature branches, as it can make PR merging fragile and beak the AzOps-pull action

**Steps to reproduce**

1. Proceed as explained in step 9 (Automatically delete head branches )
2. Later, when merging a PR, click on Merge, then ignore the warning about an Action haven't finished validations and proceed with merging the PR. Because the Action can take a couple minutes, people will click first the green Merge PR button, then ignore the warning about the actton and click on the now grey Merge PR button.
3. The branch will be automatically deleted from github, and the AzOps-pull action will fail with "Checking out existing local branch (branchname)
4. The Action fails and the PR is not taking into consideration, leaving a stale JSON file unprocessed in the Main branch

**Screenshots**

**Comment by adamlash** [comment]
Screenshot for Context
![image](https://user-images.githubusercontent.com/68923704/93638549-7aa92380-f9c5-11ea-9824-a789c7b8f931.png)

**Comment by jstabl** [comment]
I think this is what is happening to me. I pushed my branch and created a PR. The merge button was green 

Now I get an error that the push action can't find the local branch "policy-assignment-vwan"

![image](https://user-images.githubusercontent.com/7582868/104772781-fc297c00-5741-11eb-9535-62ee597ccc06.png)

**Comment by ljtill** [comment]
Closing this issue as we've had a major overhaul of the [AzOps](https://github.com/Azure/AzOps) engine and the implementation of the tool. Please visit the (AzOps-Accelerator)[https://github.com/Azure/AzOps-Accelerator] for more information.
