### ISSUE TITLE
Importanting pipeline in Azure DevOps Fails

### ISSUE THREAD

**Issue by mapoitras** [Azure/Enterprise-Scale#237]
I'm following the steps on https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/setup-azuredevops.md

When I try to "Add two new pipelines, selecting the existing files .azure-pipelines/azops-pull.yml & .azure-pipelines/azops-push.yml"

I get the following error:

"JSON error The exported JSON is not valid or is not compatible with the current product version. Try exporting and importing again."

**Comment by hjscherer** [comment]
@mapoitras can you share the step you did create the pipeline in ADO?

**Comment by krnese** [comment]
Closing as there hasn't been any recent updates.
