### ISSUE TITLE
Share Visio files for diagrams

### ISSUE THREAD

**Issue by jhueppauff** [Azure/Enterprise-Scale#239]
Would help if the visio files to the diagrams in the documentary would be shared :)

**Comment by victorar** [comment]
Hi @jhueppauff , several of the diagrams used are available on this Visio file: https://github.com/Azure/Enterprise-Scale/blob/main/docs/media/NorthStar%20Visio.vsdx

Once we've the additional diagrams in Visio format we'll share them as well.

Cheers,
Victor

**Comment by deberat** [comment]
You can find link for Enterprise Scale visio diagram in the Enterprise Scale Architecture documentation 
- [Azure Enterprise Scale Architecture Documentation](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture)
- [Azure Enterprise Scale visio diagrams](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture)
