### ISSUE TITLE
Wrong information in setup Azure DevOps documentation

### ISSUE THREAD

**Issue by dromao** [Azure/Enterprise-Scale#240]
Hello,

In file setup-azuredevops.md where it is written "In order for the pull pipeline to run, set the main branch to require build verification." it should be "In order for the push pipeline to run, set the main branch to require build verification."

Otherwise the push pipeline is not triggered when a pull request is created.

**Comment by uday31in** [comment]
@dromao  - do you minds submitting PR for this?

**Comment by dromao** [comment]
@uday31in - I have created a PR. Please let me know if you have any comments or something is missing.

**Comment by hjscherer** [comment]
> @uday31in - I have created a PR. Please let me know if you have any comments or something is missing.

**Comment by hjscherer** [comment]
@dromao can you target the PR to the main branch of this repo (Azure/Enterprise-scale) instead of the main in your fork?

**Comment by tejado** [comment]
Maybe I missunderstood something but why should the push pipeline run as a build verification during a pull request review? This concept woult be conflicting with other PR policies (e.g. needed approval). 
I would expect that the push pipeline will run AFTER merging the PR into master, but not before as the changes are (perhaps) not yet approved.

So from my perspective, the correct trigger of the push pipeline would be (in yaml):

```
trigger:
- master
```

**Comment by flomader** [comment]
@tejado I agree, but then also the condition for DeployDevelopment doesn't make sense either:
`and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['System.PullRequest.SourceBranch'], 'refs/heads/system'))`

**Comment by flomader** [comment]
@tejado As far as I understand the reason behind this is that only a successful deployment to Azure can proof that the code written is correct. If configured, there is an approval step before the Push pipeline gets executed.

**Comment by ljtill** [comment]
Closing this issue as we've redesigned [AzOps](https://github.com/Azure/AzOps) with the new [AzOps-Accelerator](https://github.com/Azure/AzOps-Accelerator) repository which includes a new deployment approach.
