### ISSUE TITLE
Bug Report-Conflict Error when deploying

### ISSUE THREAD

**Issue by zimmie67** [Azure/Enterprise-Scale#243]
Deployment is failing with status "Conflict"

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "DeploymentFailed",
                "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
                "details": [
                    {
                        "code": "BadRequest",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy assignment create request is invalid. The policy definition '/providers/Microsoft.Management/managementGroups/test/providers/Microsoft.Authorization/policyDefinitions/Deploy-Log-Analytics' could not be found.\"\r\n  }\r\n}"
                    },
                    {
                        "code": "NotFound",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy definition 'Deploy-Log-Analytics' could not be found.\"\r\n  }\r\n}"
                    }
                ]
            }
        ]
    }
}

**Steps to reproduce**

1. Created Mgt and Landing Zone subscriptions
2. Ensured account in use has proper access rights
3. Launched deployment from GitHub accepting all defaults and just specifying proper Subscriptions
4. Validation passed
![2020-09-25_9-52-11](https://user-images.githubusercontent.com/40432150/94275500-09adc280-ff15-11ea-9895-5725688f3e49.jpg)
![2020-09-25_9-51-39](https://user-images.githubusercontent.com/40432150/94275511-0e727680-ff15-11ea-8e00-1dbf65f45c1b.jpg)

**Screenshots**

**Comment by uday31in** [comment]
can you please re-run deployment?

**Comment by zimmie67** [comment]
I have twice with similar errors, but will retry once more.
thanks

**Comment by zimmie67** [comment]
No luck.
I have tried using East US and East US2 for deployment and have created new management and landing zone subscriptions

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "DeploymentFailed",
                "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
                "details": [
                    {
                        "code": "BadRequest",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLocationUpdate\",\r\n    \"message\": \"The policy assignment 'Deploy-SQL-DB-Auditing' request is invalid. The existing assignment's location cannot be changed from 'eastus' to 'eastus2'.\"\r\n  }\r\n}"
                    },
                    {
                        "code": "Conflict",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentExists\",\r\n    \"message\": \"The role assignment already exists.\"\r\n  }\r\n}"
                    },
                    {
                        "code": "BadRequest",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLocationUpdate\",\r\n    \"message\": \"The policy assignment 'Enforce-SQL-Encryption' request is invalid. The existing assignment's location cannot be changed from 'eastus' to 'eastus2'.\"\r\n  }\r\n}"
                    },
                    {
                        "code": "BadRequest",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLocationUpdate\",\r\n    \"message\": \"The policy assignment 'Deny-Storage-http' request is invalid. The existing assignment's location cannot be changed from 'eastus' to 'eastus2'.\"\r\n  }\r\n}"
                    },
                    {
                        "code": "BadRequest",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLocationUpdate\",\r\n    \"message\": \"The policy assignment 'Deny-IP-forwarding' request is invalid. The existing assignment's location cannot be changed from 'eastus' to 'eastus2'.\"\r\n  }\r\n}"
                    }
                ]
            }
        ]
    }
}

**Comment by zimmie67** [comment]
I cleaned out all subscriptions of every resource, made 2 new subscriptions for Manage and Landing Zone.
Re Ran the tool and now get this failure:

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "DeploymentFailed",
                "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
                "details": [
                    {
                        "code": "BadRequest",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy assignment create request is invalid. The policy definition '/providers/Microsoft.Management/managementGroups/CAF/providers/Microsoft.Authorization/policyDefinitions/Deploy-Log-Analytics' could not be found.\"\r\n  }\r\n}"
                    },
                    {
                        "code": "NotFound",
                        "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy definition 'Deploy-Log-Analytics' could not be found.\"\r\n  }\r\n}"
                    }
                ]
            }
        ]
    }
}

**Comment by krnese** [comment]
When re-running the deployment, pls re-deploy using the same management group prefix and region as you did when deploying the first time. Does that work?

**Comment by zimmie67** [comment]
I successfully redeployed with the same prefix and target management and landing zones.

Thanks!

**Comment by krnese** [comment]
Closing this as we have added workaround into the deployment sequence for all the reference implementations (Contoso, Adventure Works, and Wingtip)
