### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by YRollHid** [Azure/Enterprise-Scale#250]
Using the Deploy to Azure button from https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md (Deploy Enterprise-Scale with Azure VWAN)
At the Validation step I'm getting the following error: 
{"message":"The client 'username' with object id 'xxxx-xxx-xxx-xxxx' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/NoMarketplace-20200930204030' or the scope is invalid. If access was recently granted, please refresh your credentials."}

Note: the user I'm using has Owner permission at the Tenant root.

Somebody has the same issue or have any idea?

Thank you in advance.

**Comment by krnese** [comment]
Pls ensure you have followed the exact steps oulined here: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md 

Can you confirm?

**Comment by YRollHid** [comment]
Hi Kistian,
Indeed I was one scope below (tenant root group).
You must be at tenant root (/)

Thanks for the clarification.
