### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by diesher** [Azure/Enterprise-Scale#257]
**Describe the bug**
I am trying to deploy the [Hub and Spoke architecture example](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2Fdocs%2Freference%2Fadventureworks%2FarmTemplates%2Fes-hubspoke.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2Fdocs%2Freference%2Fadventureworks%2FarmTemplates%2Fportal-es-hubspoke.json).

I followed all steps to deploy the resources but I still keep getting following error message:

The client 'xxxxxxxx' with object id 'xxxx-xxx-xxxx-xxxxxx' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/NoMarketplace-20201007095759' or the scope is invalid. If access was recently granted, please refresh your credentials.

Additionally I have created a custom role with following actions:
        "Microsoft.Resources/deployments/write",
        "Microsoft.Resources/deployments/validate/action",
        "Microsoft.Resources/deployments/whatIf/action",
        "Microsoft.Resources/deployments/cancel/action"

**Steps to reproduce**

1. Grant access management for Azure resources in Azure AD properties
2. Start deployment and fill out all necessary fields

**Comment by uday31in** [comment]
https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md#configure-azure-permissions-for-arm-tenant-deployments

Please ensure you have followed step 1 and step 2 both.
