### ISSUE TITLE
Improve documentation around decommissioned subscriptions 

### ISSUE THREAD

**Issue by jhueppauff** [Azure/Enterprise-Scale#258]
Not sure if this is the right repo for the documentation. 
From what I read it is lacking a bit on explanation on how to use the decommissioned Management group.
Judging from the Policies only creation/modification isn't possible. But how are the subscriptions/landing zones for example moved over (manually?).
I guess an automation probably makes also sense to turn off every resource?

**Comment by krnese** [comment]
The intent for the decommissioned management group is to place subscriptions that are being canceled into it, and deny further resource creation until the subscriptions have been deleted (they will be in cancel state for 60 days-ish prior to being removed entirely)

**Comment by jhueppauff** [comment]
I understood that basic principles. I am just missing design principles for this. (Maybe I have not noticed them). 

How are subscriptions moved to decommissioned? Should there an automation for this? Something like applying a delete tag on the subscriptions? 

I have seen the policy which prevents resource changes. But shouldn't be there something which turns off compute resources so we can ensure that there are no dependencies and also to reduce the cost. 

What is triggering the deletion of the subscription?

Sorry if I am insisting on this. I just trying to understand the bigger picture here.

**Comment by krnese** [comment]
Canceling a subscription is something a subscription owner can do, and normally it requires the subscription to be empty with no resources (e.g., running vms). Once cancelled, it should be moved to deccommissioned
