### ISSUE TITLE
Feature Request Perquisites section is missing prerequisites 

### ISSUE THREAD

**Issue by noendscripting** [Azure/Enterprise-Scale#263]
Please add full list requirements such as subscription RBAC requirements etc to the perquisites section

**Comment by krnese** [comment]
Is this for moving the subscription into the management groups you are creating? If you follow the pre-reqs and assign Owner at the tenant root as part of the bootstrapping process, that permission will be inherited to the subscriptions as well. Did you run into any issues?

**Comment by noendscripting** [comment]
Hi Kristian

My thoughts are if we are going to have a prerequisites section then we should make it as compressive as possible. Where we simply list requirements or add links to documents that explain how to full fill these prerequisites. A good example would be our MS Graph Api reference<https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#permissions> which lists permissions required to call an API

Michael Resnick | Premier Field Engineer - US PFE - East Region
michael.resnick@microsoft.com|<mailto:michael.resnick@microsoft.com%7C> (o) 980.776.7793  (c) 917.696.1690
Premier Support: 1.800.936.3100 | Premier Online: https://premier.microsoft.com<https://premier.microsoft.com/>
[cid:image001.jpg@01D69D6F.735ACEB0]
https://twitter.com/AzureSupport<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FAzureSupport&data=02%7C01%7CMichael.Resnick%40microsoft.com%7C64ccece7594a4936f83808d7a8f9380f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637163660759497841&sdata=1sFlBVPr%2B9nm%2F%2BJNHTzBkr%2FsLOmgLAksNstTqNg7nqQ%3D&reserved=0>
https://twitter.com/MSFT365Status<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FMSFT365Status&data=02%7C01%7CMichael.Resnick%40microsoft.com%7C64ccece7594a4936f83808d7a8f9380f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637163660759497841&sdata=S05MkNQN5RJN5%2Fo59OtO88m%2B9wL1xDbJMJuJ2l7YCnI%3D&reserved=0>
If you have any feedback about my work, please let either myself or my manager, Daryl Tutton  (Daryl.Tutton@microsoft.com<mailto:Daryl.Tutton@microsoft.com>)

[cid:image003.png@01D69D72.FB9A14E0] [cid:image004.png@01D69D6F.735ACEB0]

**Comment by krnese** [comment]
What is missing from the current pre-reqs?
