### ISSUE TITLE
Different Diagnostic Logs for Functions and Web Apps

### ISSUE THREAD

**Issue by marvinbuss** [Azure/Enterprise-Scale#268]
**Describe the bug**
The Diagnostic Log categories for Functions and Web Apps are different and therefore we have to update the condition to apply the right policy. In addition we have to add a specific policy for Azure Functions.

**Steps to reproduce**

1. Check Diagnostic Logs in Azure Function and in Web App
2. Policy will not be able to reach a compliant state.

**Comment by krnese** [comment]
Should all be fixed in recent policy refresh :-)
