### ISSUE TITLE
Enforce Subscription naming convention

### ISSUE THREAD

**Issue by gallegosj3** [Azure/Enterprise-Scale#275]
Are the policies for the management groups hierarchy and subscription organization part of the deployment? If so, where are they located or referenced? For example on https://github.com/Azure/Enterprise-Scale/tree/main/docs/reference/contoso/ there are a few policies like enforcing the subscription naming convention, budget, tags, move .  Thank you.

**Screenshots**

![image](https://user-images.githubusercontent.com/29262121/96338565-b252cc00-1054-11eb-975e-e0bcb8097fb5.png)

**Comment by krnese** [comment]
Thanks for submitting this issue. We are awaiting some policy aliases in order to govern the above and will publish these policies once ready.
