### ISSUE TITLE
Unable to find subscription from the management subscription drop down

### ISSUE THREAD

**Issue by abhitrivedi2006** [Azure/Enterprise-Scale#278]
Hi there,
We have about 200 subscriptions in our environment when we try to deploy hub and spoke template we unable to see desired subscription from the drop down list in both the places (management subscription and landing zone) we are trying with account which got Ower access on the root

**Comment by abhitrivedi2006** [comment]
I think we are seeing this issue only after giving access on root ( / ).. also we have lot of " access to Azure Active Directory" subscriptions. if we try with the user ID ,doesn't have root access, seems to list all the subscriptions just fine..

**Comment by krnese** [comment]
Thanks for reaching out. The field should also allow you to filter, so you can start typing the displayName of the subscription. Is this not showing the subscription(s) you are looking for?

**Comment by abhitrivedi2006** [comment]
no field doesnt list all of my subscriptions however if I go to the portal -> subscriptions I am see all of my subscriptions there but not using this deployment template

**Comment by krnese** [comment]
Thanks - we are investigating this

**Comment by krnese** [comment]
Quick update; the issue is related to server-side pagination, and we are exploring how to fix it. If this is blocking you right now, feel free to send me an email so I can provide a workaround so you can get it deployed.
