### ISSUE TITLE
Deployment without tenant root permissions

### ISSUE THREAD

**Issue by dromao** [Azure/Enterprise-Scale#280]
Hello,

I am aware that permissions at tenant root level is one of the requirements, however I am wondering what are the plans to support deployments where the service principal has permissions on a lower management group, which would be the parent for the ES management groups (Connectivity, Management, etc). In this case the managements groups would be already created and this service principal would be used only for deployment.

Previously there was a variable in the push and pull pipelines (AZOPS_PARTIAL_MG_DISCOVERY_ROOT) for this purpose, but has been removed. Previously, I had tried to use it, without success.

Could you please let me know how could this be possible?

**Comment by uday31in** [comment]
SPN will always subject to RBAC and list of operations that is allowed at scope. If tenant level permission is missing, then tenant level operation will fail but other operations will continue to work e.g. deploying policy definition and assignment, template deployment etc.

With upcoming changes in ARM, we are exploring possibility to remove the requirement to have tenant level permission. 

RE:  AZOPS_PARTIAL_MG_DISCOVERY_ROOT 

It is supported and it is available as per  below:
https://github.com/Azure/Enterprise-Scale/blob/4918474c62f777775eb0757fe31b39091e5261b9/.github/workflows/azops-
pull.yml#L33

CC: @krnese

**Comment by krnese** [comment]
For the reference implementations (the bootstrapping templates) we will require owner permission for now, as most operations on lower level scopes require Owner, in addition to creating and utilizing the scopes that are being created. 

We will also (when ARM has published the change Uday mentioned) document and recommend to remove tenant root access post-deployment and have guidance and samples on how to deploy to the tenant root later.
