### ISSUE TITLE
Azure DevOps integration requires escaping of AZURE_CREDENTIALS

### ISSUE THREAD

**Issue by dzemp** [Azure/Enterprise-Scale#293]
**Describe the bug**
Documentation https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/setup-azuredevops.md does not mention that the JSON input for the pipeline variable AZURE_CREDENTIALS must be escaped, e.g.

e.g. { \"mykey\": \"myval\" }

Without escaping, AzOps fails with:

(entrypoint) Conversion from JSON failed with Unexpected character encountered while parsing value: Path 'clientId', line 1, position 16. 

**Steps to reproduce**

1. Store JSON as per current doc.
2. Run pipeline

**Screenshots**

**Comment by frehnejc** [comment]
I am not 100% sure what is supposed to be entered into the variable from this output, the updated MD doesn't make it clear for me:
`
{
  "clientId": "<<appId>>",
  "displayName": "<<redacted>>",
  "name": "<<redacted>>",
  "clientSecret": "<<redacted>>",
  "tenantId": "<<redacted>>",
  "subscriptionId": "<<default-subscriptionId>>"
}
`

**Comment by ljtill** [comment]
We've recently released a new version of [AzOps](https://github.com/Azure/AzOps) and [AzOps-Accelerator](https://github.com/Azure/AzOps-Accelerator) which changes the way in which we handle these credentials. Please visit the [wiki](https://github.com/azure/azops-accelerator/wiki/azure-pipelines) for more information.
