### ISSUE TITLE
Internal Server Error when using push pipeline

### ISSUE THREAD

**Issue by Lycrosa** [Azure/Enterprise-Scale#294]
We are experiencing a bug when using the enterprise scale push pipeline in Azure DevOps. When we are running the pipeline, it times out after 1 hour (default timeout for pipelines in Azure DevOps). When checking the deployments in the Azure Portal, we see a "NorthStar-MG" deployment that contains a "Microsoft.Management/managementGroups" type deployment. This deployment gets an internal server error. 

![image](https://user-images.githubusercontent.com/34133460/97977198-1eab2a80-1dcc-11eb-9d89-e1964ffd7067.png)

Here the status message:

`{
    "error": {
        "code": "InternalServerError",
        "message": "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>500 - Internal server error.</title>\r\n<style type=\"text/css\">\r\n\r\n</style>\r\n</head>\r\n<body>\r\n<div id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div class=\"content-container\"><fieldset>\r\n  <h2>500 - Internal server error.</h2>\r\n  <h3>There is a problem with the resource you are looking for, and it cannot be displayed.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n"
    }
}`

Interestingly sometimes the change we made still gets deployed. In this example we changed the deployment location of a policy definition by updating the file in our repository. 

Any ideas why this is happening?

**Comment by uday31in** [comment]
can you share the deployment template?

Please note that we are waiting for platform bug fix for management group scope deployment and expecting deployment rollout by early next week.

**Comment by Lycrosa** [comment]
Hey,

I guess you mean this file? 

[Microsoft.Management_managementGroups-pcp.parameters.txt](https://github.com/Azure/Enterprise-Scale/files/5481334/Microsoft.Management_managementGroups-pcp.parameters.txt)

**Comment by krnese** [comment]
Once the bug fix has been released, the above should work as-is. We expect this to be available by Friday this week.

**Comment by Lycrosa** [comment]
Hey Kristian,

thanks for the info. We will try again on Monday. 👍

**Comment by Lycrosa** [comment]
Hey the issue still exists. Has the bugfix been delayed?

**Comment by rbev** [comment]
I appear to be having this same issue deploying the enterprise-scale sample using devops - can we get an update on the status of this

![image](https://user-images.githubusercontent.com/1802498/100701951-a0966f80-33db-11eb-804e-cb3a2173d0ec.png)

**Comment by rbev** [comment]
Another thing to note is that my deployment is

- stored in a private repository, so is copied to blob storage for deployment
- fails whether the management group exists already or not
- deployed using an application service principal with 'Owner' role at the '/' scope

**Comment by rbev** [comment]
This actually turned out to be due to us running the deployment at maangement group scope rather than tenant scope.

Note: devops does not have a tenant scope deployment task, you have to drop back to az shell commands.

**Comment by krnese** [comment]
We have updated AzOps so if you bring parameter files per the schema, tenant deployment will use "scope": "/" now and route the request to the tenant route as appropriate (creating management groups, moving subscriptions etc.).

If you bring your own template, you must include the "scope" property on the resources where this is needed. Can you provide the JSON you are using?

**Comment by krnese** [comment]
Did you try a deployment using the "scope" property on the resource?

**Comment by krnese** [comment]
Closing this as this has been fixed in recent update to use the "scope" property when creating tenant resources when invoking deployment from management group scope.
