### ISSUE TITLE
Issue deploying Enterprise-Scale with hub and spoke architecture

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#295]
**Describe the bug**
I am trying to deploy Enterprise-Scale with hub and spoke architecture (https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md) to a MSDN subscription via the [Deploy to Azure] button.
I am using the same MSDN subscription for the management, connectivity, landingzone subscriptions.

During the validation of the deployment I get this error:
The client '' with object id '' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/NoMarketplace-20201104094402' or the scope is invalid. If access was recently granted, please refresh your credentials.

**Steps to reproduce**

1. The account (client) is global administrator in Azure AD and has following role assignments in the tenant root group and in the MSDN subscription (inherited):

- Owner
- User Access Administrator
- Resource Policy Contributor

2.

**Screenshots**
![image](https://user-images.githubusercontent.com/3228810/98090182-fc74e380-1e83-11eb-84c4-b1aeed81b7ed.png)
![image](https://user-images.githubusercontent.com/3228810/98090254-131b3a80-1e84-11eb-9c47-8ae6bce38d4f.png)
![image](https://user-images.githubusercontent.com/3228810/98090334-2dedaf00-1e84-11eb-9195-11153a164b53.png)
![image](https://user-images.githubusercontent.com/3228810/98090375-3ba33480-1e84-11eb-90cc-328ab3010e3b.png)
![image](https://user-images.githubusercontent.com/3228810/98090494-5f667a80-1e84-11eb-9041-b0691df594c5.png)

**Comment by uday31in** [comment]
can you confirm you have followed the step-2 as per below?

https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md#2-grant-access-to-user-at-root-scope--to-deploy-enterprise-scale-reference-implementation

**Comment by MSBrett** [comment]
Is there a way to deploy this without needing to grant perms in AAD to the root management group?

**Comment by krnese** [comment]
You need access at the tenant root itself (above tenant root management group) in order to deploy this end-to-end, as the deployment must start at the tenant level in order to create the management group hierarchy, move subscriptions etc. Once deployed, you can remote the roleAssignment.

**Comment by neok-g** [comment]
> can you confirm you have followed the step-2 as per below?
> 
> https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md#2-grant-access-to-user-at-root-scope--to-deploy-enterprise-scale-reference-implementation

Yes this fixed my issue. I granted the rights to the managementgroup just below the root group. Unfortunately this architecture cannot be rolled out with 1 subscription since a subscriptions can be assigned to one managementgroup (of course).

**Comment by MSBrett** [comment]
> You need access at the tenant root itself (above tenant root management group) in order to deploy this end-to-end, as the deployment must start at the tenant level in order to create the management group hierarchy, move subscriptions etc. Once 
deployed, you can remote the roleAssignmet.

Needing access to the tenant root is no good as it means I can't test this anywhere except in an MSDN subscription.  Could we please fix this so it's actually deployable in our internal subscriptions?

**Comment by krnese** [comment]
@MSBrett pls follow-up with me offline on how to do this internally.

**Comment by krnese** [comment]
@neok-g you can deploy this using a single subscription where you enable the platform side of it and leave the other options empty (e.g., not bringing subscription in for landing zone). The design itself is based on multiple subscriptions.
