### ISSUE TITLE
Deploy-vNet PolicyDefinition: vNet creation in LZ subscription fails

### ISSUE THREAD

**Issue by skiddder** [Azure/Enterprise-Scale#300]
**Describe the bug**
When a remediation task for the Deploy-vNet policy assignment is created, the deployment fails with the following message:

> {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplate","message":"Unable to process template language expressions for resource '/subscriptions/xxxxxxxx-f5d1-4740-a5cf-532682d8fccf/resourceGroups/nslz-landingzone-network/providers/Microsoft.Resources/deployments/es-ipam-nslz-landingzone-nsg-udr-vnet-hub-vwan-peering-0' at line '1' and column '2080'. 'The template parameter 'vWanVhubName' is not found. Please see https://aka.ms/arm-template/#parameters for usage details.'"}]}

**Steps to reproduce**

1. assign the [Deploy-vNet](https://github.com/Azure/Enterprise-Scale/blob/main/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/contoso%20(contoso)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-vNet.parameters.json) policy to an existing subscription below MG landingzones. My ipam parameter looks like this:

> [{"name":"nslz-landingzone-vNet","location":"westeurope","virtualNetworks":{"properties":{"addressSpace":{"addressPrefixes":["10.2.1.0/24"]}}},"networkSecurityGroups":{"properties":{"securityRules":[]}},"routeTables":{"properties":{"routes":[]}},"hubVirtualNetworkConnection":{"vWanVhubResourceId":"/subscriptions/xxxxxxxx-c0fc-49b7-8ed2-fd0bc31a645d/resourceGroups/nslz-global-vwan/providers/Microsoft.Network/virtualHubs/nslz-vhub-weu","properties":{"allowHubToRemoteVnetTransit":true,"allowRemoteVnetToUseHubVnetGateways":false,"enableInternetSecurity":true}}}]

2. Start compliance scan via ps:

> Start-AzPolicyRemediation -Name deploy-vnet2 -Scope /subscriptions/xxxxxxxx-f5d1-4740-a5cf-532682d8fccf -PolicyAssignmentId /providers/Microsoft.Management/managementGroups/nslz-landingzones/providers/Microsoft.Authorization/policyAssignments/Deploy-vNet  -ResourceDiscoveryMode ReEvaluateCompliance

3. wait until remediation task was created, compliance scan show incompliant and remediation deployment has finished.

**Screenshots**
![image](https://user-images.githubusercontent.com/56867233/98878304-e8804180-2482-11eb-8252-db29225a4beb.png)

**Comment by krnese** [comment]
Thanks for submitting this issue. We have updated the vNet policy and the new version is available in Wingtip reference implementation. We will shortly have it updated in all our reference implementations so it will be consistent.

**Comment by skiddder** [comment]
Thanks, @krnese!
I tried to deploy policies.json to my tenant, but I receive the following error:

az deployment create --location westeurope --template-file ./docs/reference/wingtip/armTemplates/auxiliary/policies.json --parameters ./examples/wingTip/policies.parameters.json --verbose

Deployment failed. Correlation ID: 3ff74f46-0cad-42af-9d96-c7bce422efdd. {
  "error": {
    "code": "PolicyDefinitionNotFound",
    "message": "The policy set definition 'Deploy-Diag-LogAnalytics' request is invalid. The following policy definitions could not be found: '/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Databricks;/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-EventGridSystemTopic;/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-FrontDoor;/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Function;/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-MariaDB'."
  }
}

**Comment by krnese** [comment]
We have now updated all the policies across the reference implementations, where there is a new policy for vnet - which must be assigned at the subscription scope. We will work to document the intent and usage of these policies in the following weeks. Pls let us know if it is still an issue.
