### ISSUE TITLE
Hardcoded deployment location?

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/Enterprise-Scale#335]
when a github repo is initialized for enterprise scale in a box, policy parameter files at path `azops\Root Management Group (blah..blah)\<es-prefix>\.AzState` are created with deployment location as northeurope.  Below is an excerpt from `Microsoft.Authorization_policyDefinitions-Deploy-Log-Analytics.parameters.json` file.

```
 "deployment": {
                  "location": "northeurope",
                  "properties": {
                    "mode": "incremental",
...
```

deployment location is then configured as `location` for resource group creation.
```
"resources": [
                        {
                          "type": "Microsoft.Resources/resourceGroups",
                          "apiVersion": "2018-05-01",
                          "name": "[parameters('rgName')]",
                          "location": "[deployment().location]",
                          "properties": {}
                        }
```

when remediation task is created for this policy to address any non-compliance then remediation task fails with following error.
```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "InvalidResourceGroupLocation",
      "message": "Invalid resource group location 'northeurope'. The Resource group already exists in location 'uksouth'."
    }
  ]
}
```

can you please confirm if this is a bug or i am missing something?

thanks.

**Comment by krnese** [comment]
I can confirm that this is not a bug, but a known gap that we cannot parameterize the location field in policyDefinitions as the field will only handle string literals. The eng team is aware and have added it to their backlog. We are also working on updating the 'in a box guidance' to solve the mismatch you are referring to. //cc @hjscherer

**Comment by Mahesh-MSFT** [comment]
Thanks @krnese and @hjscherer . Is update to guidance going to be "quick"? If it is going to take long, how can customers remediate policy drifts in the interim?

**Comment by krnese** [comment]
Did you deploy Enterprise-Scale using the reference implementation? If yes, you can assign these policies by leaving the default options enabled (per recommendations). You will then have the management subscription configured with Log Analytics, and a policy assigned to the management-management group to ensure ongoing compliance.

**Comment by Mahesh-MSFT** [comment]
My question was on the remediation tasks. I have deployed "in-a-box" Contoso reference implementation in UK South region using default options (yes for Log Analytics workspace creation). However, the name of the workspace configured is a string with prefix and a hexadecimal number. Most customers would want to change the LA workspace name to match with their some naming standard. If this name is changed in the policy definition in github repo then policy goes in non-compliant state in portal. when a remediation task is created to address this non-compliance then it fails with the error reported in the issue.  I am trying to understand how to remediate LA policy workspace name change. This issue can potentially affect other policy drift correction. also.

**Comment by Mahesh-MSFT** [comment]
LA workspace name should be globally unique. This is ESLZ prefix + sub ID. Closing this issue now.
