### ISSUE TITLE
Manual deployment of policies.json fails

### ISSUE THREAD

**Issue by skiddder** [Azure/Enterprise-Scale#337]
**Describe the bug**
Due to missing permissions at tenant root scope in a brownfield approach, we need to deploy the policy definitions at a specific management group level which we are using as root for ES.
Therefore, we need to deploy the ./docs/reference/wingtip/armTemplates/auxiliary/policies.json.
But the deployment fails with message, that several policy definitions referred to by a policy definition set are not present.

I checked the policies.json and the definitions of the missing policies are in there, but not yet deployed in my environment. I guess a dependency between policy sets and policy definitions would solve the issue...

**Steps to reproduce**

1. az deployment create --verbose --template-file ./docs/reference/wingtip/armTemplates/auxiliary/policies.json  --parameters topLevelManagementGroupPrefix='nslz' --location westeurope

Deployment failed. Correlation ID: 6d59b208-9fe9-4000-b72f-392a52373315. {
  "error": {
    "code": "PolicyDefinitionNotFound",
    "message": "The policy set definition 'Deploy-Diag-LogAnalytics' request is invalid. The following policy definitions could not be found: '/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Databricks;/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-EventGridSystemTopic;/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-FrontDoor;/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Function;/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-MariaDB'."
  }
}

**Screenshots**

**Comment by krnese** [comment]
You are likely running into a known issue, related to replication latency in ARM backend storage. https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Known-Issues.md#deploying-the-reference-implementation-fails-due-to-policy--cannot-be-found-404 

Can you re-run the deployment with the same input parameters?

**Comment by skiddder** [comment]
I am deploying to westeurope only... but I re-ran the deployment: Same error as above.

**Comment by skiddder** [comment]
Closing the loop: I mistakenly deployed at subscription scope ('az deployment create ...') but the deployment request must be at management group scope: 'az deployment **mg** create ...'
