### ISSUE TITLE
Azure Policy for "Microsoft.Sql/servers" with effect "deployIfNotExists" is showing non-compliant for the existanceCondition.

### ISSUE THREAD

**Issue by akshd** [Azure/Enterprise-Scale#338]
Hi,

I am trying to create a policy for Microsoft.Sql/servers to deploy "Microsoft.Sql/servers/securityAlertPolicies" if not configured earlier.

I am using below existanceConditions:

"existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Sql/securityAlertPolicies.state",
                "equals": "Enabled"
              },
              {
                "field": "Microsoft.Sql/servers/securityAlertPolicies/emailAccountAdmins",
                "equals": true
              }
            ]
      },

to check the policy compliance, here i am getting non-compliance result for the second condition.
I have tried different alias for it:

"Microsoft.Sql/securityAlertPolicies.emailAccountAdmins",
"Microsoft.Sql/servers/securityAlertPolicies/emailAccountAdmins",

But still it is not working.

**Error Details:**

Reason for non-compliance
Current value must be equal to the target value.

Field
Microsoft.Sql/servers/securityAlertPolicies/emailAccountAdmins

Path
properties.emailAccountAdmins

Current value
<-->

Target value
"True"

**Comment by krnese** [comment]
Are you trying to create a custom policyDefinition to achieve the above? try putting the true into quotes as it is in the policyRule. I.e., "equals": "true".

**Comment by krnese** [comment]
Did the above work for you? If not, pls re-open the issue.

Thanks
