### ISSUE TITLE
Remediation Task fails due to invalid permissions

### ISSUE THREAD

**Issue by skiddder** [Azure/Enterprise-Scale#341]
**Describe the bug**
Remediation tasks for the following policy definitions fail due to insufficient permissions of the managed identity:
- Deploy-vWAN
- Deploy-vHUB
- Deploy-FirewallPolicy

Deployment Error - Reason:
Deployment creation for policy definition '/providers/Microsoft.Management/managementGroups/nslz/providers/Microsoft.Authorization/policyDefinitions/Deploy-FirewallPolicy/' and assignment '/providers/Microsoft.Management/managementGroups/nslz-connectivity/providers/Microsoft.Authorization/policyAssignments/ed93811f4c50466c9dd34f73/' was unsuccessful.

Details - Message:
The template deployment failed with error: 'Authorization failed for template resource 'nslz-fw-policies' of type 'Microsoft.Resources/resourceGroups'. The client 'b24365a4-297d-495b-a3a9-c23eabb8c19c' with object id 'b24365a4-297d-495b-a3a9-c23eabb8c19c' does not have permission to perform action 'Microsoft.Resources/subscriptions/resourceGroups/write' at scope '/subscriptions/a6351c28-c0fc-49b7-8ed2-fd0bc31a645d/resourceGroups/nslz-fw-policies'.'.

**Steps to reproduce**

1. Assign policy - i.e. Deploy-vWAN to management group 'Connectivity'
2. Move a subscription below MG 'Connectivity'
3. Connect-AzAccount and Select-AzSubscription -Subscription <subscriptionId-of-connectivity-subscription>
4. Start-AzPolicyComplianceScan -Verbose
5. In Azure Portal open Policy blade and set scope to your connectivity subscription
6. Click into Compliance blade
7. Click 'Deploy Azure Firewall Manager policy in the subscription' policy
8. Click 'Create Remediation Task'
9. wait for the remediation task to be created. A moment later status 'in progress' changes to 'failed'

I looked up the Display name of the managed identity for the remediation task and at MG 'Connectivity' scope I assigned owner permissions (were before only Network Contributir role was assigned) and tried again. With owner permissions the remediation task could successfully deploy the resource in the remediation definition. Therefore, I assume the Network Contributor role is not sufficient here.

**Screenshots**

**Comment by krnese** [comment]
Thanks. It appears that Network Contributor does not (no longer) have the permission to perform Microsoft.Resources/resourceGroups/write, which is causing the policy to fail as it is a subscription level deployment -> which need to create the resource group. We will update the roleDefinitions needed for the policyDefinitions

**Comment by lunar87** [comment]
I had similar issue with Log Analytics policy, but there was another permission as well that it was lacking. I'll have to go back and check.
