### ISSUE TITLE
Permissions issue on deployment

### ISSUE THREAD

**Issue by stdistef** [Azure/Enterprise-Scale#342]
![image](https://user-images.githubusercontent.com/35927980/101081257-d5d7c480-3577-11eb-9cad-274935a008f8.png)

I am the Global Admin of the AD Tenant and Owner of the Subscription.    Yet deployment fails.
"The client 'Steve@stevied2898.onmicrosoft.com' with object id 'a0f9dc25-f184-4fe2-906d-fa97845a8bb4' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/NoMarketplace-20201203143921' or the scope is invalid. If access was recently granted, please refresh your credentials."
Any tips?

**Comment by lunar87** [comment]
Have you done this: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md#2-grant-access-to-user-at-root-scope--to-deploy-enterprise-scale-reference-implementation?

**Comment by stdistef** [comment]
I did not.  Thank you.  Much better now.

**Comment by stdistef** [comment]
I needed to read the manual :-)   Thanks Jonathan!
