### ISSUE TITLE
Hard coded location specified in template; assignment fails when selected other location.

### ISSUE THREAD

**Issue by EelcoLabordus** [Azure/Enterprise-Scale#344]
https://github.com/Azure/Enterprise-Scale/blob/8d640e58c3985435e83a2a7722c457f3babfc981/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/contoso%20(contoso)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-Log-Analytics.parameters.json#L86

**Comment by krnese** [comment]
If this is from the In-a-box guidance, pls note we will update it as it currently has a mismatch and the above step is not needed, as the recommendation is to deploy the reference implementation (then this policy will already be assigned and workspace created).
