### ISSUE TITLE
Invalid/Incorrect role definition Id for backup policy for wingtips/adventureworks

### ISSUE THREAD

**Issue by lunar87** [Azure/Enterprise-Scale#346]
**Describe the bug**
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/armTemplates/auxiliary/policies.json
and 
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/wingtip/armTemplates/auxiliary/policies.json

contain incorrect/invalid role definition id:
"details": {
                  "resourceGroupName": "[[resourceGroup().name]",
                  "type": "Microsoft.RecoveryServices/backupprotecteditems",
                  "roleDefinitionIds": [
                    "/providers/Microsoft.Authorization/roleDefinitions/f9980e02c-c2be-4d73-94e8-173b1dc7cf3c"
                  ],

f9980e02c-c2be-4d73-94e8-173b1dc7cf3c
is not a valid guid. The correct guid would be 9980e02c-c2be-4d73-94e8-173b1dc7cf3c. But this is for VM Contributor.
If you look at the policies file in contoso it is b24988ac-6180-42a0-ab88-20f7382dd24c which is contributor. 

**Steps to reproduce**

1. Deploy adventure works or wing tips
2. Assign the backup policy

**Screenshots**
Line |
 105 |              Write-AzOpsLog -Level Error -Topic "entrypoint" -Message  …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [19:18:02.9495] (entrypoint) 7:18:02 PM - The deployment
     | 'AzOps-Microsoft.Authorization_policyAssignments-Deploy-VM-Backup' failed with error(s). Showing 1 out of 1 error(s). Status Message: The role definition ID 'f9980e02c-c2be-4d73-94e8-173b1dc7cf3c' is not valid. (Code:InvalidRoleDefinitionId)  CorrelationId: 8ad7b8a4-3a48-4f86-a1e0-9850922b34dd

**Comment by krnese** [comment]
Thanks for reporting. We just moved this policy to built-in and will update Contoso, Wingtip, and AdventureWorks shortly to use the built-in instead of the custom policy.
The resourceId of the built-in is /providers/Microsoft.Authorization/policyDefinitions/98d0b9f8-fd90-49c9-88e2-d3baf3b0dd86
