### ISSUE TITLE
Conflicting or unclear guidance regarding Online Landing Zone connectivity in the reference deployment

### ISSUE THREAD

**Issue by larsakerlund** [Azure/Enterprise-Scale#347]
**Describe the bug**

The guidance about Online Landing Zones and their connectivity in the reference deployment is conflicting (or just unclear). The [Contoso reference](https://github.com/Azure/Enterprise-Scale/tree/main/docs/reference/contoso) deployment mentions the following about an Online Landing Zone:

> Landing Zone Management Group for online applications that will be internet-facing, which _**doesn't require hybrid connectivity**_. This is where you will create your Subscriptions that will host your online workloads

> Online Landing Zones include all Virtual Networks that have internet-facing applications via an Azure Application Gateway (v2).

[Adventure Works](https://github.com/Azure/Enterprise-Scale/tree/main/docs/reference/adventureworks#what-will-be-deployed) mentions something similiar:

> Landing Zone Management Group for online applications that will be internet-facing, where a virtual network is optional and hybrid connectivity is not required.

The [VNet deployment policy](https://github.com/Azure/Enterprise-Scale/blob/main/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/contoso%20(contoso)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-vNet.parameters.json) is however applied to the Contoso psuedo-root scope, which enables hybrid (and inter-workload) connectivity for all archetypes by default.

Cloud Adoption Framework does not really mention any preference or recommendation regarding this. Should Online Landing Zones be peered by default or not? Or is the VNet deployment policy just assigned to the wrong scope by mistake?

**Screenshots**

![](https://i.imgur.com/YGKP9hJ.png)

**Comment by krnese** [comment]
Thanks for surfacing this. In general, I believe there's an issue with the assumed assignment scope of what's outlined in the documentation for Contoso vs what's is actually done when deploying the reference implementation itself (we don't enforce virtual network connectivity on the online management group). @victorar - can you chime in on the general statement/recommendation for virtual networks in online management group?

**Comment by larsakerlund** [comment]
Thank you, that seem to be the case. I went through the Contoso reference templates and the VNet deployment definition was only created, not assigned. In the AzOps reference, it seems to be assigned to the Landing Zone management group, but the IPAM only contains a network for one of the subscriptions within corp. If @victorar has further clarification it would be very appreciated.

**Comment by victorar** [comment]
Hi @larsakerlund, thanks for reaching out and bringing this up,

The description in the docs, which you've included above, is accurate.  Online Landing Zones are designed for internet-facing applications, where no hybrid connectivity is required, and a VNet might not even be required (for example, an application built entirely with PaaS services). Please note that some online workloads might need a VNet, for example, if customer use Azure PaaS services but access them via Private Link, if application is built with IaaS, or for example if app is exposed to the internet via Azure App GW.

Thanks again for reaching out, and please let us know if further clarification is required.
