### ISSUE TITLE
Adding policyAssignment causes error code:InvalidTemplate

### ISSUE THREAD

**Issue by Jedoe830** [Azure/Enterprise-Scale#349]
**Describe the bug**
When adding a policyAssignment for a built-In policyDefinition, the assignment gets deployed (Visible in Azure Portal), but the DevOps Push Pipeline throws the error: 

`'AzOps-Microsoft.Authorization_policyAssignments-Deploy-AKS-Polic' failed with error(s). Showing 1 out of 1 error(s). Status Message: Unable to process template language expressions for resource '/providers/Microsoft.Management/managementGroups/<managementGroup>/providers/Microsoft.Authorization/roleAssignments/2dba37e0-5e7a-53f2-b15c-f451f5c8a197' at line '116' and column '9'.'The language expression property 'details' doesn't exist, available properties are 'effect'.' (Code:InvalidTemplate)`
The correlationId is: a7f82a5c-7b26-4c92-9b23-4fda3c71cc3e

So the issue regards to the roleAssignment generated in the deployment.

**Steps to reproduce**

1.Deploy a policyAssignment for the built-In roleDefinition "[Preview]: Azure Policy Add-on for Kubernetes service (AKS) should be installed and enabled on your clusters"
2.

**Screenshots**

**Comment by krnese** [comment]
Can you share how you made the assignment? If you did it using AzOps, pls share the JSON you used, as I suspect it contains an identity object - although not required for this policy since it is an audit policy

**Comment by Jedoe830** [comment]
I fixed this 'issue' by using another Built-In policyDefinition 'Deploy Azure Policy Add-on to Azure Kubernetes Service clusters'. BTW I used for the both policyDefinitions the following JSON:

`{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "input": {
            "value": {
                "Identity": {
                    "type": "SystemAssigned"
                },
                "Location": "westeurope",
                "Name": "Deploy-AKS-Policy-AddOn",
                "Properties": {
                    "Description": null,
                    "DisplayName": "Deploy-AKS-Policy-AddOn",
                    "NotScopes": null,
                    "Parameters": {},
                    "PolicyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/a8eff44f-8c92-45c3-a3fb-9880802d67a7",
                    "Scope": "/providers/Microsoft.Management/managementGroups/<managementGroup>"
                },
                "ResourceType": "Microsoft.Authorization/policyAssignments"
            }
        }
    }
}`

Even when the issue is resolved, I don't understand why the deployment with the first Built-In policyDefinition didn't work.

**Comment by krnese** [comment]
For all policyDefinitions that are not using deployIfNotExist or modify, you don't need to carry the "identity" object in the parameter file.

**Comment by Jedoe830** [comment]
Alright, thanks
