### ISSUE TITLE
Feature Request Enterprise-Scale blueprint support

### ISSUE THREAD

**Issue by mfmcdonagh** [Azure/Enterprise-Scale#353]
Hello,

Are there plans to publish the Wingtip Enterprise-Scale implementation as a Blueprint ?  
https://docs.microsoft.com/en-us/azure/governance/blueprints/overview

**Comment by uday31in** [comment]
No there are no plans to do so. 

Blueprint is limited to subscription scope only and not aligned to Cloud Adoption Framework enterprise-scale [design principles] from the platform perspective (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/design-principles)
