### ISSUE TITLE
Deny-ERPeering Policy definition

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/Enterprise-Scale#354]
I see that `Deny-ERPeering` policy is configured with  following part of definition.
```
"if": {
              "field": "type",
              "equals": "Microsoft.Network/virtualNetworks/virtualNetworkPeerings"
            }
```
My understanding is RP `Microsoft.Network/virtualNetworks` targets the Virtual Networks and not ExpressRoute. ER RP should be  something like `Microsoft.Network/expressRouteCircuits/peerings`

Should this policy be named either `Deny-VNetPeering` or should RP be changed to `Microsoft.Network/expressRouteCircuits/peerings`?

Or may be I am missing something?

Thanks.

**Comment by daltondhcp** [comment]
Thanks for the feedback Makesh. It will be fixed in our next update.

**Comment by Mahesh-MSFT** [comment]
thanks for the update @daltondhcp - can you confirm if its still `Deny-ERPeering` or `Deny-VNetPeering`?

**Comment by daltondhcp** [comment]
It will be Deny-VNetPeering.
