### ISSUE TITLE
VNet Deployment doesn't work

### ISSUE THREAD

**Issue by Lycrosa** [Azure/Enterprise-Scale#363]
I am trying to deploy a VNET via the "Deploy-Vnet" Policy. After assigning the Policy to a subscription or management group and creating a remediation task a deployment is beeing triggered. The deployment is succesfull after a couple of seconds. When looking at the deployment I see that nothing has been deployed by the deployment. 

![grafik](https://user-images.githubusercontent.com/34133460/102790267-7ebe5600-43a5-11eb-80c8-7ab223e65af3.png)

However the template is present(using the Wingtip Policy Definition):
![grafik](https://user-images.githubusercontent.com/34133460/102790387-a7465000-43a5-11eb-9afd-4ea8a01276b5.png)

Here my ipam parameter:
`{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "ipam": {
            "value": [
                {
                    "name": "bu1-weu-msx3-vNet1",
                    "location": "westeurope",
                    "virtualNetworks": {
                        "properties": {
                            "addressSpace": {
                                "addressPrefixes": [
                                    "10.51.217.0/24"
                                ]
                            }
                        }
                    },
                    "networkSecurityGroups": {
                        "properties": {
                            "securityRules": []
                        }
                    },
                    "routeTables": {
                        "properties": {
                            "routes": []
                        }
                    },
                    "hubVirtualNetworkConnection": {
                        "vWanVhubResourceId": "/subscriptions/99c2838f-a548-4884-a6e2-38c1f8fb4c0b/resourceGroups/contoso-global-vwan/providers/Microsoft.Network/virtualHubs/contoso-vhub-weu",
                        "properties": {
                            "allowHubToRemoteVnetTransit": true,
                            "allowRemoteVnetToUseHubVnetGateways": false,
                            "enableInternetSecurity": true
                        }
                    }
                }
            ]
        }
    }
}`

It seems like there is some error in the arm template. Can someone help me on this?

**Comment by krnese** [comment]
Thanks. We are working to document the policy you are using. Also, we shipped a simpler version where you can assign at the subscription directly @ https://github.com/Azure/Enterprise-Scale/blob/main/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-VNET-HubSpoke.parameters.json 

Can you pls give this a try?

**Comment by Lycrosa** [comment]
Since I wanna have a connection to an vHub I changed the arm template inside the policy defnition and it seems to be working. Thanks for the help. Before closing this I have another question. In your opinion what is best practise to deploy a new "spoke" in a vWAN setup? Whenever I think about this the only possible option I see is to create a new policy assignment for every new spoke. I don't see any way to have a policy assignment on a management group level that automatically creates a new spoke vnet for a new subscription. Am I missing something here?

**Comment by krnese** [comment]
Great question. We have several ways we can approach the above (create new connected subscription), and we are working to document these.
Here's an example where you create a new subscription, and connect it to the connectivity hub using Azure Policy (based on policyDefinition as part of the Enterprise-Scale reference implementations). https://github.com/Azure/Enterprise-Scale/tree/main/examples/landing-zones/connected-subscription

Note that the sample above will assign policy at the new subscription directly. We have another example coming for how to do this when the policy is assigned at the management group (corp).
