### ISSUE TITLE
Parameterize lz-prefix in connected-subscription template

### ISSUE THREAD

**Issue by skiddder** [Azure/Enterprise-Scale#378]
**Describe the bug**
In the [connected-subscription ARM template](https://github.com/Azure/Enterprise-Scale/blob/main/examples/landing-zones/connected-subscription/connectedSubscription.json) there should be an additional parameter 'lz-prefix'

**Steps to reproduce**
I have not found the time to deploy, but what I can see from reading through the json code is the following:
1. in line 195 'ESLZ' is hard coded in the management group reference. This should be parameterized to match customer's chosen prefix.
2. in line 197 the lz-prefix again is hard coded to 'ESLZ' but should be concatenated from a parameter 'lz-prefix' and the name of the connectivity management group
3. In order to match the naming convention, in line 220 there should be a '-' in front of 'rg-vnet' 

**Screenshots**
![image](https://user-images.githubusercontent.com/56867233/103275507-a4121c00-49c4-11eb-8e3d-6951f23a7f51.png)

**Comment by krnese** [comment]
Thanks for submitting. Yes, we will correct this and promote the remaining variables to parameters for the template.
