### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by saumilmsft** [Azure/Enterprise-Scale#381]
**Describe the bug**
when we are trying to deploy Enterprise-Scale Azure policies for management group from UI. it's not getting assigned.

**Steps to reproduce**

1. trying to deploy for management group policies from this URL:https://github.com/Azure/Enterprise-Scale/tree/main/azopsreference

**Screenshots**

![image](https://user-images.githubusercontent.com/76719429/103544811-a85b9f00-4ec6-11eb-9ca4-9ea97445c7c6.png)

**Comment by uday31in** [comment]
It is by design as we do not assign the policy. This UI only creates custom policy definition at the scope selected.

For policy assignment, you should use native portal experience to do so.
