### ISSUE TITLE
Peering between connectivity and landingzone subscriptions

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#385]
Hello,

Should the Enterprise-scale Adventureworks scripts create the spoke VNets in the corporate subscriptions and peering with the hub VNet in the connectivity subscription?
I configured 2 corporate landingzone subscriptions but I noticed that there are no VNets neither peerings created in the corp landingzone subscriptions. The hub VNet is created.

**Comment by krnese** [comment]
Thanks for submitting this issue. We are continuing to invest in the reference implementations and what can be enabled from the get-go as part of the deployment experience. The above is certainly in our backlog and we will also publish a roadmap to the repo the next following days. Pls stay tuned and once again thanks for submitting this.

**Comment by krnese** [comment]
This has been shipped as part of the associated PR to this issue. Thanks for the feedback!
