### ISSUE TITLE
User does not have authorization to perform action over NoMarketplace

### ISSUE THREAD

**Issue by PlanetWilson** [Azure/Enterprise-Scale#388]
**Describe the bug**
When deploying the template I get an issue:- "The client 'user1@madeupcompany.onmicrosoft.com' with object id '20277bd7-be69-47b4-98f7-e3509a1eb6c6' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/NoMarketplace-20210111183353' or the scope is invalid. If access was recently granted, please refresh your credentials. (Code: AuthorizationFailed)"

**Steps to reproduce**

1. Follow the template deployment

I am a tenant admin, elevated to see all resources, added to the IAM owner role on the existing subscription created.

**Comment by uday31in** [comment]
Can you please confirm  this step is followed?

https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md#2-grant-access-to-user-at-root-scope--to-deploy-enterprise-scale-reference-implementation

**Comment by PlanetWilson** [comment]
Apologies I could have sworn I had this already.

**Comment by thevinnie** [comment]
Just to confirm, I ran into this same issue with a demo tenant while working with @mboswell.  The user I was using was Global admin with the correct role assignment based on the instructions provided, but the deployments failed until I ran steps 1 AND 2 (the az role command).  Once both steps were executed, the deployment validated and ran successfully.

**Comment by uday31in** [comment]
@thevinnie  - you would need to do #2 to grant  permission for tenant level deployment. Only Global Administrator can grant permission and by default they dont have a permission. Once Tenant level deployment permission is granted, you can disable GA privilege.
