### ISSUE TITLE
Contoso reference implementation deploy fails with AuthorizationFailed

### ISSUE THREAD

**Issue by torokzs** [Azure/Enterprise-Scale#389]
I'm account admin in my subscription but I get this error message when I click on Review + create on custom deployment:

{
  "code": "AuthorizationFailed",
  "message": "XXX does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/NoMarketplace-20210113090535' or the scope is invalid. If access was recently granted, please refresh your credentials."
}

1. Go to: https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md
2. Click on "Deploy to Azure": https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true
3. Fill everything as https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/deploy-tenant.md mentions then click on "review + create" and validation fails.

I've tried with different subscriptions as well.

**Comment by torokzs** [comment]
I have a solution: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md

**Comment by skelso01** [comment]
> I have a solution: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md

This solution does not work in my case :-(
