### ISSUE TITLE
Dedicated Template Repository

### ISSUE THREAD

**Issue by krowlandson** [Azure/Enterprise-Scale#39]
The Azure/Enterprise-Scale repository is currently configured as a Template repository which customers are advised to clone into their own GitHub account using the "Use this template" option (rather than to create a Fork).

As the repository contains artefacts not needed within the customer repository (docs / examples / etc.), this feature request is to create a dedicated repository (e.g. Enterprise-Scale-Template) containing ONLY the artefacts needed by a customer, such as:

- /.github/workflows/azops.yml (the engine behind the work)
- /azops/ (empty directory)
- /README.md (a "getting started" guide, not the full Enterprise-Scale documentation)
- LICENSE

Azure/Enterprise-Scale will then be updated to focus on providing the core documentation and examples only. This will allow us to revert Azure/Enterprise-Scale to a standard repository, and the azops.yaml file can be removed.

**Comment by ljtill** [comment]
This feature work is now complete and will be part of the next major release.
(Azure/AzOps-Accelerator)[https://github.com/azure/azops-accelerator]
