### ISSUE TITLE
Use Get-AzAccessToken cmdlet to retrieve Access Tokens

### ISSUE THREAD

**Issue by stefanstranger** [Azure/Enterprise-Scale#395]
The documentation does not use the (new) Get-AzAccessToken cmdlet. e.g. https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/enable-subscription-creation.md

```PowerShell
# Fetching new token
$azureRmProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile
$profileClient = [Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient]::new($azureRmProfile)
$token = $profileClient.AcquireAccessToken($currentContext.Tenant.Id)
```
Should be changed to:

```PowerShell
$Token = Get-AzAccessToken
```

**Comment by hjscherer** [comment]
Thank  you for providing this feedback. Provided some feedback in the PR.

**Comment by hjscherer** [comment]
@stefanstranger thank you for contributing. Will go ahead and close this issue now.
