### ISSUE TITLE
AZOPS_SKIP_RESOURCE_GROUPS should be AZOPS_SKIP_RESOURCE_GROUP

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/Enterprise-Scale#40]
Uncovered this typo.

In AzOps the env variable is singular, in Enterprise-Scale it is plural.

https://github.com/Azure/AzOps/blob/0425f8e36455cea1170937c5a6e054a3b0e6b90b/src/private/Invoke-AzOpsGitPullRefresh.ps1#L7

https://github.com/Azure/AzOps/blob/86563d865b717f6c93bdd4f3134363033c76711c/src/private/Invoke-AzOpsGitPushRefresh.ps1#L10

https://github.com/Azure/Enterprise-Scale/blob/0ce0f7068b4d5bee8671d257f551f2ebb38b8226/.github/workflows/azops.yml#L31

Pinging @hjscherer

**Comment by hjscherer** [comment]
Thank you very much for reporting this bug.
