### ISSUE TITLE
ES with hub and spoke architecture does not deploy the spoke VNet and peering

### ISSUE THREAD

**Issue by Agazoth** [Azure/Enterprise-Scale#400]
According to the documentation found [here](https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md), a VNet and a peering to the hub network will be deployed on a corp subscription when running the "Deploy to Azure" on the same page.

No network configuration for the spoke subscription is available in the guide, when the deployment is configured and no VNet is deployed to the corp subscription.

**Steps to reproduce**

1. Click the Deploy to Azure button
2. Sign in to a tenant with sufficient subscriptions with an account with sufficient access rights.

**Screenshots**
![image](https://user-images.githubusercontent.com/15127301/104878787-e217b580-595c-11eb-9783-b00c178b876d.png)

![image](https://user-images.githubusercontent.com/15127301/104878819-f0fe6800-595c-11eb-83ae-e727af791198.png)

If the point is, that the spoke network should be deployed in a separate pipeline, the documentation should be updated accordingly. Else, the Deploy To Azure should include the spoke network deployment.

**Comment by krnese** [comment]
Thanks. This is in our backlog to 1) enable creation of multiple connectivity regions, and 2) connect the corp connected landing zones as part of the deployment experience.

**Comment by krnese** [comment]
Closing this as we shipped this as part of Adventure Works reference implementation
