### ISSUE TITLE
'managementGroups' could not be found in the namespace 'Microsoft.Management' for api version '2020-06-01'

### ISSUE THREAD

**Issue by devopsleigh** [Azure/Enterprise-Scale#402]
**Describe the bug**

Deploying the "connected" subscription LZ fails:
`{"error":{"code":"InvalidResourceType","message":"The resource type 'managementGroups' could not be found in the namespace 'Microsoft.Management' for api version '2020-06-01'. The supported api-versions are '2020-10-01,2020-05-01,2020-02-01,2019-11-01,2018-03-01-preview,2018-01-01-preview,2017-11-01-preview,2017-08-31-preview,2017-06-30-preview,2017-05-31-preview,2018-03-01-beta'."}}`

**Steps to reproduce**

1. Open Cloud Shell
2. Run Az CLI script as per [the doco](https://github.com/Azure/Enterprise-Scale/tree/main/examples/landing-zones/connected-subscription#deploy-using-azure-cli)
3. Note the error as above.

As expected, executing this via the portal deployment template also fails, however without any meaningful error messages.

**Screenshots**
N/A

**Comment by krnese** [comment]
Can you share the exact cmdlets you are using to invoke the deployment with CLI?

**Comment by devopsleigh** [comment]
Sure, @krnese. I've replaced our prefix with "PREFIX" and any GUIDs with "GUID".

```
az deployment mg create \
  --name testelz1 \
  --location AustraliaEast \
  --management-group-id "/providers/Microsoft.Management/managementGroups/PREFIX-online" \
  --template-uri "https://raw.githubusercontent.com/Azure/Enterprise-Scale/main/examples/landing-zones/connected-subscription/connectedSubscription.json"

Please provide string value for 'subscriptionAliasName' (? for help): testelz1
Please provide string value for 'targetManagementGroup' (? for help): PREFIX-online
Please provide string value for 'billingAccountId' (? for help): /providers/Microsoft.Billing/enrollmentAccounts/GUID
Please provide string value for 'lzVnetCidr' (? for help): 10.100.0.0/24
Please provide string value for 'lzVnetRegion' (? for help): AustraliaEast
Please provide string value for 'esConnectivityHubId' (? for help): /subscriptions/GUID/resourceGroups/BSM-connectivity/providers/Microsoft.Network/virtualWans/PREFIX-vwan-australiaeast
```

**Comment by krnese** [comment]
For the '--management-group-id' parameter, the expected input is the final segment of your management group resource id. I.e., PREFIX-online in your case. Can you try that?

**Comment by devopsleigh** [comment]
Thanks, I missed that. I've now got a permissions issue, but I expect I misread the prereqs there as well.
