### ISSUE TITLE
Missing pre-requisites for subscription creation?

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/Enterprise-Scale#404]
Are there any pre-requisites (e.g. enrollment account type, tenancy, etc.) to create subscription programmatically?

when I use guidance on [enabling subscription creation](https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/enable-subscription-creation.md) on MSDN tenant, I don't get  `enrollmentAccount` associated with it. see below excerpt from `$listBillingAccount.value[0].properties`.

```
accountStatus            : Active
accountType              : Individual
agreementType            : MicrosoftOnlineServicesProgram
billingProfiles          : @{hasMoreResults=False}
displayName              : XXX XXX
hasReadAccess            : True
notificationEmailAddress : XXX@outlook.com
soldTo                   : @{addressLine1=XXX; addressLine2=; addressLine3=; city=XXX;       
                           companyName=XXX; country=XXX; firstName=XXX;
                           lastName=XXX; phoneNumber=XXX; postalCode=XXXX; region=} 
```

with M365 Developer Program tenant, i don't even get `listBillingAccount`

does creating subscriptions works with only EA tenants?

**Comment by krnese** [comment]
There's different pre-requisites for EA, MCA, and MPA. Public docs @ https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=rest-getEnrollments%2Crest-EA
