### ISSUE TITLE
Deny-Subnet-Without-Nsg will allow a network with a subnet to be created.

### ISSUE THREAD

**Issue by papatari** [Azure/Enterprise-Scale#407]
Deny-Subnet-Without-Nsg will allow a network with a subnet to be created.

The Deny-Subnet-Without-Nsg rule works for existing networks. Apparently when you try to add the subnet it will block you.
However if you create a new vNET with a subnet it will go through and then mark it as non-compliant.

**Comment by krnese** [comment]
Thanks. This is a known issue due to the different ways you can model a subnet today, 1) either as a top-level child resource, or 2) as declared in the property bag of the virtualNetworks resourceType (parent). We don't have a fix for this until the platform addresses it.
