### ISSUE TITLE
Landing Zone Peering to Hub MI Permissions

### ISSUE THREAD

**Issue by jstabl** [Azure/Enterprise-Scale#410]
Landing Zone policy for creating a new vnet in the landing zone and subsequently peer that vnet to the vhub fails because of a permission error. When the vnet policy is deployed a new managed identity is created as the scope of that landing zone subscription. But that managed identity is not granted contributor access to the Platform/Connectivity subscription. Is it expected this permission update is a manual process?

Create policy to deploy-vnet-hubspoke and scope it at the landing zone subscription. 

Identity type is SystemAssigned

**Comment by krnese** [comment]
This is expected. When you assign a policy at the landing zone (or child scopes to landing zones) that requires access to the platform side - such as policy to peer networking from a subscription in the landing zone to the connectivity subscriptio, the managed identity must have access also to the connectivity subscription/resource group.

**Comment by jstabl** [comment]
Ok - If this is expected that is fine. Just has to be dealt with after the policy deployment and part of operation documentation. Thank you for the response.
