### ISSUE TITLE
Landing Zone Example for connected vWan

### ISSUE THREAD

**Issue by dgitw** [Azure/Enterprise-Scale#413]
The Connected Landing Zone assumes a "Hub" vNet to which the LZ "Spoke" is peered, not a vWAN hub. 

Given the some of the "In a box" templates (Contoso for Example) deploys a vWAN, it would be great to get a LZ example that connects to the vWAN presumably creating a Microsoft.Network/virtualHubs/hubVirtualNetworkConnections rather than a Microsoft.Network/virtualNetworks/virtualNetworkPeerings resource.

**Comment by krnese** [comment]
Thanks for the feedback. We recently enabled this in Adventure Works (traditional hub & spoke with virtual network peering), and plan to enable the same for Contoso which is using vWan.

**Comment by krnese** [comment]
Due to some known platform limitations, we will hold this for now and not enable peering as part of the vwan deployment as that would impact the deployment success rate.
