### ISSUE TITLE
Specified path for Log Analytics parameter file does not exist

### ISSUE THREAD

**Issue by Gordonby** [Azure/Enterprise-Scale#416]
**Describe the bug**
The documentation refers to an optional step to deploy the Log Analytics Policy, the path provided does not exist in the repo.
There are however 4 instances of the file in the repository, so the path should be changed.

Current value for the path;
```
azopsreference\3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)\contoso (contoso)\platform (platform)\management (feab2d15-66b4-438b-accf-51f889b30ec3)\.AzState
```

I believe the correct one should be;
```
azopsreference\3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)\ESLZ (ESLZ)\ESLZ-platform (ESLZ-platform)\ESLZ-management (ESLZ-management)\management (feab2d15-66b4-438b-accf-51f889b30ec3)\.AzState
```

**Steps to reproduce**

1. Go to https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/use-git-pipeline.md#optional-assign-the-log-analytics-policy
2. In the 2nd step of this section, that begins "Copy the file Microsoft.Authorization_policyAssignments-Deploy-Log-Analytics.parameters.json" - review the path that is provided
3. Check the repo for the existence of this path...

**Screenshots**

**Comment by krnese** [comment]
Thanks. We will update the doc. Recommendation is to deploy one of the reference implementations hence this step is not needed.

**Comment by krnese** [comment]
Closing this as we will shortly remove the docs with the outdated instructions.
