### ISSUE TITLE
How to add a non-compliant message in a policyAssignment?

### ISSUE THREAD

**Issue by Jedoe830** [Azure/Enterprise-Scale#418]
**Describe the bug**
In the Azure Portal you can provide a non-compliance message in the policy assignment. This step has not been described in the Docs yet. But it's available. How do we implement that with ARM?

**Steps to reproduce**

1. Open a policy definition
2. Click "Assign"
3. Open the "non-compliance message" blade.

**Screenshots**

![image](https://user-images.githubusercontent.com/73531562/106485285-bb0ac900-64b0-11eb-9f1b-c94b42e94f55.png)

**Comment by krnese** [comment]
Example:

json````
        {
            "type": "Microsoft.Authorization/policyAssignments",
            "apiVersion": "2020-09-01",
            "name": "[guid(deployment().name)]",
            "properties": {
                "description": "fooo",
                "displayName": "baar",
                "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e765b5de-1225-4ba3-bd56-1ac6695af988",
                "scope": "[subscription().id]",
                "parameters": {
                    "listOfAllowedLocations": {
                        "value": ["westeurope"]
                    }
                },
                "nonComplianceMessages": [
                    {
                        "message": "The request was denied as it tried to create resource in an Azure region that is not allowed by Azure Policy."
                    }
                ]
            }
        }
`````

**Comment by Jedoe830** [comment]
Thank you. I deployed the policy assignment successfully. Unfortunately, when I try to deploy something what gets denied by the policy, I don't get the non-compliance-message I specified but:
![image](https://user-images.githubusercontent.com/73531562/106573267-b3dbcd80-6539-11eb-8e1d-677a66986f68.png)

My policyAssignment is the following:
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "input": {
            "value": {
                "Identity": null,
                "Location": null,
                "Name": "Deny-IP-Forwarding",
                "PolicyAssignmentId": "/providers/Microsoft.Management/managementGroups/bcp-az-landingzones/providers/Microsoft.Authorization/policyAssignments/Deny-IP-Forwarding",
                "Properties": {
                    "Description": "This policyAssignment denies the network interfaces which enabled IP forwarding",
                    "DisplayName": "Deny-IP-Forwarding",
                    "NotScopes": null,
                    "PolicyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/88c0b9da-ce96-4b03-9635-f29a937e2900",
                    "Scope": "/providers/Microsoft.Management/managementGroups/bcp-az-landingzones"
                },
                "nonComplianceMessages": [
                    {
                        "message": "The request was denied as it tried to create a network interface with IP Forwarding enabled."
                    }
                ],
                "ResourceType": "Microsoft.Authorization/policyAssignments"
            }
        }
    }
}

**Comment by krnese** [comment]
You will see the detailed custom message in the "raw" response of the error, as well as in the activity log.

**Comment by jtp64** [comment]
I wish the message would show up in the summary to make it more user friendly.  I did not think it was working until I went looking around and found it in the RAW Error.

**Comment by Jedoe830** [comment]
Is don't see it in neither in the raw response nor in the acrivity log. But the Assignment file seems to be okay. When I set a message in the Azure portal, I can see the message in the "Failed to save network interface" message. After pulling the changes, the policyAssignment doesn't contain the noncompliancemessage object.

**Comment by krnese** [comment]
Yes this is currently in the raw response. We will schedule work to reconcile the nonCompliantMessage array into policyAssignment as part of AzOps

**Comment by scottstout** [comment]
@krnese any update on this? I'm trying to make this seamless for users to understand what they need to do next. In our case I want to point them to a URL where they can request an exemption.
