### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by robertvanvugt** [Azure/Enterprise-Scale#42]
**Describe the bug**
First of all, I think the work your doing here is awesome! 

I do encounter an issue when trying to deploy the template to any of my Azure tenants using any off my accounts. I'm receiving the following error: 

"The client '{my account}' with object id '{my object id}' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/Microsoft.Template-20200624223131' or the scope is invalid. If access was recently granted, please refresh your credentials."

**RAW ERROR**

`{
  "deploymentStatusCode": -1,
  "stage": 6,
  "expected": true,
  "error": {
    "message": "The client '{my account}' with object id '{my object id}' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/Microsoft.Template-20200624223131' or the scope is invalid. If access was recently granted, please refresh your credentials."
  },
  "location": "westeurope",
  "deploymentName": "Microsoft.Template-20200624223131",
  "details": {
    "code": "AuthorizationFailed",
    "message": "The client '{my account}' with object id '{my object id}' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/Microsoft.Template-20200624223131' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}`
 
The accounts I've tested have **Global Administrator** permissions in AAD, they have **Owner** been assigned the owner role on the subscription(s), and they have been assigned **elevated rights** at the tenant root management group level.

**Steps to reproduce**

1. Trying to deploy using the Deploy to Azure link: https://ms.portal.azure.com/?feature.customportal=false#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzOps%2Fmain%2Ftemplate%2Fux-foundation.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzOps%2Fmain%2Ftemplate%2Fesux.json
2. Filling in the required information, tried most options, non of them work.
3. In the final blade I'm getting the validation error.

**Screenshots**
![image](https://user-images.githubusercontent.com/34948679/85627503-e69e1900-b66e-11ea-8720-b2722b8cb6ec.png)

**Comment by uday31in** [comment]
Can you please grant required permission to user account you are using to provision template?

Step -1 :
```
Get-AzRoleAssignment | ? {$_.RoleDefinitionName -eq "User Access Administrator" `
  -and $_.SignInName -eq "<username@example.com>" -and $_.Scope -eq "/"}
```

Step -2 :
```
New-AzRoleAssignment -SignInName <yourLoginName> -Scope "/" -RoleDefinitionName "Owner"
```

**Comment by robertvanvugt** [comment]
@uday31in This was a clear case of PEBCAK on my side.

`New-AzRoleAssignment -SignInName "<myLoginName>#EXT#@<myDomain>.onmicrosoft.com" -Scope "/" -RoleDefinitionName "Owner"`

I only used `<myLoginName>` but missed the external account bit when attempting to assign Onwer permissions at root: **#EXT#@**`<myDomain>`**.onmicrosoft.com**

After properly assigning Owner permissions at root it worked fine indeed.

Many thanks!

Robert

**Comment by DamianFlynn** [comment]
For anyone that hits this issue. The accounts utilised MUST NOT BE GUESTS to the Tenant - you must be authenticated with an account that is a member of the Tenants.
