### ISSUE TITLE
azOps: Missing Features discovered during the ESLZ Pilot

### ISSUE THREAD

**Issue by basvanbennekommsft** [Azure/Enterprise-Scale#423]
Hi all, 

As you might know, we have conducted an ESLZ pilot. During this pilot, we discovered that azOps is missing various features:

- Removing Policy Definitions, Sets and Assignments is not directly supported: So, when we are removing one of these objects (e.g. key-vault-policy-definition.json) from the repository, azOps Push does not pick up the change and subsequently remove the object. Instead, we need to remove it via for instance PowerShell and run azOps pull to ensure that the changes are made in the repository.
- Interacting with multiple Azure Active Directory (AAD) objects is not supported.
- Creating Exemptions is not supported: we want to move away from Exclusions (as they require you to redeploy a Policy Assignment) and use Exemptions instead. Unfortunately, this is not supported by azOps at the moment.

If you require additional information, please feel free to reach out to me via bas.van.bennekom@microsoft.com. 

Cheers!

**Comment by timowille** [comment]
Hi all,
we are also looking for a way to handle exemptions in enterprise scale. Is there a way to get exemptions created using the azure portal into git using the pull pipeline? Is this topic on the roadmap?
Thanks for your great work!
Best regards
Timo

**Comment by krnese** [comment]
Thanks for the feedback. Yes, support for exemptions is in the backlog

**Comment by daltondhcp** [comment]
Closing as these features are tracked as individual items in the AzOps repository already. 
Microsoft.Authorization/policyExemptions: https://github.com/Azure/AzOps/issues/407
Resource Deletion: https://github.com/Azure/AzOps/issues/395
