### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Eric2XU** [Azure/Enterprise-Scale#424]
I can not create the template due to the subscription not being in the pick list. I have created two new subs both dont show up, I am a global admin, I gave myself owner rights to the sub, had another user with same rights do it as well. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12671152/106962212-c5c19a00-670c-11eb-9b18-6b22fef03b83.png)

Side note, what list is this pulling, are there are other requirements? The Subs are no with no resources in them.

**Comment by krnese** [comment]
Thanks for reporting. The issue here is related to pagination when collecting the list of subscription. While we work to fix this, can you pls send me an email @ krnese[at]microsoft.com and I can provide you with a workaround.

**Comment by uday31in** [comment]
Fixed as  part of #575
