### ISSUE TITLE
DNS LogAnalytics Policy Definition missing

### ISSUE THREAD

**Issue by Jedoe830** [Azure/Enterprise-Scale#431]
**Describe the bug**
In the vWAN approach there are policies that need to be assigned. In the policies section "Enforce diagnostics/metrics to platform workspace" there are several policies. The policy definition for "DNS" cannot found in the repository. There is no link to the definition either. Does this definition still need to be assigned?

**Screenshots**

![image](https://user-images.githubusercontent.com/73531562/108041173-7baab380-703e-11eb-80c2-51c18f0755d0.png)

**Comment by Jedoe830** [comment]
Hi, is there any update on this?

**Comment by krnese** [comment]
The plan is to update the documentation and move away from linking to individual policyDefinitions as part of the reference implementation, so expect to see more consistency regarding the documentation for the reference implementations shortly.

Specifically for this policy, we have added it to our backlog. In the meantime, you can use the same pattern as we have for the other diagnostics policies and ensure the RP namespace and resourceType is correct, as well as the expected metrics/log categories for DNS services, and it should work.

**Comment by Jedoe830** [comment]
Ok, thanks. If I understand this article correctly (https://docs.microsoft.com/de-de/azure/dns/dns-alerts-metrics#azure-dns-metrics) it is for public DNS zones only. Just wanted to mention that for anybody else looking for this.
