### ISSUE TITLE
'Deploy the Log Analytics' Policy Improvements

### ISSUE THREAD

**Issue by liamfoneill** [Azure/Enterprise-Scale#436]
**Describe the bug**
Policy Definition 'Deploy Log Analytics in the Subscription' needs some improvements. I have written a newer version of this policy which incorporates the below changes. For the daily cap, this is set as a parameter but a nice enhancement would be to have no daily cap if no parameter is supplied (I haven't had time to look at that). 

https://gist.github.com/liamfoneill/341401cd673170cb381ccc83f2f94af3

Issues
There are some problems with this policy
1. There are 2 roles in this policy for the Managed Identity, Log Analytics Contributor and Monitoring Contributor. However, this policy also need Contributor as it tries to deploy a resource group into the subscription and fails.
2. The versions for the APIs are all quite old and there are newer ones available for the 3 resources.
3. There is a depends_on bug in this template when the linked setting for the Log Analytics Workspace to Connect to the Automation account doesn't see the depends_on for the parent log analytics resource
4. It would be nice to have the option of setting the daily cap for Log Analytics Ingestion

**Screenshots**
![SNAG-0123](https://user-images.githubusercontent.com/1243172/108321368-f5b47700-71bb-11eb-87c7-ecda8b4881cc.png)

**Comment by krnese** [comment]
Can you please point to the policyDefnition that is causing the issue? The invocation of this policy is used in all reference implementation deployments when log analytics is added, so would be interesting to see why the dependency is not honored in your case.

**Comment by liamfoneill** [comment]
Hi Kristian,

I did the AdventureWorks template deployment so it's the custom policy that gets included with that. The display name is : 'Deploy Log Analytics in the Subscription'

**Comment by krnese** [comment]
I wonder if there's something else going on here. Can you pls check the subscription you try to remediate onto, and if the resource group and the workspace + automation account got created?
