### ISSUE TITLE
Policy: Deploy the configurations to the Log Analytics Workspace

### ISSUE THREAD

**Issue by liamfoneill** [Azure/Enterprise-Scale#437]
**Describe the bug**
This policy for me is always complaint as the existence condition just checks the parameters I passed match the Log Analytics workspace that has already been deployed. 

**Steps to reproduce**

1. Use the other policy ('Deploy the Log Analytics Workspace') to deploy the Log Analytics Workspace + Automation Account
2. Assign the 'Deploy the configurations to the Log Analytics Workspace' policy to the same subscription as the Log Analytics Workspace.
3. Expected Result: The Solutions are deployed into the workspace
4. Actual Result: The empty LA workspace is marked as complaint so no solutions are deployed.

Suggestion: The existence condition should check if the solutions already exist and deploy them if not. These fields I found in the resources.azure.com in screenshot should allow that or check for the existance of a '"type": "Microsoft.OperationsManagement/solutions",' 

**Screenshots**
![image](https://user-images.githubusercontent.com/1243172/108402536-92efc980-7215-11eb-99fb-05a7642d3081.png)

**Comment by krnese** [comment]
These are two separate policies, and the conditions for the Log Analytics workspace are not bound to the solutions themselves - and vice versa. To have an all-up view of this, it would have to be an initiative that would ensure compliance state for the workspace existence, as well as the solutions (different RP namespace and aliases).

**Comment by liamfoneill** [comment]
Hi Kristian, I did the AdventureWorks template deployment so it would be the custom policy that gets include with that deployment

**Comment by krnese** [comment]
Closing this issue as the policies have been moved to built-ins now.
