### ISSUE TITLE
Azure vWAN Bootstrapping suggests /16 hub address range

### ISSUE THREAD

**Issue by paulgrimley** [Azure/Enterprise-Scale#440]
![image](https://user-images.githubusercontent.com/25264573/108853196-55f15180-75de-11eb-9c85-123ccf36cb3f.png)

The vWAN connectivity subscription bootstrapping config leads with a /16 address range which is misleading, the recommendation is to use a /23 range - could we update the deployment ARM to reflect this.

**Comment by daltondhcp** [comment]
Thank you for reporting Paul, we'll take a look at it!

**Comment by zebak007** [comment]
Confirmed. I just did a fresh deployment and the CIDR proposed in the Azure landing zone accelerator deployment UI is still referring to 10.100.0.0/16.

**Comment by jtracey93** [comment]
@zebak007 please see #716 where this has recently been re-logged.

Also I have just submitted a PR which is being reviewed by my colleagues which will fix this #718
