### ISSUE TITLE
Failed when I didnt go with ER for Trey Research.

### ISSUE THREAD

**Issue by rajanbhayana** [Azure/Enterprise-Scale#445]
**Describe the bug**

```
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy assignment create request is invalid. The policy definition '/providers/Microsoft.Management/managementGroups/mg/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-ExpressRoute' could not be found.\"\r\n  }\r\n}"
            }
        ]
    }
}
```

**Steps to reproduce**

1. Select Trey Research template
2. select ER/VPN Gateway/Firewall setup as No.

**Screenshots**

**Comment by krnese** [comment]
The issue you are running into is described @ https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Known-Issues.md#deploying-the-reference-implementation-fails-due-to-policy--cannot-be-found-404

Pls re-run the deployment with the same input and it should succeed. Pls let me know how it goes

**Comment by krnese** [comment]
Pls re-run and select 'No' on all the policies assigned on the landing zones.
