### ISSUE TITLE
Remove hard-coded references to "location" for deployment templates

### ISSUE THREAD

**Issue by krowlandson** [Azure/Enterprise-Scale#454]
## Problem Statement

A number of custom DINE policies provided within Enterprise-scale include nested deployment templatesusing hard-coded values for the deployment "location" field.

This means it isn't possible to control the location of deployments generated by these policies.

## Feature Request

This request is to set this value using a parameter (with default value) to allow customisation when setting up this policy in an assignment.

Original request raised by customer via the Terraform module here:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/23

## Instances Found

Instances of this configuration found in the following policy definitions:

- [Deploy-DDoSProtection](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-DDoSProtection.parameters.json#L71)
- [Deploy-Diagnostics-ActivityLog](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-Diagnostics-ActivityLog.parameters.json#L76)
- [Deploy-FirewallPolicy](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-FirewallPolicy.parameters.json#L71)
- [Deploy-HUB.parameters](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-HUB.parameters.json#L94)
- [Deploy-Log-Analytics](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-Log-Analytics.parameters.json#L99)
- [Deploy-vHUB](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-vHUB.parameters.json#L102)
- [Deploy-vNet](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-vNet.parameters.json#L67)
- [Deploy-VNET-HubSpoke](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-VNET-HubSpoke.parameters.json#L84)
- [Deploy-vWAN](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-vWAN.parameters.json#L71)

## Example of alternative

The following is an example of a policy within Enterprise-scale which uses a parameter to set the deployment location based on user-preference:

- [Deploy-Diagnostics-ACR](https://github.com/Azure/Enterprise-Scale/blob/52c20c768d8fd37e13f9fbc0667f002a46068125/azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ%20(ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-Diagnostics-ACR.parameters.json#L130)

**Comment by krnese** [comment]
This cannot be fixed until work on RP side has completed.
