### ISSUE TITLE
Excluded subnets for Deny Subnets without NSG

### ISSUE THREAD

**Issue by krowlandson** [Azure/Enterprise-Scale#456]
**Describe the bug**
As per [Issue 38](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/38) in the Terraform module, the "Deny Subnets without NSG" policy currently doesn't allow for networks needing subnets for internal services which do not support NSGs, such as `GatewaySubnet`, `AzureFirewallSubnet`, and `AzureFirewallManagementSubnet`.

**Steps to reproduce**

1. Create a virtual network
2. Assign the policy
3. Try to create one of the subnets which do not support NSGs

**Comment by daltondhcp** [comment]
@jtracey93 - would you mind taking a look at this one as well since it is very similar to the UDR one?
