### ISSUE TITLE
Deploy Diagnostic Settings for API Management to Log Analytics workspace - Schema issue

### ISSUE THREAD

**Issue by paulgrimley** [Azure/Enterprise-Scale#457]
When applying the 'Deploy Diagnostic Settings for API Management to Log Analytics workspace' policy it errors on deployment due to a mismatch on schema with the following error 

![image](https://user-images.githubusercontent.com/25264573/110644745-50cefd80-81ad-11eb-9bfd-cd9c7c13c53e.png)

"Metric category 'Gateway Requests' is not supported, supported categories are: 'AllMetrics'."

From the UI I can see that there is only one metric called 'AllMetrics'
![image](https://user-images.githubusercontent.com/25264573/110644410-f6ce3800-81ac-11eb-8287-37556dbc9eb9.png)

From looking at the policy this block needs consolidating from

                                                                {
                                                                    "category": "Gateway Requests",
                                                                    "enabled": "[[parameters('metricsEnabled')]",
                                                                    "retentionPolicy": {
                                                                        "days": 0,
                                                                        "enabled": false
                                                                    },
                                                                    "timeGrain": null
                                                                },
                                                                {
                                                                    "category": "Capacity",
                                                                    "enabled": "[[parameters('metricsEnabled')]",
                                                                    "retentionPolicy": {
                                                                        "days": 0,
                                                                        "enabled": false
                                                                    },
                                                                    "timeGrain": null
                                                                },
                                                                {
                                                                    "category": "EventHub Events",
                                                                    "enabled": "[[parameters('metricsEnabled')]",
                                                                    "retentionPolicy": {
                                                                        "days": 0,
                                                                        "enabled": false
                                                                    },
                                                                    "timeGrain": null
                                                                },
                                                                {
                                                                    "category": "Network Status",
                                                                    "enabled": "[[parameters('metricsEnabled')]",
                                                                    "retentionPolicy": {
                                                                        "days": 0,
                                                                        "enabled": false
                                                                    },
                                                                    "timeGrain": null
                                                                }

To

                                                                {
                                                                    "category": "AllMetrics",
                                                                    "enabled": "[[parameters('metricsEnabled')]",
                                                                    "retentionPolicy": {
                                                                        "days": 0,
                                                                        "enabled": false
                                                                    },
                                                                    "timeGrain": null
                                                                },

**Comment by krnese** [comment]
Ack. Thank you. We will fix this and link this issue with the upcoming PR.
