### ISSUE TITLE
Limit log analytics daily data cap by default

### ISSUE THREAD

**Issue by rajanbhayana** [Azure/Enterprise-Scale#463]
set and limit log analytics daily data cap to a bare minimum so that idle environments don't pay any major bills. Currently hub is generating more than 3 GB logs daily and I have only one VM there. Which has put the log analytics bill to over a 100$ per month. Not something a small team or individual just exploring hub/spoke wants to see straight away before using any other azure service.

https://docs.microsoft.com/en-us/azure/azure-monitor/logs/manage-cost-storage

**Comment by krnese** [comment]
We currently don't have any plans to bring this front and center as part of the deployment experience
