### ISSUE TITLE
Inconsistent naming of resource groups

### ISSUE THREAD

**Issue by bagwyth** [Azure/Enterprise-Scale#465]
**Describe the bug**
For all reference implementations the convention for naming resource groups is inconsistent:
- Under platform they're named like "_companyprefix_-mgmt", or "_companyprefix_-Connectivity" (note no suffix or prefix used to indicate that the objects are resource groups).
- Under landing zones we show them like "network-rg" or "app-n-rg" (note presence of "-rg" suffix to indicate that the objects are resource groups).

Personally, I don't have a strong preference for using a prefix, suffix, or not using either, but I think it's probably important to be consistent.

Note that the [CAF contains some resource naming recommendations](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming#example-names-general) which suggests using a "rg-" prefix when naming resource groups.

**Steps to reproduce**

N/A.

**Screenshots**

![es-rg-naming-inconsistent](https://user-images.githubusercontent.com/28044543/111287523-37a9cf00-863b-11eb-9658-2b12117c596c.png)

**Comment by krnese** [comment]
The diagrams are conceptually showing what is being deployed, but doesn't represent the actual resource names. To guarantee certain resources are created successfully for N tenants, we need to ensure there's a deterministic uniqueness for those resources, such as log anlaytics workspace, key vaults etc. Regarding naming convention in the landing zone, this is fully up to the organization to decide. Hope this helps
