### ISSUE TITLE
Pull request is not scheduled in Azure DevOps

### ISSUE THREAD

**Issue by mcdrm** [Azure/Enterprise-Scale#467]
The documentation at Enterprise-Scale/docs/Deploy/setup-azuredevops.md mentions:

> By default the AzOps Pull pipeline will run every 6 hours, however you can invoke this action at any time when you suspect configuration drift due to Out of Band changes in Azure.

However there is no schedule set in the YAML file

**Comment by mcdrm** [comment]
I can see its defined in the YAML code but it is not running or pulling through in schedules. I will have a look at it and report back.

**Comment by ljtill** [comment]
@mcdrm - Please visit the [Accelerator](https://github.com/Azure/AzOps-Accelerator/) repository for the latest versions of the [pipelines](https://github.com/Azure/AzOps-Accelerator/tree/main/.pipelines). Within the Pull source we have a section defined for scheduled runs (every six hours). Please raise an issue on the [AzOps](https://github.com/Azure/AzOps) repository if you encounter any further issues.
