### ISSUE TITLE
Deploy NSG Flow Logs policy - error

### ISSUE THREAD

**Issue by Vallentyne** [Azure/Enterprise-Scale#471]
The policy def for NSG flow logs doesn't seem to assess the existence condition right, and doesn't deploy NSG flow logs.

**Steps to reproduce**
When I check the activity logs, the remediation job shows the following error:

    "errorMessage": "The 'ifNotExists' target resource type 'Microsoft.Network/networkWatchers/flowLogs' and name '' are not valid in policy assignment '/providers/Microsoft.Management/managementGroups/CV3/providers/Microsoft.Authorization/policyAssignments/3eb8a63530e147aebf163f1e' and definition '/providers/Microsoft.Management/managementGroups/CV3/providers/Microsoft.Authorization/policyDefinitions/Deploy-Nsg-FlowLogs' when evaluating a resource of type 'microsoft.network/networksecuritygroups'.",

**Comment by krnese** [comment]
Thanks! When did you deploy the reference implementation? We had an issue with the NSG policy earlier, but it was fixed a few weeks back

**Comment by Vallentyne** [comment]
hm, might be older than that.  ok. will redeploy and have a look.  thanks, will update here when I know.
