### ISSUE TITLE
Unable to deploy Adventureworks Reference Implementaiton  - Failed to add Management Group

### ISSUE THREAD

**Issue by shalu-kumar-katonic** [Azure/Enterprise-Scale#477]
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md

**Describe the bug**

Hi Team, Please help us with us deploying this Reference - https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md 
We are receiving the error 'Failed to add subscription to Management Group'
**Steps to reproduce**

1.Deploye Azure for AdventureWorks Reference Implementation
2.Review & Create
3.Failed to add subscription to Management Group
**Screenshots**
![error](https://user-images.githubusercontent.com/78348424/112455497-c88d5280-8d7f-11eb-9905-34d2cb5b99f3.jpg)

**Comment by krnese** [comment]
Thanks - we will investigate this.
Can you pls confirm that you are using a unique subscription for connectivity and management?

**Comment by shalu-kumar-katonic** [comment]
> Thanks - we will investigate this.
> Can you pls confirm that you are using a unique subscription for connectivity and management?

No, we are using the same subscription. Please advice on the same.

**Comment by krnese** [comment]
You cannot use the same subscription for both management and connectivity. We will fix to invalidate if that happens, but for now, pls bring dedicated subscriptions to both management and connectivity (they must be separated)

**Comment by shalu-kumar-katonic** [comment]
> You cannot use the same subscription for both management and connectivity. We will fix to invalidate if that happens, but for now, pls bring dedicated subscriptions to both management and connectivity (they must be separated)

okay, thank you very much! Can you please guide me with how do we create multiple subscriptions with the single account?

**Comment by krnese** [comment]
Please see the documentation here: https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/create-subscription

**Comment by shalu-kumar-katonic** [comment]
> Please see the documentation here: https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/create-subscription

Thank you very much @krnese !

**Comment by shalu-kumar-katonic** [comment]
@krnese - can you please let me know if we can refer to the "Enterprise Scale "in-a-box" tutorial" and implement the "AdventurWorks Reference Implementation"?

**Comment by krnese** [comment]
To deploy Adventure Works, you should use the reference implementation for that. 'In-a-box' is primarily a tutorial for infrastructure as code.

**Comment by shalu-kumar-katonic** [comment]
> To deploy Adventure Works, you should use the reference implementation for that. 'In-a-box' is primarily a tutorial for infrastructure as code.

Okay. Thank you.
