### ISSUE TITLE
Creation of empty subscription fails with Invalid scope error

### ISSUE THREAD

**Issue by vishnu-vashist** [Azure/Enterprise-Scale#483]
New-AzManagementGroupDeployment: 7:37:49 PM - The deployment 'xxxx' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Not a valid subscription creation scope (Code:InvalidSubCreationScope)
CorrelationId: 3cc29bf8-3127-46df-a13a-8e54f3eccae1

If we remove the scope in the template then it throws the following error:

New-AzManagementGroupDeployment: 7:32:07 PM - The deployment 'nvnbnm' failed with error(s). Showing 1 out of 1 error(s).
Status Message: The resource type 'managementGroups' could not be found in the namespace 'Microsoft.Management' for api version '2020-09-01'. The supported api-versions are '2021-04-01,2020-10-01,2020-05-01,2020-02-01,2019-11-01,2018-03-01-preview,2018-01-01-preview,2017-11-01-preview,2017-08-31-preview,2017-06-30-preview,2017-05-31-preview,2018-03-01-beta'. (Code:InvalidResourceType)
CorrelationId: 33d564c3-a17f-45ea-8fd2-f0b16ea1f6e7

**Comment by krnese** [comment]
This is likely because the wrong/incorrect billingId is provided. Can you share the template?

**Comment by krnese** [comment]
Closing this as we haven't heard back. If you have further details, it would be good to know:
* Which template you are using
* Where you are invoking the deployment (tenant, management group scope).
Please re-open the issue if you have the above details and are still blocked.
