### ISSUE TITLE
Policy Deployment Error - Unable to download deployment content

### ISSUE THREAD

**Issue by ClinteRich** [Azure/Enterprise-Scale#484]
**Describe the bug**
When you try to deploy to either a Management Group or Subscription from this "Deploy to Azure" action. At the following link:
https://github.com/Azure/Enterprise-Scale/tree/main/azopsreference

I receive the following error for the deployment:
Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/AzOps/main/template/template.json'. The tracking Id is 'c468a903-0961-4c7f-ac75-120604d6b4df'. Please see https://aka.ms/arm-deploy for usage details. (Code: InvalidContentLink)

**Steps to reproduce**

1. Visit here: https://github.com/Azure/Enterprise-Scale/tree/main/azopsreference
2. Choose either Deploys the policyDefinition of your choice to a management group or Deploys the policyDefinition of your choice to a subscription
3. Run through the deployment choosing any region and any one of the Policy Definitions.
4. You will get the error during Template Validaiton.

**Screenshots**
![image](https://user-images.githubusercontent.com/8038915/113489719-b902bd80-9493-11eb-8063-062c6fbbac2a.png)

![image](https://user-images.githubusercontent.com/8038915/113489735-cc158d80-9493-11eb-93b3-036129407524.png)

![image](https://user-images.githubusercontent.com/8038915/113489744-d768b900-9493-11eb-833f-f72704324d42.png)

![image](https://user-images.githubusercontent.com/8038915/113489746-de8fc700-9493-11eb-99a6-c3af211e09df.png)

**Comment by krnese** [comment]
Thank you. We are about to deprecate the azopsfolder and the individual policy deployment. To get the policies, I highly recommend deploying the reference implementation(s)

**Comment by ClinteRich** [comment]
Understood, I do think its a nice feature to be able to "test drive" an individual policy without having to deploy the entire landing zone. Also, you may not have the permissions to interact with constructs such as AAD and/or Management Groups if using a MSDN/VS type Azure subscription. Thanks for your reply.

**Comment by krnese** [comment]
We have added a button to deploy all policies to a management group now. Can you see if this solves it for you?

**Comment by ClinteRich** [comment]
I think it's the other way. Sorry if that was confusing. So the same intent as the original two deploy buttons. Just have them work. So be able to deploy individual CAF inspired policies definition to either the subscription or management group scope. That would help me be able to test drive these at a subscription level or management group on the customer side.
