### ISSUE TITLE
Deploy native ARM Templates using the push pipeline

### ISSUE THREAD

**Issue by Jedoe830** [Azure/Enterprise-Scale#485]
We're trying to deploy several resources in an ARM template (no policy) and push this template using the Push Pipeline. This works fine, except when we add dependencies. In our ARM template (works locally fine) we're deploying several resources in different deployments. As you can see in our code there are dependencies between the deployments, but I think the Pipeline cannot handle them:

My Code:
`"resources": [
        {
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2020-06-01",
            "name": "nestedSub",
            "location": "[parameters('nestedLocation')]",
            "subscriptionId": "[parameters('nestedSubId')]",
            "properties": {
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "parameters": {},
                    "variables": {},
                    "resources": [
                        {
                            "type": "Microsoft.Resources/resourceGroups",
                            "apiVersion": "2020-06-01",
                            "name": "[parameters('nestedRG')]",
                            "location": "[parameters('nestedLocation')]"
                        }
                    ]
                }
            }
        },
        {
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2020-06-01",
            "name": "layer1",
            "subscriptionId": "[parameters('nestedSubId')]",
            "resourceGroup": "[parameters('nestedRG')]",
            "dependsOn": [
                "[resourceId('Microsoft.Resources/deployments', 'nestedSub')]"
            ],
            "properties": {
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "resources": [
                        {
                            "type": "Microsoft.Web/serverfarms",
                            "apiVersion": "2018-02-01",
                            "name": "[concat(parameters('functionAppName'))]",
                            "location": "[parameters('nestedLocation')]",
                            "sku": {
                                "name": "Y1",
                                "tier": "Dynamic"
                            },
                            "properties": {
                                "name": "[parameters('functionAppName')]",
                                "computeMode": "Dynamic"
                            }
                        },
                        {
                            "type": "microsoft.insights/components",
                            "apiVersion": "2018-05-01-preview",
                            "name": "[parameters('functionAppName')]",
                            "location": "[parameters('nestedLocation')]",
                            "tags": {
                                "[concat('hidden-link:', concat('subscriptions/',parameters('nestedsubId'),'/resourceGroups/',parameters('nestedRG'),'/providers/Microsoft.Web/sites/',parameters('functionAppName')))]": "Resource"
                            },
                            "properties": {
                                "ApplicationId": "[parameters('functionAppName')]",
                                "Request_Source": "IbizaWebAppExtensionCreate"
                            }
                        }
                    ]
                }
            }
        },
        {
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2020-06-01",
            "name": "layer2",
            "subscriptionId": "[parameters('nestedSubId')]",
            "resourceGroup": "[parameters('nestedRG')]",
            "dependsOn": [
                "[resourceId('Microsoft.Resources/deployments', 'layer1')]"
            ],
            "properties": {
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "resources": [
                        {
                            "type": "Microsoft.Web/sites",
                            "apiVersion": "2018-11-01",
                            "name": "[parameters('functionAppName')]",
                            "location": "[parameters('nestedLocation')]",
                            "kind": "functionapp",
                            "identity": {
                                "type": "SystemAssigned"
                            },
                            "properties": {
                                "enabled": true,
                                "serverFarmId": "[concat('subscriptions/',parameters('nestedsubId'),'/resourceGroups/',parameters('nestedRG'),'/providers/Microsoft.Web/serverfarms/',parameters('functionAppName'))]",
                                "siteConfig": {
                                    "appSettings": [
                                        {
                                            "name": "AzureWebJobsStorage",
                                            "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('functionStorageAccountName'), ';AccountKey=', listKeys(concat('subscriptions/',parameters('nestedsubId'),'/resourceGroups/',parameters('nestedRG'),'/providers/Microsoft.Storage/storageAccounts/',parameters('functionStorageAccountName')), '2019-06-01').keys[0].value)]"
                                        },
                                        {
                                            "name": "FUNCTIONS_EXTENSION_VERSION",
                                            "value": "~3"
                                        },
                                        {
                                            "name": "FUNCTIONS_WORKER_RUNTIME",
                                            "value": "powershell"
                                        },
                                        {
                                            "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
                                            "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('functionStorageAccountName'), ';EndpointSuffix=', environment().suffixes.storage, ';AccountKey=',listKeys(concat('subscriptions/',parameters('nestedsubId'),'/resourceGroups/',parameters('nestedRG'),'/providers/Microsoft.Storage/storageAccounts/',parameters('functionStorageAccountName')), '2019-06-01').keys[0].value)]"
                                        },
                                        {
                                            "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
                                            "value": "[reference(variables('insightsResourceId'), '2018-05-01-preview').InstrumentationKey]"
                                        },
                                        {
                                            "name": "keyVaultName",
                                            "value": "[parameters('keyVaultName')]"
                                        },
                                        {
                                            "name": "appObjectId",
                                            "value": "c628c5ea-c3d6-41a7-834d-b22067c76023"
                                        }
                                    ]
                                }
                            },
                            "resources": [
                                {
                                    "type": "functions",
                                    "apiVersion": "2018-11-01",
                                    "name": "[parameters('functionName')]",
                                    "properties": {
                                        "config": {
                                            "bindings": [
                                                {
                                                    "type": "eventGridTrigger",
                                                    "name": "eventGridEvent",
                                                    "direction": "in"
                                                }
                                            ],
                                            "disabled": false
                                        },
                                        "language": "powershell"
                                    },
                                    "dependsOn": [
                                        "[concat('subscriptions/',parameters('nestedsubId'),'/resourceGroups/',parameters('nestedRG'),'/providers/Microsoft.Web/sites/',parameters('functionAppName'))]"
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        }`

One of the error message is:
`The deployment 'AzOps-Deploy-Rotator-Infra' failed with error(s). Showing 1 out of 1 error(s). Status Message: The Resource 'Microsoft.Web/sites/rotator-fnapp' under resource group 'pcp-mgmt' was not found.`

The error depends on what resources are deployed already. When I queue the pipeline three times in a row the last one is successful. 

Is this the recommended way to deploy resources in the ES approach?

**Comment by mcdrm** [comment]
I asked this question also: https://github.com/Azure/Enterprise-Scale/discussions/469

For me its not clear in this documentation / process and its a shame there is not clearer guidance on how this should look or be structured.

**Comment by Jedoe830** [comment]
> I asked this question also: #469
> 
> For me its not clear in this documentation / process and its a shame there is not clearer guidance on how this should look or be structured.

And how did you manage multiple deployments in one ARM template using the pipeline?

**Comment by krnese** [comment]
AzOps will invoke the template deployment at the scope where you make the PR (management group, subscription). We recently made some updates to AzOps so resource group deployments are also covered. We are in the midst of updating our docs to reflect these changes, and if you can send me an email I can share the doc with you as we are transitioning it to markdown as we speak.

Regarding the error; can you also share the template with me? AzOps, as I said will invoke the deployment, but you are in charge of your own destiny in terms of resource composition and sequencing within the template(s) yourself.

**Comment by Jedoe830** [comment]
Ok, I will. I know that we're responsible for the sequencing inside the template ourselfes. The Powershell command "New-AzManagementGroupDeployment" doesn't have any issues with our sequencing. That's why we're confused. However, I'll send you the details via mail.

Thanks!
