### ISSUE TITLE
Landing Zones perspective in Enterprise Scale

### ISSUE THREAD

**Issue by ManuInNZ** [Azure/Enterprise-Scale#49]
**Describe the solution you'd like**

My experience in design principles I try to push now in Enterprise Scale type deployment would be to consider Landing Zones a potential parallel to the "Product". I.e. not just one Application, which could be misunderstood for an app services, but more as the whole solution.
I would argue that in a DevOps culture and the autonomy requirements, the landing zone as a dedicated subscription and set of resources all required with just a Enterprise level push of policy driven governance, is the right way to have enablement of the flow for value creation.
As described in the ES design you then share the core resources from the hub/platform subscription, e.g. APIM as a pivotal resources to share APIs internally (between products) or externally. 

Not sure if this request is for this repo or the docs page.

Cheers
Manu

**Comment by hjscherer** [comment]
Thank you @ManuInNZ for your feedback apologize for the delay. In ESLZ we are focusing on platform architecture and what needs to be true before an application/workload/product can be deployed to Azure. Working with customers we have seen a lot of different names used for the ressource used to build a "workload". This comes down to the company nomenclature.
However we have started to look into workload specific LZ design and guidance. Can you share more information and requirements on your customer sceanrio?

**Comment by hjscherer** [comment]
Perfect, will reach out to via teams.
