### ISSUE TITLE
Make use of newer ARM goodness

### ISSUE THREAD

**Issue by ManuInNZ** [Azure/Enterprise-Scale#50]
**Describe the solution you'd like**

I was thinking about some --whatif to have a review of the proposed changes probably more for discovery and early days of the setup to bring assurance on what will happen.
.

**Comment by krnese** [comment]
Can you elaborate more on the use case, as what-if supports only resource group and subscription scoped deployments currently?

**Comment by ManuInNZ** [comment]
That might come from my misunderstanding at this stage of this initiative.
To me for the introduction of the adoption or just the addition of a new landing zones, it provides reassurance to have a "what is going to happen".
My point of view is that I see the --what-if as the opportunity to document/review the "plan"  (terraform like) and include this as an artefact of the adoption or lifecycle of the landing zone.
I did not know that the --what-if was not available on higher constructs such as Management groups yet I see value to see things like resource groups, vnets and their peerings and so on.
Just an opinion 😄

**Comment by krnese** [comment]
We have included this and once PS support for management group and tenant scope is available, we will enable -whatIf

**Comment by ManuInNZ** [comment]
Merci
