### ISSUE TITLE
Deploy Enterprise-scale for small enterprises

### ISSUE THREAD

**Issue by melwinlawrance** [Azure/Enterprise-Scale#502]
**Describe the bug**
After the deployment not able to see the Resource Group for the identity, Which is mentioned in the architecture diagram.
Is this expected or is the template is missing the identity section?

**Steps to reproduce**

1. Deploy the template to Azure
2.

**Screenshots**
![image](https://user-images.githubusercontent.com/82506650/114690141-b8311d80-9d16-11eb-835c-2f57aede4c04.png)

Regards,
Melwin Lawrance

**Comment by krnese** [comment]
The RG for identity is not created as part of the deployment (nor is the domain controllers). The diagram is showing conceptually how one can organize these resources in this subscription.

For greater scale and clear separation of duties, the other 3 reference implementations have dedicated subscriptions (management, identity, and connectivity) where there's additional resources that can be deployed and configured.

**Comment by melwinlawrance** [comment]
Thanks for the clarification.
