### ISSUE TITLE
VPN GW Deployment fails

### ISSUE THREAD

**Issue by florianwanner** [Azure/Enterprise-Scale#504]
VPN Gateway ressource creation fails - because of v1/v2 mismatch:
"statusMessage": "{\"error\":{\"code\":\"VirtualNetworkGatewaySkuCannotBeCreatedForSpecifiedVmGeneration\",\"message\":\"The Virtual Network Gateway Sku VpnGw1 cannot be used when VirtualNetworkVpnGatewayGeneration is set to Generation2.\",\"details\":[]}}",

**Comment by krnese** [comment]
Thanks for reporting this issue. Can you let me know which reference implementation you are deploying?

**Comment by florianwanner** [comment]
AdventureWorks with one LandingZone


________________________________
Von: Kristian Nese ***@***.***>
Gesendet: Wednesday, April 14, 2021 5:59:01 PM
An: Azure/Enterprise-Scale ***@***.***>
Cc: Florian Wanner ***@***.***>; Author ***@***.***>
Betreff: Re: [Azure/Enterprise-Scale] VPN GW Deployment fails (#504)


Thanks for reporting this issue. Can you let me know which reference implementation you are deploying?

**Comment by krnese** [comment]
Thanks. Can you also pls share a screenshot of the configuration you made on the connectivity blade (Hub & Spoke)?
