### ISSUE TITLE
LocationNotAvailableForResourceType norwayeast

### ISSUE THREAD

**Issue by FallenHoot** [Azure/Enterprise-Scale#507]
**Can't deploy to Norway East**

```JSON
{
  "code": "LocationNotAvailableForResourceType",
  "message": "The provided location 'norwayeast' is not available for resource type 'Microsoft.Resources/deploymentScripts'. List of available regions for the resource type is 'eastasia,southeastasia,australiaeast,brazilsouth,canadacentral,switzerlandnorth,germanywestcentral,eastus2,eastus,centralus,northcentralus,francecentral,uksouth,centralindia,southindia,japaneast,koreacentral,northeurope,uaenorth,westcentralus,westeurope,westus2,westus,southcentralus'."
}
```

**Steps to reproduce**

Deploy WIngtip ESLZ into Norway East

What Azure Services are missing from Norway East to make this region not available? 
Is the location hardcoded?
What checks does it do?

Azure Key Vault
Azure Log Analytics
Azure Security Center
Azure Sentinel

**Comment by krnese** [comment]
We use the location from the deployment itself (deployment().location), and it looks like you are trying to deploy the Git integration to a region where some of the underlying resources aren't available. If you can target the deployment to a different region where the resourceType is present, it should work.

**Comment by FallenHoot** [comment]
When I pick ***No*** for the "Platform DevOps and Automation" It works!

![image](https://user-images.githubusercontent.com/19664186/114934640-713c4880-9e3a-11eb-8787-229edb03744a.png)


What are the underlying resources that are not available? So I can get this looked at?

This option ("Subscription used for git initialization") goes away once I pick "Platform management, security, and governance" Management Subscription (required).
![image](https://user-images.githubusercontent.com/19664186/114937853-a480d680-9e3e-11eb-8be3-7541672acb0c.png)

![image](https://user-images.githubusercontent.com/19664186/114937991-d09c5780-9e3e-11eb-8bf8-f2ef8cba1566.png)

Do you have another method to pick a different region? 

If I change "Basics" Region: from Norway East to West Europe
![image](https://user-images.githubusercontent.com/19664186/114938203-1eb15b00-9e3f-11eb-96df-bdda0dba542e.png)

It works as it should. I am back to my issue, of not being able to use Norway East.

**Comment by krnese** [comment]
Microsoft.Resources/deploymentScripts is the resource that is yet not available, that we use to initialize Git integration and AzOps.

**Comment by krnese** [comment]
Closing this one now as deploymentScripts is made available in Norway East.
