### ISSUE TITLE
VNet Peer Identity Subscription as part of Bootstrap for AdventureWorks (Hub and Spoke)

### ISSUE THREAD

**Issue by paulgrimley** [Azure/Enterprise-Scale#517]
**Describe the bug**
Currently when bootstrapping AdventureWorks the identity subscription is not peered to the connectivity hub. Given this subscription may contain AD DC servers this connectivity is needed for IaaS domain joined VM's for authentication. I'm not sure if Contoso (Azure vWAN) also doesn't have this configured and needs addressing?

**Comment by victorar** [comment]
Thanks for logging this issue, @paulgrimley. We have added this to our backlog.
