### ISSUE TITLE
Ability to filter the region for the first virtual network hub -- Quality of Life

### ISSUE THREAD

**Issue by FallenHoot** [Azure/Enterprise-Scale#526]
**Issue**
As the Regions increase, so does the scrolling. I understand it is not a top priority, but would like it to function like the Basic tab (example below). The list is just bad, thus allowing the filter option would improve the quality of life. 

![image](https://user-images.githubusercontent.com/19664186/115843784-7f342f80-a41f-11eb-8d59-eeb1a38e6a42.png)

**Describe the solution you'd like**
This is code is just an example, could have errors, or not work as described. 
```json
{
                        "name": "esNwLocation",
                        "type": "Microsoft.Common.DropDown",
                        "label": "Region for the first virtual network hub",
                        "toolTip": "Select the target region for you connectivity deployment (requires you to provide a subscriptionId for connectivity)",
                        "multiselect": false,
                        "selectAll": false,
                        "filter": true,
                        "filterPlaceholder": "Filter items ...",
                        "multiLine": true,
                        "constraints": {
                            "allowedValues": "[map(steps('esConnectivityGoalState').esLocationsApi.value, (item) => parse(concat('{\"label\":\"', item.displayName, '\",\"value\":\"', item.name, '\"}')))]",
                            "required": true
                        },
                        "visible": "[equals(steps('esConnectivityGoalState').esHub, 'Yes')]"
                    }
```
![image](https://user-images.githubusercontent.com/19664186/115841597-4004df00-a41d-11eb-9afb-033fb52b6f6a.png)

**Comment by juazasan** [comment]
@krnese can you please add @aarunraaj to this issue? We are looking at addressing together with the other changes we are making to align TR with the other RIs. Thanks.
