### ISSUE TITLE
Microsoft.Authorization/roleAssignments always failed with this template  Enterprise-Scale/blob/main/docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json

### ISSUE THREAD

**Issue by Scarlettliuyc** [Azure/Enterprise-Scale#541]
**Describe the bug**
Hi team,
I'm Scarlett from ARM Support team. 
We have a customer always have  400 error for "PUT/SUBSCRIPTIONS/PROVIDERS/MICROSOFT.AUTHORIZATION/ROLEASSIGNMENTS/"
customer confirmed have owner role in Management Group and also for subscriptions. 
But customer have another subscription deleted all the Policy assignment, it can deployed successfully.
There is a Policy in this template, but we cannot sure what's the reason for this resource deployed failed 
     
 "policyDefinitions": {
            "dDoSPolicyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/94de2ad3-e0c1-4caf-ad78-5d47bbc83d3d"
        },
        "policyAssignmentNames": {
            "deployDdoS": "Enable-DDoS-VNET"
        },
        "roleAssignmentNames": {
            "deployDdoS": "[guid(concat(parameters('toplevelManagementGroupPrefix'),variables('policyAssignmentNames').deployDdoS, 'platform'))]"
        },

**Steps to reproduce**

1. Create necessary subscriptions (Management, Online, Corp, Hub)
2. Deploy Enterprise scale templates : https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md
3. Remove all resource groups and resources from all subscriptions.
4. Remove created management groups.
5. Remove previous deployments  https://github.com/Azure/Enterprise-Scale/blob/main/docs/enterprise-scale-iab/troubleshooting.md#deployment-region
6. Try to deploy once again the same templates in the same subscriptions

**Error:**
{\"error\":{\"code\":\"RoleAssignmentUpdateNotPermitted\",\"message\":\"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"}}",  "statusMessage": "{\"status\":\"Failed\",\"error\":

{\"code\":\"ResourceDeploymentFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"DeploymentFailed\",\"message\":\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\"details\":[{\"code\":\"BadRequest\",\"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"RoleAssignmentUpdateNotPermitted\\\",\\r\\n    \\\"message\\\": \\\"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\\\"\\r\\n  }\\r\\n}\"}]}]}}",

**Questions:**
We checked this template ,cannot sure which part right about the role assignment, could you please point our about it ?
And we tried to reproduce the issue, it's like there some limitation in our Microsoft Tenant . We cannot reproduce the issue.
How can we do it ?

Thank you

**Comment by dsv591** [comment]
The roleAssignment here is for a system assigned managed identity, which has a different principal id every time it is created. Since the roleAssignment is updating the principal id, that results in the error.

The cleanup procedure must include removing the roleAssignments created by these templates.

**Comment by krnese** [comment]
Closing this as we solved this offline.

**Comment by dsv591** [comment]
@krnese I'm ok with this being closed, but you should provide some docs for customers to do cleanup if they need to do redeployment.
