### ISSUE TITLE
File path too long to clone on windows

### ISSUE THREAD

**Issue by rocketingineer** [Azure/Enterprise-Scale#547]
**Describe the bug**

Hello, 

When I forked Enterprise-scale into my company's github and cloned it down locally to my windows dev environment, I ran into a character length issue pasted below. The azropsreference contains a lengthy guid. Thanks!

error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/.AzState/Microsoft.Authorization_policyDefinitions-Deploy-Sql-vulnerabilityAssessments.parameters.json: Filename too long
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-decommissioned (ESLZ-decommissioned)/.AzState/Microsoft.Management_managementGroups-ESLZ-decommissioned.parameters.json: Filename too long
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/.AzState/Microsoft.Authorization_policyAssignments-0f9a435f7c0f4d8391459d14.parameters.json: Filename too long

**Steps to reproduce**

1. Fork it to company repo https://github.com/companyABC/enterprise-scale-upstream 
2. clone it locally to c:\projects\github\companyABC and it errors out due to file length problems. 

**Screenshots**

***UPDATE***

I also tried cloning to a folder "p" on the root on my "c:\" drive for the shortest length possible and it still errored out. 

PS C:\projects\github> cd c:\p
PS C:\p> git clone https://github.com/CompanyABC/enterprise-scale-upstream.git
Cloning into 'enterprise-scale-upstream'...
remote: Enumerating objects: 647, done.
remote: Counting objects: 100% (647/647), done.
remote: Compressing objects: 100% (409/409), done.
Receiving objects:  76% (492/647eused 482 (delta 211), pack-reused 0R
Receiving objects: 100% (647/647), 16.84 MiB | 18.25 MiB/s, done.
Resolving deltas: 100% (317/317), done.
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/.AzState/Microsoft.Authorization_policyAssignments-0f9a435f7c0f4d8391459d14.parameters.json: Filename too long
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/.AzState/Microsoft.Authorization_policyAssignments-60f47429123045638942e8bd.parameters.json: Filename too long
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/.AzState/Microsoft.Authorization_policyAssignments-Deny-RDP-from-internet.parameters.json: Filename too long
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/.AzState/Microsoft.Authorization_policyAssignments-Deny-Subnet-Without-Nsg.parameters.json: Filename too long
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/.AzState/Microsoft.Authorization_policyAssignments-Deploy-SQL-DB-Auditing.parameters.json: Filename too long
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/.AzState/Microsoft.Authorization_policyAssignments-Enforce-SQL-Encryption.parameters.json: Filename too long
error: unable to create file azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/ESLZ-corp (ESLZ-corp)/.AzState/Microsoft.Management_managementGroups-ESLZ-corp.parameters.json: Filename too long
fatal: cannot create directory at 'azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560 (3fc1081d-6105-4e19-b60c-1ec1252cf560)/ESLZ (ESLZ)/ESLZ-landingzones (ESLZ-landingzones)/ESLZ-corp (ESLZ-corp)/bu1-ncus-msx4 (61c7653d-4d0f-4729-a0d2-c8138cfa1434)/.AzState': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

PS C:\p>

Thank you!

**Comment by krnese** [comment]
Thanks. For the IaC setup (GitHub or Azure DevOps), pls follow the instructions - and use the template repository from here: https://github.com/Azure/AzOps-Accelerator

We are in the midst of updating the documentation etc for this repository to make this more clear, as this repository will only contain the documentation and the deployment experience of Enterprise-Scale.

Thanks

**Comment by daltondhcp** [comment]
Like Kristian mentioned above, we are working on restructuring our docs. Solution for your particular issue is documented here right now: https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/getting-started.md#enabling-long-paths-on-windows

**Comment by rocketingineer** [comment]
Cheers, thank you

Joshua Corbett
Lead Cloud Engineer
c: (313) 450-5321
***@***.***D74037.09B0A730]
