### ISSUE TITLE
WingTip: Failed Deployment 'Subscription is not registered to use microsoft.insights'

### ISSUE THREAD

**Issue by doherty100** [Azure/Enterprise-Scale#549]
**Describe the bug**
When deploying WingTip reference architecture using two Visual Studio Enterprise subscriptions, the deployment fails with the following error `The subscription '155ce69d-6ce9-4716-a500-778337f532f2' is not registered to use microsoft.insights.'

**Steps to reproduce**

1. Deploy a AAD tenant via Microsoft 365 Developer subscription (E5)
2. Enable access management for Azure resources
2. Create two Azure Subscriptions using [Monthly Azure credit for Visual Studio Enterprise (MPN) subscribers](https://azure.microsoft.com/en-us/offers/ms-azr-0029p/)
3. Change the directory for the two Azure Subscriptions to the AAD tenant created in step 1
4. Grant owner role assignment at Tenant Root Group
5. Deploy WingTip using default settings, use different Azure subscriptions for Management and Landing Zone 
6. In Azure Portal navigate to Home >Management groups > [your top level management group] > deployments
7. Look for an failed deployment named `EntScale-DiagSec-....` and click on it to open Deployment details
8. Click error details and observe errors shown in [rd/Microsoft.Resources/EntScale-DiagSec-eastusd575beb4-6510-5fbd-91e6-239d2bbd8d9d](https://gist.github.com/doherty100/8176f0064e2e4779a45108f93f9a5b4c)
9. Note first conflict failure for resource `subscriptionToLa` with the details "The subscription '155ce69d-6ce9-4716-a500-778337f532f2' is not registered to use microsoft.insights."

**Comment by doherty100** [comment]
De-provisioned everything, moved subscriptions back into tenant root group, unregistered `microsoft.insights` (note case) resource provider from both subscriptions, then re-registered on both subscriptions. Deployed a second time with the same settings and deployment failed again, this time on the `EntScale-Monitoring-...` resource. 

```json
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy assignment create request is invalid. The policy definition '/providers/Microsoft.Management/managementGroups/rd/providers/Microsoft.Authorization/policyDefinitions/Deploy-Log-Analytics' could not be found.\"\r\n  }\r\n}"
            },
            {
                "code": "NotFound",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy definition 'Deploy-Log-Analytics' could not be found.\"\r\n  }\r\n}"
            }
        ]
    }
}
```

**Comment by krnese** [comment]
The first issue where the RP is not registered is a race condition. When you create resources, ARM should implicitly also register the RP. In your case that didn’t happen before the resourceType creation was attempted.

the second issue is a known issue and documented under “known issues” in this repository, also related to backend replication latency that sometimes can occur depending on the region you deploy to.

if you re-deploy with same input parameters, it should work

**Comment by doherty100** [comment]
@krnese thanks and love the picture from high school LoL.
