### ISSUE TITLE
How to deploy changing platform components

### ISSUE THREAD

**Issue by Lycrosa** [Azure/Enterprise-Scale#551]
Hey we are trying to use the enterprise scale approach and are running into issues with resources that are changing. We are deploying every platform component via Azure Policy. This includes resources like Firewall Policies, DNS Server VMs and so on. In order to change those resources, the policies need to have a "complex" condition, that makes a policy assignment not compliant and "remediatable" in order to apply the new changes. This seems like a lot of effort. 
Is this the way the enterprise scale apporach wants to handle changing platform resources or did we missunderstand something and there is a "cleaner" more "straight forward" approach?

Regards

**Comment by Lycrosa** [comment]
Hey, is there any recommendation for this?

**Comment by krnese** [comment]
Thanks for submitting this issue. Can you please elaborate on 'deploying every platform component via Azure policy - which includes DNS Server VMs"?

**Comment by Lycrosa** [comment]
Hey Kristian, for example we deploy our DNS Server VMs via Azure Policy (deployIfNotExists). If we wanna change the size of the VM we have to change the policy (have a condition that checks for the vm size and change the vm size in the policy definition/assignment) and then run a remediation task. This process seems to complex to me. I hope this helps you understanding my point

**Comment by krnese** [comment]
We have added a new section to our FAQ where we aim to clarify how and where to use a Policy Driven Governance approach. Can you see if this helps? https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-FAQ.md#are-we-supposed-to-use-azure-policy-for-workload-deployments
