### ISSUE TITLE
Question regarding separation of Stages / Environment

### ISSUE THREAD

**Issue by J0F3** [Azure/Enterprise-Scale#56]
Hi,

First of all: Awesome work! I think the templates and the documentation are really useful and answer a lot of questions organizations may have while starting to use Azure. 👍 

During studying the [Contoso Reference](https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md) documentation I got a question regarding separation of stages or environments like Dev, PreProd, Prod, etc.. Especially for the Platform Subscriptions and Resources you may want to have a Prod and at least one other Non-Prod setup where you can test out changes first. 
For example if you need to makes changes to resources in the connectivity subscription you may test the connectivity changes first in an non-prod setup. Are such things intended and if yes how? 
Or is this maybe more a concept / way of thinking from on-perm which is not really applicable anymore in the cloud context?

Thank you!
Jonas

**Comment by hjscherer** [comment]
Yes, we have seen customer building out platform staging environments. Various requirements driving this and customer have  chosen different approaches how to segregate environements. The implementation usualy depends on security and compliance requirements. This topic is also covered across the eight critical desgin areas of Enterprise-Scale.

**Comment by hjscherer** [comment]
@J0F3 does this answer your question. If yes, then I would suggest that we close this issue.

**Comment by J0F3** [comment]
@hjscherer Sorry for not answering back. Yes, I think it does. Thank you. 
I also saw in the meantime that the in the Contoso Reference it states also:

> The default root Management Group will not be used directly, allowing for greater flexibility in the future to incorporate an equivalent test environment for their end-to-end Azure architecture

So close please. 😊

**Comment by hjscherer** [comment]
Perfect thank you.
