### ISSUE TITLE
Bug Report - Deploy Vnet policy

### ISSUE THREAD

**Issue by extmaper** [Azure/Enterprise-Scale#561]
**Describe the bug**
When using Deploy-Vnet (vWAN version) policy definition assigned at subscription level the following problems is noted

- Condition targets **"field": "Microsoft.Network/virtualNetworks/virtualNetworkPeerings[*].remoteVirtualNetwork.id",  "exists": true** which will set the policy as compliant if there are other vnets in the same subscription that also is configured with vnet connection.

- When doing remediation on policy that is configured with subnets, the subnets are being deleted if empty. If subnet have resources the remediation fails.

**Steps to reproduce**

1. Assign policy
2. Verify that resources are created
3. Change values to make policy non-compliant
4. Run remediation task or re-run the deployment

**Screenshots**

**Comment by daltondhcp** [comment]
Thank you for submitting the issue, we will investigate and update when we have more info.

**Comment by daltondhcp** [comment]
Closing this as the first one was a false positive and the second issue is a 'known issue' with the Network Resource Provider.
