### ISSUE TITLE
Feature Request - RG Budgets

### ISSUE THREAD

**Issue by frehnejc** [Azure/Enterprise-Scale#563]
There is a Policy "Deploy a default budget on subscriptions" to enforce budgets on a Subscription, however it would be nice to enforce budgets on RG's.

**Comment by krnese** [comment]
Thanks for submitting this request. Can you tell us a bit more on why having this on the RG would be preferred? In context of Enterprise-Scale, the landing zone is the subscription, so the subscription is the unit of cost, management, etc. Would love to learn more about the scenario and if this is mandated from the platform, or if the ask is for the application team to put this in place for their own usage.

**Comment by frehnejc** [comment]
Many smaller organisations such as Trey Research have dev teams or outsourced teams that need to report on and manage cost for small projects, traditionally the projects will be in a RG.

**Comment by krnese** [comment]
We have reviewed this ask, and decided that we will not ship policy for RG budgets as this primarily violates the design principles of enterprise-scale, as the application teams should be empowered to manage this themselves, and not be enforced centrally per subscription ->rg level from platform perspective. 

Also note that cost management is quite flexible from a reporting perspective, so you can compose the view as you want per mg, sub, rgs, tags etc., to get the full view of usage subject to the RBAC permission you have.
