### ISSUE TITLE
We are running the ARM Templates; however API fetches only 50 subscription

### ISSUE THREAD

**Issue by nitangulati** [Azure/Enterprise-Scale#564]
We are running the ARM Templates; however API fetches only 50 subscription and for your information we have more than 100 subscriptions and hence the request.

![image](https://user-images.githubusercontent.com/84068360/117940638-e6f6df80-b326-11eb-8001-906a81571c5b.png)

**Steps to reproduce**

1.
2.

**Screenshots**

![apiscreenshot](https://user-images.githubusercontent.com/84068360/117940603-dba3b400-b326-11eb-8726-873a365bdf2e.png)

**Comment by krnese** [comment]
We have added this into our FAQ - pls see if this workaround helps: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-FAQ.md#enterprise-scale-deployment-ux-do-not-display-all-subscriptions-in-subscription-picker-drop-down-list

**Comment by nitangulati** [comment]
+ Neelam.

Regards,
Nitan Gulati | Group Manager | Evalueserve | + 91 124 462 2300 (Extn. 1371)

Evalueserve.com Private Limited,Tower 6, 7th Floor, Candor Gurgaon One Realty Projects Pvt. Ltd., IT/ITES SEZ, Candor TechSpace, Tikri Sector-48, Gurugram-122001, Haryana, India

**Comment by krnese** [comment]
Update: We have a fix for this issue, and we aim to push the changes either end of this week or early next week. So until it's ready, pls use the workaround that we have documented.

**Comment by nitangulati** [comment]
Sure thanks.

Regards,
Nitan Gulati | Group Manager | Evalueserve | + 91 124 462 2300 (Extn. 1371)

Evalueserve.com Private Limited,Tower 6, 7th Floor, Candor Gurgaon One Realty Projects Pvt. Ltd., IT/ITES SEZ, Candor TechSpace, Tikri Sector-48, Gurugram-122001, Haryana, India
