### ISSUE TITLE
Missing documentation on discovery of current Azure environment

### ISSUE THREAD

**Issue by vidyann** [Azure/Enterprise-Scale#566]
**Describe the bug**
This page https://github.com/azure/azops/wiki/deployments has a section "How to deploy ARM templates with AzOps" with a link to "Initialize Git With Current Azure configuration"  ( https://github.com/azure/azops/wiki/discover-environment.md ) . This link is empty. Please put in the right link in case the capability exists. 

**Steps to reproduce**

1. Go to the page https://github.com/azure/azops/wiki/deployments
2. Click on the link to Initialize Git With Current Azure configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/5483637/118114173-dd43a980-b404-11eb-9b61-2e4a776dc5ae.png)

**Comment by FallenHoot** [comment]
Should this be closed? To focus on https://github.com/Azure/Enterprise-Scale/wiki
@ljtill or are we still updating the wiki on AzOps?

**Comment by jtracey93** [comment]
Hi @FallenHoot,

The AzOps repo wiki is being updated and used so this is still valid 👍 

Thanks

**Comment by jtracey93** [comment]
This has been resolved in latest Wiki updates over past few months in AzOps Wiki https://github.com/azure/azops/wiki
