### ISSUE TITLE
New Subscriptions are not getting listed while deploying ES-LZ

### ISSUE THREAD

**Issue by melwinlawrance** [Azure/Enterprise-Scale#571]
**Describe the bug**

Subscriptions (Management, Identity, Connectivity) that are created for deploying ES-LZ is not able to list in the drop-down when deploying the template. None of the 3 subscriptions are available in the drop-down list to choose from. 

I have Global Admin access in the tenant and I have owner access to all three subscriptions. 

**Steps to reproduce**

1. Create a new subscription in EA and try to select that subscription for deploying ES-LZ.
2.

**Screenshots**

**Comment by krnese** [comment]
The subscription picker has a limit of 50 subscriptions, so pls see the workaround described here and let me know if that helps: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-FAQ.md#enterprise-scale-landing-zones-deployment-ux-do-not-display-all-subscriptions-in-subscription-picker-drop-down-list
