### ISSUE TITLE
Provide networking details for hub and spoke

### ISSUE THREAD

**Issue by victorar** [Azure/Enterprise-Scale#573]
The enterprise-scale landing zones reference implementation for a hub and spoke network topology does not provide networking details about how a hub and spoke network topology looks like, and how this is enabled via shared resources in the hub such as ExpressRoute/VPN gateways, gateway transit property in VNet peering and transitive connectivity across spokes via NVA in the hub.

The following articles should be updated to reflect this.

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/implementation > Here provide a link/short description to hub and spoke network topology.

https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md > Here provide a short description with a diagram of key components of a hub and spoke network topology.

**Comment by jtracey93** [comment]
PR Created to update CAF docs with links to Hub/Spoke & VWAN architectures.

Will start work on diagrams in RIs soon.

**Comment by jtracey93** [comment]
Closing issue as CAF docs PR also now merged and rolling out. RI also updated
