### ISSUE TITLE
Bicep ESLZ Modules

### ISSUE THREAD

**Issue by krnese** [Azure/Enterprise-Scale#579]
**Describe the solution you'd like**
* Provide generic Bicep files to build out Enterprise-Scale architecture yourself, where the user can use the files and sequence them on their own, at their own pace
* Provide documentation and deployment instructions (PS, CLI)

**Comment by pazdedav** [comment]
Is this something you would like help with, @krnese?

**Comment by SenthuranSivananthan** [comment]
> Is this something you would like help with, @krnese?

Happy to start helping with the Bicep versions as well @krnese.  Are you tracking individual work items for the components.

**Comment by krnese** [comment]
Thanks for the support! We will flush out the details shortly and update this item with the goal state and work required.

**Comment by DaFitRobsta** [comment]
Maybe this is a different issue or request; I'd like the ability to use bicep files in AzOps.

**Comment by jtracey93** [comment]
Hi @DaFitRobsta,

We added support to deploy Bicep files in AzOps a couple of weeks ago in release [v1.2.0](https://github.com/Azure/AzOps/releases/tag/1.2.0) 👍 

Is this what your were looking for?

**Comment by DaFitRobsta** [comment]
Yes and thank you!!!!

Robert Lightner

**Comment by DaFitRobsta** [comment]
What is the naming format for the parameters file?

For example:
Foobar.bicep
Foobar.parameters.json

Robert Lightner

**Comment by jtracey93** [comment]
@ljtill Could you advise on the above for Bicep files in AzOps?

**Comment by khushal08** [comment]
@ljtill Are we converting the exiting ARM based policies to bicep?

**Comment by ljtill** [comment]
> @ljtill Lyon Till FTE Could you advise on the above for Bicep files in AzOps?

@daltondhcp Can you advise on the implementation?

**Comment by ljtill** [comment]
> @ljtill Lyon Till FTE Are we converting the exiting ARM based policies to bicep?

@krnese Can you advise?

**Comment by daltondhcp** [comment]
> > @ljtill Could you advise on the above for Bicep files in AzOps?
> 
> @daltondhcp Can you advise on the implementation?

Sorry for the late reply @DaFitRobsta - if you haven't tested it yet, we follow that exact convention for parameter files in combination with bicep. (see example below) 
![image](https://user-images.githubusercontent.com/16622613/127287881-57e832cf-3945-402a-95a0-c97a5873352e.png)

**Comment by jtracey93** [comment]
Just an update on this. We have begun the work on bicep templates for ESLZ. 

Watch this space. But we expect to have something ready in September if all goes to plan.

**Comment by jtracey93** [comment]
Hey everyone,

Just an update here is that we are now targeting closer to an October release for Bicep ESLZ, but hopefully sooner 👍

Thanks

Jack

**Comment by jordanenglish** [comment]
Hi @jtracey93 - any update on Bicep for ESLZ?

**Comment by jtracey93** [comment]
Hey @jordanenglish we are very close. Just got some internal reviews etc to finish. 

Tune into the community call next week #803 where I'll be showing it off in a small demo 👍

**Comment by jtracey93** [comment]
Hey all, just an update here on Bicep.

We are just finishing up a few key pieces before we can release a "public preview" stay tuned and it should be out by the end of this year! 👍👍

**Comment by Schillman** [comment]
Hello everyone hope you all have had a great beginning to the new year 🎉
I'm wondering if we have any news around this topic?

**Comment by jtracey93** [comment]
Hey @Schillman,

We unfortunately found a few bugs in ARM & Bicep that have delayed us.

However, we met as a team last night and have agreed a path forward to Public Preview launch end of January/start of February.

We just have some tidying up to do and we will be able to release it to the world 👍

Stay tuned!

**Comment by dani3lheidemann** [comment]
Hi @jtracey93,
thanks for all this effort! Can you give us an update on this? 
Thank you!

**Comment by jtracey93** [comment]
Keep an eye out for later today 👍

**Comment by tcrevel** [comment]
@jtracey93 Geat! 
Missing a bicep emoji to like this breaking news ❤️

**Comment by jtracey93** [comment]
And we are live: https://github.com/Azure/ALZ-Bicep 🥳🥳🥳🥳🥳🥳🥳

> I will close this issue now as we can track on the other repo for Bicep 👍
