### ISSUE TITLE
Bug Report for Policy 'Deploy-Diagnostics-EventGridSub'

### ISSUE THREAD

**Issue by GitHubUser1339** [Azure/Enterprise-Scale#588]
**Describe the bug**
Policy evaluation of 'Deploy-Diagnostics-EventGridSub' policy results in non-compliant resources with status 'Not Found' or 'Bad Request'. Out of 3 'test' EventGrid Subscription resources with different Topics (SA, Subscr, RG) only one is reported by the policy.

It's unclear whether resource type 'Microsoft.EventGrid/eventSubscriptions' supports diagnostics settings, or whether these are 'inherited' from the topics resource.

**Steps to reproduce**

1. Create EventGrid Subscription
2. Assign policy at proper scope
3.  Run evaluation

**Screenshots**
![image](https://user-images.githubusercontent.com/17045753/119492237-1e21b380-bd5f-11eb-96e6-40db373d0626.png)

![image](https://user-images.githubusercontent.com/17045753/119492286-2c6fcf80-bd5f-11eb-886c-533e0e4eb84e.png)

**Comment by MathieuRietman** [comment]
@GitHubUser1339 not able to reproduce the error, what is the exact deployment.

**Comment by jtracey93** [comment]
Closing as no response
