### ISSUE TITLE
Bug Report - Key Vault Soft Delete marked as non-compliant

### ISSUE THREAD

**Issue by liamfoneill** [Azure/Enterprise-Scale#59]
**Describe the bug**
Append Key Vault Soft Delete policy does enable soft delete when you deploy a key vault with it disabled. However the policy still marks key vaults as not in compliance, despite the policy enabling soft delete.

**Steps to reproduce**

1. Assign Append Key Vault Soft Delete Policy
2. Deploy a key vault with soft delete explicitly disabled
3. Once Key Vault is deployed, check if soft delete is enabled (it should be)
4. Run 'Start-AzPolicyComplianceScan' to refresh policy compliance.

**Screenshots**
![image](https://user-images.githubusercontent.com/1243172/86588258-4c4da780-bf83-11ea-962a-f3813995302f.png)
![image](https://user-images.githubusercontent.com/1243172/86588279-52438880-bf83-11ea-8399-c4f00b391ff2.png)
![image](https://user-images.githubusercontent.com/1243172/86588311-6091a480-bf83-11ea-8798-6bd584aa8c65.png)
![image](https://user-images.githubusercontent.com/1243172/86588343-6edfc080-bf83-11ea-9216-062335b8b27f.png)

**Comment by daltondhcp** [comment]
Thanks for reporting @liamfoneill - this will be fixed in the next policy refresh.
