### ISSUE TITLE
ESLZ-Polices filtered by Policy `Category`

### ISSUE THREAD

**Issue by FallenHoot** [Azure/Enterprise-Scale#596]
Since MD can't filter the columns, it would be great to have it filtered by Policy `Category`. This field is also missing. 
https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md#eslz-custom-policy-definitions

**Comment by hjscherer** [comment]
@FallenHoot thank you for submitting your request. We'll consider this in our next update cycle. In the meantime, please feel free to make a PR directly.
