### ISSUE TITLE
Exclude AzureBastionSubnet from policy that enforces UDR

### ISSUE THREAD

**Issue by victorar** [Azure/Enterprise-Scale#604]
User Defined Routing (UDR) is not supported on Azure Bastion subnet (AzureBastionSubnet). Thus, we need to have the capability to not enforce this policy if the subnet is called AzureBastionSubnet.

**Comment by jtracey93** [comment]
Have created PR to add this capability 👍

**Comment by jtracey93** [comment]
Closing as PR merged will follow same pattern for #456 shortly
