### ISSUE TITLE
Enterprise Scale deployment to private enterprise github with self hosted runners

### ISSUE THREAD

**Issue by vivek99singh** [Azure/Enterprise-Scale#612]
**Describe the bug**
I am tying to implement Enterprise Scale with self hosted runners in github as in private enterprise github you cannot have github managed runners.
Changed the pull.yml to have step of **runs-on: self-hosted** instead of  runs-on: ubuntu-20.04.
Now when running the workflow it fails with the below error in the dependencies step:
Run Install-Module -Name "AzOps" -Force
Error:File not found: 'pwsh'

**Steps to reproduce**

1. Install linux self hosted runner in Github using the link https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
2.change the pull.yml to have self hosted runner.
3.Execute pull.yml you will get the error

**Screenshots**
![image](https://user-images.githubusercontent.com/42897444/121381571-81f6cf80-c94e-11eb-8ba2-d7c5a5f018ef.png)

**Comment by ljtill** [comment]
Thanks for opening this issue @vivek99singh. Can you check that PowerShell (7.0+) is installed on the runner?
In the meantime, give me a few days and I'll write up the configuration guide for self-hosted runners with AzOps.

**Comment by vivek99singh** [comment]
Yes I got it resolved by getting JQ and Powershell Installed on a Self
hosted runner. It will be great if we can get some documentation for
configuration of self hosted for github enterprise.

**Comment by daltondhcp** [comment]
Thanks for confirming, @vivek99singh. 
We will add this to our backlog.
