### ISSUE TITLE
How to assign a role using policy?

### ISSUE THREAD

**Issue by Jedoe830** [Azure/Enterprise-Scale#621]
We want to assign the role "Virtual Machine Administrator Login" to a group. So we created a role assignment on management group scope successfully. The role is visible in the portal for the group. However, the role doesn't work on management group level (Error when signing in to vm). Doing so the same way on subscription level works completely. So we want to assign this role on every subscription using a policy. Unfortunately, with the code below Azure just creates an App with the name of the policy and assigns the role to this app. How do we setup this correctly?

Policy Assignment
`{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "input": {
      "value": {
        "Identity": {
          "type": "SystemAssigned"
        },
        "Location": "westeurope",
        "Name": "Deploy-VM-Login",
        "PolicyAssignmentId": "/providers/Microsoft.Management/managementGroups/pcp/providers/Microsoft.Authorization/policyAssignments/Deploy-VM-Login",
        "Properties": {
          "Description": "Deploy-VM-Login",
          "DisplayName": "Deploy-VM-Login",
          "NotScopes": null,
          "Parameters": {},
          "PolicyDefinitionId": "/providers/Microsoft.Management/managementGroups/pcp/providers/Microsoft.Authorization/policyDefinitions/Deploy-VM-Login",
          "Scope": "/providers/Microsoft.Management/managementGroups/pcp"
        },
        "ResourceType": "Microsoft.Authorization/policyAssignments"
      }
    }
  }
}
`

PolicyDefinition:
`{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "input": {
      "value": {
        "Name": "Deploy-VM-Login",
        "ResourceId": "/providers/Microsoft.Management/managementGroups/pcp/providers/Microsoft.Authorization/policyDefinitions/Deploy-VM-Login",
        "ResourceName": "Deploy-VM-Login",
        "ResourceType": "Microsoft.Authorization/policyDefinitions",
        "SubscriptionId": null,
        "PolicyDefinitionId": "/providers/Microsoft.Management/managementGroups/pcp/providers/Microsoft.Authorization/policyDefinitions/Deploy-VM-Login",
        "Properties": {
          "Description": null,
          "DisplayName": null,
          "Mode": "All",
          "Parameters": {},
          "PolicyRule": {
            "if": {
              "allOf": [
                {
                  "field": "type",
                  "equals": "Microsoft.Resources/subscriptions"
                }
              ]
            },
            "then": {
              "effect": "deployIfNotExists",
              "details": {
                "type": "Microsoft.Authorization/roleAssignments",
                "deploymentScope": "subscription",
                "existenceScope": "subscription",
                "roleDefinitionIds": [
                  "/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4"
                ],
                "deployment": {
                  "location": "westeurope",
                  "properties": {
                    "mode": "incremental",
                    "parameters": {},
                    "template": {
                      "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                      "contentVersion": "1.0.0.0",
                      "parameters": {},
                      "variables": {},
                      "resources": [
                        {
                          "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
                          "contentVersion": "1.0.0.0",
                          "parameters": {
                            "input": {
                              "value": {
                                "Id": "/providers/Microsoft.Management/managementGroups/pcp/providers/Microsoft.Authorization/roleAssignments/1f716500-5ec5-5167-8792-e856cf13cd2a",
                                "Name": "1f716500-5ec5-5167-8792-e856cf13cd2a",
                                "properties": {
                                  "DisplayName": "Deploy-VM-Monitoring",
                                  "ObjectType": "ServicePrincipal",
                                  "PrincipalId": "b819711f-b15d-4330-8a84-263f3760812a",
                                  "RoleDefinitionId": "/providers/Microsoft.Authorization/RoleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635",
                                  "RoleDefinitionName": "Owner"
                                },
                                "ResourceType": "Microsoft.Authorization/roleAssignments"
                              }
                            }
                          }
                        }                        
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
`
Result:
![image](https://user-images.githubusercontent.com/73531562/122125535-e0c9b680-ce30-11eb-99ec-bfdbfba70279.png)

**Comment by krnese** [comment]
It can take approx 30 minutes or so for the RBAC at management group to propagate to the child subscriptions. Can you check if this is the case here?

**Comment by Jedoe830** [comment]
This is not the case. The main problem is that an AD App is created which gets the role, nothing happens to the AD group specified in the role assignment.

**Comment by krnese** [comment]
I'd recommend to open a support case on this one so we can investigate what is happening, and not use Azure Policy to make roleAssignments per subscription.

**Comment by daltondhcp** [comment]
Hope that this has now been resolved. Closing as this is not related to any of the artifacts in Enterprise-Scale.
