### ISSUE TITLE
Best PRactice Check fail for Enterprise VWAN

### ISSUE THREAD

**Issue by JustinGrote** [Azure/Enterprise-Scale#638]
Not very confidence-inspiring...
![image](https://user-images.githubusercontent.com/15258962/123181528-51c92980-d442-11eb-9c33-0d77e759aa1c.png)

**Comment by synapp** [comment]
Thanks for posting this. I noticed yesterday, but such a noob wanted to research a bit.

... Watching

**Comment by jtracey93** [comment]
Thanks for raising this. I have created a PR to remove this badge from all reference implementations as it actually wasn't valid and is from a very early commit to this repo.

Thanks

Jack
