### ISSUE TITLE
Develop prescriptive DevOps guidance

### ISSUE THREAD

**Issue by segraef** [Azure/Enterprise-Scale#646]
<p>Define/develop model for roles &amp; responsibilities (corporate, as well as AD/AAD/RBAC) of how different teams (such as Platform/Net/Sec/DevOps) use third-party tools and define structure in a multi-tenant, and/or multi-stage (dev/test/prod) environment. Integrate security practices and tool chains. </p>
<p>@matebarabas, @pagyP, @MSFTWJONES  </p>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by jtracey93** [comment]
This now exists in CAF under the platform automation and DevOps design area
