### ISSUE TITLE
Feature Request: Allow Active/Active VPN Gateway Configuration

### ISSUE THREAD

**Issue by chrisking81** [Azure/Enterprise-Scale#655]
<p><strong>Describe the solution you'd like</strong> </p>
<p>At deployment time of the reference implementation, can we please have the choice to deploy the VPN Gateway in Active/Active mode with a secondary public IP? </p>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by JefferyMitchell** [comment]
@jtracey93 Closing this issue and changes is merged! 
https://github.com/Azure/Enterprise-Scale/pull/1415

Thank you for the feedback @chrisking81
