### ISSUE TITLE
Ability to sync previously 'click to deploy' environments with the latest policy updates and fixes

### ISSUE THREAD

**Issue by paulgrimley** [Azure/Enterprise-Scale#662]
<p>As Enterprise Scale becomes established, consumers of the click to deploy solution will start to see their policies age against an ever changing ESLZ repo where bug fixes and enhancements occur. It would be very useful to have guidance on how to update these environments to maintain the latest updates and guidance on how these should be applied and tested against the current implementation with things to consider. </p>

**Comment by KerryARoss** [comment]
@jtracey93  what is the estimated time frame for this issue resolution? This would be a very helpful feature

**Comment by jtracey93** [comment]
Hey @KerryARoss,

This is still under review at this moment. But I would hope to have something available in the next month or so.

Keep and eye on the "what's new?" page https://aka.ms/es/whatsnew 

Thanks

Jack

**Comment by jtracey93** [comment]
@KerryARoss 

Could you reply in the comments here with some further clarity on the expectations/guidance you are looking for here to ensure we cover the scenarios 👍  

We have been discussing this internally and feel this leans more towards just the policy side of ESLZ rather than the other components. But would love your feedback 👍

Let me know 😃

**Comment by KerryARoss** [comment]
“It would also be helpful to sync the AzOps integrated CI/CD solution with the latest updates and fixes.”

**Comment by jsandquist** [comment]
> “It would also be helpful to sync the AzOps integrated CI/CD solution with the latest updates and fixes.”

Maybe I misinterpret this, but isn't this supported already by the 'update' workflow/pipeline?

**Comment by jtracey93** [comment]
> > “It would also be helpful to sync the AzOps integrated CI/CD solution with the latest updates and fixes.”
> 
> Maybe I misinterpret this, but isn't this supported already by the 'update' workflow/pipeline?

I think this only updates the AzOps tooling rather than the implementation.

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by paulgrimley** [comment]
I'm pleased to confirm that we can now close this issue and guidance is now available to address this aka.ms/alz/update
