### ISSUE TITLE
Reference implementations fail to deploy using default parameter values

### ISSUE THREAD

**Issue by JimPaine** [Azure/Enterprise-Scale#671]
When deploying `Trey Research` implementation from the cli using the default values for the parameters the deployment fails with an error of `resource group not found`

**Steps to reproduce**

1. Create params file with default values populated
2. Override required items, such as `enterpriseScaleCompanyPrefix` and subscriptions ids
3. deploy from cli

```
...

az deployment tenant create \
  --name "$name" \
  --template-spec "$id" \
  --parameters \
    @deploy.parameters.json \
    enterpriseScaleCompanyPrefix="$company_prefix" \
    location="$location" \
    platformSubscriptionId="$platformSubscriptionId" \
    onlineLzSubscriptionId="[\"${onlineLzSubscriptionIds[*]// /\",\"}\"]" \
    corpLzSubscriptionId="[\"${corpLzSubscriptionIds[*]// /\",\"}\"]" \
    subscriptionSecurityConfigTemplateId="$subscriptionSecurityConfigId" \
  --location "$location" \
  --debug
```

**Expected outcome**

Deployment successful

**Actual outcome**

Failed deployment

```json
{
  "status": "Failed",
  "error": {
      "code": "DeploymentFailed",
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
      "details": [{
          "code": "Conflict",
          "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"NotFound\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceGroupNotFound\\\",\\r\\n    \\\"message\\\": \\\"Resource group 'myroot-mgmt' could not be found.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"
       }]
   }
}
```

**Additional details**

After some initial investigation it appears this is due to the default flag for enabling log analytics is set to `No` and the nested deployment in `logAnalytics.json` contains the creation of the resource group mentioned in the error. Overriding the default value to `Yes` and running the deployment again allows the deployment to be successful. I haven't had a chance to properly look into which resources are dependent on the resource group and log analytics, but it looks like it is potentially the solutions and some policies, but this would need to be investigated futher.

**Comment by daltondhcp** [comment]
As written in our [FAQ ](https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-FAQ.md#can-we-take-the-arm-templates-for-enterprise-scale-reference-implementations-and-check-them-into-our-repository-and-deploy-it-from-there-instead-of-via-the-azure-portal), all ARM templates for the Enterprise-Scale Landing Zones reference implementations are developed for - and optimized for a curated self-service deployment experience in the Azure portal. We do not recommend nor support customization of these templates at this time.

However, as per #578,  we are working on shipping composite ARM and Bicep templates that can be used to deploy the reference implementations in smaller chunks, with any client.
