### ISSUE TITLE
Provide prescriptive guidance on use of Private Hosted Agents for DevOps

### ISSUE THREAD

**Issue by paulgrimley** [Azure/Enterprise-Scale#675]
<p>There is a preference from certain customers / industries to use Private Hosted Agents for DevOps. Seeking guidance from the ES documentation to provide a recommendation for the placement of these to include: </p>
<ul>
<li>Azure Management Group location recommendations </li>
<li>Security of Private Hosted Agents </li>
<li>ACI vs VMSS </li>
<li>Agent pool recommendations (single shared vs multiple pools) </li>
</ul>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2
