### ISSUE TITLE
Bug Report - User has root root level access but unable to deploy wingtip template

### ISSUE THREAD

**Issue by onlyutkarsh** [Azure/Enterprise-Scale#69]
**Describe the bug**
User has `User Access Administrator` role and has root-level scope. Verified using azure cli command
```
az role assignment list --role "User Access Administrator" --scope "/"
```
![image](https://user-images.githubusercontent.com/2685029/87679815-8a617d00-c774-11ea-86c5-d8bb188a8940.png)

Verified the permission also in the portal (See `Image 5` below)

But when we click `Deploy to Azure` button from [this page](https://github.com/Azure/Enterprise-Scale/tree/main/docs/reference/wingtip) validation fails with below error

`
The client 'utkarsh@xxxxxx.onmicrosoft.com' with object id '<GUID-xxxxx-xxxxx-xxxxx-xxxx>' does not have authorization to perform action 'Microsoft.Resources/deployments/validate/action' over scope '/providers/Microsoft.Resources/deployments/Microsoft.Template-20200716144824' or the scope is invalid. If access was recently granted, please refresh your credentials.
`

**Steps to reproduce**

1. Providing user with root level access
2. Verify in the portal and also via Azure CLI
3. Go to https://github.com/Azure/Enterprise-Scale/tree/main/docs/reference/wingtip and click `Deploy to Azure`
4. Select UK South (See `Image 1` below)
5. Provide the prefix `xyz` and leave `Enable management subscription` empty. (See `Image 2` below)
6. Leave selection to `Foundation` in the next screen (See `Image 3` below)
7. Select `Enable Resource Deployments` to `No` in the next screen
8. Get the error (See `Image 4` below)

**Screenshots**
- **Image 1**
![image](https://user-images.githubusercontent.com/2685029/87680780-bfba9a80-c775-11ea-9d1d-565545143884.png)

- **Image 2**
![image](https://user-images.githubusercontent.com/2685029/87680940-f09acf80-c775-11ea-811c-50db81316525.png)

- **Image 3**
![image](https://user-images.githubusercontent.com/2685029/87681253-643cdc80-c776-11ea-9d2d-818e2cb9166e.png)

- **Image 4**
![image](https://user-images.githubusercontent.com/2685029/87681601-bb42b180-c776-11ea-9d2a-97b7cbe65bc1.png)

- **Image 5**
![image](https://user-images.githubusercontent.com/2685029/87680423-53d83200-c775-11ea-9097-410d9784cde8.png)

**Comment by onlyutkarsh** [comment]
Thanks for your response. It has been more than 3-4 hours that the user had this permission. Have tried logging off and logging back in and also in incognito mode. Still fails.

**Comment by azMantas** [comment]
My bet is that owner role could fix the trouble.

**Comment by uday31in** [comment]
can you please confirm that you have granted "Owner" permission as documented in step 4. 

Use and/or SPN will require Owner permission for deployment. In order to grant Owner permission, you would require to elevate to UAA.

https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/setup-github.md

![image](https://user-images.githubusercontent.com/14359777/87688519-f9dc6a00-c77e-11ea-9544-3d687b80374c.png)

**Comment by onlyutkarsh** [comment]
> My bet is that owner role could fix the trouble.

Thanks! That was the problem. Assigned the "Owner" role and now validation passes! Closing the issue.
