### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by rkuehfus** [Azure/Enterprise-Scale#70]
I also noticed for following warning on disabled subscriptions (attached)

<img width="1464" alt="Warning message for disabled subs" src="https://user-images.githubusercontent.com/17836524/87683267-d8638a00-c74e-11ea-85a7-52d24d8fcbfc.png">
We should provide a better message that explains these are disabled?

**Comment by daltondhcp** [comment]
The method for subscription exclusion as well as the output that is returned has now been changed as per https://github.com/Azure/AzOps/pull/98 and https://github.com/Azure/AzOps/pull/99
