### ISSUE TITLE
Create Workload Agnostic Scenario with ES RIs and IaCS Landing Zone Workloads

### ISSUE THREAD

**Issue by segraef** [Azure/Enterprise-Scale#700]
Elaborate and develop several combined (ES RIs + IaCS for LZ Workloads) solution approaches like developing quickstarts / RIs with or without AzOps and IaCS Modules (ARM via TemplateSpecs, Artifacts, etc.).

@segraef, @johansciard, @ShantnuS

**Comment by krnese** [comment]
We have recently converged the reference implementations to 1 single, with all the options. Can you elaborate a bit on what several 'ES RIs + IaCS for LZ workloads' means in this context?

**Comment by segraef** [comment]
Hey @krnese feel free to ignore this Issue since I was just coming up with ideas and tried to set this up as an item. I will rather look into the eslzArm parts anyway, Thanks!
