### ISSUE TITLE
Enhance guidance on how to deploy LZ VNets connected to vWAN hub

### ISSUE THREAD

**Issue by daltondhcp** [Azure/Enterprise-Scale#702]
<ul><li>Recommended approach to create vNET and connect it to vWAN hub </li><li>Policy vs ARM templates </li><li>Caveat with concurrency </li> </ul>
<div><a href="https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/deploy-lz-vnet.md" style="">Enterprise-Scale/deploy-lz-vnet.md at main · Azure/Enterprise-Scale (github.com)</a><br> </div>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by JefferyMitchell** [comment]
Please review the documentation on Subscription Vending 
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/subscription-vending#configure-networking
