### ISSUE TITLE
Azure Bastion in ESLZ

### ISSUE THREAD

**Issue by victorar** [Azure/Enterprise-Scale#703]
Provide prescriptive guidance for Azure Bastion in Enterprise-Scale landing zones. This should include architectural guidance in ESLZ documentation.

**Comment by matsest** [comment]
Would be a nice addition to ESLZ guidance, especially considering the latest improvements on Azure Bastion Standard SKU.

**Comment by victorar** [comment]
Hi @matsest , thanks for your comment. Certainly this is in our backlog and will be including such guidance shortly.

**Comment by davidkarlsen** [comment]
I'm a bit confused between the different azure tf modules.
You have a lot in this org: https://github.com/aztfmod/terraform-azurerm-caf - but then there are a lot of the same (and overlapping) modules in this azure org - which one will continue to live?

**Comment by victorar** [comment]
Hi @krowlandson, can you comment on @davidkarlsen question above? Thanks.

**Comment by krowlandson** [comment]
@davidkarlsen, the official module for Enterprise-scale is the [Azure/caf-enterprise-scale](https://registry.terraform.io/modules/Azure/caf-enterprise-scale/azurerm/latest) module.

However the [Microsoft] team responsible for the [aztfmod](https://registry.terraform.io/namespaces/aztfmod) modules have integrated it into their solution so you can go with whichever approach you prefer.

The [Azure/caf-enterprise-scale](https://registry.terraform.io/modules/Azure/caf-enterprise-scale/azurerm/latest) module focuses specifically on the resources needed to manage the platform and was designed to be consumed as a standard module.

The `aztfmod` modules are more application workload focused and form part of a broader eco-system based on the [rover](https://github.com/aztfmod/rover), which provides a prescriptive way of running Terraform for Azure. [Rover](https://github.com/aztfmod/rover) handling things like `tfstate` management and a layering approach to allow pipelines to consume outputs from other `tfstate` files in a layered approach.

**Comment by jtracey93** [comment]
@davidkarlsen we also spoke about this here, https://youtu.be/Zx_gHevekm0?t=2753, on the ESLZ community call in August that may be worth a quick watch 👍

**Comment by jtracey93** [comment]
CAF Doc published https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-virtual-machine-remote-access
