### ISSUE TITLE
Review eslzArm *IaCS

### ISSUE THREAD

**Issue by segraef** [Azure/Enterprise-Scale#705]
Templates
https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslz-portal.json
https://github.com/Azure/Enterprise-Scale/tree/main/eslzArm

**Comment by daltondhcp** [comment]
Issues in here should be ideally be related to ESLZ related bugs, feature requests and engineering items. 
The above doesn't fall under any of those categories, hence, I am closing this issue.

Thank you.
