### ISSUE TITLE
Feature Request - Deny Private DNS in Landing Zone Subscriptions

### ISSUE THREAD

**Issue by edm-ms** [Azure/Enterprise-Scale#707]
<p>In line with deploying private DNS zones in the connectivity subscription to support private link we should also block the creation of privatelink.* DNS zones in the landing zone management group. </p>

**Comment by krnese** [comment]
Can we check where we are in terms of having this as built-in as part of the effort? :-) // @victorar @daltondhcp

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2
