### ISSUE TITLE
Compliant workloads (library)

### ISSUE THREAD

**Issue by krnese** [Azure/Enterprise-Scale#708]
**Describe the solution you'd like**

In order to accelerate app/workload deployments into landing zones, that are configured and compliant per the prescriptive policy driven governance principle of ESLZ for those app teams who want to take a code-first approach, we must create a library of templates that will:
* Be deployed successfully, into online and corp landing zones
  * ARM template
  * Bicep file
* Must also provide instructions how to stage the ARM template into templateSpecs 
* Assume and expect policies from ESLZ to be assigned, and honor segregation of duties (platform vs app team responsibility). I.e., a resource that needs connectivity should not include virtual networks etc in the template, but assume it exists and ask for the resourceId
* All settings must be optional, but default parameter value etc. should be per our recommendations and per policy assignments.

Example for compliant Key Vault honoring the above can be found @ https://github.com/Azure/Enterprise-Scale/tree/main/workloads/keyvault and additional templates should be added here following the same structure.

Prioritized resources:
* App Services
* Storage Account
* SQL Server and Databases
* CosmosDb
* Event Hub
* Event Grid
* AKS
* Virtual Machines (Linux, Windows)
* Virtual Machine Scale Sets (Linux, Windows)
* Service Fabric

**Comment by MrMCake** [comment]
Linking work-in-progress library at [Azure/Modules](https://github.com/Azure/Modules)

**Comment by jtracey93** [comment]
Closing this off as covered by CARML as linked in above comment https://github.com/Azure/ResourceModules
