### ISSUE TITLE
Azure vWAN Bootstrapping suggests /16 hub address range - Reappeared

### ISSUE THREAD

**Issue by paulgrimley** [Azure/Enterprise-Scale#714]
As per https://github.com/Azure/Enterprise-Scale/issues/440 where this was recently fixed it seems to have reappeared within the bootstrap deployment latest update

**Comment by jtracey93** [comment]
Thanks @paulgrimley have created PR #718 to resolve this which is under review currently by the team and hopefully will be merged soon!
