### ISSUE TITLE
Failed Deployment due to Multiple Conflicts when re-deploying Azure Enterprise 

### ISSUE THREAD

**Issue by synapp** [Azure/Enterprise-Scale#716]
Any suggestions on how to troubleshoot / overcome multiple resource deployments that failed with a Status of "Failed"? I'm redeploying the AdventureWork reference architecture after the initial failed to deploy some of the policies.

The Error on the Overview page is:

`"code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",`

All of the Details Messages from the Error Overview say the same thing.

Digging into the Operation Details for each of the Resource Deployments indicates a variety of issues:

`"details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"
            }`

`"details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidPolicyDefinitionIdUpdate\",\r\n    \"message\": \"The policy assignment 'Deploy-Resource-Diag' create request is invalid. Cannot update existing assignment's policy definition '/providers/Microsoft.Management/managementGroups/Mercury/providers/Microsoft.Authorization/policySetDefinitions/Deploy-Diag-LogAnalytics' with new policy definition '/providers/Microsoft.Management/managementGroups/Mercury/providers/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics'.\"\r\n  }\r\n}"
            }`

`"details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"
            }`

This one is particularly concerning. The error indicates that the resource is to be moved to \<NULL> location?

`"details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidLocationUpdate\",\r\n    \"message\": \"The policy assignment 'Deny-IP-forwarding' request is invalid. The existing assignment's location cannot be changed from 'eastus' to ''.\"\r\n  }\r\n}"
            }`

Thanks in advance.

**Comment by jtracey93** [comment]
Hi @synapp,

Just to confirm, could you provide the link to the "Deploy To Azure Button" you are using?

Also what was the time duration between the intial deployment and the second deployment? (dates would be great here if available?)

Finally, were all of the same options selected/entered during the deployment experiences?

**Comment by synapp** [comment]
hey @jtracey93,
[here's the url](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json) I used to initiate the Deployment.

This is the [URL that's in the delpoyment.json file](https://raw.githubusercontent.com/Azure/Enterprise-Scale/main/eslzArm/eslzArm.json)

First Deployment was on 7/26/21 the second I did today - 7/28/21. About 40 Hours between deployments.

I cannot be 100% that both deployments had all of the same options selected/entered.

**Comment by jtracey93** [comment]
Was this environment "greenfield" prior to any deployments?

And for clarity, did you do the deployment via the portal experience both times?

**Comment by synapp** [comment]
> Was this environment "greenfield" prior to any deployments?

Yes / No
This was all new Subscriptions but existing Management Groups. I had done a previous deployment with the Trey Research reference template (that one didn't go well either). With the recent changes the Enterprise-Scale team did in the project (combining the Models into one experience) I decided to blow the Subs away and start again.

> deployment via the portal experience both times?

Yes,
Deploying via the Portal.

I've opened a case with Azure Premier Support, not sure how far that will go since technically I'm deploying someone else's code. I'm open to canceling all of the subscriptions & deleting management groups if that's advised.

**Comment by krnese** [comment]
When redeploying, you cannot change the deployment location. Pls provide exact same input to the parameters and use the same location as when deploying initially.

**Comment by jtracey93** [comment]
Removing all management groups and deploying again will likely fix this as it will be greenfield again. 

However as said all the options must be set the same to deploy the same experience over the top. 

Support will assist as it's just technically an ARM deployment 👍

Let us know.

**Comment by synapp** [comment]
Just redeployed Greenfield
Deleted existing Management Groups that were created previously and used new empty Subscriptions.

Digging into the Failed Deployments, they all appear to be in the Connectivity Subscription

`{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "InternalServerError",
      "message": "An error occurred."
    }
  ]
}`

This Error is repeated 5 Times
`{
    "status": "Failed",
    "error": {
        "code": "Conflict",
        "message": "The subscription '<REDACTED - ID of the Connectivity Subscription> is not registered to use microsoft.insights."
    }
}`

Thanks in Advance. I also opened a case with Support

**Comment by krnese** [comment]
The issue you are facing is a race condition, as the Resource Provider (Microsoft.Insights) gets implicitly registered when the first diagnostic settings gets created in the subscription. If you register the Resource Provider explicitly on the subscription and re-run, it should work.

**Comment by synapp** [comment]
Thanks @krnese I'll try that.

For my edification, can you link to a reference in documentation on this how Microsoft.Insights is used. Could I have drawn this conclusion with some additional research? In a search, I found reference to Office Workspace analytics and an Outlook Plug-in.

**Comment by jtracey93** [comment]
Hi @synapp, this page should help you match resource providers to services https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-services-resource-providers#match-resource-provider-to-service.

Also, https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider

**Comment by krnese** [comment]
@synapp , circling back to see if this one got resolved per the recommendations given earlier?

**Comment by synapp** [comment]
Hey @krnese , thanks for the follow up.
Unfortunately No.

I registered Microsoft.Insights in the Connectivity Sub and redeployed over the top. There are Multiple Bad Request errors - I think root cause of those are are resources previously deployed are in a failed state. Redeploying over top does not seem to resolve those.

I worked with Support yesterday and we deployed over the top a 2nd time while capturing a HAR file. I also sent them the parameters.json & template.json. Failed once again with similar messages. They are investigating. Any chance I could connect with someone on this Team for a closer look?

**Comment by krnese** [comment]
Thanks. When you say template and parameter file, you mean the parameter file (output) that is generated by the portal, and not where you try to deploy this outside of portal context?
You can reach out to me over email (krnese at microsoft) and we can set something up to see what's going on.

**Comment by krnese** [comment]
@synapp - thanks for the call yesterday. Are you ok to close this issue now?

**Comment by synapp** [comment]
Yes sir! Thanks again for the assistance
