### ISSUE TITLE
Feature Request: ESLZ for Data / IoT / ML

### ISSUE THREAD

**Issue by kawo123** [Azure/Enterprise-Scale#717]
A lot of enterprise customers are adopting ESLZ for secure and scalable Azure deployment. Based on my understanding, the current ESLZ focuses around Azure IaaS deployment. It will be great to see similar ESLZ for Data & IoT & ML domains.

**Comment by daltondhcp** [comment]
This is absolutely something we are looking to release in the coming months. 
Stay tuned!

**Comment by marvinbuss** [comment]
Hi @kawo123,
Stay tuned. We will announce something very soon.

**Comment by daltondhcp** [comment]
@kawo123 - In case you missed it, this has now been released to the public
https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/scenarios/data-management/
https://github.com/Azure/data-management-zone/
