### ISSUE TITLE
Built-in policies DINE policies for DNSZoneGroup registration missing

### ISSUE THREAD

**Issue by pkorolo** [Azure/Enterprise-Scale#725]
<p><strong>Describe the bug</strong> </p>
<p>Custom ESLZ &quot;Configure Azure PaaS services to use private DNS zones&quot; does not work as expected; tested with storage account, although it does configure the private endpoint with the appropriate private DNS zone, it does NOT also automatically create the respective A record for the private endpoint </p>
<p><strong>Steps to reproduce</strong> </p>
<ol>
<li>Deploy ESLZ </li>
<li>create a storage account with private endpoint, and do not pre-configure it with private DNS, since the policy is supposed to do so </li>
</ol>
<p><strong>Screenshots</strong> </p>

**Comment by krnese** [comment]
@victorar /@daltondhcp - can you have a look at this when back? :-)

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by jtracey93** [comment]
Hey @pkorolo,

Just picking this back up and re-triaging. Is this effectively saying that the `Deploy-Private-DNS-Zones` ALZ Custom Policy Initiative does not contain a policy for configuring blob storage private DNS zone groups?

It doesn't look like there is a built-in so we would have to work with the storage PG to get one published or create a custom one. I checked here for all the latest built-ins https://www.azadvertizer.net/azpolicyadvertizer_all.html#%7B%22col_3%22%3A%7B%22flt%22%3A%22private%20DNS%20zones%22%7D%2C%22col_0%22%3A%7B%7D%2C%22col_8%22%3A%7B%7D%2C%22page_length%22%3A100%7D

We have also already done some gap analysis of private link supported services and whether there is a built-in private DNS zone group DINE policy.

Let us know

**Comment by pkorolo** [comment]
Hello @jtracey93 

Indeed, some months back when I was doing some testing, the custom initiative then called "Configure Azure PaaS services to use private DNS zones" (definition: /providers/Microsoft.Management/managementGroups/<alz_root_mg>/providers/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones ), which was a bundle of individual build-in policies (per-PaaS Service), did not include the respective DINE policy for (blob) storage.

Now it has been a while since then (I haven't re-deployed and tested in the interim), and maybe this is not the case anymore.
For sure back then, it was, hence if you see the thread above, Johan proposed (as interim resolution), to edit the initiative and add the missing DINE policies from the (previously existing) custom ones (as per existing documentation).

If you have a relatively recent deployment, you can check if the respective initiative now does include DINE policies for storage services' private DNS zone groups or not. 
If you don't have something handy, I will redeploy myself rather soon (by the end of the week that is), and check for myself (and let you know of course).

Hope this helps!
