### ISSUE TITLE
vnet peering not done correctly in 'Deploys virtual network peering to hub' policy

### ISSUE THREAD

**Issue by pagyP** [Azure/Enterprise-Scale#728]
**Describe the bug**
When assigning this policy the vnet peering is configured to enable gateway transit at each end of the peering.  Spoke side of the peering also has 'use remote gateway' set to false.  Result is the spoke vnet cannot use the vnet gateway in the hub virtual network

**Steps to reproduce**

1.Assign policy to relevant scope
2.Vnets are peered but each vnet has 'gateway transit' enabled.
3. Spoke vnet does not have 'use remote gateway enabled'

**Screenshots**

spoke vnet without 'use remote gateway' enabled
![image](https://user-images.githubusercontent.com/34237608/128221426-1d1f9547-e7d8-497e-9e7b-28ce6bf7da6c.png)

spoke to hub vnet peering
![image](https://user-images.githubusercontent.com/34237608/128220192-ac118049-3c08-4b22-b602-6d6bfa9edb21.png)

hub to spoke peering
![image](https://user-images.githubusercontent.com/34237608/128220280-3cf5b58c-adab-448a-a820-86b9e2c87ae0.png)

Use remote gateway set to false
![image](https://user-images.githubusercontent.com/34237608/128220439-ff7cf539-34f0-41f6-bfaf-e23ad50eb2d8.png)

![image](https://user-images.githubusercontent.com/34237608/128220525-119720ba-cbf6-40fb-ac51-6595460a3cd3.png)

I think the policy should look like this this instead:

Set use remote gateway param to true (or make param such that you have the choice of true or false at assignment time)
![image](https://user-images.githubusercontent.com/34237608/128220627-8c230643-0c34-4893-a16e-fc1a445c96ca.png)

set enable gateway transit to false at the spoke side of the peering
![image](https://user-images.githubusercontent.com/34237608/128220719-4f295402-0104-4844-ac9c-5d26f94b6235.png)

**Comment by daltondhcp** [comment]
Thank you for reporting, we will make sure to fix this in one of our coming releases!
