### ISSUE TITLE
Numerous spelling errors across content pages that could be easily fixed.

### ISSUE THREAD

**Issue by CRYP70N1X** [Azure/Enterprise-Scale#735]
<p><strong>Describe the bug</strong>
Hello, </p>
<p>I read through just about all of the content on this topic and found numerous spelling mistakes and errors. 
They are not critical but some of them make no sense and look a bit unprofessional. 
I have attached the pictures with the weblinks where they are located </p>
<p><strong>Steps to reproduce</strong> </p>
<ol>
<li>look at the links where they are located in the pictures </li>
<li>see the highlighted info in the pictures. </li>
</ol>
<p><strong>Screenshots</strong> </p>
<p><img src="https://user-images.githubusercontent.com/86801738/129113248-58d49c1d-8672-459a-b7dd-a34feeab02d7.png" alt=Snag_1cc385f3> </p>
<p><img src="https://user-images.githubusercontent.com/86801738/129113257-9fdcc18b-ab97-4c90-aeec-026cacb5caf3.png" alt=Snag_1cc3a7b4> </p>
<p><img src="https://user-images.githubusercontent.com/86801738/129113270-816bd980-740d-4869-b165-1a20ea314088.png" alt=Snag_1cc3c4d1> </p>
<p><img src="https://user-images.githubusercontent.com/86801738/129113293-5792faea-e64f-4735-95a6-0c31a01a8990.png" alt=Snag_1cc3ffe6> </p>
<p><img src="https://user-images.githubusercontent.com/86801738/129113320-cfd6c59d-70cf-4560-9faa-e045a1e7669b.png" alt=Snag_1cc452e8> </p>
<p><img src="https://user-images.githubusercontent.com/86801738/129113301-2d09b1ad-52e7-458e-b5e6-650f13508519.png" alt=Snag_1cc41b4d> </p>
<p><img src="https://user-images.githubusercontent.com/86801738/129113307-207a399a-fefe-4610-be94-5ab2011e21ca.png" alt=Snag_1cc4328e> </p>
<p><img src="https://user-images.githubusercontent.com/86801738/129113334-4734047d-abcd-439f-be5d-eb7a7208d068.png" alt=Snag_1cc4719b> </p>

**Comment by synapp** [comment]
Hi @CRYP70N1X,
The awesome thing about open source is that everyone can contribute. You clearly put a lot of work into this write up and screenshots. But if you do a Pull and make the changes yourself you'll make it so easy to for the code owners to implement. Plus, you'll be registered as a contributor on this project!

**Comment by krnese** [comment]
> @synapp I would love to fix these myself, but honestly I'm just not sure how to Pull and make these changes myself...still learning the ropes on github :(
> I'll continue to investigate how to resolve these myself if I can, but I wanted to add them here also for visibility.

Can you see if this helps? https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Contribution.md#how-to-submit-pull-request-to-upstream-repo

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by JefferyMitchell** [comment]
All items have been reviewed and updated! Thanks for the input!
