### ISSUE TITLE
Prescriptive guidance for highly regulated customers

### ISSUE THREAD

**Issue by matebarabas** [Azure/Enterprise-Scale#738]
Develop prescriptive guidance for customers in highly regulated industries/environments (where Azure Policy DINE is not suitable) for deploying and managing the life cycle of the core platform and workload landing zones.

Actions to take:
1. Documentation update to create guidance that outlines how customers who are not ready for DINE can deploy ESLZ without the DINE effect enabled (puts it in audit mode) to take an incremental approach. Once the customer reviews the non-compliant results then can enable DINE to remediate or manually remediate until they are ready to enable DINE. @mblant to drive with @simonbMS
2. Code update to the Portal based deployment and PowerShell examples to provide an option to disable DINE (which puts it in Audit mode) once the guidance has been created, reviewed, and published. @krnese and @matebarabas to update.

**Comment by krnese** [comment]
We are not using - nor recommending DINE to deploy the actual platform components, but the 'auxiliary' resources/services that are required in order to remain compliant. The same goes for the landing zones and workloads that will drop. More details can be found here: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-FAQ.md#what-does-policy-driven-governance-means-and-how-does-it-work

**Comment by rkuehfus** [comment]
Let's define the problem statement on why DINE is not suitable.  

Problem Statement:
Customer requires granular control on resources deployed at the Azure Landing Zone platform layer.  This control includes testing and and approval before resource deployment.  A system applying changes without a person approval.  This must be reviewed before deployed.  

The goal is Enterprise-Scale for all customers.  To reach this goal we need to provide a bridge to DINE for customers that fall into the problem statement.  This bridge plan should include documentation on how DINE works and where one can go to review new resources deployed with DINE, an deployment template with Audit policy to use in place of the DINE policies.

Questions:
If we do provide Audit policy, who handles resolving the non-compliant landing zones (app team? Central IT?).  How do the go from Audit to DINE?  What is our guidance here?  How do we get them on the path?

Next Steps:
- Create ESLZ Guidance on how to understand and get on the path to DINE? 

Open Items:
- Should we provide code as well?

**Comment by rkuehfus** [comment]
We have alignment on the following Actions to address this feedback item:

And add two actions:

1.	Documentation update to create guidance that outlines how customers who are not ready for DINE can deploy ESLZ without the DINE effect enabled (puts it in audit mode) to take an incremental approach. Once the customer reviews the non-compliant results then can enable DINE to remediate or manually remediate until they are ready to enable DINE. @mblant to drive with @simonbMS 
2.	Code update to the Portal based deployment and PowerShell examples to provide an option to disable DINE (which puts it in Audit mode) once the guidance has been created, reviewed, and published. @krnese and @matebarabas to update.

@krnese  can you please move this to our GitHub Project?
