### ISSUE TITLE
How to Cleared down failed deployment

### ISSUE THREAD

**Issue by Ashley72** [Azure/Enterprise-Scale#747]
<p><strong>Describe the solution you'd like</strong>
It would be useful to have instructions or script that can be run to clear down failed deployments. </p>

**Comment by jtracey93** [comment]
Hi @ashley72,

Thanks for raising this. Would you see this script/guidance completely remove everything deployed and put any subscriptions moved back to the Tenant Root Group?

**Comment by Ashley72** [comment]
Hi @jtracey93 

Yes I would see this deleting all resources deployed, especially MG and Subscription placed back into Tenant Root. This comes more from when your testing/learning and want to deploy the ESLZ following a failed deployment and needing to start again, but following attempts fail due to conflicts as resources are already deployed.

**Comment by jtracey93** [comment]
Understood. I know a few of us do have scripts that do something like this. Let me take this away and come back to you 👍

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2
