### ISSUE TITLE
Wording changes - Section - Why are there custom policy definitions as part of Enterprise-Scale Landing Zones?

### ISSUE THREAD

**Issue by tdsan** [Azure/Enterprise-Scale#751]
We work with - and learn from our customers and partners, and ensures that we evolve and enhance the reference implementations to meet customer requirements. 

Section - 
I am thinking this is a typo, what about **"We work with and learn from a myriad of customers and partners; this ensures that our deep partner interaction is constantly evolving as our architecture/implementation(s) exceed an assortment of customer requirements."**

**Comment by jtracey93** [comment]
Hi @tdsan,

Please feel free to create a PR with this change. You can do this by just hitting the edit (pencil) icon on the correct markdown (.md) page and submit as a suggestion.

If not, please advise what page you are referring to here 👍

Thanks

Jack

**Comment by jtracey93** [comment]
Closing as stale
