### ISSUE TITLE
Change the wording, suggestion

### ISSUE THREAD

**Issue by tdsan** [Azure/Enterprise-Scale#752]
Azure Policy and deployIfNotExist enables the autonomy in the platform, and reduces the operational burden as you scale your deployments and subscriptions in the Enterprise-Scale architecture. 

Wording Suggestion: **"Azure Policy and deployIfNotExist enables the autonomy in the platform, this action reduces the operational burden as the end-user scales their deployments and subscriptions in the overall Enterprise Architecture".**

**Comment by jtracey93** [comment]
Hi @tdsan,

Please feel free to create a PR with this change. You can do this by just hitting the edit (pencil) icon on the correct markdown (.md) page and submit as a suggestion.

If not, please advise what page you are referring to here 👍

Thanks

Jack

**Comment by jtracey93** [comment]
Closing as stale
