### ISSUE TITLE
Bug Report: Deploy Diagnostic Settings to Azure Services initiative was not assigned

### ISSUE THREAD

**Issue by Vinodoct** [Azure/Enterprise-Scale#773]
Couple of issues to report
1. "Deploy Diagnostic Settings to Azure Services" initiative got created at intermediate root mgmt group location, however, it wasn't assigned/deployed to remediate the non-compliant resources

![image](https://user-images.githubusercontent.com/66834714/131483785-660a402c-5069-45a2-a71b-44b560fbaf44.png)

2. DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"PolicyDefinitionNotFound","message":"The policy assignment create request is invalid. The policy definition '/providers/Microsoft.Management/managementGroups/caf-/providers/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-NIC' could not be found.

3. Resourcegroup 'xxx-privatedns' could not be found - Doesn't ESLZ template take care of Resourcegroup creation by its own, if not may be it should be recorded in pre-requisities documentation.
Thanks a bunch !!

**Comment by daltondhcp** [comment]
Hey @Vinodoct,

To better understand what went wrong, can you please share some further details about your deployment. 
What deployment region did you select? 
Did you by any chance select the same subscription for management and connectivity?

**Comment by Vinodoct** [comment]
Hi @daltondhcp,

Thanks for following up!
It was EastUS region. I selected two different subscriptions - one for management and one for connectivity. 
ESLZ deployment did create the management group hierarchy and had about 85-90% success in deploying the underlying resources/policies with a couple of failure messages shared above. And one major issue was the policies/initiatives were created but not assigned.

**Comment by krnese** [comment]
This is a known issue, and similar to the issue submitted here: https://github.com/Azure/Enterprise-Scale/issues/775#issuecomment-909502099

Please rerun with same input parameters and location, and the policy should be replicated in our backend storage.

**Comment by Vinodoct** [comment]
Hi @krnese, Thanks for your assistance, rerun deployment was successful, however, I was expecting it will overwrite the previous configuration but it didn't meaning I have two sets of mgmt group hierarchy, if i try to delete the deployment, it would not clean up the resources but just the deployment history under deployment blade of the management group. 

![image](https://user-images.githubusercontent.com/66834714/132289282-688194be-c7ae-435d-8177-bc262c2ced83.png)

The other thing is where do i find central deployment entry if there is one to delete all deployment instead going to individual management groups which were created as part of this build. Mgmt groups hierarchy have different set of deployments. 

![image](https://user-images.githubusercontent.com/66834714/132289397-739de4c7-7363-4033-b100-e6e4c4ccd035.png)

Thanks,

**Comment by krnese** [comment]
if you used a different prefix, you will certainly end up with another ESLZ deployment peer to what you attempted the first time. Cleaning up the deployments will only clean up the deployment resources - not the rest of it.
