### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Ashley72** [Azure/Enterprise-Scale#775]
When deploying ARM templates the EntScale-SubnetNsg- reports a conflict
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidCreatePolicyAssignmentRequest\",\r\n    \"message\": \"The policy definition specified in policy assignment 'Deny-Subnet-Without-Nsg' is out of scope. Policy definitions should be specified only at or above the policy assignment scope. If the management groups hierarchy changed recently or if assigning a management group policy to new subscription, please allow up to 30 minutes for the hierarchy changes to apply and try again.\"\r\n  }\r\n}"
            }
        ]
    }
}

**Steps to reproduce**

1. I've clean up my subscriptions and MG prior to running the Example
2. I'm deploying to UK South 
2. I selected no to Connectivity 

**Screenshots**

**Comment by krnese** [comment]
This is a known issue that sometimes can happen when you deploy to a paired region in Azure, as described in our 'known issues' @ https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Known-Issues.md#deploying-the-reference-implementation-fails-due-to-policy--cannot-be-found-404

Please re-run the deployment with the exact input parameters (mgmt group prefix and same deployment location), and it should complete.

**Comment by Vinodoct** [comment]
It was a success, Thanks @krnese , Apppreciate your help
