### ISSUE TITLE
Update User Guide - post Deployment activities - create new role assignment

### ISSUE THREAD

**Issue by Ashley72** [Azure/Enterprise-Scale#776]
<p>Could you please elaborate on the how to create new role assignment part of the user guide. Add items like what file type to create? eg JSON and where is best place to save that file. </p>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by jtracey93** [comment]
https://github.com/Azure/Enterprise-Scale/wiki/Deploying-Enterprise-Scale-Platform-DevOps#create-new-role-assignment-on-a-landing-zone
