### ISSUE TITLE
Bug Report - Include CIDR range validation to ER/VPN GW subnet

### ISSUE THREAD

**Issue by victorar** [Azure/Enterprise-Scale#779]
**Describe the bug**
New CIDR range validation is applied to Hub address space, AZFW subnet and corp-connected LZs, but the validation is not being done on ER/VPN GW Subnet

**Steps to reproduce**

1. Launch Azure Landing Zone accelerator, and complete sections until arrive to the Network topology and connectivity section.
2. Select Hub and spoke with Azure Firewall network topology
3. Provide a valid address space for the hub virtual network
4. Select Yes to deploy VPN or ExpressRoute Gateway
5. Provide any string on the Subnet for VPN/ExpressRoute Gateways. You will notice that any string will be accepted

**Screenshots**
![image](https://user-images.githubusercontent.com/16934655/131829480-b525c957-0468-49ca-9be8-4205771674a7.png)

![image](https://user-images.githubusercontent.com/16934655/131829586-0300b85f-8bb4-4135-aa3c-33a5f201885f.png)

![image](https://user-images.githubusercontent.com/16934655/131829643-95b04a5f-cabc-4b35-b093-5b6dc5fc7bde.png)

**Comment by jtracey93** [comment]
We should also ensure that the GatewaySubnet is a /27 or larger as per guidance here: https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-gateway-settings#gwsub

**Comment by jtracey93** [comment]
> @jtracey93 Jack Tracey FTE > That is a separate issue, which I'll log as well (and will be not only for GW Subnet, but AZFW subnet as well).

Cool. Do you not think

**Comment by marvinbuss** [comment]
@victorar And these subnets need to be within the Vnet address space. This is also something we need to check. Let me quickly look into that.

**Comment by victorar** [comment]
Yes! Thanks Marvin 🙏

**Comment by marvinbuss** [comment]
We also have to add this check for the AZ Firewall subnet.

**Comment by victorar** [comment]
I think that is already been checked in the AZFW subnet:

![image](https://user-images.githubusercontent.com/16934655/131838760-b65196f6-f60f-4004-82c1-93825e55fbcc.png)
