### ISSUE TITLE
Initial/minimal subnet sizes for AZFW and ER/VPN GW

### ISSUE THREAD

**Issue by victorar** [Azure/Enterprise-Scale#783]
Provide/recommend the initial VPN/ER and AZFW subnet sizes for the hub and spoke network topology:

Azure Firewall: /26
https://docs.microsoft.com/en-us/azure/firewall/firewall-faq#why-does-azure-firewall-need-a--26-subnet-size

ExpressRoute and/or VPN Gateway: /27
https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-coexist-resource-manager#limits-and-limitations

Besides recommending this initial size, validation should be made to ensure customers don't provide a smaller subnet. However, customers should be able to provide a larger subnet, should they want to.

**Comment by marvinbuss** [comment]
@victorar what should be the max/min subnet mask?

Azure Firewall: [10, 26], [1, 26], ...?
ER/VPN GW: [10, 27], [1, 27], ...?

**Comment by victorar** [comment]
Ideally, should be no larger than the hub VNet address space. But if we need to define an potential max size, I'd suggest:

AZFW: [20, 26]
ER/VPN GW: [20, 27]
