### ISSUE TITLE
Limit cross tenant private endpoint connections

### ISSUE THREAD

**Issue by victorar** [Azure/Enterprise-Scale#785]
Describe and provide policies to limit (or block) private endpoint connections across Azure AD tenants. This will help  customers who need to ensure that private endpoints can be limited to Azure services within their own tenant only.

**Comment by marvinbuss** [comment]
@victorar The first policy is included here: https://github.com/Azure/Enterprise-Scale/pull/786 (for AML)

**Comment by krnese** [comment]
Is "Audit" the correct default value here?

**Comment by marvinbuss** [comment]
"Deny" will block some data workloads. "Audit" may not be sufficient for some customers. Please let me know, how you want to proceed.

**Comment by victorar** [comment]
Closing issue. Guidance and policies have been published as per the following article: 

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/limit-cross-tenant-private-endpoint-connections
