### ISSUE TITLE
Review the number of options on each tab for "Trey Research"

### ISSUE THREAD

**Issue by JefferyMitchell** [Azure/Enterprise-Scale#787]
<p>Review the number of options on each tab for the Azure Landing Zone Accelerator for &quot;Trey Research&quot; configuration </p>
<p>For each tab there should be a shorter list, @juazasan with details for each option. </p>

**Comment by juazasan** [comment]
@JefferyMitchell Can you please add @aarunraaj to this issue? We will be both driving this from our side. Thanks.

**Comment by jtracey93** [comment]
I have done this 👍

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2
