### ISSUE TITLE
Error in deploying DINE-VMBackupPolicyAssignment.json

### ISSUE THREAD

**Issue by faister** [Azure/Enterprise-Scale#791]
**Describe the bug**
Error in running the DIY deployment of DINE-VMBackupPolicyAssignment.json template as per instructions in https://github.com/Azure/Enterprise-Scale/tree/main/eslzArm

**Steps to reproduce**

1. Run the following PowerShell command:
# Assign Azure Policy to enforce VM Backup on VMs on the landing zones management group

New-AzManagementGroupDeployment -Name "$($DeploymentName)-vm-lz-backup" `
                                -Location $Location `
                                -ManagementGroupId "$($ESLZPrefix)-landingzones" `
                                -TemplateFile .\eslzArm\managementGroupTemplates\policyAssignments\DINE-VMBackupPolicyAssignment.json `
                                -topLevelManagementGroupPrefix $eslzPrefix `
                                -Verbose                                

2. Error returned:
VERBOSE:
VERBOSE: 4:33:06 PM - Template is valid.
VERBOSE: 4:33:07 PM - Create template deployment 'Eslz-vm-lz-backup'
VERBOSE: 4:33:07 PM - Checking deployment status in 5 seconds
VERBOSE: 4:33:12 PM - Resource Microsoft.Authorization/policyAssignments 'Deploy-VM-Backup' provisioning status is succeeded
VERBOSE: 4:33:12 PM - Resource Microsoft.Authorization/policyAssignments 'Deploy-VM-Backup' provisioning status is succeeded
New-AzManagementGroupDeployment: 4:33:12 PM - The deployment 'Eslz-vm-lz-backup' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Tenant ID, application ID, principal ID, and scope are not allowed to be updated. (Code:RoleAssignmentUpdateNotPermitted)
CorrelationId: 62c5b578-031e-41d6-91e9-c2853bfa1e0a

**Screenshots**

**Comment by krnese** [comment]
This error is expected if you have deployed the policyAssignment before elsewhere in your tenant, using the exact same deployment name and location, as some of the properties of the roleAssignment is immutable. Either clean up previous deployments, or change the deployment name and location.

**Comment by faister** [comment]
ack, thanks
