### ISSUE TITLE
Feature Request - add metadata for custom Enterprise-Scale Policy/Set definitions

### ISSUE THREAD

**Issue by JulianHayward** [Azure/Enterprise-Scale#798]
Add metadata 'EnterpriseScale' or something like that for custom Enterprise-Scale Policy/Set definitions.
Having that identifier may be helpful consolidating custom Policy/Set definitions.

e.g.
```
            "metadata": {
              "version": "1.0.0",
              "category": "Monitoring",
              "EnterpriseScale": true
            }
```

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#metadata

**Comment by krnese** [comment]
Thanks for submitting this issue. Can you please elaborate on 'helpful consolidating custom policy/set definitions'?

**Comment by JulianHayward** [comment]
some use cases that I have in mind:
- assessing the environment for policy/set definitions determine which belong to ESLZ
- cleanup of unused policy/set definitions (one may want to keep the unused ESLZ definitions but decommission other custom definitions). Today the mapping of policy/set definitions to ESLZ can only be done by the policy/set's displayName (I think)
- inventory based on metadata

**Comment by marvinbuss** [comment]
Thanks for the suggestion @JulianHayward. 👍  Is it not sufficient to select `Custom` in the Azure Portal Dropdown menu?
![image](https://user-images.githubusercontent.com/34542414/133575945-954471ee-a1fa-44fc-9088-c57169bb870a.png)

ESLZ custom policies should probably not be treated differently than any other custom policies defined inside the tenant.
Do you agree?
Can you please elaborate how the tags improve the user experience?
Are you querying and filtering defined policies in the tenant using Tags and Azure CLI or PowerShell?

**Comment by krnese** [comment]
The ESLZ policies are transitioning to built-ins, and for now, you can filter on custom as Marvin said, and also by category as we use the same categories as built-ins. We do not intend to surface as unique policies in ESLZ context by populating the metadata object.
