### ISSUE TITLE
README.md still references 3 reference implementations no longer used?

### ISSUE THREAD

**Issue by ChrisPetr0** [Azure/Enterprise-Scale#811]
Based on this [commit](https://github.com/Azure/Enterprise-Scale/pull/734/files), shouldn't the three reference implementations no longer used be removed completely (and all other documentation related to) from `README.md`?  I'm relatively new to this repo but having this information there with all 3 pointed to the same ARM template and UI definition file is confusing.  

```
| Contoso | On-premises connectivity using Azure vWAN |[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json) | [Detailed description](./docs/reference/contoso/Readme.md) |
| AdventureWorks | On-premises connectivity with Hub & Spoke  |[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json) | [Detailed description](./docs/reference/adventureworks/README.md) |
| WingTip | Azure without hybrid connectivity |[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json) | [Detailed description](./docs/reference/wingtip/README.md)
```

Thanks

**Comment by jtracey93** [comment]
Hi @ChrisPetr0,

You are correct in that the implementation has now been consolidated from 3 separate implementation templates into a single one. 

However, we have left the 3 reference architectures in place as all of them are still valid and can all be implemented based on the options selected during the deployment portal experience. This allows for users who have been using ESLZ for a while to still find what they need whilst moving forward to a single implementation template that delivers each of the architectures based on the input provided and simplified management of ESLZ for the maintainers. 

Hope that helps to explain the reason why 👍

Thanks

Jack
