### ISSUE TITLE
Error running Azure landing zone accelerator deployment

### ISSUE THREAD

**Issue by tommysvensson0** [Azure/Enterprise-Scale#816]
**Describe the bug**
Review fails:
{
  "code": "InvalidTemplate",
  "message": "Deployment template parse failed: 'Required property 'contentVersion' not found in JSON. Path '', line 2431, position 1.'."
}

**Steps to reproduce**
Accepting all default values in the wizard, filling in SPN and Github information. Select VWAN and a premium firewall. 
Using seperate subscriptions for management, connectivity, identity, corp and online landing zone. So 5 subscriptions.
**Screenshots**

**Comment by krnese** [comment]
We're not able to reproduce based on the information given, could you please share the input parameter (you will see a list/summary on the review + create tab) with us, so we can explore further?

**Comment by tommysvensson0** [comment]
Here's the list of parameters:

Deployment location
Region
West Europe
Azure core setup
Management Group prefix
ccd
Select dedicated subscriptions or single subscription for platform resources
Dedicated (recommended)
Platform management, security, and governance
Deploy Log Analytics workspace and enable monitoring for your platform and resources
Yes (recommended)
Log Analytics Data Retention (days)
30
Subscription
Azure subscription 1
Deploy Agent Health solution
Yes (recommended)
Deploy Change Tracking solution
Yes (recommended)
Deploy Update Management solution
Yes (recommended)
Deploy Activity Log solution
Yes (recommended)
Deploy VM Insights solution
Yes (recommended)
Deploy Service Map solution
Yes (recommended)
Deploy SQL Assessment solution
Yes (recommended)
Deploy Azure Security Center and enable security monitoring for your platform and resources
Yes (recommended)
Azure Security Center Email Contact
tommy.svensson@cygate.se
Enable Azure Defender for servers
Yes (recommended)
Enable Azure Defender for AppServices
Yes (recommended)
Enable Azure Defender for Storage
Yes (recommended)
Enable Azure Defender for Azure SQL Database
Yes (recommended)
Enable Azure Defender for SQL servers on machines
Yes (recommended)
Enable Azure Defender for Key Vault
Yes (recommended)
Enable Azure Defender for Azure Resource Manager
Yes (recommended)
Enable Azure Defender for DNS
Yes (recommended)
Enable Azure Defender for Kubernetes
Yes (recommended)
Enable Azure Defender for Container registries
Yes (recommended)
Deploy Azure Sentinel
Yes (recommended)
Platform DevOps and automation
Deploy integrated CICD pipeline?
Yes (recommended)
Select CICD option
GitHub Actions
GitHub organization or username
CygateCloud
New GitHub repository name
CCD-ES
GitHub personal access token
****************************************
Service Principal Id
d43e8243-1118-4bbc-9a25-15e29b723490
Password
*************************************
Network topology and connectivity
Deploy networking topology
Virtual WAN (Microsoft managed)
Subscription
Azure subscription 2
Address space (required for vWAN hub)
10.100.0.0/23
Region for the first networking hub
West Europe
Enable DDoS Protection Standard
Yes (recommended)
Deploy VPN Gateway
No
Deploy ExpressRoute Gateway
No
Deploy Azure Firewall
Yes (recommended)
Enable Azure Firewall as a DNS proxy
No
Select Azure Firewall tier
Premium
Identity
Assign recommended policies to govern identity and domain controllers
Yes (recommended)
Subscription
Azure subscription 3
Prevent inbound RDP from internet
Yes (recommended)
Ensure subnets are associated with NSG
Yes (recommended)
Prevent usage of public IP
Yes (recommended)
Ensure Azure VMs (Windows & Linux) are enabled for Azure Backup
Yes (recommended)
Create virtual network and connect to the connectivity hub (optional)?
Yes (recommended)
Virtual network address space
10.110.0.0/24
Landing zone configuration
Corp landing zone subscriptions (optional)
Azure subscription 4
Online landing zone subscriptions (optional)
Azure subscription 5
Enable DDoS Protection Standard
Yes (recommended)
Prevent usage of Public Endpoints for Azure PaaS services in the corp connected landing zones
Yes (recommended)
Ensure encryption in transit is enabled for PaaS services
Yes (recommended)
Ensure Azure VMs (Windows & Linux) are being monitored
Yes (recommended)
Ensure Azure VMSS (Windows & Linux) are being monitored
Yes (recommended)
Enable Kubernetes (AKS) for Azure Policy
Yes (recommended)
Prevent privileged containers in Kubernetes clusters
Yes (recommended)
Prevent privileged escalation in Kubernetes clusters
Yes (recommended)
Ensure HTTPS ingress is enforced in Kubernetes clusters
Yes (recommended)
Prevent public IP for Databricks workloads in the corp connected landing zones
Yes (recommended)
Ensure VNet injection is enabled for Databricks workspaces in corp connected landing zones
Yes (recommended)
Ensure Databricks workloads are using the right SKU to ensure enterprise security and Azure RBAC
Yes (recommended)
Ensure Azure VMs (Windows & Linux) are enabled for Azure Backup
Yes (recommended)
Prevent inbound RDP from internet
Yes (recommended)
Ensure subnets are associated with NSG
Yes (recommended)
Prevent IP forwarding
Yes (recommended)
Ensure Azure SQL is enabled with transparent data encryption
Yes (recommended)
Ensure auditing is enabled on Azure SQL
Yes (recommended)
Ensure secure connections (HTTPS) to storage accounts
Yes (recommended)

**Comment by tommysvensson0** [comment]
Deployment location
Region
West Europe
Azure core setup
Management Group prefix
ccd
Select dedicated subscriptions or single subscription for platform resources
Dedicated (recommended)
Platform management, security, and governance
Deploy Log Analytics workspace and enable monitoring for your platform and resources
Yes (recommended)
Log Analytics Data Retention (days)
30
Subscription
Azure subscription 1
Deploy Agent Health solution
Yes (recommended)
Deploy Change Tracking solution
Yes (recommended)
Deploy Update Management solution
Yes (recommended)
Deploy Activity Log solution
Yes (recommended)
Deploy VM Insights solution
Yes (recommended)
Deploy Service Map solution
Yes (recommended)
Deploy SQL Assessment solution
Yes (recommended)
Deploy Azure Security Center and enable security monitoring for your platform and resources
Yes (recommended)
Azure Security Center Email Contact
asdgmail.com
Enable Azure Defender for servers
Yes (recommended)
Enable Azure Defender for AppServices
Yes (recommended)
Enable Azure Defender for Storage
Yes (recommended)
Enable Azure Defender for Azure SQL Database
Yes (recommended)
Enable Azure Defender for SQL servers on machines
Yes (recommended)
Enable Azure Defender for Key Vault
Yes (recommended)
Enable Azure Defender for Azure Resource Manager
Yes (recommended)
Enable Azure Defender for DNS
Yes (recommended)
Enable Azure Defender for Kubernetes
Yes (recommended)
Enable Azure Defender for Container registries
Yes (recommended)
Deploy Azure Sentinel
Yes (recommended)
Platform DevOps and automation
Deploy integrated CICD pipeline?
Yes (recommended)
Select CICD option
GitHub Actions
GitHub organization or username
ccd
New GitHub repository name
CCD-ES
GitHub personal access token
****************************************
Service Principal Id
d43e8243-1118-4bbc-9a25-15e29b723490
Password
*************************************
Network topology and connectivity
Deploy networking topology
Virtual WAN (Microsoft managed)
Subscription
Azure subscription 2
Address space (required for vWAN hub)
10.100.0.0/23
Region for the first networking hub
West Europe
Enable DDoS Protection Standard
Yes (recommended)
Deploy VPN Gateway
No
Deploy ExpressRoute Gateway
No
Deploy Azure Firewall
Yes (recommended)
Enable Azure Firewall as a DNS proxy
No
Select Azure Firewall tier
Premium
Identity
Assign recommended policies to govern identity and domain controllers
Yes (recommended)
Subscription
Azure subscription 3
Prevent inbound RDP from internet
Yes (recommended)
Ensure subnets are associated with NSG
Yes (recommended)
Prevent usage of public IP
Yes (recommended)
Ensure Azure VMs (Windows & Linux) are enabled for Azure Backup
Yes (recommended)
Create virtual network and connect to the connectivity hub (optional)?
Yes (recommended)
Virtual network address space
10.110.0.0/24
Landing zone configuration
Corp landing zone subscriptions (optional)
Azure subscription 4
Online landing zone subscriptions (optional)
Azure subscription 5
Enable DDoS Protection Standard
Yes (recommended)
Prevent usage of Public Endpoints for Azure PaaS services in the corp connected landing zones
Yes (recommended)
Ensure encryption in transit is enabled for PaaS services
Yes (recommended)
Ensure Azure VMs (Windows & Linux) are being monitored
Yes (recommended)
Ensure Azure VMSS (Windows & Linux) are being monitored
Yes (recommended)
Enable Kubernetes (AKS) for Azure Policy
Yes (recommended)
Prevent privileged containers in Kubernetes clusters
Yes (recommended)
Prevent privileged escalation in Kubernetes clusters
Yes (recommended)
Ensure HTTPS ingress is enforced in Kubernetes clusters
Yes (recommended)
Prevent public IP for Databricks workloads in the corp connected landing zones
Yes (recommended)
Ensure VNet injection is enabled for Databricks workspaces in corp connected landing zones
Yes (recommended)
Ensure Databricks workloads are using the right SKU to ensure enterprise security and Azure RBAC
Yes (recommended)
Ensure Azure VMs (Windows & Linux) are enabled for Azure Backup
Yes (recommended)
Prevent inbound RDP from internet
Yes (recommended)
Ensure subnets are associated with NSG
Yes (recommended)
Prevent IP forwarding
Yes (recommended)
Ensure Azure SQL is enabled with transparent data encryption
Yes (recommended)
Ensure auditing is enabled on Azure SQL
Yes (recommended)
Ensure secure connections (HTTPS) to storage accounts
Yes (recommended)

**Comment by krnese** [comment]
Thanks. Still not able to reproduce, and wonder if the issue you encountered was circumstantial. Are you able to consistently reproduce the error?

**Comment by tommysvensson0** [comment]
I just tried again and I'm afraid so, can't get passed it.

**Comment by krnese** [comment]
Can you pls share the deployment link you are using?

**Comment by tommysvensson0** [comment]
https://aka.ms/caf/ready/accelerator

**Comment by tommysvensson0** [comment]
Tried again now and validation went through without a hitch.

**Comment by bhicks329** [comment]
I've been seeing exactly this error. When it occurs, no amount of revalidation clears it. I have to completely refresh the page and try again. A successful validation occurs 1 out of every 10 attempts.
