### ISSUE TITLE
4/5 policySetDefinitions fails during custom ARM deployment to management group

### ISSUE THREAD

**Issue by ekrof** [Azure/Enterprise-Scale#819]
This might be similar to issue #716, but I cannot deploy the enterprise scale polices into either Tenant root management group, or a sub-management group. The issue seems to be only with 4/5 of the _policySetDefinitions_ / Initiatives as you can see in the screenshot:
 
![image](https://user-images.githubusercontent.com/14015087/135091463-bf7bd3d8-43d7-487a-b2e1-4828ccab2a13.png)
 
I've tried using both Custom template deployment in Azure portal, and AZ CLI using the following:

`az deployment mg create --management-group-id 'cust-root-mg' --location 'westeurope' --name 'enterprise-scale-policies' --template-uri https://raw.githubusercontent.com/Azure/Enterprise-Scale/main/eslzArm/managementGroupTemplates/policyDefinitions/policies.json --parameters topLevelManagementGroupPrefix=cust`

but I'm getting the same error. This is also reproduced using a different tenant, and with an entire new management group. 
The underlying policy definitions is successfully imported, but the initiatives aren't with the following error message:

`The policy set definition ‘Failing-Definition-Name’ request is invalid. Policy definitions should be specified only at or above the policy set definition’s scope. The following policy definitions are invalid: xxxx-xxx-xxxx. (Code: InvalidCreatePolicySetDefinitionRequest)`

**Comment by jtracey93** [comment]
Hi @ekrof,

Have you tried re-running the deployment with the exact same input parameters after the first deployment. This looks like the policy definition is deploying but when the initiative is trying to create it doesn't think they exist.

Normally re-running after the initial deployment resolves this issue 

Let us know

Thanks

Jack

**Comment by ekrof** [comment]
> Have you tried re-running the deployment with the exact same input parameters after the first deployment. This looks like the policy definition is deploying but when the initiative is trying to create it doesn't think they exist.
> 
Just ran it again, downloaded the .JSON files from the first deployment and created another custom deployment, still gives me the same errors 😞 
![image](https://user-images.githubusercontent.com/14015087/135215530-01d0fb7d-788a-4451-a2e7-6e755e68abd8.png)

Noticed there wasn't a redeploy button so I had to recreate the deployment. It's weird that the Enforce-Encryption-CMK Initiative works but not the others 👀

**Comment by jtracey93** [comment]
Hey @ekrof,

Yo shouldn't need to download the files you should just be able to re run with the files directly from the url to the GitHub repo as you did originally. 

Can you confirm that you did this second deployment on the same management group?

As from the command you shared above it looks like the management group being targeted is different to the parameter being provided for topLevelManagementGroupPrefix: 

az deployment mg create --management-group-id 'cust-root-mg' --location 'westeurope' --name 'enterprise-scale-policies' --template-uri https://raw.githubusercontent.com/Azure/Enterprise-Scale/main/eslzArm/managementGroupTemplates/policyDefinitions/policies.json --parameters topLevelManagementGroupPrefix=cust

This "--management-group-id 'cust-root-mg'" and this "--parameters topLevelManagementGroupPrefix=cust" should be the same. 

I think this may be the issue. 

Also is this Azure Public?

**Comment by ekrof** [comment]
Yeah, sorry I changed the parameter to censor real customer data. Here's the result running again for the 4th time in my test tenant -  both in Azure Public. So I don't think the ManagementGroupPrefix is the issue.

![image](https://user-images.githubusercontent.com/14015087/135232995-ace8586a-48c0-43fe-95b3-d69350ed2b32.png)

![image](https://user-images.githubusercontent.com/14015087/135233371-bfa75df0-9d4c-4577-bd3b-2b3ef937d71c.png)


And one more time, for good measure directly after the first.
![image](https://user-images.githubusercontent.com/14015087/135234119-99d36ccc-18dc-4000-887a-928318dce7f0.png)

**Comment by daltondhcp** [comment]
Just like Jack mentioned, it looks like you are submitting the deployment to the management platform mg and not the intermediate root mg. I just tested in my environment and deployment succeeded without any issues. See my example below:
![image](https://user-images.githubusercontent.com/16622613/135242215-b23a868b-4903-4f79-bc1b-7b360417a912.png)

**Comment by jtracey93** [comment]
Thanks @daltondhcp for testing this (beat me to it this morning 👍 )

@ekrof does this help and mean we can close this issue?

**Comment by ekrof** [comment]
Damn, you're right. I didn't realize prefix was supposed to be identical to the management group ID 😩  Thanks both!

![image](https://user-images.githubusercontent.com/14015087/135248987-b0ff37cc-720e-4633-9575-e173c33b6a01.png)


BUT, here's the new problem. In my actual tenant, the management group ID is 11 characters, whereas the topLevelManagementGroupPrefix parameter only supports 10.  Is this an enterprise-scale policy? I can probably just increase the cap manually in the .JSON, but I was planning to encorporate the policies in a pipeline which updates every month and that makes things more difficult.

**Comment by jtracey93** [comment]
No worries.

Is your top level management group `jonas-mgmt` and not just `jonas` as per ESLZ guidance all policies should be at the intermediate root level.

The management group name can be longer but I haven't seen many need it longer than 10.

**Comment by ekrof** [comment]
For clarity, here's the actual Management Group I'm trying to deploy to (in the middle)
![image](https://user-images.githubusercontent.com/14015087/135255828-bfcabcfd-5281-4b81-9b56-de2c8e42dfea.png)

So that's why deployig to the tenant root group also fails (because of more than 10 characters).

In this case, `mg-all` would work, but not the `abl-root-mg` group. Since I couldn't find any reference in [enterprise-scale docs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization) to the group naming having a character length , I see no reason for why there should be a cap at all for this particular parameter. Suffice to say, my problems would've be gone if the cap were removed or increased to like 15 chars, but I understand if you want to keep it the way it is 🙂  I will close the issue if this is just the way it is. Thanks for your help at least!

**Comment by jtracey93** [comment]
Hey @ekrof,

We are tracking the naming concerns you raised internally on our backlog and also in this issue here #674 & #545 so ill link this issue up to those as more evidence 👍

I'll close this one off for now but feel free to raise other issues if you need further support or have questions 👍

**Comment by jtracey93** [comment]
Also @ekrof, just to provide further context. The display name for the Management Groups, isn't restricted, it is just the Name/ID, as the prefix you enter is used elsewhere in the ESLZ deployment so by keeping it restricted we prevent other Resoruce deployment failures due to name length issues.

But I agree it should be documented and this is something that is already in action on our backlog 👍

**Comment by ekrof** [comment]
That's a fair point. I've seen my teammates just naming their management group IDs the same as the management group name, which I've learned now is not the best practice 🤞  Thanks for the clarification. I'll take this in context the next time I'm creating management groups. Keep up the good work!
