### ISSUE TITLE
Custom Route Table Update

### ISSUE THREAD

**Issue by JefferyMitchell** [Azure/Enterprise-Scale#823]
Propose a improvement of the current ESLZ policies for custom route tables in hub&spoke networks. The proposal is based on learnings from actual customer engagements. In a nutshell, the current ESLZ implementation contains policies that:

-	Prevent creation of route tables
-	Deploy (via a DINE effect) custom route tables with a default route pointing to the hub firewall for all newly created VNets/subnet.

**Comment by fguerri** [comment]
Resolved by [Replaced 'Deploy-Default-Udr' policy with 'Deploy-Custom-Route-Table' #853](https://github.com/Azure/Enterprise-Scale/pull/853)
