### ISSUE TITLE
Management group hierarchy folder is not create in git repo(CI/CD)

### ISSUE THREAD

**Issue by Asha-Hiremath** [Azure/Enterprise-Scale#840]
Hi Team, 

I have tried the Adventure Work Enterprise Landing zone scripts. 

I have management, connectivity, identity and landing zone subscriptions.  I don;t have corp subscription as this is for testing only. 

When I deployed the script, in the git I can only see .Pipeline and  and .github folders. Deployment is successful. However, I don't a folder with management group hierarchy. I have followed the steps exactly the same. 

Can you advise what could have been the issue.

Kind Regards,
AKM

**Comment by daltondhcp** [comment]
Hey @Asha-Hiremath - do you still need assistance or can this issue be closed?
