### ISSUE TITLE
Azure Landingzone Accelerator failed DNS role 

### ISSUE THREAD

**Issue by stdistef** [Azure/Enterprise-Scale#852]
Just ran a fresh Azure Landing Zone Accelerator based deployment of the Wig Tip template, (with enabled Networking) and I saw that all Private DNS entries failed.  I narrowed it down by noticing all the Private DNS errors occurred because this first command failed (EntScale-DNSZoneRole-centralusa37ecdd9-57b0-53dd-a59a-82f3f8ab93)

<see screenshot in attached Word Doc>

The error occurred with: Microsoft.Authorization/roleAssignments

<see screenshot in attached Word Doc>
 
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"
            }
        ]
    }
}
 
I should share that while I did not adjust the template or parameters at all, I did make the following AFW and DNS Proxy selections in the Accelerator:

<see screenshot in attached Word Doc>
 
The subscription for this segment is this one:

<see screenshot in attached Word Doc>
 

 
[WT_with_networking_screenshots.docx](https://github.com/Azure/Enterprise-Scale/files/7487065/WT_with_networking_screenshots.docx)

**Comment by jtracey93** [comment]
As discussed offline this was due to the environment already having an ESLZ deployment and different inputs being used on this run as the error below details:

``` 
{
  "error": {
    "code": "InvalidDeploymentLocation",
    "message": "Invalid deployment location 'centralus'. The deployment 'EntScale-connectivityHubSub' already exists in location 'eastus2'."
  }
}
```
