### ISSUE TITLE
Deploy to Azure Button Inconsistencies

### ISSUE THREAD

**Issue by ElanShudnow** [Azure/Enterprise-Scale#854]
<p>On this page: https://github.com/Azure/Enterprise-Scale#deploying-enterprise-scale-architecture-in-your-own-environment </p>
<p>On the page, Trey Research Deploy to Azure button links to the following json:
https://portal.azure.com/#blade/Microsoft<em>Azure</em>CreateUIDef/CustomDeploymentBlade/uri/https%3A%2f%2fraw.githubusercontent.com%2fAzure%2fEnterprise-Scale%2fmain%2fdocs%2freference%2ftreyresearch%2farmTemplates%2fes-lite.json/createUIDefinitionUri/https%3A%2f%2fraw.githubusercontent.com%2fAzure%2fEnterprise-Scale%2fmain%2fdocs%2freference%2ftreyresearch%2farmTemplates%2fportal-es-lite.json </p>
<p>However, when you click on Detailed Description for Trey Research, the Deploy to Azure button links to the following json:
https://portal.azure.com/#blade/Microsoft<em>Azure</em>CreateUIDef/CustomDeploymentBlade/uri/https%3A%2f%2fraw.githubusercontent.com%2fAzure%2fEnterprise-Scale%2fmain%2feslzArm%2feslzArm.json/uiFormDefinitionUri/https%3A%2f%2fraw.githubusercontent.com%2fAzure%2fEnterprise-Scale%2fmain%2feslzArm%2feslz-portal.json </p>
<p>Contoso, AdventureWorks, and WingTip all point to the same json for the Deploy to Azure button in both the table and each of their Detailed Descriptions. But I think this may be intentional for these 3 to all share the same json. </p>

**Comment by krnese** [comment]
Thank you. This will shortly be corrected as we will move "Trey Research" into the same single deployment experience with all options.

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2
