### ISSUE TITLE
ARM template for "Azure landing zone" fails when deploying to Azure Gov - "code": "BadRequest"

### ISSUE THREAD

**Issue by techdawg70** [Azure/Enterprise-Scale#857]
**Describe the bug**
ARM template for "Azure landing zone" fails when deploying to Azure Gov - "code": "BadRequest"

**Steps to reproduce**

1. Log into Azure Gov tenant Portal
2. Create a Resource
3. Template deployment
4. Select Azure landing zone
5. Where applicable - Select "Yes" to deploying defined Azure policy
6. Review & Create
7. Deployment fails with the following message details: "message": "{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy set definition 'Deploy-ASCDF-Config' request is invalid. The following policy definitions could not be found: '/providers/Microsoft.Authorization/policyDefinitions/44433aa3-7ec2-4002-93ea-65c65ff0310a;/providers/Microsoft.Authorization/policyDefinitions/50ea7265-7d8c-429e-9a7d-ca1f410191c3;/providers/Microsoft.Authorization/policyDefinitions/b40e7bcd-a1e5-47fe-b9cf-2f534d0bfb7d;/providers/Microsoft.Authorization/policyDefinitions/64def556-fbad-4622-930e-72d1d5589bf5;/providers/Microsoft.Authorization/policyDefinitions/1f725891-01c0-420a-9059-4fa46cb770b7'.\"\r\n  }\r\n}"

This error is occurring with deployments targeted towards Azure Gov cloud because the json files listed under the url below reference policy definitions which only exist in the Azure Commercial cloud.

https://github.com/Azure/Enterprise-Scale/tree/main/eslzArm/managementGroupTemplates/policyDefinitions/gov
fairfaxDENY-PublicEndpointsPolicySetDefinition.json
fairfaxDINE-PrivateDNSZonesPolicySetDefinition.json
fairfaxPolicies.json

I have searched policy definitions in Azure Gov and have provided what I believe is the Azure Gov equivalent policies below which should be called within the referenced json files.

Az Comm-> Configure Azure Defender for open-source relational databases to be enabled -> 44433aa3-7ec2-4002-93ea-65c65ff0310a
Az Gov -> Configure Advanced Threat Protection to be enabled on open-source relational databases -> /providers/Microsoft.Authorization/policySetDefinitions/e77fc0b3-f7e9-4c58-bc13-cb753ed8e46e

Az Comm -> Configure Azure Defender for SQL servers on machines to be enabled -> 50ea7265-7d8c-429e-9a7d-ca1f410191c3
Az Gov -> Configure Azure Defender to be enabled on SQL servers -> /providers/Microsoft.Authorization/policyDefinitions/36d49e87-48c4-4f2e-beed-ba4ed02b71f5

Az Comm -> Configure Azure Defender for App Service to be enabled -> b40e7bcd-a1e5-47fe-b9cf-2f534d0bfb7d
Az Gov -> Deploy Azure Defender for Azure App Services -> /providers/Microsoft.Management/managementGroups/usva/providers/Microsoft.Authorization/policyDefinitions/Deploy-ASC-Defender-AppSrv

Az Comm -> [Preview]: Configure Azure Kubernetes Service clusters to enable Defender profile -> 64def556-fbad-4622-930e-72d1d5589bf5
Az Gov -> Configure Azure Defender for Kubernetes to be enabled -> /providers/Microsoft.Authorization/policyDefinitions/133047bf-1369-41e3-a3be-74a11ed1395a

Az Comm -> Configure Azure Defender for Key Vaults to be enabled -> 1f725891-01c0-420a-9059-4fa46cb770b7
Az Gov -> Deploy Azure Defender for AKV -> /providers/Microsoft.Management/managementGroups/usva/providers/Microsoft.Authorization/policyDefinitions/Deploy-ASC-Defender-AKV

**Screenshots**

**Comment by krnese** [comment]
Thank you for submitting this issue. There are currently a few built-in policies missing in Gov that we will track. We will create a short-term fix to ignore these for now, and re-enable once available. (The resourceId is the same across public and gov)

**Comment by techdawg70** [comment]
Running through the ARM template selecting all options but deselecting the recommended option to deploy ASC still fails with the same error.

BTW - As I mentioned, via Azure Gov tenant portal -> Policy -> Definitions -> search field -> past each ID as noted in the error and NONE are found in Az Gov. Doing so in Az Comm via my AIRS subscription I do find the IDs. Additionally, I searched Az Gov based on the name and again didn't find parity. That said - as I documented above I did find the policies in Az Gov which I believe achieve the same result as the ones in Az Comm which is why I documented those for you in the hopes it would speed the resolution along faster.  This time I have also attached a screenshot.

![2021-11-17_10-09-23](https://user-images.githubusercontent.com/22530519/142226695-c541903f-532c-4359-9abb-ac42b942e48d.png)
r.

**Comment by jtracey93** [comment]
Hey @techdawg70,

Can you confirm on the "Platform management, security and governance" blade this option is set to "no"?

![image](https://user-images.githubusercontent.com/41163455/142235986-55ad5b71-adc1-44d3-ad89-3f133e43af14.png)

**Comment by jtracey93** [comment]
Just an update on my looking into this, the workaround suggested above will not work due to the deployment of the policies is non-conditional in the `eslzARM.json` template: https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslzArm.json#L900 that is used by the deployment. And this is where your deployment is failing today.

We are investigating a fix internally and will come back to this thread when we have a way forward 👍

**Comment by seversen** [comment]
Just to add on to this ticket.

This is a major roadblock for my organization as we are in the process of standing up our Azure Government tenant. We have been working with Microsoft employees to build out our environment using the Cloud Adoption Framework and this is a core part of that process.

Prompt attention to this issue would be greatly appreciated.

**Comment by krnese** [comment]
Thanks @seversen. We have a fix ready and will release shortly depending on test results.

**Comment by seversen** [comment]
Any further updates on this bug or ETA for a fix to be available?

**Comment by jtracey93** [comment]
Hey @seversen this is linked to the PR #863 which is under review at this time.

It's close 👍

**Comment by seversen** [comment]
Awesome. This resolved the issues. Thanks again for the quick fix!!!
