### ISSUE TITLE
Redeployment Role Assignment Error

### ISSUE THREAD

**Issue by AlphaBun** [Azure/Enterprise-Scale#859]
Hi there, having issues with redeployment using the deploy with ARM template in the link below. The first instance of deployment works fine. Deleted all the resources groups, policy assignments, management groups and moved the subscriptions back to root tenant. But when I try to deploy the same template using the same subscription the second time I get the following error. Not sure if Im missing any other steps in the clean up process. Appreciate your guidance please. Thank you.

https://github.com/Azure/Enterprise-Scale/tree/main/docs/reference/adventureworks

![image](https://user-images.githubusercontent.com/47685752/142575503-936ba1e6-d151-4777-ae7c-96c2fbc415ee.png)

![image](https://user-images.githubusercontent.com/47685752/142575453-e1423677-54e4-4bac-953a-eb948f2e0b5b.png)

**Comment by krnese** [comment]
On the subscription used for connectivity/platform, you will likely have a dangling roleAssignment now that the policyAssignment from the LZ management group is deleted. Deleting this - followed by a re-run of the deployment should do the trick.

**Comment by AlphaBun** [comment]
Works like a charm. Thank you so much for the quick response! :)
