### ISSUE TITLE
Add missing parameters to `Deploy-Diagnostics-LogAnalytics` Policy Set Definition

### ISSUE THREAD

**Issue by krowlandson** [Azure/Enterprise-Scale#860]
<p><strong>Describe the solution you'd like</strong> </p>
<p>To allow customers to correctly configure their diagnostics settings to meet regulatory compliance scenarios (such as the <a href="https://docs.microsoft.com/en-us/azure/governance/policy/samples/ukofficial-uknhs"><code>UK OFFICIAL and UK NHS</code> Policy Set Definition</a>), we need to add missing parameters to the <code>Deploy-Diagnostics-LogAnalytics</code> Policy Set Definition provided as part of Enterprise-scale so they can configure the required settings without create custom copies of the definition. </p>
<p>An example of one of the missing parameters is given in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/207 which highlights the missing parameter needed to set <code>&quot;metricsEnabled&quot;: &quot;True&quot;</code> on the <code>KeyVaultDeployDiagnosticLogDeployLogAnalytics</code> Policy Definition. </p>
<p>As part of this, we should ideally surface all parameters for all linked Policy Definitions to allow full customisation of settings. </p>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by Springstone** [comment]
Closing this as we've deprecated all our diagnostic settings policies and shifted to the PG owned initiative to do the same. Please review https://aka.ms/alz/whatsnew for details.
