### ISSUE TITLE
Misconfigured Policy Definition

### ISSUE THREAD

**Issue by MatiasTontti** [Azure/Enterprise-Scale#864]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.0.5

**azure provider**:  2.76.0

**module**: 0.4.0 (Policy definition looks same as in 1.0.0)

### Description

**Describe the bug**

I was doing a check for our Landing Zone Policies and noticed a misconfiguration in one of the policy definitions.
Initiative Definition "Deploy Diagnostic Settings to Azure Services" has a policy called "Deploy Diagnostic Settings for Automation to Log Analytics workspace".  This policy enables diagnostic settings for Automation Account created by the module. Policy is shown as non-compliant, even though i had done the remediation successfully.

**Expected Output**
Expected output is that the policy should be compliant.

**Actual Output**
Policy is non-compliant even though the remediation was done successfully.

**Steps to Reproduce**

1. Don't set any diagnostic settings to the Automation Account created by the module.
2. Run remediation for the policy "Deploy Diagnostic Settings for Automation to Log Analytics workspace"
3. Check the compliance of the policy after evaluation scan, it should be shown as non-compliant

**Screenshots**
First screenshot shows the diagnostic settings and the policy compliance after running the remediation.
![non-compliant](https://user-images.githubusercontent.com/18305706/142649379-03622ca3-c83c-4bd5-b36d-469bcf7ec792.png)
Second screenshot show the diagnostic settings and the policy compliance when remediation is run and AuditEvent category is enabled manually.
![Compliant](https://user-images.githubusercontent.com/18305706/142649382-2cab91fe-5501-4f1e-835c-cf645d955da6.png)

**Additional context**
Policy will be shown as compliant, if AuditEvent option is chosen in Diagnostic settings of the Automation Account.
The problem would be solved if AuditEvent option is enabled in the policy definition.

**Comment by krowlandson** [comment]
Fix was proposed in https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/201 by @marcusfriede but have transferred issue to source repository.
