### ISSUE TITLE
Mooncake: New Defender policy definitions not available as built-in

### ISSUE THREAD

**Issue by faister** [Azure/Enterprise-Scale#867]
**Mooncake: New Defender policy definitions not available as built-in**

**Steps to reproduce**

1. Deploy Deploy-ASCDF-Config policy set definitions in any Azure China region.
2. The following policy definitions could not be found: 
/providers/Microsoft.Authorization/policyDefinitions/b40e7bcd-a1e5-47fe-b9cf-2f534d0bfb7d; defenderForAppServices
/providers/Microsoft.Authorization/policyDefinitions/b7021b2b-08fd-4dc0-9de7-3c6ece09faf9; defenderForArm
/providers/Microsoft.Authorization/policyDefinitions/2370a3c1-4a25-4283-a91a-c9c1a145fb2f; defenderForDns
/providers/Microsoft.Authorization/policyDefinitions/1f725891-01c0-420a-9059-4fa46cb770b7; defenderForKeyVaults
/providers/Microsoft.Authorization/policyDefinitions/64def556-fbad-4622-930e-72d1d5589bf5; defenderForKubernetesService
/providers/Microsoft.Authorization/policyDefinitions/44433aa3-7ec2-4002-93ea-65c65ff0310a; defenderForOssDb
/providers/Microsoft.Authorization/policyDefinitions/50ea7265-7d8c-429e-9a7d-ca1f410191c3; defenderForSqlServerVirtualMachines
/providers/Microsoft.Authorization/policyDefinitions/74c30959-af11-47b3-9ed2-a26e03f427a3; defenderForStorageAccounts

**Screenshots**
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PolicyDefinitionNotFound\",\r\n    \"message\": \"The policy set definition 'Deploy-ASCDF-Config' request is invalid. The following policy definitions could not be found: '/providers/Microsoft.Authorization/policyDefinitions/b40e7bcd-a1e5-47fe-b9cf-2f534d0bfb7d;/providers/Microsoft.Authorization/policyDefinitions/b7021b2b-08fd-4dc0-9de7-3c6ece09faf9;/providers/Microsoft.Authorization/policyDefinitions/2370a3c1-4a25-4283-a91a-c9c1a145fb2f;/providers/Microsoft.Authorization/policyDefinitions/1f725891-01c0-420a-9059-4fa46cb770b7;/providers/Microsoft.Authorization/policyDefinitions/64def556-fbad-4622-930e-72d1d5589bf5;/providers/Microsoft.Authorization/policyDefinitions/44433aa3-7ec2-4002-93ea-65c65ff0310a;/providers/Microsoft.Authorization/policyDefinitions/50ea7265-7d8c-429e-9a7d-ca1f410191c3;/providers/Microsoft.Authorization/policyDefinitions/74c30959-af11-47b3-9ed2-a26e03f427a3'.\"\r\n  }\r\n}"}]}}

**Comment by faister** [comment]
please feel free to assign this to me and I'll work on a PR to sort this out for mooncake, thanks

**Comment by jtracey93** [comment]
Looping in @krnese here as this is likely the same fix that is being worked on for #857 & the PR #863.

@krnese can we do a similar fix that you are heading towards in #863 for Mooncake as well? Let us know if you want @faister or myself to assist 👍

**Comment by krnese** [comment]
> please feel free to assign this to me and I'll work on a PR to sort this out for mooncake, thanks

Yes please :-) the Gov would be finalized tomorrow, and if you will, you can take the same approach and then update the do-it-yourself guidance.
