### ISSUE TITLE
Gen2 vms are not included in Enable Azure Monitor policies deployed from ESLZ accelerator

### ISSUE THREAD

**Issue by pameruoso** [Azure/Enterprise-Scale#868]
**Describe the bug**
Azure policies included in the Azure Accelerator deployment do not include Azure VMs Gen2 Images.

After deploying the accelerator in a brownfield environment with Azure Monitor option enabled, gen2 vms are not configured.

This is because the azure policies only apply to gen1 images in the array.

**Steps to reproduce**

1. Create a gen2 vm in any subscription
2. Deploy the ESLZ accelerator with azure monitor enabled and select the subscription from point 1.

Azure gen2 vms will not get the configuration regarding Azure monitor (MMA agent and diagnostic settings).

**Screenshots**

**Comment by jtracey93** [comment]
Hi @pameruoso, thanks for raising this issue. 

This is a built-in definition that we assign, so we will need to speak to the engineering teams who maintain this definition to get them to update it in the platform. 

We will reach out to them and leave this issue here for tracking 👍

**Comment by jtracey93** [comment]
Closing to track in #884 going forward
