### ISSUE TITLE
InvalidCreatePolicyAssignmentRequest - The policy definition specified in policy assignment 'Deny-Subnet-Without-Nsg' is out of scope.

### ISSUE THREAD

**Issue by seversen** [Azure/Enterprise-Scale#872]
**Describe the bug**
I received the following error during deployment of Enterprise-scale for Azure Government today. It may be a fluke but figured I would report it. I have a workaround noted in this report.

{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidCreatePolicyAssignmentRequest\",\r\n    \"message\": \"The policy definition specified in policy assignment 'Deny-Subnet-Without-Nsg' is out of scope. Policy definitions should be specified only at or above the policy assignment scope. If the management groups hierarchy changed recently or if assigning a management group policy to new subscription, please allow up to 30 minutes for the hierarchy changes to apply and try again.\"\r\n  }\r\n}"
            }
        ]
    }
}

**Steps to reproduce**

1. Deploy Enterprise-scale for Azure Government.

2. I had pretty much all options set at default in the wizard except for the following options which were declined:
    - Deploy CI/CD Pipeline
    - Azure DDoS Protection Standard
    - Azure Firewall
    - Azure VPN Gateway

3. The deployment failed after about 20 minutes with the below screenshot and included error. 

**Workaround**

I was able to get past this issue by running a new deployment with all of the exact same settings right over the top of what had already been deployed. It sounds like the operation failed because it was attempted too quickly after a management group was created.

**Screenshot**
![ESDeployError](https://user-images.githubusercontent.com/94721301/144678687-83e55d50-b151-4da1-8d74-adfbc9c60d6d.JPG)

**Comment by krnese** [comment]
Thanks - and glad it got sorted. Did you by any chance re-deploy this initially, using a management group prefix you have used in the past?

**Comment by seversen** [comment]
Yes, I was using the same prefix from past runs for the initial deploy as well as the re-deploys.

**Comment by dalejmarshall** [comment]
I've just had the same issue whilst deploying Enterprise-scale hub and spoke today, and yes I think I may have used the same prefix I have used in a past deployment that has since been deleted. Deploying again over the top of the initial deployment completed successfully.

"message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidCreatePolicyAssignmentRequest\",\r\n    \"message\": \"The policy definition specified in policy assignment 'Deny-Public-Endpoints' is out of scope. Policy definitions should be specified only at or above the policy assignment scope. If the management groups hierarchy changed recently or if assigning a management group policy to new subscription, please allow up to 30 minutes for the hierarchy changes to apply and try again.\"\r\n  }\r\n}"

**Comment by jtracey93** [comment]
Hey @dalejmarshall,

Have you been able able to retry by deploying it with exactly the same input parameters as the first run, this should resolve the issue👍

You may need to wait 5-10 mins, or even 30 as the error states, before trying the redeployment to allow the backend to update fully.

Let us know

**Comment by dalejmarshall** [comment]
Hi @jtracey93 , yes I have thank you. It worked after leaving it for around 15 minutes. Thanks.

**Comment by krnese** [comment]
This issue cannot be solved within the ESLZ implementation as it [requires backend work by Azure engineering](https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Known-Issues.md#deploying-the-reference-implementation-fails-due-to-policy--cannot-be-found-404). Leaving this open with "wontfix" label in case others are running into the same.

**Comment by jtracey93** [comment]
Closing this to track in master issue #902 for hygiene
