### ISSUE TITLE
Azure Migrate | Migrated VM | How to deploy Azure Monitor via Policy?

### ISSUE THREAD

**Issue by DaFitRobsta** [Azure/Enterprise-Scale#878]
After a VM is migrated with Azure Migrate, it is not onboarded to Azure Monitor.  The built-in policy "Deploy - Configure Log Analytics extension to be enabled on Windows virtual machines", policyRule does not match the migrated VM properties and thereby does not assign the MicrosoftMonitoringAgent extension. It appears the built-in policy is looking for the following properties:

- imagePublisher
- imageOffer
- imageSKU

And the migrated VM is missing them.

Here's a screenshot of the migrated VM.
![image](https://user-images.githubusercontent.com/49571483/146092712-1bbf3593-c518-49aa-9ccf-5487433b286b.png)

I'm looking for ESLZ guidance and/or I might have to build my own policy to align migrated VMs with native marketplace VM deployment standards.

**Comment by jtracey93** [comment]
Hey @DaFitRobsta,

Thanks for raising this. 

Is there anything listed in the property of 'Microsoft.Compute/imageId' for this VM and the others migrated?

As this could be added to the policy assignment parameter of this policy called 'listOfImageIdToInclude_linux' or 'listOfImageIdToInclude_windows' depending on which flavour it is. 

Let us know 👍

**Comment by DaFitRobsta** [comment]
Hello Jack,

When looking at a Market Place VM and a migrated VM, neither have an imageId in the Resource Graph Explorer nor when viewing the export VM template.

Robert Lightner

**Comment by jtracey93** [comment]
Thanks for the info. So from the policy rule is there any condition it would match against that you can see?

Or are none of those properties checked actually present for the migrated VM?

**Comment by jtracey93** [comment]
Linking this with #868 as it's a similar query in terms of the policy rule `if` rules for this initiative & definitions

**Comment by jtracey93** [comment]
Closing to track in #884 going forward
