### ISSUE TITLE
Azure Monitor for VMs - Various Issues/Feature Requests

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#884]
<h1 id=summary>Summary </h1>
<p>This issue combines multiple issues and feedback received in relation to Azure Monitor agents (Log Analytics &amp; Dependency agents) for VMs in ESLZ into a single issue for ease of tracking and updates. </p>
<h2 id=linkedissues>Linked Issues </h2>
<ul>
<li>#878 </li>
<li>#868 </li>
<li>#998 </li>
<li>#1300 </li>
</ul>
<h2 id=others>Others </h2>
<ul>
<li>Server 2022 support for <a href="https://www.azadvertizer.net/azpolicyinitiativesadvertizer/55f3eceb-5573-4f18-9695-226972c6d74a.html">Enable Azure Monitor on VMs policy initiative</a> </li>
</ul>
<blockquote>
  <p>Other issues may be added over time to this in an effort to consolidate efforts </p>
</blockquote>

**Comment by paulgrimley** [comment]
Currently working with the Azure Monitor product group to determine potential fixes / solutions to these.

**Comment by paulgrimley** [comment]
Just in the way of a quick update on these, I am working with the respective product groups to progress.

As regards the Azure Migrate issue we are trying to locate the team who manage custom image metadata provisioning.

For the Gen2 and Windows 2022 we are in discussions with the team who manage the agents and are discussing options around AMA suitability and timescales.

If anyone else is experiencing issues related to any of these please respond to this thread so we can capture these.

Thanks
Paul

**Comment by kevinevans1** [comment]
Hello

Just to highlight my customers are running into the same issues when deploying Gen2 or Server 2022 virtual machines against Enterprise-scale best practices. (Azure policy enforcement) 

timelines for the new AMA agent would be appreciated.  :)

**Comment by paulgrimley** [comment]
Just to provide an update on this as its been rumbling on for sometime, Monitor engineering team have confirmed they won't be adding Gen2 or Server 2022 for current built-in policy. They have confirmed that AMA will support these and they are working hard to provide parity and I expect a lot of the features to light up this CY. Please look to work with your Microsoft counterparts to help planning your migration from MMA to AMA.

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by arjenhuitema** [comment]
The AMA work has been completed. All linked issues have been reviewed and resolved.
