### ISSUE TITLE
Azure Firewall Policy tier is Standard when using Azure Firewall Premium SKU

### ISSUE THREAD

**Issue by brianabrams** [Azure/Enterprise-Scale#889]
If you select premium for firewallSku when deploying a 'Hub and spoke with Azure Firewall' architecture, the deployed Azure Firewall Policy tier is configured as Standard instead of Premium.

**Comment by jtracey93** [comment]
Hey @brianabrams, 

Thanks for raising this. 

A standard policy is supported with a premium FW as documented here: https://docs.microsoft.com/en-us/azure/firewall-manager/policy-overview#standard-and-premium-policies

But I take it you are looking for these features on the policy that are missing?

- TLS Inspection
- Web Categories
- URL Filtering
- IDPS

I will start work on a PR to fix this shortly

Thanks

Jack
