### ISSUE TITLE
delegated subnet, created by blueprint, does not allow actions of service; blocked by deny assignment

### ISSUE THREAD

**Issue by phwecker** [Azure/Enterprise-Scale#891]
**Describe the bug**
when creating a vnet via a blueprint, and create a subnet delegated to e.g. app service, a downstream "create vnet integration" operation fails due to the "deny assignment" applied by the blueprint.

is there a way to create a vnet with delegated subnets through blueprints and allow after-the-fact operations by the respective services?

in particular the issue manifests when the vnet is deployed via a blueprint as part of a "landingszone" approach, and then an app service tries to create a vnet integration into that respective vnet. 

question is, whether or not there is a workaround to make this possible or the only way would be to move off blueprints for this usecase. 

**Steps to reproduce**

**Screenshots**

**Comment by jtracey93** [comment]
Hi @phwecker,

Thanks for raising the issue. Can you confirm this is related to Enterprise Scale, as in Enterprise Scale we do not utilise Blueprints.

So it may be that this isn't the correct place for your query.

Can you provide some screenshots or error messages so we can help confirm if this is related to Enterprise Scale or not?

Thanks

Jack

**Comment by phwecker** [comment]
hi @jtracey93 , i was asked to create an entry here for this topic. i am aware that ES does not use blueprints, but as i understand the reasoning was that there might be workaround suggestions from this group available. 

the core issue seems to be the deny assignment used by blueprints, that allow creation of resources like NICs, but do not allow the steps necessary for the app service vnet integration to get enabled (subnet delegation). 

the associated error seems to indicate as much. 

The client 'michael.med-lz@ritccoedev.onmicrosoft.com' with object id '###' has permission to perform action 'Microsoft.Network/virtualNetworks/subnets/write' on scope '###'; however, the access is denied because of the deny assignment with name 'Deny assignment '###' created by Blueprint Assignment '/subscriptions/###/providers/Microsoft.Blueprint/blueprintAssignments/mm-blueprint'.' and Id '###' at scope '###'."

**Comment by jtracey93** [comment]
Hey @phwecker,

Understood. I have reached out to you offline so we can discuss this further.

But as this is not ESLZ related I will close this issue here to avoid confusion.

Thanks

Jack
