### ISSUE TITLE
Policy: Deploy-Diagnostics-MlWorkspace doesnt work - BadRequest

### ISSUE THREAD

**Issue by jkorterink** [Azure/Enterprise-Scale#893]
**Describe the bug**

The policy Deploy-Diagnostics-MlWorkspace (part of Initiative Definition Deploy-Diagnostics-LogAnalytics)  doesn't work. When a Machine Learning workspace is created/updated the DeployIfNotExists operation failed:

`"properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": "00000000-0000-0000-0000-000000000000",
        "statusMessage": "{\"code\":\"BadRequest\",\"message\":\"Metric category 'Run' is not supported, supported categories are: 'AllMetrics'.\"}",
        "eventCategory": "Administrative",
        "entity": "/subscriptions/xxx/resourcegroups/rg-machinelearning/providers/Microsoft.MachineLearningServices/workspaces/ml-diagdemo/providers/Microsoft.Insights/diagnosticSettings/setbypolicy",
        "message": "Microsoft.Insights/diagnosticSettings/write"
    }`

**Steps to reproduce**

1. Deploy and assign Initiative Definition "Deploy Diagnostic Settings to Azure Services"
2. Deploy / update a Machine Learning workspace
3. Wait till DeployIfNotExist action is running
4. Error: Metric category 'Run' is not supported, supported categories are: 'AllMetrics'.

**Screenshots**

![Deploy-Diagnostics-MlWorkspace](https://user-images.githubusercontent.com/2323352/149947947-ba5e9d43-89fa-4ac4-943d-a38346b5f535.jpg)

**Comment by jtracey93** [comment]
Thanks @jkorterink for raising. Assigning this to @jfaurskov to triage and provide update 👍
