### ISSUE TITLE
Databricks Policies Assignments Failing ("out of scope")

### ISSUE THREAD

**Issue by villeodell** [Azure/Enterprise-Scale#901]
**Describe the bug**
For new deployments via the portal experience, the databricks polices fail as the policy definitions as specified in policy assignment is "out of scope".

**Steps to reproduce**

1. Deploy ESLZ via the portal experience
2. Opt out of identity, connectivity configs to mimic Wingtip (have not tested with alternate options to know if this has any effect or not).

I have deployed two times with the same result.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/38110594/152003783-7b7a0b18-b224-4960-b927-33a1f44db9b5.png)

The error is the same for the three policies:

 ```
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidCreatePolicyAssignmentRequest\",\r\n    \"message\": \"The policy definition specified in policy assignment 'Deny-DataB-Sku' is out of scope. Policy definitions should be specified only at or above the policy assignment scope. If the management groups hierarchy changed recently or if assigning a management group policy to new subscription, please allow up to 30 minutes for the hierarchy changes to apply and try again.\"\r\n  }\r\n}"
            }
        ]
    }
}

```

**Comment by jtracey93** [comment]
linking to #872

**Comment by villeodell** [comment]
Confirming that re-running with same inputs fixed everything. Thank you for the guidance to resolve!
