### ISSUE TITLE
AzOps deployment uses a Powershell script external to this repository

### ISSUE THREAD

**Issue by jovadker** [Azure/Enterprise-Scale#912]
**Describe the bug**
AzOps deployment (\eslzArm\resourceGroupTemplates\azOpsArm.json) uses a PowerShell script that is located outside of this repository. The url is base64 encoded and it refers to https://raw.githubusercontent.com/krnese/ns/master/umiAzOpsSetup.ps1

**Steps to reproduce**

1. Open up the azOpsArm.json
2. Look for the line 127 having that reference

**Screenshots**
![image](https://user-images.githubusercontent.com/24881415/153439112-dc6029ce-f926-4be6-ae3c-b386dd1c7ac2.png)

**Comment by daltondhcp** [comment]
Thank you for reporting this @jovadker - we will take action and move it to a Microsoft managed repository.
