### ISSUE TITLE
ESLZ forked to a private repository - linked templates

### ISSUE THREAD

**Issue by jovadker** [Azure/Enterprise-Scale#913]
**Describe the solution you'd like**
If Enterprise-Scale repository is forked to a private repository (Azure DevOps Services or GitHub), the deployment of the ESLZ is not possible, because the ARM templates are not publicly available. One of the common approaches to deploy such ARM templates with linked templates is to copy them to an Azure Storage and then create a SAS token to access that particular Azure Storage Files container. This can be done by introducing an additional parameter in eslzArm.json that holds the SAS token and that will be passed over to all the linked template URIs:
"deploymentUris": {
            "managementGroups": "[concat(uri(deployment().properties.templateLink.uri, 'managementGroupTemplates/mgmtGroupStructure/mgmtGroups.json'), parameters('containerSasToken'))]",

The other option would be to reduce the size of the eslz in order to use Azure TemplateSpecs as a staging storage for the landing zone.

Would it be possible to introduce the placeholder for that shared access signature token in eslzArm.json?

**Comment by jtracey93** [comment]
Hey @jovadker,

Thanks for raising the issue. The ARM templates here are really to support the Portal experience we have and are not engineered for ideal consumption via manual ARM deployments.

However we have just released our bicep versions (in preview) of ALZ/ESLZ which I highly recommend you check out instead. https://github.com/Azure/ALZ-Bicep

And you can, if needs be, compile these via `bicep build` to get ARM templates, however native Bicep is the way I would go 👍

Going to close this issue as this is not something we would consider I'm afraid. But hopefully the Bicep approach can meet your requirements 👍
