### ISSUE TITLE
Missing mandatory custom policies in repo

### ISSUE THREAD

**Issue by EMSanlioglu** [Azure/Enterprise-Scale#927]
It seems like there are missing custom policies for Enterpise Scale. We're not able to find them in this repo. The policies are listed in https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md

**Mandatory policies:** 
* Deploy the configuration to the Log Analytics workspace in the subscription
* Deploy DNS Zone Group for Storage-Table Private Endpoint
* Deploy DNS Zone Group for SQL Private Endpoint
* Deploy DNS Zone Group for Storage-Queue Private Endpoint
* Deploy DNS Zone Group for Key Vault Private Endpoint
* Deploy DNS Zone Group for Storage-File Private Endpoint
* Deploy DNS Zone Group for Storage-Blob Private Endpoint

**Optional, recommended policies:** 
* Deploy Diagnostics settings for Azure Data Lake store to Log Analytics workspace
* Deploy Diagnostics settings for Analysis Services for FHIR to Log Analytics workspace
* Deploy Log Analytics workspace

**Comment by jtracey93** [comment]
Hi @EMSanlioglu,

Thanks for raising this issue.

I think the majority of these policies are built-in policies, hence why you cannot find them as custom. This was detailed here: https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#policy-7

> Using AzAdvertizer you can search for all these policies, including ESLZ policies. Here is a link to look for all policies about DNS Zones: https://www.azadvertizer.net/azpolicyadvertizer_all.html#%7B%22col_3%22%3A%7B%22flt%22%3A%22dns%20zones%22%7D%7D

#### Mandatory policies:

| Policy | Answer |
| ------ | -------- |
| Deploy the configuration to the Log Analytics workspace in the subscription | Removed as per [July Whats New Notes](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#policy-7) |
| Deploy DNS Zone Group for Storage-Table Private Endpoint | No built-in or custom available today. Can author your own custom following the below instructions. |
| Deploy DNS Zone Group for SQL Private Endpoint | No built-in or custom available today. Can author your own custom following the below instructions. |
| Deploy DNS Zone Group for Storage-Queue Private Endpoint | No built-in or custom available today. Can author your own custom following the below instructions. |
| Deploy DNS Zone Group for Key Vault Private Endpoint | [Built-in - ac673a9a-f77d-4846-b2d8-a57f8e1c01d4](https://www.azadvertizer.net/azpolicyadvertizer/ac673a9a-f77d-4846-b2d8-a57f8e1c01d4.html) |
| Deploy DNS Zone Group for Storage-File Private Endpoint | No built-in or custom available today. Can author your own custom following the below instructions. |
| Deploy DNS Zone Group for Storage-Blob Private Endpoint| No built-in or custom available today. Can author your own custom following the below instructions. |

> For the DNS Zone policies that are missing from built-in today you can create your own custom by copying one of the other existing policies and setting the correct GroupID in the policy if logic. You can see an example here for blob: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale#policy-definitions (in step 3). 
> All the GroupID's are listed here: https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#private-link-resource

#### Optional Policies

| Policy | Answer |
| ------ | -------- |
| Deploy Log Analytics workspace | [Built-in - 8e3e61b3-0b32-22d5-4edf-55f87fdb5955](https://www.azadvertizer.net/azpolicyadvertizer/8e3e61b3-0b32-22d5-4edf-55f87fdb5955.html?desc=compareJson&left=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2F8e3e61b3-0b32-22d5-4edf-55f87fdb5955_1.0.0.json&right=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2F8e3e61b3-0b32-22d5-4edf-55f87fdb5955_2.0.0.json) |
| Deploy Diagnostics settings for Azure Data Lake store to Log Analytics workspace | [Built-in - d56a5a7c-72d7-42bc-8ceb-3baf4c0eae03](https://www.azadvertizer.net/azpolicyadvertizer/d56a5a7c-72d7-42bc-8ceb-3baf4c0eae03.html) - Also part of policy set initiative - https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Diagnostics-LogAnalytics.html|
| Deploy Diagnostics settings for Analysis Services for FHIR to Log Analytics workspace | [Custom ESLZ Policy - Deploy-Diagnostics-ApiForFHIR](https://www.azadvertizer.net/azpolicyadvertizer/Deploy-Diagnostics-ApiForFHIR.html) - Also part of policy set initiative - https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Diagnostics-LogAnalytics.html | 

Hope this helps and we are always happy for contributions for the missing policies if you wish to contribute 👍

**Comment by EMSanlioglu** [comment]
Hi @jtracey93,

Thank you for your quick response. I'll create my own definitions regarding DNS Zone Group. 

The answer for built-in policy "Deploy Diagnostics settings for Azure Data Lake store to Log Analytics workspace" seems like it is for another policy, "Deploy Diagnostic Settings for Data Lake Analytics to Log Analytics workspace". 

https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md#policies-included-in-enterprise-scale-landing-zones-reference-implementations shows that there are 2 policies for Data Lake. 

Policy | Description | Missing?
-- | -- | --
Deploy Diagnostics settings for Data Lake to Log Analytics workspace | Deploys the diagnostics settings for Data Lake, and connects to a Log Analytics workspace | No
Deploy Diagnostics settings for Azure Data Lake store to Log Analytics workspace | Deploys the diagnostics settings for Azure Data Lake store, and connects to a Log Analytics workspace | Yes


The same goes for built-in policy "Deploy Diagnostics settings for Analysis Services for FHIR to Log Analytics workspace" seems like it is for another policy, "Deploy Diagnostic Settings for Azure API for FHIR to Log Analytics workspace". 

https://github.com/Azure/Enterprise-Scale/blob/main/docs/ESLZ-Policies.md#policies-included-in-enterprise-scale-landing-zones-reference-implementations shows that there are 2 diagnostic setting policies for FHIR. 

Policy | Description | Missing?
-- | -- | --
Deploy Diagnostics settings for Azure API for FHIR to Log Analytics workspace | Deploys the diagnostics settings for Azure API for FHIR, and connects to a Log Analytics workspace | No
Deploy Diagnostics settings for Analysis Services for FHIR to Log Analytics workspace | Deploys the diagnostics settings for Analysis Services, and connects to a Log Analytics workspace | Yes

**Comment by jtracey93** [comment]
Hey @EMSanlioglu,

No worries at all. Feel free to contribute those policies back if you wish via a PR 👍

As for the data lake question. ADLS gen 2 is based on Azure Storage accounts using blob as documented here https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction. So the existing policy for blob diagnostic will work here.

As for the "Deploy Diagnostics settings for Analysis Services for FHIR to Log Analytics workspace" could you tell me what service or point me to the docs for the service you want this policy for so i can assist further?

Thanks

**Comment by EMSanlioglu** [comment]
Sure, I could do that, @jtracey93 

Regarding "Deploy Diagnostics settings for Analysis Services for FHIR to Log Analytics workspace", I don't have any use case for that service. I was just trying to implement all recommended policies for our platform.

**Comment by jtracey93** [comment]
Thanks. 

FHIR is specifically for the healthcare industry, so may not be required in your situation; hence this being optional. https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/overview

Hopefully that clears everything up for you. If so, can we close out this issue?

**Comment by EMSanlioglu** [comment]
Thank you for clarification!

We can close this issue :)
