### ISSUE TITLE
Connectivty Subscription not moved to the connectivity management group during vWAN deployment.

### ISSUE THREAD

**Issue by autocloudarc** [Azure/Enterprise-Scale#932]
**Describe the bug**
The connectivity subscription selected doesn't get placed into the corresponding connectivity management group.

**Steps to reproduce**

1. Deploy the Contoso reference implementation.

**Screenshots**

![no-connectivity-subscription-placement](https://user-images.githubusercontent.com/15109536/157259209-b8e34e74-ba0d-4e5b-9bb7-f89916dd4467.jpg)

**Comment by jtracey93** [comment]
Investigating

**Comment by jtracey93** [comment]
Hey @autocloudarc,

Have just tested a VWAN deployment myself and it seems to be working fine.

![image](https://user-images.githubusercontent.com/41163455/157291535-36562865-b60b-45f5-9987-51dd1a27e737.png)

Could you check your connectivity management group deployments to share the status of this deployment, if it exists?

![image](https://user-images.githubusercontent.com/41163455/157292008-da5e637e-bf4b-4dd9-b086-a192f9795f7a.png)

Could you also share the link you used to open the ALZ Accelerator (Portal deployment experience) so I can check that.

Also, if you can share a correlation ID that will help me investigate this further, but this doesn't seem like a bug from my testing.

Thanks

Jack
