### ISSUE TITLE
AzOps CI/CD setup support for GitHub Enterprise Managed Users

### ISSUE THREAD

**Issue by autocloudarc** [Azure/Enterprise-Scale#936]
**Describe the solution you'd like**

AzOps support for Integration with GitHub Enterprise Managed Users (EMU) solution (The public github.com solution is ok).

**Comment by jtracey93** [comment]
@autocloudarc, this is supported. Just not from the portal accelerator experience.

You need to just configure AzOps manually on GitHub Enterprise. Following the instructions https://github.com/azure/azops/wiki/github-actions 

I see this is also mentioned on the issue in the AzOps repo here: https://github.com/Azure/AzOps/issues/576
