### ISSUE TITLE
Bug Report - Role Assignment to MS Graph Changes

### ISSUE THREAD

**Issue by hanchoi** [Azure/Enterprise-Scale#939]
**Describe the bug**
API calls got migrated to Microsoft Graph so assigning root permission to user is not working 

**Steps to reproduce**

run either
1.  powershell cmdlet : New-AzRoleAssignment -Scope '/' -RoleDefinitionName 'Owner' -ObjectId $user.Id 
2. or bash script : az role assignment create --scope '/' --role 'Owner' --assignee-object-id $(az ad signed-in-user show --query objectId) --assignee-principal-type User

**Screenshots**
![image](https://user-images.githubusercontent.com/3829473/158927345-0456b2f1-cb49-4903-984b-a0f4819ff77b.png)

**Related page **
https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md
https://docs.microsoft.com/en-us/answers/questions/433662/user-dont-have-authorization-to-perform-action-39m.html

**Comment by jtracey93** [comment]
Hey @hanchoi,

Thanks for raising this issue. I have tested the commands as shown here (https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md) this morning and they work correctly as expected.

From the "Forbidden" error you are seeing; it looks like you have elevated your user logged into the cli/pwsh session as per: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md#1-elevate-access-to-manage-azure-resources-in-the-directory

Could you try following the elevation as above and logout and back in to the cli/pwsh and try again. If you get the same error please do the following in powershell:

```pwsh
$DebugPreference='Continue'
New-AzRoleAssignment -Scope '/' -RoleDefinitionName 'Owner' -ObjectId $user.Id
```

You will see a more verbose output and a more descriptive error message in the body returned from the API, like the example shown below (for a different error):
![image](https://user-images.githubusercontent.com/41163455/159247701-3b3148f4-d665-4cc5-a90b-e83bc331f7d9.png)

Let us know

Thanks

Jack

**Comment by hanchoi** [comment]
Hi Jack, thanks a lot for the response. I think my error msg above was due to my mistake not specifying AzTenant since my account is connected to multiple tenants
Now I found it working after running [Set-AzContext](https://docs.microsoft.com/en-us/powershell/module/az.accounts/Set-AzContext?view=azps-7.3.2)

But one thing I found was, the type of (Get-AzContext).Account is User, not UPN. Is this something that module version changed and it should be modified accordingly? 
![image](https://user-images.githubusercontent.com/3829473/159684940-c53c1889-7b52-45f3-9a9b-4c0ccbf4d2c7.png)

**Comment by jtracey93** [comment]
Great news @hanchoi 👍

The guidance here (https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md#2-grant-access-to-user-andor-service-principal-at-root-scope--to-deploy-enterprise-scale-reference-implementation) accounts for SPNs also with different commands for finding the SPNs Object ID that is needed for the RBAC assignment.

As for the `Get-AzContext` command itself this is not something we look after in ESLZ, we just use it. So would recommend creating an issue on that repo (https://github.com/Azure/azure-powershell) if you wish to take this further on that command.

**Comment by hanchoi** [comment]
Thanks a lot for the response @jtracey93, I do understand the limitation of managing the code up to date ;). Let me send an pull request with the working code (for now)
