### ISSUE TITLE
Documentation Update - Azure Firewall, DDOS, WAF, and other Network Security services should be "recommended" instead of "optional"

### ISSUE THREAD

**Issue by ataghiyev** [Azure/Enterprise-Scale#941]
Looking at the Enterprise-Scale deployment examples, the architecture diagram contain Azure Firewall, WAF, DDOS, and other Network Security services while the corresponding text has these as "optional". I think it is a better approach and delivers a different (stronger) message if "optional" were to be changed to "recommended" for any security services mentioned in the public docs.

**Comment by jtracey93** [comment]
Thanks @ataghiyev,

Could you provide some links and screenshots of this so we can consider?

However, we take the stance of optional from an "Azure" offering perspective as customers may choose to use 3rd party alternatives for these. Hence stating optional instead of recommended.

Hope that helps

Thanks

Jack

**Comment by ataghiyev** [comment]
Thanks @jtracey93!

Here is just one example: https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md 

Under "What will be deployed?", the documentation states

An Azure Subscription dedicated for connectivity, which deploys core Azure networking resources such as:
- Azure VWAN
- VWAN Hub
- ExpressRoute Gateway (optional)
- VPN Gateway (optional)
- Azure Firewall (optional)
- Firewall Policies (optional)
- Azure DDoS Standard protection plan (optional)

I completely understand your stance - customers may choose to go with the 3rd party but we either need to then add some clarification/note on that or we can say looking from an "Azure" perspective (without any visibility into customers' 3rd party alignment) we recommend these services to be deployed as a standard. I feel like "optional" carries a different meaning and can be misunderstood as "being nice to have" and it's different from "you need to have" (or have something similar aka 3rd party) if we are offering them best practices. 

Hope this makes sense.

**Comment by jtracey93** [comment]
Thanks @ataghiyev, do you want to open a PR and contribute a suggestion on this wording. Now that you are aware of our perspective?

**Comment by jtracey93** [comment]
stale
