### ISSUE TITLE
Where is the GitHub Personal Access Token (PAT) used in this project

### ISSUE THREAD

**Issue by rahul-ve** [Azure/Enterprise-Scale#942]
Hi team,

What all workflows and tasks is the GitHub Token used for?
I don't see it being stored in the secrets, only the below four values are saved to the secrets. 

```
  ARM_CLIENT_ID
  ARM_TENANT_ID
  ARM_SUBSCRIPTION_ID
  ARM_CLIENT_SECRET

```

There are few places where the token is referenced but I don't see it's use:
```
.github/workflows/pull.yml:60:  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
.github/workflows/update.yml:47:        token: ${{ secrets.WORKFLOW_TOKEN }}
.github/workflows/update.yml:60:        token: ${{ secrets.GITHUB_TOKEN }}
.github/workflows/update.yml:122:        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
.github/workflows/validate.yml:90:          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

The reason for asking this question is due to the fact that GitHub PATs are linked to personal accounts and if this PAT is used for long term workflow tasks, we would like this to be generated under a non-user account. 

Thanks,
Rahul

**Comment by uday31in** [comment]
PAT token is only used to create initial GitHub repo as a part of portal provisioning and not used as a part of any workflow.
