### ISSUE TITLE
ES Portal Accelerator - Creates privatelink.datafactory.azure.com (wrong)

### ISSUE THREAD

**Issue by omgitsjocke** [Azure/Enterprise-Scale#944]
Hi,

During ES portal accelerator deployment (adventureworks) we decided to have private link domains provisioned.
Now we have discovered that privatelink.datafactory.azure.com was created, it's supposed to be privatelink.datafactory.azure.net according to documentation.

![image](https://user-images.githubusercontent.com/40201598/161822036-34129a1f-f915-4a41-87b5-7df034167663.png)

[Documentation ](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns)states:
<html>
<body>

Azure Data Factory (Microsoft.DataFactory/factories) / dataFactory | privatelink.datafactory.azure.net | datafactory.azure.net
-- | -- | --

</body>
</html>

Verified in Azure by checking domain used for creating a Private Endpoint for ADF:
![image](https://user-images.githubusercontent.com/40201598/161822531-37baebd8-b270-4684-b434-f3e422a9593c.png)

We did the deployment at 15/3 in case it's already fixed, could not find any open nor closed issues on this.

**Comment by jtracey93** [comment]
Thanks for raising this @omgitsjocke 👍

We will review all the Private DNS Zones are correct as per the docs https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns#azure-services-dns-zone-configuration and get this updated ASAP 👍

Thanks

Jack
