### ISSUE TITLE
[2nd May 2022] ALZ (ESLZ) External Community Call

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#949]
We are excited to invite you to our 3rd external Azure Landing Zones community call on the 2nd of May @ 17:30 CET! (16:30 UK/BST - 11:30 EST - 08:30 PST - 01:30 ACT)

> As always this will be recorded and published to YouTube and shared via our [community calls wiki page](https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls) 👍

As before we have an open agenda, so please comment below with things you would like to cover or any questions you have👍

### Agenda:

- Azure Landing Zones news roundup and updates
- ALZ Bicep overview
- Tailoring Azure Landing Zones & Archetypes
- Q&A (please raise topics and questions to discuss in this issue)

### Registration

**Sign up for the call** [here!](https://teams.microsoft.com/registration/v4j5cvGGr0GRqy180BHbRw,wgHao85GuUi3w7EobmVFaQ,2FLe236n0UOvrLWsfJLyEA,GUxhNIO_3E-U7d8DiZSqGA,ytOJ6GH510uU7_ZKmpyyWg,1QUOph6kgEubyCUilihDTA?mode=read&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)

🔔**NEW REGISTRATION LINK DUE TO LAST ONE NOT WORKING CORRECTLY - PLEASE RE-REGISTER**🔔

### Round-up

We look forward to another interactive discussion with lots interesting topics!

**For links to our previous community calls see:** [https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls](https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls)

**Comment by johnlokerse** [comment]
Hey @jtracey93, I am unable to sign up using the registration link (on mobile). I get the message: “The corresponding webinar was not found.”

**Comment by jtracey93** [comment]
> Hey @jtracey93, I am unable to sign up using the registration link (on mobile). I get the message: “The corresponding webinar was not found.”

Odd as I have seen others register. Let me investigate 👍

**Comment by jtracey93** [comment]
Have had to raise a support ticket internally as doing the same for me @johnlokerse this morning after working fine for the last few days. I'll keep you posted via this chat👍

**Comment by jtracey93** [comment]
Just an update here, this is still being investigated internally by our Teams support teams. Hopefully will be resolved soon 👍

**Comment by jtracey93** [comment]
@johnlokerse we have a new link, please sign up.

To everyone else that signed up, you will need to re-register, please use this [link](https://teams.microsoft.com/registration/v4j5cvGGr0GRqy180BHbRw,wgHao85GuUi3w7EobmVFaQ,2FLe236n0UOvrLWsfJLyEA,GUxhNIO_3E-U7d8DiZSqGA,ytOJ6GH510uU7_ZKmpyyWg,1QUOph6kgEubyCUilihDTA?mode=read&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)

I will send an e-mail to all those that registered previously also to ensure we don't miss anyone

**Comment by kishoreg2** [comment]
The signup link is not accepting personal email addresses, it is looking for a Microsoft login.

**Comment by jtracey93** [comment]
> The signup link is not accepting personal email addresses, it is looking for a Microsoft login.

I have just tested with my own personal email address and it worked fine. 

Could you share a screenshot of this error?

**Comment by kishoreg2** [comment]
Below is the error, I tried signing up using private window and it worked fine. The issue seems to be occurring when you have already logged in with corp m3665 credentials.

<img width="879" alt="ESLZ signin" src="https://user-images.githubusercontent.com/1876097/165456207-b734c2c8-13a0-4e2f-b80c-fa8f55ca9e61.png">

**Comment by jtracey93** [comment]
Glad you got it solved @kishoreg2

**Comment by jtracey93** [comment]
Thanks everyone who attended the recording and slides can be found here: https://github.com/Azure/Enterprise-Scale/wiki/Community-Calls

Short link: https://aka.ms/alz/community
