### ISSUE TITLE
Bug Report - Issues deploying to Sweeden Central

### ISSUE THREAD

**Issue by martydevlin** [Azure/Enterprise-Scale#951]
<p><strong>Describe the bug</strong>
Unable to deploy hub and spoke reference architecture (arm templates) to Sweden Central </p>
<p><strong>Steps to reproduce</strong> </p>
<ol>
<li>Deploy enterprise at scale - hub and spoke arm templates to Sweden Central </li>
<li>Able to discuss / supply logs </li>
<li>NB - Sweden Central is a new Region probably missing services from my own troubleshooting - <a href="https://docs.microsoft.com/en-us/azure/automation/how-to/region-mappings">Supported regions for linked Log Analytics workspace | Microsoft Docs</a> we may need to build this into our validation checking for all deployment methods. </li>
</ol>
<p><strong>Screenshots</strong> </p>

**Comment by jtracey93** [comment]
Hi @martydevlin,

Can you provide some information about what is not working here for you so we can assist further?

Thanks

Jack

**Comment by jtracey93** [comment]
Also @martydevlin was the issue around VNET deployment by any chance and related to this https://github.com/Azure/Enterprise-Scale/issues/881 ?

Let us know or provide a correlation ID and we can investigate further (https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal#correlation-id-and-support) 👍

**Comment by jtracey93** [comment]
Spoke with @martydevlin offline as FTE.

He will send me a list of things that were causing issues, but this is primarily related to not being able to link to LAW & Automation account in Sweeden Central today as not supported (https://docs.microsoft.com/en-us/azure/automation/how-to/region-mappings)

This is something we cannot resolve ourselves as requires PG teams to enable capabilities. 

May add a note to portal experience about supported regions for LAW & Auto linking?

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by Springstone** [comment]
Closing this issue as linking automation account to Log Analytics workspaces is no longer required for ALZ, only required for legacy update management, change tracking and start/stop vms v1. Deployment to Sweden Central works as expected.
