### ISSUE TITLE
Clarification Request on policies

### ISSUE THREAD

**Issue by FPMilan** [Azure/Enterprise-Scale#956]
In the ESLZ-Policies.md is no information which policies are contained in a given policy set definition (initiative).
E.g., there are 61 "Deploy Diagnostics Settings" for different resources as policy definitions.
But there is also a  Policy Set Definition for "Deploy Diagnostic Settings". Are both required?

Is the policy definition list the full list off all policies or only the ones which are not bundled into a set definition? And how to determine which policies are within each set definition?

Thanks for clarification!

**Comment by jtracey93** [comment]
Hey @FPMilan,

We are aware this is a bit of a manual task today, unfortunately. But this is something we are investigating and planning to resolve by splitting up the `policies.json` files into individual files to make it easier to read.

However, we have been working with the team behind AzAdvertizer and integrated the ESLZ policies (updated daily) into that tool to help. See here as an example: https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Diagnostics-LogAnalytics.html

![image](https://user-images.githubusercontent.com/41163455/162923055-af0f44fd-4e83-40a8-a5b5-d194eeb6ecd0.png)

You can also see the individual file approach we use here in ALZ-Bicep and ALZ Terraform: https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.json

Hope this helps

Thanks

Jack

**Comment by FPMilan** [comment]
will have a look thank you @jtracey93
