### ISSUE TITLE
Query - Unable to deploy an Application gateway within a ES LZ 

### ISSUE THREAD

**Issue by davedraffin** [Azure/Enterprise-Scale#957]
Our hybrid landing zone requires PaaS components to be protected by an Infrastructure perimeter, 

Thus to enable the ingress for external web traffic to the workload in the LZ we are looking to deploy

FrontDoor -> Application Gateway -> AppService (protected via Private Endpoints) 

Our LZ utilises the standard ES policy set in the ES github , that have a few key Policys that apply for this configuration

* prevents public IP addresses from being deployed outside of the connectivity subscription
* prevents PaaS components utilising public networking (requiring use of private endpoints)
* prevents application gateways being deployed without a WAF.

We have been unable to deploy an application gateway with this ES policy configuration as, 

**a)** V2 SKU Application gateways cannot be deployed without public IP addresses, and thus are blocked by the no public IP address policy.

With this issue 

"type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "Deny creation of Public IP Addresses",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "True",
                  "expressionKind": "Field",
                  "expression": "type",
                  "path": "type",
                  "expressionValue": "Microsoft.Network/publicIPAddresses",
                  "targetValue": "Microsoft.Network/publicIPAddresses",
                  "operator": "Equals"
                }
              ]
            },

**b)** V1 WAF Application gateways (which can use a private Front end IP address) cannot be deployed as they are not compliant with the WAF policy 
additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "Application Gateway should be deployed with WAF enabled",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "True",
                  "expressionKind": "Field",
                  "expression": "type",
                  "path": "type",
                  "expressionValue": "Microsoft.Network/applicationGateways",
                  "targetValue": "Microsoft.Network/applicationGateways",
                  "operator": "Equals"
                },
                {
                  "result": "True",
                  "expressionKind": "Field",
                  "expression": "Microsoft.Network/applicationGateways/sku.name",
                  "path": "properties.sku.name",
                  "expressionValue": "WAF_Medium",
                  "targetValue": "WAF_v2",
                  "operator": "NotEquals"
                }
              ]
            },
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/mg-hal/providers/Microsoft.Authorization/policyDefinitions/Deny-AppGW-Without-WAF",
            "policyDefinitionName": "Deny-AppGW-Without-WAF",
            "policyDefinitionEffect": "Deny",

It looks like the policy requires a V2 WAF SKU.

What is the supported configuration for protecting hybrid workloads using a Front Door and an AG?

**Comment by jtracey93** [comment]
Hi @davedraffin,

Thanks for raising this issue/query.

Are you able to share an anonymised management group hierarchy and where these policies are assigned at a high-level? Also showing where you are trying to deploy the App GW?

In the default [ALZ/ESLZ architecture](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/landing-zone/#azure-landing-zone-conceptual-architecture) we would only suggest assigning the `Deny-Public-IP` policy to the `Corp` management group. 

But modern web app workloads typically would be deployed beneath the `Online` management group which would permit the application gateway to be deployed as the public IP wouldn't be blocked by policy.

> Further recommendations for app delivery in ALZ: https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-app-delivery

Hope this helps, let us know

**Comment by davedraffin** [comment]
Hi @jtracey93 

Yep this is in the corp landing zone here's a copy of our MG group structure. All of our workloads are 'modern' with little or no use of IaaS in the estate. I presume the recommendation therefore to allow public IP's everywhere?

![image](https://user-images.githubusercontent.com/42065869/162949797-ae677fdc-7928-46e5-89f1-25acafc968ac.png)

**Comment by jtracey93** [comment]
Hi @davedraffin,

Thanks for the rapid reply.

It may be the case indeed. Especially as the other policies ensure WAF is configured and used to provide the inspection/protection capabilities. Alongside other policies like:

- Enable DDoS Protection Standard Plan on all VNETs (if using DDoS standard plan)
- Deny IP Forwarding (prevents building your own routers etc.)
- Ensure App GW use WAF
- Deny or Deploy and Append TLS requirements and SSL enforcement on resources without encryption in transit
- Public network access should be disabled for PaaS services
- etc.

These all help "secure" the workloads in different ways whilst still allowing the agility required.

Hope that helps. Will close the issue but feel free to comment or re-open if not resolved 👍
<body>


Public network access should be disabled for PaaS services
--


<br class="Apple-interchange-newline">
</body>
</html>
