### ISSUE TITLE
Bug Report - default budget on all subscriptions under the assigned scope

### ISSUE THREAD

**Issue by alancdias7** [Azure/Enterprise-Scale#958]
**Describe the bug**

When implementing the Deploy policy a "default budget on all subscriptions under the assigned scope", no result is obtained.
The policy was assigned to the managed group and later in the subscription, however, the policy is in compliance, but the budget is not created nor the subscriptions are listed.

**Steps to reproduce**

1. Assign the policy "Deploy a default budget on all subscriptions under the assigned scope" on the management group or subscriptions.

2. Check if the budget has been created.

**Screenshots**

![image](https://user-images.githubusercontent.com/53276043/163424093-192982cb-34e1-4ea1-9a70-68ac926b6672.png)

![image](https://user-images.githubusercontent.com/53276043/163424249-a3f2a330-ec84-4590-8801-eb777edf736c.png)

![image](https://user-images.githubusercontent.com/53276043/163424391-f0afcfe1-f71e-4041-b36d-cae533a14e98.png)

**Comment by jtracey93** [comment]
Hey @alancdias7,

Thanks for raising this.

I have tested this in fresh environment this morning at the policy works as expected. (see below)

### Questions for you

1. What type of subscriptions are you using? (EA/MCA/PAYG/CSP/MSDN, etc.)
2. Have you reviewed the [pre-reqs here](https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/tutorial-acm-create-budgets#prerequisites)?
3. Can you create a budget manually for the same subscriptions?
4. How long did you wait after assigning the policy and having the subscription "in scope" of the policy? It can take some time
5. Have you tried manually triggering a compliance scan on the subscription "in scope" of the policy with `Start-AzPolicyComplianceScan` more info here: https://docs.microsoft.com/en-us/powershell/module/az.policyinsights/start-azpolicycompliancescan?view=azps-7.4.0
6. Have you tried creating a remediation task once youve got non-compliant subscriptions? https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources

### Before remediating
![image](https://user-images.githubusercontent.com/41163455/163997507-f6cba893-edc6-4f5a-ba83-3db1164207b0.png)
![image](https://user-images.githubusercontent.com/41163455/163997518-0a051467-0d90-40a6-9756-a123d2992634.png)
![image](https://user-images.githubusercontent.com/41163455/163997523-b35aaa61-7f64-48b9-98ea-3e81690905b1.png)
![image](https://user-images.githubusercontent.com/41163455/163997535-b8e1b00a-5b4c-4b4e-8f22-14028162e865.png)
![image](https://user-images.githubusercontent.com/41163455/163997545-06ea19a7-4318-4863-a08e-c55900ddc97c.png)

### Remediating & Post-Remediation
![image](https://user-images.githubusercontent.com/41163455/163998184-30e3d25d-a698-47ac-b1f9-2703f29dd654.png)
![image](https://user-images.githubusercontent.com/41163455/163998198-4a377bc0-14ca-4439-a31e-f4fd665ece41.png)
![image](https://user-images.githubusercontent.com/41163455/163998213-13b461de-58ab-462f-b6b9-3d369b87c041.png)
![image](https://user-images.githubusercontent.com/41163455/163998227-a76cebf7-d864-4caf-93cb-a32651a2caca.png)
![image](https://user-images.githubusercontent.com/41163455/163998245-407667d9-42db-4ece-be67-516902e5b63a.png)
![image](https://user-images.githubusercontent.com/41163455/163998899-67f2e94c-9eb5-40cd-91ee-6b235a5e65a3.png)

### Summary

Let us know.

It may be one that you may need to raise via Azure Support so they can investigate your environment further, as the policy is working as expected in our environments.

Thanks

Jack

**Comment by jtracey93** [comment]
Closing as stale
