### ISSUE TITLE
Bug Report - Policy Deploy-Storage-sslEnforcement

### ISSUE THREAD

**Issue by Felix-Tr** [Azure/Enterprise-Scale#971]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.1.3

**azure provider**: >= 2.20, < 3.0.0

**module**: archetypes

### Description

The Policy is used to enforce the Recommendation _Secure transfer to storage accounts should be enabled_ but causes an Error because of the following miss-match regarding the resource type.

[Line 66](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/5cbcbe27006144f54a4310383be41342fa98cbe9/modules/archetypes/lib/policy_definitions/policy_definition_es_deploy_storage_sslenforcement.json#L66):

```          "type": "Microsoft.DBforPostgreSQL/servers",
          "existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Storage/storageAccounts/supportsHttpsTrafficOnly",
                "equals": "true"
              },
              {
                "field": "Microsoft.Storage/storageAccounts/minimumTlsVersion",
                "equals": "[parameters('minimumTlsVersion')]"
              },
              {
                "field": "Microsoft.Storage/storageAccounts/supportsHttpsTrafficOnly",
                "equals": "false"
              }
            ]
          },
```

should be:

```
          "type": "Microsoft.Storage/storageAccounts",
          "existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Storage/storageAccounts/supportsHttpsTrafficOnly",
                "equals": "true"
              },
              {
                "field": "Microsoft.Storage/storageAccounts/minimumTlsVersion",
                "equals": "[parameters('minimumTlsVersion')]"
              }
            ]
          },
```

to correct the type and only set the existenceCondition=True if secure transfer (supportsHttpsTrafficOnly) is enabled

1. apply module
2. wait for provisioning of resources
3. check policy compliance in the azure portal

**Screenshots**

![image](https://user-images.githubusercontent.com/51694852/166928817-22cffbce-0c87-4907-a9bf-1cc573cf4d9c.png)

**Comment by krowlandson** [comment]
@Felix-Tr thank you for logging this issue.

I've moved it to our upstream repository for triage where all policies are maintained for ES/ALZ.

cc: @jtracey93, @matt-FFFFFF
