### ISSUE TITLE
Update Deny-PublicPaaSEndpoints to include all PaaS Resource Types

### ISSUE THREAD

**Issue by jim-mclean** [Azure/Enterprise-Scale#975]
<p>We have a few use cases in our organization that require us to prevent public access to any resources in a subscription.  Ideally we'd just apply the <a href="https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/managementGroupTemplates/policyDefinitions/DENY-PublicEndpointsPolicySetDefinition.json">Public network access should be disabled for PaaS services</a> and call it a day.  However, it looks like this policy initiative does not cover all PaaS resources types.  Event Hubs are not in here and without reviewing all the other PaaS resource types I am not sure what else might be missing. </p>
<p>Is it possible to get this Initiative updated to comprehend all PaaS services? </p>

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2

**Comment by jtracey93** [comment]
We have done this to the latest built-in's available in #1273 🥳
