### ISSUE TITLE
Update `ESLZ-Policies.md`and Enhance with Default Assignments Also

### ISSUE THREAD

**Issue by jtracey93** [Azure/Enterprise-Scale#980]
Today `ESLZ-Policies.md` is difficult to understand, read and use to know what custom ALZ definitions are included in ALZ reference implementation.

Also, we do not detail today what are the default policy assignments and at what scope in an easy-to-read style.

We should also include links to the AzAdvertizer integration as document here in the `ALZ-Bicep` repo: https://github.com/jtracey93/ALZ-Bicep/blob/add-policy-guidance/docs/wiki/PolicyDeepDive.md#azadvertizer-integration

In this issue, we will track fixing this 👍

**Comment by jtracey93** [comment]
Tagging @paulgrimley for awareness

**Comment by jtracey93** [comment]
@tuckwelladev will be picking this up and will propose a draft of the update in a PR by the 10/06/2022 (estimate)

**Comment by ATuckwell** [comment]
@jtracey93, as discussed happy to pick this up if you can assign to me.

**Comment by skiddder** [comment]
Can't get to the PolicyDeepDive.md which is linked above (github 404 error page) - maybe missing permissions?

It would be awesome to have an overview:
- what Azure built-in Policies are available/being used by ALZ
- what additional Policies come with ALZ

Additionally, it would be great to have a way to filter that Policy list by category - i.e. showing only Policies which add resources if missing, or only network security/best-practices policies etc.

**Comment by paulgrimley** [comment]
@ATuckwell, @skiddder was the person who initiated this feedback item just fyi

**Comment by jtracey93** [comment]
@skiddder apologies see this new link https://github.com/azure/ALZ-Bicep/wiki/PolicyDeepDive#azadvertizer-integration
