### ISSUE TITLE
Bug Report - Enable DDoS Std policy does not work with managed VNets

### ISSUE THREAD

**Issue by pazdedav** [Azure/Enterprise-Scale#983]
<p><strong>Describe the bug</strong>
Certain PaaS services - we tested Databricks and AKS - manage underlying network in a specific way. In my customer environment, we have the following policy enabled (comes as part of Contoso reference implementation): </p>
<ul>
<li>Policy name: Virtual networks should be protected by Azure DDoS Protection Standard </li>
<li>Policy definition ID: <code>/providers/Microsoft.Authorization/policyDefinitions/94de2ad3-e0c1-4caf-ad78-5d47bbc83d3d</code> </li>
</ul>
<p>This is a 'Modify' policy, but it doesn't work for PaaS services mentioned above. Their VNets are then listed as <strong>non-compliant</strong> and there seems to be no way to fix it. </p>
<p><strong>Steps to reproduce</strong> </p>
<ol>
<li>Deploy Azure Databricks service in your subscription, where this policy has been assigned (in the RI, it is assigned on <code>{prefix}-landingzones</code> MG). </li>
<li>Check the compliance in the Azure Policy - Compliance blade. </li>
</ol>
<p><strong>Screenshots</strong>
<img src="https://user-images.githubusercontent.com/12873988/172202371-0c48b319-687b-40bd-8f53-9c0ce2bdc2e4.png" alt=image> </p>

**Comment by jtracey93** [comment]
Thanks for raising awareness of this @pazdedav.

Do you get any error messages when trying to remediate the policy or enable DDoS on the VNET manually? (share any correlation IDs 👍)

**Comment by jtracey93** [comment]
Any updates @pazdedav?

We were able to test on a databricks VNET and it worked

![image](https://user-images.githubusercontent.com/41163455/172908651-a895158c-0991-429c-bfe2-ff64c4c6d021.png)

**Comment by pazdedav** [comment]
I got write access to the environment, so I could reproduce the error and provide more input / info, @jtracey93 . I will update this issue with more details 👍.

**Comment by pazdedav** [comment]
Hello @jtracey93 
I was able to reproduce an error (about "deny assignment") when trying to remediate that non-compliant VNet:

![image](https://user-images.githubusercontent.com/12873988/173535940-d69afd25-182b-48ab-bc5d-04c18ab31621.png)

It is important to note, we are testing a scenario with **Databricks-provided VNet** and not "Bring Your Own VNet", where I assume we have more control.

**Comment by jtracey93** [comment]
Thanks @pazdedav, this actually looks like its because its a locked VNET rather than a policy issue. Have you raised or the customer raised a support ticket to ask if possible? Could be a good idea

**Comment by jtracey93** [comment]
No worries and thanks for yours to @pazdedav,

I think for now whilst we work on if this could be supported on managed VNETs with engineering **we would advise** to create an [exemption](https://docs.microsoft.com/azure/governance/policy/concepts/exemption-structure) for the resources or scopes, as required so the compliance report is reflected correctly.

**Comment by pazdedav** [comment]
Thanks for the guidance @jtracey93. Much appreciated.

**Comment by jtracey93** [comment]
Trigger ADO Sync 1

**Comment by jtracey93** [comment]
Trigger ADO Sync 2
