### ISSUE TITLE
ALZ Visio Diagram Issues

### ISSUE THREAD

**Issue by danycontre** [Azure/Enterprise-Scale#989]
**Describe the bug**
Typos and missing letter denominator on Vision diagram Enterprise-Scale/docs/media/Enterprise-scale architecture.vsdx

**Steps to reproduce**

1. Download vision file Enterprise-Scale/docs/media/Enterprise-scale architecture.vsdx

**Screenshots**
![Screenshot 2022-06-14 121135](https://user-images.githubusercontent.com/78437433/173636828-25d396d9-261c-4492-92bb-55300ac17533.png)
![Screenshot 2022-06-14 121228](https://user-images.githubusercontent.com/78437433/173637027-65af38be-c357-48a2-a4fa-c74ad66b8343.png)

**Comment by jtracey93** [comment]
The files to be updated, live here: https://github.com/microsoft/CloudAdoptionFramework/tree/master/ready
