### ISSUE TITLE
Add option for enabling Auto Provisioning for Mdfc policy

### ISSUE THREAD

**Issue by neok-g** [Azure/Enterprise-Scale#995]
**Describe the solution you'd like**
The policyset definition 'Deploy Microsoft Defender for Cloud configuration' does not deploy the Auto provisioning of extensions. This can be set  (in bicep) as follows:

resource resMdfcAutoProvisioning 'Microsoft.Security/autoProvisioningSettings@2017-08-01-preview' = {
  name: 'default'  
  properties: {
    autoProvision: 'On'
  }
}

It would be nice if that would be part of the policyset definition and can be configured via a boolean parameter (default true)

**Comment by jtracey93** [comment]
Hey @neok-g,

We cover this by assigning the follow policy initiative to do the same thing at the same scope (intermediate root management group) https://www.azadvertizer.net/azpolicyinitiativesadvertizer/55f3eceb-5573-4f18-9695-226972c6d74a.html - this policy handles the agent side of things to all the VMs etc. to the central log analytics workspace
