### ISSUE TITLE
Where are the Policy Definitions and Initiatives located?

### ISSUE THREAD

**Issue by furrm** [Azure/Enterprise-Scale#999]
Hi team, I was wondering where I can locate the Policy Definitions and Initiatives for ALZ/ELZ that are listed in the ALZ documentation and called out via https://www.azadvertizer.net.  For example, I want to use [Deny-VNET-Peer-Cross-Sub](https://www.azadvertizer.net/azpolicyadvertizer/Deny-VNET-Peer-Cross-Sub.html) and assign it to the Sandbox MG.  What repo do I go to get the definition?

On the topic of azpolicyadvertizer, what are the API's that it is using to aggregate the policy info from? 

Many thanks

**Comment by jtracey93** [comment]
Hi @furrm,

The policies are all located here: https://github.com/Azure/Enterprise-Scale/tree/main/eslzArm/managementGroupTemplates/policyDefinition. Mainly in the `policies.json` file.

AzAdvertizer actually just pulls all the definitions from these files in this location and builds its library from there.

You could just take the definition from AzAdvertizer directly in its JSON section for that policy? 
![image](https://user-images.githubusercontent.com/41163455/176209950-c775c554-081e-491d-89c2-a75b350a74b7.png)

If not I would advise checking out the ALZ-Bicep policy library library, as you can see the policy you referred to here: https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/policy/definitions/lib/policy_definitions/policy_definition_es_deny_vnet_peer_cross_sub.json. You could also use this ALZ-Bicep module, https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions, to get all the ALZ policies or edit the arrays to only take the ones you want.

This library is also built from the same `policies.json` and other definition files as explained here https://github.com/Azure/ALZ-Bicep/wiki/PolicyDeepDive

Hope that helps

Thanks

Jack

**Comment by furrm** [comment]
Thanks for the prompt response @jtracey93.

Lots of great links to consume.  Unfortunately I get 404 for https://github.com/Azure/Enterprise-Scale/tree/main/eslzArm/managementGroupTemplates/policyDefinition.

Cheers,

Mike

**Comment by jtracey93** [comment]
No worries at all @furrm.

Seems I cut off an `s` by mistake from the link, try: https://github.com/Azure/Enterprise-Scale/tree/main/eslzArm/managementGroupTemplates/policyDefinitions
